### ISSUE TITLE
Attach is broken on MacOS when using AdoptOpenJDK JDK 8 builds

### ISSUE THREAD

**Issue by vyazelenko** [raphw/byte-buddy#1001]
At least some AdoptOpenJDK JDK 8 builds that are available [here](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases) contain definition of the `sun.tools.attach.BsdVirtualMachine` class that is different from the one found in the Zulu download, i.e. there is a only a _native_ method `sun.tools.attach.BsdVirtualMachine#createAttachFile` whereas Zulu has a native method `sun.tools.attach.BsdVirtualMachine#createAttachFile0` and a non-native method `createAttachFile` which invokes the `createAttachFile0`.

We got the following exception when running on  https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01/OpenJDK8U-jdk_x64_mac_hotspot_8u275b01.tar.gz:
```java
org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 1.8
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 25.275-b01
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_275-b01
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.15.7
    at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:234)
    ... 17 more

    Caused by:
    java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@eff5fee
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:117)
        ... 17 more

        Caused by:
        java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
            at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
            ... 21 more

            Caused by:
            java.lang.UnsatisfiedLinkError: sun.tools.attach.BsdVirtualMachine.createAttachFile0(Ljava/lang/String;)V
                at sun.tools.attach.BsdVirtualMachine.createAttachFile0(Native Method)
                at sun.tools.attach.BsdVirtualMachine.createAttachFile(BsdVirtualMachine.java:296)
                at sun.tools.attach.BsdVirtualMachine.<init>(BsdVirtualMachine.java:73)
                at sun.tools.attach.BsdAttachProvider.attachVirtualMachine(BsdAttachProvider.java:63)
                at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
                ... 27 more
```

The same source is also in the current latest release https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u282b08.tar.gz.

**Comment by vyazelenko** [comment]
Here is a stack trace from Mockito:
```java
                Caused by:
                org.mockito.exceptions.base.MockitoInitializationException: 
                Could not initialize inline Byte Buddy mock maker.

                It appears as if your JDK does not supply a working agent attachment mechanism.
                Java               : 1.8
                JVM vendor name    : AdoptOpenJDK
                JVM vendor version : 25.275-b01
                JVM name           : OpenJDK 64-Bit Server VM
                JVM version        : 1.8.0_275-b01
                JVM info           : mixed mode
                OS name            : Mac OS X
                OS version         : 10.15.7
                    at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:234)
                    ... 17 more

                    Caused by:
                    java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@eff5fee
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
                        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:117)
                        ... 17 more

                        Caused by:
                        java.lang.reflect.InvocationTargetException
                            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                            at java.lang.reflect.Method.invoke(Method.java:498)
                            at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
                            at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
                            ... 21 more

                            Caused by:
                            java.lang.UnsatisfiedLinkError: sun.tools.attach.BsdVirtualMachine.createAttachFile0(Ljava/lang/String;)V
                                at sun.tools.attach.BsdVirtualMachine.createAttachFile0(Native Method)
                                at sun.tools.attach.BsdVirtualMachine.createAttachFile(BsdVirtualMachine.java:296)
                                at sun.tools.attach.BsdVirtualMachine.<init>(BsdVirtualMachine.java:73)
                                at sun.tools.attach.BsdAttachProvider.attachVirtualMachine(BsdAttachProvider.java:63)
                                at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
                                ... 27 more
```

**Comment by raphw** [comment]
This almost seems like an error in the build to me. As if there is a native file missing for the particular platform. Have you tried taking it up with zulu?

**Comment by vyazelenko** [comment]
I don't think this is a problem with either AdopOpenJDK or Zulu even though they differ in how the `BsdVirtualMachine` class is defined. Instead I suspect this to be a Gradle issue.

We are using Github Actions to run the build on the [macos-10.15 VM](https://github.com/actions/virtual-environments/blob/8be00cadcbed0a97cdf4273de6a2b279ea08dfbb/images/macos/macos-10.15-Readme.md). See [one of the failing builds](https://github.com/real-logic/aeron/runs/1762947741?check_suite_focus=true). The build does the following:
1. Installs the latest Java 8 build to ensure that we use Zulu JVM to run the actual build.
2. Runs `cmake` for the native build.
   At this point the ENV variables are set correctly.
   ```
   JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
   BUILD_JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
   BUILD_JAVA_VERSION: 8
   ```
3.  Cmake invokes Gradle to run the java tests.
   Here the ENV vars are also correct:
   ```
    [GRADLE] java.home=/Users/runner/hostedtoolcache/jdk/8.0.282/x64/jre
    [GRADLE] JAVA_HOME=/Users/runner/hostedtoolcache/jdk/8.0.282/x64
    [GRADLE] BUILD_JAVA_HOME=/Users/runner/hostedtoolcache/jdk/8.0.282/x64
    [GRADLE] BUILD_JAVA_VERSION=8
   ```

  **Note:** the Gradle itself was started with the correct Zulu JDK.
4. The Gradle script has the [Java toolchain](https://docs.gradle.org/current/userguide/toolchains.html) configured and it is set to `BUILD_JAVA_VERSION` ENV var.
5. Gradle is supposed to use the configured toolchain to run the tests. However we get a wrong JDK used as the output from the test confirms:
   ```
   java.home: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
   java.version: 1.8.0_275
   JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
   BUILD_JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
   BUILD_JAVA_VERSION: 8
   ```
   **Note:** The ENV vars are correct but the actual JDK used is wrong.
6. The test fails with the attach exception, because we have a wrong combination of the `tools.jar` from Zulu JDK and the VM which is AdoptOpenJDK, i.e the `java.class.path` contains `/Users/runner/hostedtoolcache/jdk/8.0.282/x64/lib/tools.jar` but the `/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java` is invoked.

**Comment by VladimirKempik** [comment]
Zulu8 has a backport of 8157236 hence it differs from openjdk8u.
