### ISSUE TITLE
Cannot resolve type description for redis.clients.jedis.Jedis$auxiliary$43wAW823

### ISSUE THREAD

**Issue by hnwyllmm** [raphw/byte-buddy#1008]
Hi raphw:
I want to enhance class redis.clients.jedis.Jedis, but I got error as below. the classes which name with auxiliary is generated by bytebuddy, why them cannot be found? I can't get the point. Can you give some tips?

part of exception information:
`java.lang.IllegalStateException: Cannot resolve type description for redis.clients.jedis.Jedis$auxiliary$43wAW823
    at com.youzan-shaded.interceptor.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
    at com.youzan-shaded.interceptor.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
    at com.youzan-shaded.interceptor.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8140)
    at com.youzan-shaded.interceptor.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
    at com.youzan-shaded.interceptor.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
    at com.youzan-shaded.interceptor.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7649)`

**Comment by hnwyllmm** [comment]
After the process started, I use the arthas tool to attach it and I can see the class information by the command jad.

**Comment by raphw** [comment]
The byte code of Byte Buddy-generated code is not normally retained. If you want to keep it available, you need to use a `ClassLoadingStrategy` that does retain it such as `ClassLoadingStrategy.Default.WRAPPER_PERSISTENT`.

**Comment by hnwyllmm** [comment]
redis.clients.jedis.Jedis has been enhanced by another library. It was enhanced twice

**Comment by hnwyllmm** [comment]
I have no idea to use ClassLoadingStrategy as there is no option in agentBuilder or DynamicType.Builder.
Another question, why not put the generated classes to the TypePool?

**Comment by raphw** [comment]
That's unfortunately a hard limitation. If you want to use unloaded type descriptions, the byte code needs to be resolved for being able to describe classes. If that's not possible, Byte Buddy cannot do much about it.

Are you using an agent? There's a possibility to use a fallback strategy that operates on loaded types.

**Comment by hnwyllmm** [comment]
Fallback strategy doesn't work too. 
the code like below:
```java 
.with(AgentBuilder.FallbackStrategy.Simple.ENABLED)
```

I will use some other ways.
Thanks very much raphw.

**Comment by lindzh** [comment]
@hnwyllmm Have this problem resolved?  I have also encountered the same exception.

**Comment by hnwyllmm** [comment]
> @hnwyllmm Have this problem resolved? I have also encountered the same exception.

Sorry. It's past too long and I can't remember that.

**Comment by lindzh** [comment]
This problem has been fixed with this issue. Any one encountered please refer to

https://github.com/raphw/byte-buddy/issues/1198
https://github.com/raphw/byte-buddy/issues/1071
