### ISSUE TITLE
Error using Agent: Duplicate class definition for AgentBuilder$Default$Dispatcher$ForJava6CapableVm

### ISSUE THREAD

**Issue by adamhamlin** [raphw/byte-buddy#1011]
Hi,

I'm new to ByteBuddy, and I'm able to get things to work fine locally (java 8). I was also--at one point--able to get the same agent working on Databricks (java 8). However, I was refactoring and (probably) screwed something up and I'm now getting the following output & error on Databricks:
```
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Ignored from file:/databricks/jars/my-agent.jar]
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$CreationAction from file:/databricks/jars/my-agent.jar]
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher from file:/databricks/jars/my-agent.jar]
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$ForJava6CapableVm from file:/databricks/jars/my-agent.jar]
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$ForLegacyVm from file:/databricks/jars/my-agent.jar]
[Loaded net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$ForJava6CapableVm from file:/databricks/jars/my-agent.jar]
[Loaded java.lang.Throwable$PrintStreamOrWriter from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.lang.Throwable$WrappedPrintStream from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
[Loaded java.util.IdentityHashMap$KeySet from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]
FATAL ERROR in native method: processing of -javaagent failed

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "net/bytebuddy/agent/builder/AgentBuilder$Default$Dispatcher$ForJava6CapableVm"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$CreationAction.run(AgentBuilder.java:9643)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Dispatcher$CreationAction.run(AgentBuilder.java:9631)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.<clinit>(AgentBuilder.java:8513)
	at com.immuta.spark.agent.MyClassTransformer.transformClasses(MyClassTransformer.java:20)
	at com.immuta.spark.agent.MyAgent.premain(MyAgent.java:7)
```
As the error suggests, there are two [Loaded] entries for `AgentBuilder$Default$Dispatcher$ForJava6CapableVm`.
My `premain` function new's up the following class and calls `transformClasses`:
```java
public class MyClassTransformer {
    public void transformClasses(Instrumentation instrumentation) {
        new AgentBuilder.Default()
            .with(AgentBuilder.Listener.StreamWriting.toSystemError().withErrorsOnly())
            .type(
                ElementMatchers.isSubTypeOf(SomeInterface.class)
                .and(ElementMatchers.not(ElementMatchers.isInterface())))
            ).transform((builder, type, classLoader, module) -> {
                return builder
                        .method(ElementMatchers.nameStartsWith("execute"))
                        .intercept(MethodDelegation.to(MyClassTransformer.class));
            }).installOn(instrumentation);
    }

    @RuntimeType
    public static Object intercept(@Origin Method method, @SuperCall Callable<?> callable) throws Exception {
        // do stuff
        return callable.call();
    }
}
```
Again, I have no problems running locally. I've tried to systematically retrace my steps back to the point where things were working on Databricks, but no luck. Obviously, running on Databricks adds a lot of variables to the equation, but it DID work at some point.

Any idea why this class would be loaded twice? It certainly shouldn't match what's being instrumented (and I also tried to explicitly ignore `net.bytebuddy.*` to no avail). Thanks very much for your time.

**Comment by raphw** [comment]
I assume that you are shading Byte Buddy and it is included in your */databricks/jars/my-agent.jar*. I also assume that Byte Buddy already is on the class path for other reasons. In this case, it can come to the error you are seeing.

To avoid this, you can use the [Maven Shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/) to move Byte Buddy to a different namespace.

**Comment by adamhamlin** [comment]
Thanks @raphw for your quick response (and apologies for the delay).

Correct, I was already shading ByteBuddy using maven shade plugin + including it in my agent jar. Relocating yielded the same error with the relocated path. However, Byte Buddy is not on the classpath without my jar there, and it's not a transient dependency of anything else in my jar.

On Databricks, it seems that some/many/all/? classes loaded for the `premain` entrypoint are being loaded twice (I've confirmed the agent is not specified twice). In fact, I now actually see this behavior for other libraries when I take Byte Buddy out--it just happened to be the first thing referenced in the `premain` function. Using an agent in Databricks may just not be a fully-supported feature.

All of which is to say, I don't think this is a Byte Buddy problem. Sorry for the trouble. But if you have any other ideas or possible remedies, please don't hesitate.

Thanks again.

**Comment by adamhamlin** [comment]
Sorry, meant to comment here again that the issue appears to be a Databricks problem when simultaneously using a java agent + a custom security manager (tho it still works sometimes...). Closing

**Comment by Instein98** [comment]
@adamhamlin Hi, I have the same issue using javaagent with another microservice application. Do you have any idea why this problem is happening?

**Comment by adamhamlin** [comment]
> @adamhamlin Hi, I have the same issue using javaagent with another microservice application. Do you have any idea why this problem is happening?

@Instein98 unfortunately I don't, perhaps a class loading "chicken or the egg" problem with bootstrapping a java agent + security manager. FWIW, I was able to get around this problem by using `ByteBuddyAgent` for hot swapping vs the `premain` agent. However that does significantly limit the type/extent of byte buddy transformations you can do.
