### ISSUE TITLE
ElementMatchers.isSubTypeOf() fails with IllegalStateException when IntelliJ's debugger is attached (with "instrumenting agent" setting enabled)

### ISSUE THREAD

**Issue by mattnworb** [raphw/byte-buddy#1013]
Hi, I have an Instrumentation/AgentBuilder that is set up like so:

```java
final Instrumentation instrumentation = ByteBuddyAgent.install();

...
  
new AgentBuilder.Default()
    .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
    .with(AgentBuilder.TypeStrategy.Default.DECORATE)
    .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
    .with(AgentBuilder.Listener.StreamWriting.toSystemError())
    .ignore(ElementMatchers.none())
    .type(ElementMatchers.isSubTypeOf(Future.class))
    .transform(...)
    .asTerminalTransformation()
    .installOn(instrumentation);
```

and I've noticed that if I happen to run JUnit tests where this is installed, _and_ I attach IntelliJ's debugger, then an IllegalStateException inside the `isSubTypeOf()` matcher is thrown when inspecting a `com.intellij.rt.debugger` class which ends up preventing the transformation from being invoked for any and all other classes.

On stderr from the listener output I see this:

```
[Byte Buddy] DISCOVERY com.intellij.rt.debugger.agent.CaptureStorage$ExceptionCapturedStack [null, unnamed module @17f7cd29, loaded=false]
[Byte Buddy] ERROR com.intellij.rt.debugger.agent.CaptureStorage$ExceptionCapturedStack [null, unnamed module @17f7cd29, loaded=false]
java.lang.IllegalStateException: Cannot resolve type description for com.intellij.rt.debugger.agent.CaptureStorage$CapturedStack
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:8024)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7424)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7451)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.isAssignableFrom(TypeDescription.java:8247)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7431)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:7465)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:47)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:26)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1291)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:9975)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:9988)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:10244)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:10576)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10543)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10506)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10272)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10955)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10893)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10462)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at com.intellij.rt.debugger.agent.CaptureStorage.createCapturedStack(CaptureStorage.java:155)
	at com.intellij.rt.debugger.agent.CaptureStorage.capture(CaptureStorage.java:43)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.<init>(CompletableFuture.java:1722)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1750)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:1944)
	at com.spotify.foobar.FoobarTest.nonBlockingGet(FoobarTest.java:143)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

If I attempt to `ignore` classes related to `com.intellij.rt.debugger`, then this seems to prevent the debugger from functioning at all - no breakpoints are hit, even though the tests run to completion.

From looking for other references on this, I found https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000166640-Running-Debug-in-Java-can-t-find-CaptureAgent which lead me to find that disabling the "Instrumenting Agent" setting here will unbreak things:

![image](https://user-images.githubusercontent.com/113840/108427159-c0834580-720a-11eb-8878-841e3e83d909.png)

Through experimentation, I found that having this setting enabled causes IntelliJ to invoke the `java` process to run the tests wtih an extra argument of `-javaagent:/Users/mattbrown/Library/Caches/JetBrains/IntelliJIdea2020.3/captureAgent/debugger-agent.jar`, but since it is enabled by default I am curious if there is a way to workaround the error in code too.

Is there a way to configure my Instrumentation/AgentBuilder or use the `ignore` method so that a failure to  resolve the `com.intellij.rt.debugger.agent.CaptureStorage$ExceptionCapturedStack` class information within the `isSubTypeOf()` matcher doesn't prevent my Transformer instance from running on non-intellij classes? 

The stacktrace above is with version 1.9.7 but I see the same behavior with 1.10.20 as well.

**Comment by raphw** [comment]
How does your ignore matcher look like? It should ideally ignore by name, then the byte code is never loaded. I do however wonder if `AgentBuilder.RedefinitionStrategy.RETRANSFORMATION` triggers a retransformation without the IntelliJ agent being triggered, in case its not capable of retransforming.

I would think that adding an ignore matcher as `nameStartsWith("com.intellij.rt.")` should do the trick.

**Comment by mattnworb** [comment]
I tried a few different combinations of ignore and type matchers, and for each one with IntelliJ Ultimate 2020.3 and the "Instrumenting Agent" setting enabled, attaching the IDE's debugger to tests where the test code is making sure the transformer did its work end up failing (in other words, the debugger being attached seems to prevent my transformer from running)

- `.ignore(ElementMatchers.nameStartsWith("com.intellij.rt."))` - no errors, but my transformer/advice does not run
- `.ignore(ElementMathcers.none())` and `.type(not(nameStartsWith("com.intellij.rt")).and(isSubTypeOf(Future.class)))` - no errors, but my transformer/advice does not run
- `.ignore(none())` and `type(isSubTypeOf(Future.class))` - `java.lang.IllegalStateException: Cannot resolve type description for com.intellij.rt.debugger.agent.CaptureStorage$CapturedStack` and my transformer/advice does not run

Ultimately it is not a big deal for me to disable the "Async Stack Traces / Instrumenting Agent" setting in IntelliJ - I am not using that feature at all - but I was just wondering if there is anything obvious I am missing or a "right" way to fix this when IntelliJ's agent is also active.

**Comment by raphw** [comment]
I'd take it up with IntelliJ, their agent seems to break something in the agent mechanism. I wonder if it possibly replaces the byte code for the classes in question without acknowledging the transformations made by your agent. If you can create a simple enough reproducer, maybe they are giving you a hint into the right direction.

**Comment by mattnworb** [comment]
That makes sense, thanks!
