### ISSUE TITLE
NullPointerException from ForExplicitMethod.hashCode()

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#1019]
I am getting a `NullPointerException` during a transformation from `ForExplicitMethod.hashCode()`. It looks like that method in turn is generated by `HashCodeAndEqualsPlugin.Enhance`.

```
Caused by: java.lang.NullPointerException
	at net.bytebuddy.implementation.MethodCall$MethodLocator$ForExplicitMethod.hashCode(MethodCall.java)
	at net.bytebuddy.implementation.MethodCall.hashCode(MethodCall.java)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.hashCode(MethodRegistry.java)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:458)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:221)
	at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4703)
	at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4660)
	at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.complete(Plugin.java:3768)
	at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4519)
	at net.bytebuddy.build.maven.ByteBuddyMojo.apply(ByteBuddyMojo.java:404)
	... 32 more
```

An example can be found in the RESTBucks project:

```
$ git clone https://github.com/odrotbohm/spring-restbucks
$ cd spring-restbucks
$ git checkout hacking/jmolecules
$ mvn clean test-compile
```

**Comment by raphw** [comment]
I cannot find a branch with that name. Did you push it?

From looking at the code, this can really only happen if you invoke `MethodCall.invoke(MethodDescription)` with `null` as an argument.

**Comment by odrotbohm** [comment]
It was indeed [a mistake](https://github.com/xmolecules/jmolecules-integrations/issues/37) on my side. Feel free to close.
