### ISSUE TITLE
VerifyError trying to instrument log4j class

### ISSUE THREAD

**Issue by randallt** [raphw/byte-buddy#1030]
Hi, thanks for all your work on ByteBuddy! We have used it on custom instrumentation in our fork of the OpenTracing Contrib Java SpecialAgent.

I'm hitting an issue that I've researched a bit, and can't seem to overcome. I am trying to mimic automatic MDC injection in Log4J (v1.2.17) using ByteBuddy v1.10.22. (I also tried ByteBuddy versions 1.10.14 and 1.10.2), as done by the DataDog Java Agent:

https://github.com/DataDog/dd-trace-java/blob/v0.70.0/dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/Log4j1MDCInstrumentation.java

Here is my attempt:

```
public class Log4J1AgentRule extends AgentRule {

	@Override
	public AgentBuilder buildAgentChainedGlobal1(AgentBuilder builder) {
		if (Util.isLogInjectionEnabled()) {
			return builder.with(new io.opentracing.contrib.specialagent.DebugListener()) // TODO remove
					.type(named("org.apache.log4j.MDC")).transform(new Transformer() {
						@Override
						public Builder<?> transform(final Builder<?> builder, final TypeDescription typeDescription,
								final ClassLoader classLoader, final JavaModule module) {
							return builder.visit(advice(typeDescription).to(Log4J1AgentRule.MDCAdvice.class)
									.on(isTypeInitializer()));
						}
					});
		} else {
			return builder; // not enabled
		}
	}

	private static class MDCAdvice {
		@Advice.OnMethodExit(suppress = Throwable.class)
		public static void mdcClassInitialized(@Advice.Origin final Class<?> mdcClass) {
			Util.printDebug("Log4J1AgentRule.MDCAdvice entered");
			try {
				final Method putMethod = mdcClass.getMethod("put", String.class, Object.class);
				final Method removeMethod = mdcClass.getMethod("remove", String.class);
				DualUtil.addDatadogLogScopeListener("log4j1", putMethod, removeMethod);
			} catch (Exception e) {
				Util.printError("Failed to add log4j ThreadContext span listener: " + e);
			}
		}
	}

    
```

If this runs in a JVM where the MDC is requested, then I get the following exception:

```
java.lang.VerifyError: (class: org/apache/log4j/MDC, method: <clinit> signature: ()V) Illegal type in constant pool
	at org.apache.log4j.spi.LoggingEvent.getMDC(LoggingEvent.java:338)
	at org.apache.log4j.helpers.PatternParser$MDCPatternConverter.convert(PatternParser.java:479)
	at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:65)
	at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.info(Log4jLoggerAdapter.java:305)
```

I saw the issue

https://github.com/raphw/byte-buddy/issues/81

that seemed to match, but I couldn't figure out how to apply your suggestions to disable the origin cache (maybe it's no longer applicable in this version). Help is appreciated.

**Comment by raphw** [comment]
Try adding a TypeConstantAdjustment as a visitor to the agent, before anything else. I assume log4j compiles to a rather old Java version and the class file does not support regular type tokens.

**Comment by randallt** [comment]
Can you provide an example of how to do that? I'm having trouble finding an example.

**Comment by randallt** [comment]
Like this?

```
@Override
	public AgentBuilder buildAgentChainedGlobal1(AgentBuilder builder) {
		if (Util.isLogInjectionEnabled()) {
			return builder
					.with(new io.opentracing.contrib.specialagent.DebugListener()) // TODO remove
					.type(named("org.apache.log4j.MDC")).transform(new Transformer() {
						@Override
						public Builder<?> transform(final Builder<?> builder, final TypeDescription typeDescription,
								final ClassLoader classLoader, final JavaModule module) {
							return builder.visit(TypeConstantAdjustment.INSTANCE).visit(advice(typeDescription).to(Log4J1AgentRule.MDCAdvice.class)
									.on(isTypeInitializer()));
						}
					});
		} else {
			return builder; // not enabled
		}
	}

```

**Comment by raphw** [comment]
Yes, something like that. There's no harm in registering it multiple times.

**Comment by randallt** [comment]
Looks like that worked. Thanks!
