### ISSUE TITLE
IllegalAccessError occured when applying dynamical generated Advice classes

### ISSUE THREAD

**Issue by FrankChen021** [raphw/byte-buddy#1032]
I'm implementing a java agent with bytebuddy. The agent first dynamically generates interceptor classes based on a given class template, and then hook these dynamic generated interceptors to target methods. This agent works well with bytebuddy's `MethodDelegation` mechanism.

Today I'm changing `MethodDelegation` to `Advice` so that we could provide a way for those dynamic generated interceptors to modify input arguments of intercepted methods. But I got a problem as below that I have no idea what's wrong.

```
java.lang.IllegalAccessError: tried to access class net.bytebuddy.asm.Advice$NoExceptionHandler from class net.bytebuddy.asm.Advice$Dispatcher$SuppressionHandler$Suppressing
	at net.bytebuddy.asm.Advice$Dispatcher$SuppressionHandler$Suppressing.of(Advice.java:6723)
	at net.bytebuddy.asm.Advice$Dispatcher$Resolved$AbstractBase.<init>(Advice.java:7374)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved.<init>(Advice.java:7647)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.<init>(Advice.java:8029)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter$WithRetainedEnterType.<init>(Advice.java:8218)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.of(Advice.java:8070)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining.asMethodEnter(Advice.java:7593)
	at net.bytebuddy.asm.Advice.to(Advice.java:356)
	at net.bytebuddy.asm.Advice.to(Advice.java:326)
	at net.bytebuddy.asm.Advice.to(Advice.java:303)
	at net.bytebuddy.agent.BootstrapAgentInjection$2.transform(BootstrapAgentInjection.java:57)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10436)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10374)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10140)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10759)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10706)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10297)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1002)
	at net.bytebuddy.agent.BootstrapAgentInjection.main(BootstrapAgentInjection.java:31)
```

The code I used is listed below:

```
package net.bytebuddy.agent;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassInjector;
import net.bytebuddy.implementation.bytecode.assign.Assigner;
import net.bytebuddy.matcher.ElementMatchers;
import net.bytebuddy.pool.TypePool;
import net.bytebuddy.utility.JavaModule;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.instrument.Instrumentation;
import java.lang.reflect.Method;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import static net.bytebuddy.matcher.ElementMatchers.named;

public class BootstrapAgentInjection {
    public static void main(String[] args) throws Exception {
        premain(null, ByteBuddyAgent.install());

        HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
        urlConnection.connect();
    }

    public static void premain(String arg, Instrumentation instrumentation) throws Exception {
        final Map<String, byte[]> classes = dynamicGenerateAdviceClass();
        //
        // dynamic generate a AOP class based on given class template and inject it into bootstrap class loader
        //
        ClassInjector.UsingUnsafe.Factory factory = ClassInjector.UsingUnsafe.Factory.resolve(instrumentation);
        factory.make(null, null).injectRaw(classes);

        //
        // install Advice for target method 'HttpURLConnection.connect()'
        //
        new AgentBuilder.Default()
            .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
            .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(factory))
            .type(ElementMatchers.named("sun.net.www.protocol.http.HttpURLConnection"))
            .transform(new AgentBuilder.Transformer() {
                           @Override
                           public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                                   TypeDescription typeDescription,
                                                                   ClassLoader classLoader,
                                                                   JavaModule module) {
                               try {
                                   return builder.visit((Advice.to(Class.forName("DynamicGeneratedAdviceClass"),

                                                                   // provide a class file loader to resolve the dynamic generated class
                                                                   new ClassFileLocator() {
                                                                       @Override
                                                                       public Resolution locate(String name)
                                                                           throws IOException {
                                                                           if ( classes.containsKey(name) ) {
                                                                               byte[] bytes = classes.get(name);
                                                                               return new Resolution.Explicit(bytes);
                                                                           } else {
                                                                               return new Resolution.Illegal(name);
                                                                           }
                                                                       }

                                                                       @Override
                                                                       public void close() throws IOException {

                                                                       }
                                                                   })
                                                               .on(named("connect"))));
                               } catch (ClassNotFoundException e) {
                                   e.printStackTrace();
                                   return null;
                               }
                           }
                       }
            )
            .with(new AgentBuilder.Listener.Adapter() {
                @Override
                public void onError(String s,
                                    ClassLoader classLoader,
                                    JavaModule javaModule,
                                    boolean b,
                                    Throwable throwable) {
                    throwable.printStackTrace();
                }
            })
            .installOn(instrumentation);
    }

    public static Map<String, byte[]> dynamicGenerateAdviceClass() {
        try {
            Map<String, byte[]> classesTypeMap = new HashMap<>();

            // inject Advice related annotation into bootstrap class loader
            // so that these annotations in generated class could be found by bytebudd
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$AllArguments");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$Enter");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$Local");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$OnMethodEnter");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$OnMethodExit");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$Origin");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$Return");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$This");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$Thrown");
            inject(classesTypeMap, "net.bytebuddy.asm.Advice$NoExceptionHandler");
            inject(classesTypeMap, "net.bytebuddy.implementation.bytecode.assign.Assigner$Typing");

            String internalInterceptorName = ConnectionMethodInterceptor.class.getName();
            TypePool typePool = TypePool.Default.of(BootstrapAgentInjection.class.getClassLoader());
            TypeDescription templateTypeDescription = typePool.describe(BootstrapAop.class.getName()).resolve();
            DynamicType.Unloaded interceptorType = new ByteBuddy().redefine(templateTypeDescription,
                                                                            ClassFileLocator.ForClassLoader
                                                                                .of(BootstrapAgentInjection.class.getClassLoader()))
                                                                  .name("DynamicGeneratedAdviceClass")
                                                                  .field(named("TARGET_INTERCEPTOR"))
                                                                  .value(internalInterceptorName)
                                                                  .make();

            classesTypeMap.put("DynamicGeneratedAdviceClass", interceptorType.getBytes());

            inject(classesTypeMap, IInterceptor.class.getName());
            return classesTypeMap;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private static void inject(Map<String, byte[]> loadedTypeMap, String className) {
        String classResourceName = className.replaceAll("\\.", "/") + ".class";
        try {
            try (InputStream resourceAsStream = ClassLoader.getSystemClassLoader()
                                                           .getResourceAsStream(classResourceName)) {
                if (resourceAsStream == null) {
                    throw new RuntimeException(String.format("Class [%s] for bootstrap injection not found",
                                                             className));
                }

                try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
                    byte[] buffer = new byte[2048];
                    int len;

                    while ((len = resourceAsStream.read(buffer)) != -1) {
                        os.write(buffer, 0, len);
                    }

                    loadedTypeMap.put(className, os.toByteArray());
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(String.format("Failed to load class [%s]: %s", className, e.getMessage()));
        }
    }

    public interface IInterceptor {
        void before();

        void after();
    }

    /**
     * AOP template class
     */
    public static class BootstrapAop {
        private static String TARGET_INTERCEPTOR;
        private static IInterceptor INTERCEPTOR;

        @Advice.OnMethodEnter
        public static boolean enter(
            final @Advice.Origin Class clazz,
            final @Advice.Origin Method method,
            final @Advice.This(optional = true) Object target,
            final @Advice.AllArguments Object[] args,
            @Advice.Local("context") Object context
        ) {
            System.out.println("enter:context=" + context.toString() + ",oring=" + method.toString());
            INTERCEPTOR = createInterceptor(TARGET_INTERCEPTOR);
            return true;
        }

        @Advice.OnMethodExit(onThrowable = Throwable.class)
        public static void exit(final @Advice.Enter boolean skip,
                                final @Advice.Origin Method method,
                                final @Advice.This Object target,
                                final @Advice.Return(typing = Assigner.Typing.DYNAMIC) Object returning,
                                final @Advice.AllArguments Object[] args,
                                final @Advice.Thrown Throwable exception,
                                final @Advice.Local("context") Object context) {

            System.out.println("exit");
            System.out.println(context == null ? "null" : context.toString());
        }

        public static <T> T createInterceptor(String className) {
            try {
                Class<?> interceptor = ClassLoader.getSystemClassLoader().loadClass(className);
                return (T) interceptor.newInstance();
            } catch (Exception e) {
            }
            return null;
        }
    }

    public static class ConnectionMethodInterceptor implements IInterceptor {
        @Override
        public void before() {
            System.out.println("before");
        }

        @Override
        public void after() {
            System.out.println("after");
        }
    }
}

```

Any response is very appreciated.

**Comment by raphw** [comment]
Might Byte Buddy possibly already be on the class path? To me this looks like an issue related to two versions being blend.

**Comment by FrankChen021** [comment]
Hi @raphw , thanks very much for your response.

In our formal project, Byte Buddy is referenced by the 'Class-path' property in MANIFEST.MF packed in the agent jar file . 

And the code I attached above is an independent program which could be run in intellij to re-produce the problem. And from intellij, we could see that Byte Buddy is on the class path.

So what's your suggestion to solve this problem ?

**Comment by raphw** [comment]
Yes, I am wondering if there's a version of Byte Buddy both on the class path and contained in the agent jar?

Also, can you set a break point in the line of question? I wonder if you can check the class loader of both the `Advice` class and the exception class that you find there?

**Comment by FrankChen021** [comment]
> Yes, I am wondering if there's a version of Byte Buddy both on the class path and contained in the agent jar?

No, I checked again that there's only one version of Byte Buddy.

> Also, can you set a break point in the line of question? I wonder if you can check the class loader of both the `Advice` class and the exception class that you find there?

from the debugging view, we can see that `net.bytebuddy.asm.Advice$NoExceptionHandler` is loaded by bootstrap class loader, and `net.bytebuddy.asm.Advice` is loaded by system class loader.

![image](https://user-images.githubusercontent.com/6525742/112840057-79be2080-90d1-11eb-8e24-5726b266fdaf.png)

Is this the reason which causes the problem ? I did inject some classes including `net.bytebuddy.asm.Advice$NoExceptionHandler` into bootstrap class loader as the way I did with `MethodDelegation`.

![image](https://user-images.githubusercontent.com/6525742/112840560-0ec11980-90d2-11eb-91a8-a94ba7b84d34.png)

**Comment by raphw** [comment]
Yeah, that's not something you want to do. Why is your advice injected into the boot loader? You should avoid this. How do you apply your advice and why do you feel these classes need injection?

**Comment by FrankChen021** [comment]
We want to intercept classes loaded by bootstrap class loader. So the advice class should also be loaded by bootstrap class loader. 

If these annotation are not injected into bootstrap class loader, there will be such exception 

```
java.lang.IllegalArgumentException: No advice defined by class DynamicGeneratedAdviceClass
	at net.bytebuddy.asm.Advice.to(Advice.java:350)
	at net.bytebuddy.asm.Advice.to(Advice.java:326)
	at net.bytebuddy.asm.Advice.to(Advice.java:303)
	at net.bytebuddy.agent.BootstrapAgentInjection$2.transform(BootstrapAgentInjection.java:57)
```
![image](https://user-images.githubusercontent.com/6525742/112844603-7b3e1780-90d6-11eb-9150-63fc568a57a6.png)

**Comment by FrankChen021** [comment]
@raphw You reminded me. There's no need to inject the dynamically generated advice classes into bootstrap class loader. `Advice` works differently from `MethodDelegation `. I tried just now to put all those generated advice classes into system class loader, it works!

Thanks very much for your time. I will close this issue.
