### ISSUE TITLE
enhance class failed

### ISSUE THREAD

**Issue by xu1009** [raphw/byte-buddy#1039]
enhance class failed , error stack trace like this

ERROR 2021-04-15 19:16:08:120 main SkyWalkingAgent : Enhance class ams.crm.microservice.policy.controller.KFrameTransferController error. 
java.lang.IllegalArgumentException: None of [protected void java.lang.Object.finalize() throws java.lang.Throwable, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, 
public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.
equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), protected nati
ve java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException, public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll(), public j
ava.lang.Object org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(java.lang.Object,java.lang.Object[],java.util.concurrent.Callable,java.lang.reflect.Method) throws
 java.lang.Throwable] allows for delegation from public ams.crm.starter.service.common.vo.ServiceResponse ams.crm.microservice.policy.controller.KFrameTransferController.createKFrameTransfer(java.lang.Stri
ng,ams.crm.microservice.policy.controller.vo.CreateKFrameTransferRequest)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1346)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.
java:5316)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1480)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:711)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:394)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:252)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10366)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10687)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10634)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10225)
        at org.apache.skywalking.apm.agent.core.plugin.bytebuddy.CacheableTransformerDecorator$1.transform(CacheableTransformerDecorator.java:94)

**Comment by xu1009** [comment]
i find the problem, i use self annotation in the method, when i remove the annotation, it works，so why self annotation  not work

**Comment by xu1009** [comment]
*/
    @RuntimeType
    public static Object intercept(@This Object obj, @AllArguments Object[] allArguments, @SuperCall Callable<?> zuper,
        @Origin Method method) throws Throwable {
        EnhancedInstance targetObject = (EnhancedInstance) obj;

        prepare();

        MethodInterceptResult result = new MethodInterceptResult();
        try {
            if (INTERCEPTOR != null) {
                INTERCEPTOR.beforeMethod(targetObject, method, allArguments, method.getParameterTypes(), result);
            }
        } catch (Throwable t) {
            if (LOGGER != null) {
                LOGGER.error(t, "class[{}] before method[{}] intercept failure", obj.getClass(), method.getName());
            }
        }

        Object ret = null;
        try {
            if (!result.isContinue()) {
                ret = result._ret();
            } else {
                ret = zuper.call();
            }
        } catch (Throwable t) {
            try {
                if (INTERCEPTOR != null) {
                    INTERCEPTOR.handleMethodException(targetObject, method, allArguments, method.getParameterTypes(), t);
                }
            } catch (Throwable t2) {
                if (LOGGER != null) {
                    LOGGER.error(t2, "class[{}] handle method[{}] exception failure", obj.getClass(), method.getName());
                }
            }
            throw t;
        } finally {
            try {
                if (INTERCEPTOR != null) {
                    ret = INTERCEPTOR.afterMethod(targetObject, method, allArguments, method.getParameterTypes(), ret);
                }
            } catch (Throwable t) {
                if (LOGGER != null) {
                    LOGGER.error(t, "class[{}] after method[{}] intercept failure", obj.getClass(), method.getName());
                }
            }
        }

        return ret;
    }



    @ApiOperation(value = "xx")
    @Monitored(interfaceName = "/xx")
    @PostMapping(value = "/xx/xx")
    @RequiredRolePermission(permissionId = Constants.xxx)
    public ServiceResponse<Void> xxxxx(
            @RequestHeader(name = xx) String xx,
            @RequestBody @Validated xxxx request) {
        xxxx.xxx(targetStaffName, request.xxxx());
        return new ServiceResponse<>();
    }



        AgentBuilder agentBuilder = new AgentBuilder.Default(byteBuddy).ignore(
                nameStartsWith("net.bytebuddy.")
                        .or(nameStartsWith("org.slf4j."))
                        .or(nameStartsWith("org.groovy."))
                        .or(nameContains("javassist"))
                        .or(nameContains(".asm."))
                        .or(nameContains(".reflectasm."))
                        .or(nameStartsWith("sun.reflect"))
                        .or(allSkyWalkingAgentExcludeToolkit())
                        .or(ElementMatchers.isSynthetic()));


        agentBuilder.type(pluginFinder.buildMatch())
                .transform(new Transformer(pluginFinder)) 
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new Listener())
                .installOn(instrumentation);

**Comment by raphw** [comment]
What du you mean by "self annotation"? I am a bit lost here. The exception indicates that the parameter in question cannot be mapped for the method in the exception message.

**Comment by xu1009** [comment]
> What du you mean by "self annotation"? I am a bit lost here. The exception indicates that the parameter in question cannot be mapped for the method in the exception message.

RequiredRolePermission annotation is my custom annotation, when i add it to the method, it can not be mapped,  when i remove it, i works, so, the annotation leads the exception?

**Comment by raphw** [comment]
Is the annotation bound to something? The presence of an annotation by itself should not disturb the binding. Do you have a reproduction?

**Comment by xu1009** [comment]
> Is the annotation bound to something? The presence of an annotation by itself should not disturb the binding. Do you have a reproduction?

i get，the problem is https://github.com/raphw/byte-buddy/issues/971

**Comment by raphw** [comment]
Alright, then updating should do the trick. That issue was resolved.
