### ISSUE TITLE
JVM throws IncompatibleClassChangeError during class redefinition

### ISSUE THREAD

**Issue by mariusoe** [raphw/byte-buddy#1040]
Hi,

we're using ByteBuddy in a custom Java agent to observe specific methods.
For this purpose, we're using a `ClassFileTransfomer` to instrument method based on certain conditions.

Inside of this transfomer, we use ByteBuddy just to generate the desired bytecode. For this, we create a `DynamicType.Builder` which we use to apply the desired bytecode modification. The code is basically the following:

```
@Override
public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] bytecode) throws IllegalClassFormatException {
    // ...
    TypeDescription type = TypeDescription.ForLoadedType.of(classBeingRedefined);
    ClassFileLocator byteCodeClassFileLocator = ClassFileLocator.Simple.of(type.getName(), bytecode);
    DynamicType.Builder<?> builder = new ByteBuddy().redefine(type, byteCodeClassFileLocator);
    // ...
    // instrumenting methods and return the new bytecode
}
```

This works very well - good job for ByteBuddy - but for certain classes (proxy classes generated by the target application), the following error occurs when calling above `new ByteBuddy().redefine(..)`. It is important to note, that the class is already loaded and the transformer triggered due to a retransfomation of the target class.

```
java.lang.IncompatibleClassChangeError: MyClass and MyClass$ProxyFor__1234 disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.getEnclosingClass(Class.java:1517)
	at java.base/java.lang.reflect.Constructor.getAnnotatedReceiverType(Constructor.java:628)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2760)
	... 25 common frames omitted
Wrapped by: java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedReceiverType
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2764)
	at net.bytebuddy.description.method.MethodDescription$ForLoadedConstructor.getReceiverType(MethodDescription.java:1080)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:796)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:373)
	at net.bytebuddy.description.method.MethodList$AbstractBase.asTokenList(MethodList.java:70)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:390)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:782)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:757)
	...
```

The application uses OpenJDK 11.0.10 and we are using ByteBuddy in version 1.10.14.

We don't have any clue what the cause for this error can be and what is meant by `disagree on InnerClasses attribute`.
Forthermore, our agent is not adding any methods or fields to the instrumented class or changing any signatures.

Any ideas?

**Comment by raphw** [comment]
The inner classes attribute regulates what is an inner class of what. I assume that your proxy `MyClass$ProxyFor__1234` is generated by you? The JVM in the older days considered the `$` as an inner class inference mechanism. I assume that's what it is confused about.

**Comment by mariusoe** [comment]
Hi @raphw 

thanks for your answer.

No, the `MyClass$ProxyFor__1234` is not generated by us but by the target application itself. For this reason, I can't give too much information about it myself, as I don't know what exactly this proxy class is used for.

However, the application itself runs without problems, so I would have assumed that this class should also be valid. But I do not understand why the JVM throws this error. As far as I understand the call `DynamicType.Builder<?> builder = new ByteBuddy().redefine(type, byteCodeClassFileLocator);` does not make any changes to the classes etc.

**Comment by raphw** [comment]
No, redefinition should not change anything, it would however append the inner class attribute. You could dump the byte code via `-Dnet.bytebuddy.dump=/some/folder` and also get hold of the class file of `MyClass$ProxyFor__1234` and look at the classes using *javap*. One of the classes likely defines a different modifier for an inner class and it would be necessary to see which one is wrong about it.

**Comment by mariusoe** [comment]
Thanks for your help @raphw 
We didn't solved the problem, yet. We have to understand the classes causing the problems and your hint regarding dumping the generated bytecode is a good starting point. I'll reopen this in case we have more questions.

**Comment by mariusoe** [comment]
Hi @raphw ,

I'm reopening this issue because we've still the described problem and I'm able to provide a sample class for reproducing the error.

As mentioned before, the problem occures when calling `new ByteBuddy().redefine(proxyClass)`, where `proxyClass` is a generated class. The classes are generated by Gosu (https://github.com/gosu-lang/gosu-lang).

When calling the described method, the following exception occures:

```
Exception in thread "main" java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.reflect.AnnotatedElement net.bytebuddy.description.method.MethodDescription$InDefinedShape$AbstractBase$Executable.getAnnotatedReceiverType(java.lang.Object)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1111)
	at net.bytebuddy.description.method.$Proxy8.getAnnotatedReceiverType(Unknown Source)
	at net.bytebuddy.description.method.MethodDescription$InDefinedShape$AbstractBase$ForLoadedExecutable.getReceiverType(MethodDescription.java:407)
	at net.bytebuddy.description.method.MethodDescription$ForLoadedConstructor.getReceiverType(MethodDescription.java:1019)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:869)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:435)
	at net.bytebuddy.description.method.MethodList$AbstractBase.asTokenList(MethodList.java:87)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:421)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:782)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:757)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:735)
	at sample.TestMain.main(TestMain.java:15)
Caused by: java.lang.IncompatibleClassChangeError: examples.Programs and examples.Programs$ProxyFor_4689667750169763299 disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
Caused by: java.lang.IncompatibleClassChangeError: examples.Programs and examples.Programs$ProxyFor_4689667750169763299 disagree on InnerClasses attribute
	at java.base/java.lang.Class.getEnclosingClass(Class.java:1518)
	at java.base/java.lang.reflect.Constructor.getAnnotatedReceiverType(Constructor.java:628)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:974)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1098)
	... 11 more
```

FYI, I'm using Java 11:
```
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

I've attached an archive containing a ready-to-use Gradle/IntelliJ project, that can be used to reproduce the error. I've added a small class which just calls ByteBuddy's `redefine` method using the generated classes. This is more or less what our agent is doing.
The generated classes from Gosu are located in the `gosu-classes` directory.

I've no idea what could be the problem with these classes.

[sample-project.zip](https://github.com/raphw/byte-buddy/files/6969587/sample-project.zip)

It would be great if you could take a look at it.
All the best!

**Comment by raphw** [comment]
The issue has nothing to do with Byte Buddy, I am afraid. Your generated code contains the class `examples.Programs` which contains the following inner classes attribute:

    InnerClasses:
      public #12= #11 of #2;                  // block_0_=class examples/Programs$block_0_ of class examples/Programs

Its inner class `examples.Programs$ProxyFor_4689667750169763299` however contains this inner class attribute:

    InnerClasses:
      public static #12= #2 of #11;           // ProxyFor_4689667750169763299=class examples/Programs$ProxyFor_4689667750169763299 of class examples/Programs

The attributes disagree. While `examples.Programs$ProxyFor_4689667750169763299` claims to be an inner class of `examples.Programs`, this is not confirmed by `examples.Programs` such that this error is thrown.

Attribute validation occurs lazily. Therefore, when Byte Buddy requests an attribute - the annotations of a class upon redefinition - the validation is triggered and the error is thrown.

The error is however in your code generator. It generates illegal class files.

**Comment by mariusoe** [comment]
Hi @raphw 

thanks for looking into this problem.
Now, I understood the problem and that this is related to the invalid bytecode.

Due to the fact that we do only use wrappers like `Advice` which are used via the `builder.visit`method, I've tested switching from ByteBuddy's `redefine` method to `decorate`. I've done this because you also mentioned in a different ticket of mine (https://github.com/raphw/byte-buddy/issues/1067#issuecomment-862787257), that `decorate` would also be sufficient in case no transformation is done at all (except adding wrappers to the methods).
It seems like when using `decorate`, the error is not occuring. Is it possible that the validation is not triggered by the JVM in this case?

Sure, it would not be a clean solution because the bytecode is still broken, but at least we can add advices to it.

**Comment by raphw** [comment]
Yes, the idea of decorate is to retain most properties but to only allow for the decoration of byte code. This should ve s viable solution for you.

**Comment by mariusoe** [comment]
Due to the fact that this problem is not related to ByteBuddy itself and the `decorate` sovles our problem, this ticket is closed.

Thanks a lot for your help.
