### ISSUE TITLE
How can I redefine class with Advice?

### ISSUE THREAD

**Issue by Yelijah** [raphw/byte-buddy#1049]
I want to redefine a class with Advice，but it throw a Exception: "java.lang.IllegalStateException: Cannot call super (or default) method". And it worked if I use subclass or rebase.
```java
public class User {
    private int age;
    private double weight;
    private String name;

    public String eat() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return "eat over";
    }
}
```
```java
public class TimeAdvisor {

    @Advice.OnMethodEnter
    public static long onMethodEnter(@Advice.This(optional = true, typing = Assigner.Typing.DYNAMIC) Object proxy,
                                     @Advice.Origin Method method,
                                     @Advice.AllArguments(typing = Assigner.Typing.DYNAMIC, readOnly = true) Object[] args) {
        System.out.printf("enter! object:%s, method:%s, args:%s\n", proxy, method, Arrays.toString(args));
        return System.currentTimeMillis();
    }

    @Advice.OnMethodExit( onThrowable = Exception.class)
    public static long onMethodExit(@Advice.This(optional = true, typing = Assigner.Typing.DYNAMIC) Object proxy,
                                    @Advice.Origin Method method,
                                    @Advice.AllArguments(typing = Assigner.Typing.DYNAMIC, readOnly = true) Object[] args,
                                    @Advice.Return(typing = Assigner.Typing.DYNAMIC, readOnly = true) Object result,
                                    @Advice.Thrown(typing = Assigner.Typing.DYNAMIC) Exception e,
                                    @Advice.Enter(typing = Assigner.Typing.DYNAMIC, readOnly = true) long enterMethodResult) {
        long time = System.currentTimeMillis() - enterMethodResult;
        if (e == null) {
            System.out.printf("exit!! object:%s, method:%s, args:%s, use:%s\n", proxy, method, Arrays.toString(args), time);
        } else {
            System.out.printf("exit!! object:%s, method:%s, args:%s, use:%s, exception:\n", proxy, method, Arrays.toString(args), time);
            e.printStackTrace();
        }
        return System.currentTimeMillis();
    }
}
```
my test:
```java
        DynamicType.Unloaded<?> dynamicType = new ByteBuddy()
                .redefine(User.class)
                .name("bytebuddy.AdviceUser")
                .method(ElementMatchers.named("eat"))
                .intercept(Advice.to(TimeAdvisor.class))
                .make();
        dynamicType.saveIn(FOLDER);
        Object methodDelegationUser = dynamicType.load(getClass().getClassLoader())
                .getLoaded()
                .newInstance();

        Reflect.on(methodDelegationUser).call("eat");
```
it throws Exception:
```java
java.lang.IllegalStateException: Cannot call super (or default) method for public java.lang.String cn.elijah.bytebuddy.AdviceUser.eat()

	at net.bytebuddy.implementation.SuperMethodCall$Appender.apply(SuperMethodCall.java:133)
	at net.bytebuddy.asm.Advice$Appender$EmulatingMethodVisitor.resolve(Advice.java:10635)
	at net.bytebuddy.asm.Advice$Appender.apply(Advice.java:10588)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:5316)
	at net.bytebuddy.jar.asm.MethodVisitor.visitCode(MethodVisitor.java:232)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1490)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:721)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:401)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
	at cn.yelijah.bytebuddy.advisor.AdviceTest.test(AdviceTest.java:31)
```
Any ideas?

**Comment by Yelijah** [comment]
I what to create a new class by redefining an existing class,  it couldn't happen? Agentbuilder seems to apply to direct modify an existing class, but not create a new one.

**Comment by Yelijah** [comment]
It works! Thank u very much!
