### ISSUE TITLE
ByteBuddy on java modular run

### ISSUE THREAD

**Issue by andresluuk** [raphw/byte-buddy#1050]
When I run my test program on jdk modular run with on JDK 16 I fail with:
java.lang.NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException
        at net.bytebuddy/net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:357)
        at net.bytebuddy/net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at net.bytebuddy/net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at net.bytebuddy/net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at autotest/autotest.Test.implement(Test.java:24)
        at autotest/autotest.Test.<init>(Test.java:13)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
        at java.base/java.lang.Class.newInstance(Class.java:642)
        at jrautorunner/test.run.TestRunner.newTestClassInstance(TestRunner.java:138)
        at jrautorunner/test.run.TestRunner.runTests(TestRunner.java:77)
        at jrautorunner/test.run.TestRunner.run(TestRunner.java:28)
        at jrautorunner/test.run.CLI.main(CLI.java:29)
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.IllegalClassFormatException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        Test returned with 42 from pid 29964
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 17 more
I have done auto-modules of all the dep jars ie bytebuddy. My own module-info looks like this:
module autotest {
  opens autotest;
  requires net.bytebuddy;
  requires junit;
}
if does not fail if jdk modules are not used.
When I run the program with jrebel (as I normally do) I get a more detailed error message:
class net.bytebuddy.dynamic.loading.NoOpClassFileTransformer (in module net.bytebuddy) cannot access class java.lang.instrument.ClassFileTransformer (in module java.instrument) because module net.bytebuddy does not read module java.instrument
Maybe byte-buddy should have a module-info.java?
I used latest release byte-buddy: 
<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <version>1.11.0</version>
</dependency>

**Comment by raphw** [comment]
You are right, Byte Buddy only depends on *java.instrument* statically, but I forgot to remove one reference to the instrumentation API. I just fixed this on master and it will work from the next release. In the mean time, you can add:

    requires java.instrument;

to your module info and avoid this error.

**Comment by andresluuk** [comment]
Thank you. Tried it out. It worked with: requires java.instrument; in my module-info.java
Will wait for the next version and then use the one with the fix.
