### ISSUE TITLE
Can not resolve for inner class for a codegen code

### ISSUE THREAD

**Issue by Aitozi** [raphw/byte-buddy#1055]
I have a reproduce program below , test three case 

- enhance inner class [work]
- enhance codegen class [work]
- enhance codegen class with inner class  [**not work**]

```
package bytebuddy;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.This;
import net.bytebuddy.utility.JavaModule;

import java.lang.instrument.Instrumentation;

import static net.bytebuddy.matcher.ElementMatchers.isSubTypeOf;
import static net.bytebuddy.matcher.ElementMatchers.named;

public class Agent {

    public static void premain(String arguments, Instrumentation instrumentation) {
        System.out.println("premain");
        AgentBuilder builder =
                new AgentBuilder.Default()
                        .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                        .type(isSubTypeOf(AbstractTest.class))
                        .transform(
                                new AgentBuilder.Transformer() {

                                    @Override
                                    public DynamicType.Builder<?> transform(
                                            DynamicType.Builder<?> builder,
                                            TypeDescription typeDescription,
                                            ClassLoader classLoader,
                                            JavaModule javaModule) {
                                        return builder.method(named("test"))
                                                .intercept(MethodDelegation.to(HelloClass.class));
                                    }
                                });
        builder.installOn(instrumentation);
    }

    public static class HelloClass {

        @RuntimeType
        public static void intercept(@This Object target) {
            System.out.println("intercept " + target.getClass().getName());
        }
    }
}
```

```
package bytebuddy;

public abstract class AbstractTest {
    public abstract void test();
}
```
```
package bytebuddy;

public class NotCodegenTest extends AbstractTest {

    private INNER innerVal = new INNER();

    @Override
    public void test() {
        System.out.println("NotCodegenTest");
    }

    public class INNER {}
}
```

```
package bytebuddy;

import org.codehaus.janino.SimpleCompiler;

public class AgentTest {

    public static void main(String[] args) throws Exception {
        if (args[0].equalsIgnoreCase("codegen-inner")) {
            testCodegenInner();
        } else if (args[0].equalsIgnoreCase("inner")) {
            testInner();
        } else if (args[0].equalsIgnoreCase("codegen")) {
            testCodegen();
        }
    }

    public static void testCodegen() throws Exception {
        String klass1 =
                "public class CodengenAgentTest extends bytebuddy.AbstractTest {\n"
                        + "        public void test() {\n"
                        + "            System.out.println(\"test invoked\");\n"
                        + "        }\n"
                        + "    }";
        SimpleCompiler compiler = new SimpleCompiler();
        compiler.cook(klass1);
        Class kclass1 = compiler.getClassLoader().loadClass("CodengenAgentTest");
        Object o1 = kclass1.newInstance();
        ((AbstractTest) o1).test();
    }

    public static void testCodegenInner() throws Exception {
        String klass1 =
                "    public class CodengenAgentTest extends bytebuddy.AbstractTest {\n"
                        + "        INNER innerVal = new INNER();\n"
                        + "        public void test() {\n"
                        + "            System.out.println(\"test invoked\");\n"
                        + "        }\n"
                        + "\n"
                        + "        public class INNER {}\n"
                        + "    }";
        SimpleCompiler compiler = new SimpleCompiler();
        compiler.cook(klass1);
        Class kclass1 = compiler.getClassLoader().loadClass("CodengenAgentTest");
        Object o1 = kclass1.newInstance();
        ((AbstractTest) o1).test();
    }

    public static void testInner() {
        NotCodegenTest notCodegenTest = new NotCodegenTest();
        notCodegenTest.test();
    }
}
```

I use janino to generate code at runtime, i want to enhance the generated code. When generated code is a plain class, it works as expected by output 

```
intercept CodengenAgentTest
```
But if the codegen code has a inner class, and has a field `innerVal` point to the inner type it will fail, with the error output

```
[Byte Buddy] ERROR CodengenAgentTest [org.codehaus.janino.ByteArrayClassLoader@6379eb, null, Thread[main,5,main], loaded=false]
java.lang.IllegalStateException: Cannot resolve type description for CodengenAgentTest$INNER
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:973)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8409)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.isStatic(ModifierReviewable.java:329)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.getInnerClassCount(TypeDescription.java:8041)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw$RawAnnotatedType.getDeclaredAnnotations(TypePool.java:3635)
```
I think it caused by that the inner class can not be found in classloader, it is loaded by `org.codehaus.janino.ByteArrayClassLoader`. 

Is there any way to work with a generated inner class ? @raphw

**Comment by raphw** [comment]
Inner classes are in no way special to the JVM. They are merely a construct used by the Java language. Have you tried the `TypeStrategy.Default.DECORATE` strategy? It restricts your options on instrumentation but avoids resolving parts of the type.

**Comment by Aitozi** [comment]
I try to use the `TypeStrategy.Default.DECORATE` but it seems can not work,
```
new AgentBuilder.Default()
                        .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                        .with(AgentBuilder.TypeStrategy.Default.DECORATE)
                        .type(isSubTypeOf(AbstractTest.class))
```
 with the exception

```
[Byte Buddy] ERROR CodengenAgentTest [org.codehaus.janino.ByteArrayClassLoader@6379eb, null, Thread[main,5,main], loaded=false]
java.lang.UnsupportedOperationException: Cannot intercept method for decorated type: class CodengenAgentTest
	at net.bytebuddy.dynamic.scaffold.inline.DecoratingDynamicTypeBuilder.invokable(DecoratingDynamicTypeBuilder.java:446)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.invokable(DynamicType.java:3607)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.method(DynamicType.java:3593)
	at bytebuddy.Agent$1.transform(Agent.java:34)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11125)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11063)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10805)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:11455)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:11402)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10970)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.codehaus.janino.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bytebuddy.AgentTest.testCodegenInner(AgentTest.java:47)
	at bytebuddy.AgentTest.main(AgentTest.java:13)
```
Besides 

> Inner classes are in no way special to the JVM 

I also test the normal inner class case, it can be enhanced as expected. But if the inner class is generated by janino , it can not work. Does it caused by the special classloader? At the time of transform `CodengenAgentTest`, classFileLocator will try to locate the inner class `CodengenAgentTest$INNER` . But the default classFileLocator may be can not found class loaded by `org.codehaus.janino.ByteArrayClassLoader`.  @raphw

**Comment by raphw** [comment]
Indeed, if you are using `MethodDelegation`, this cannot work, sorry, I thought you were using decoration only, such as `Advice`.

I assume that it is due to the class loader of Janino, Byte Buddy queries an instrumented class's `ClassLoader` via `getResourceAsStream` where it asks for the *.class* file for this class. Does the class loader offer such a class file? I am not sure how Janino works. Does it compile before execution or does it runtime generate the code? The class loader must be able to provide such a class file but I assume that Janino might not implement the resource lookup correctly.

Note that you can provide a custom `ClassFileLocator` to resolve a class file from a different source.

**Comment by Aitozi** [comment]
You mean that the `TypeStrategy.Default.DECORATE` may work with `Advice` api ? I have not try that. What's the difference between `MethodDelegation` and `Advice`, i can not find some doc about `Advice` usage? 

FYI, I solved this problem as you say. By enhance the Janino `cook` method to dump the class file to a folder. Then use the `ForFolder` strategy to lookup class, if it can not be found in the default classloader .

**Comment by raphw** [comment]
Advice (used via `visit`) wraps a method without creating a new method. The code is typically inlined. `MethodDelegation` delegates to another method and replaces the existing method. To access the original code, you can delegate back to the class but this requires that Byte Buddy copies the original method into a new method what is not allowed for retransformation (and decorating code).

**Comment by Aitozi** [comment]
Get it, thanks
