### ISSUE TITLE
Cannot resolve type description for com.alibaba.dubbo.common.bytecode.proxy1

### ISSUE THREAD

**Issue by szsuyuji** [raphw/byte-buddy#1099]
2021-08-20 15:36:06.258 localhost-startStop-1 WARN: matcher type error: java.lang.IllegalStateException: Cannot resolve type description for com.alibaba.dubbo.common.bytecode.proxy1
	at com.chebada.apm.dep.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:134)
	at com.chebada.apm.dep.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
	at com.chebada.apm.dep.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:7005)
	at com.chebada.apm.dep.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3329)
	at com.chebada.apm.dep.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:295)
	at com.chebada.apm.dep.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:266)
	at com.chebada.apm.dep.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:35)
	at com.chebada.apm.dep.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:15)
	at com.chebada.apm.dep.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)

source code for javassit generate code
https://github.com/szsuyuji/dubbo/blob/e28acb0acfeddbcae1aa8f212cd946a7d34d7b3f/dubbo-common/src/main/java/com/alibaba/dubbo/common/bytecode/Proxy.java   

config
![image](https://user-images.githubusercontent.com/1931764/130201866-350ce2f6-66a7-4448-b37e-8e40228298d2.png)

**Comment by szsuyuji** [comment]
![image](https://user-images.githubusercontent.com/1931764/130216236-e71104c4-cf06-49c2-b8c3-0144fc2db7dd.png)
failed

**Comment by szsuyuji** [comment]
![image](https://user-images.githubusercontent.com/1931764/130217229-7088648c-a55e-4958-890a-7daefe769adc.png)
webappClassLoader parent URLClassLoader

**Comment by raphw** [comment]
This seems like a generated class, possibly the class cannot be located for this reason. Generated classes often have no byte code present and are therefore not resolvable what causes this error.

This does not have to be a problem. Often such proxies are not required for instrumentation and the error occurs during matching, not instrumentation.

**Comment by szsuyuji** [comment]
@raphw thanks ，i will ignore the package
