### ISSUE TITLE
java.lang.ClassFormatError: Duplicate method name&signature in class file

### ISSUE THREAD

**Issue by novoj** [raphw/byte-buddy#1106]
Creating a class ends up with duplicate method name&signature error:

```
java.lang.ClassFormatError: Duplicate method name&signature in class file com/fg/edee/proxy/bytebuddy/error/TestClass$AbstractClass$ByteBuddy$HFvUraO3

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.access$300(ByteArrayClassLoader.java:53)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:677)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:629)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.doPrivileged(ByteArrayClassLoader.java)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:398)
```

The test case that replicates the behaviour is as follows:

``` java
public class DuplicateMethodNameAndSignatureTest {
	private static final String INVOCATION_HANDLER_FIELD = "dispatcherInvocationHandler";

	@Test
	public void shouldNotProduceDuplicateMethodNameAndSignatureError() throws InstantiationException, IllegalAccessException {
		assertNotNull(new ExampleClass(new ByteBuddyDispatcherInvocationHandler()));

		final Class<?> proxy = new ByteBuddy().subclass(AbstractClass.class)
				.implement(Trait.class)
			// WE'LL CREATE PRIVATE FINAL FIELD FOR STORING OUR INVOCATION HANDLER ON INSTANCE
			.defineField(INVOCATION_HANDLER_FIELD, ByteBuddyDispatcherInvocationHandler.class, Modifier.PRIVATE + Modifier.FINAL)
			// LET'S HAVE PUBLIC CONSTRUCTOR
			.defineConstructor(Modifier.PUBLIC)
			// ACCEPTING SINGLE ARGUMENT OF OUR INVOCATION HANDLER
			.withParameter(ByteBuddyDispatcherInvocationHandler.class)
			// AND THIS CONSTRUCTOR WILL
			.intercept(
				FieldAccessor.ofField(INVOCATION_HANDLER_FIELD).setsArgumentAt(0)
			)
			// AND TRAP ALL METHODS EXCEPT CONSTRUCTORS AND FINALIZER
			.method(
				ElementMatchers.noneOf(
					ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()
				)
			)
			// AND DELEGATE CALL TO OUR INVOCATION HANDLER STORED IN PRIVATE FIELD OF THE CLASS
			.intercept(MethodDelegation.toField(INVOCATION_HANDLER_FIELD))
			// NOW CREATE THE BYTE-CODE
			.make()
			// AND LOAD IT IN CURRENT CLASSLOADER
			.load(DuplicateMethodNameAndSignatureTest.class.getClassLoader())
			// RETURN
			.getLoaded();

		final Object theInstance = proxy.newInstance();
		assertNotNull(theInstance);
	}

	public static class ExampleClass extends AbstractClass implements Trait {
		private final ByteBuddyDispatcherInvocationHandler dispatcherInvocationHandler;

		public ExampleClass(ByteBuddyDispatcherInvocationHandler dispatcherInvocationHandler) {
			this.dispatcherInvocationHandler = dispatcherInvocationHandler;
		}

	}

	public static abstract class AbstractClass implements SomeSharedInterface {

	}

	public interface Trait extends SomeSharedInterface {

	}

	public interface SomeSharedInterface {

		default String getCode() {
			return "whatever";
		}

	}

	public static class ByteBuddyDispatcherInvocationHandler {

		@RuntimeType
		public Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			return superMethod.call();
		}

	}

}
```

I have more complicated setup in my own code, but I was able to cut the complexity to this minimal setup which produces the error.

`ExampleClass` is the class that is expected to be created - Java compiles it fine. Then I try to create the same class with ByteBuddy. The problem is connected somehow with using `MethodDelegate` and also having `SomeSharedInterface` implemented twice by `AbstractClass` and also `Trait` interface - both mixing in the same generated subclass.

**Comment by novoj** [comment]
The ByteBuddy is repackaged with `jarjar` maven plugin in my library - that's why the package `com/fg/edee/proxy/bytebuddy` is mentioned in the error (just to clarify).

**Comment by raphw** [comment]
You found a bug, it turns out. Byte Buddy creates two accessors, one for the super method call and one for the default method call, but names them the same as it does not consider that both can exist at the same time for hierarchies as yours. I already fixed this on master, and it will be solved in the next version.

For your constructor call, you need to invoke the super constructor first. Add:

`MethodCall.invoke(AbstractClass.class.getConstructor()).onSuper().andThen`

You might also want to add a `ConstructorStrategy` to disable creating default constructors.

**Comment by novoj** [comment]
Thank you for answer. I tried following - but the error stays the same:

```java
final Class<?> proxy = new ByteBuddy().subclass(AbstractClass.class, Default.NO_CONSTRUCTORS)
				.implement(Trait.class)
			// WE'LL CREATE PRIVATE FINAL FIELD FOR STORING OUR INVOCATION HANDLER ON INSTANCE
			.defineField(INVOCATION_HANDLER_FIELD, ByteBuddyDispatcherInvocationHandler.class, Modifier.PRIVATE + Modifier.FINAL)
			// LET'S HAVE PUBLIC CONSTRUCTOR
			.defineConstructor(Modifier.PUBLIC)
			// ACCEPTING SINGLE ARGUMENT OF OUR INVOCATION HANDLER
			.withParameter(ByteBuddyDispatcherInvocationHandler.class)
			// AND THIS CONSTRUCTOR WILL
			.intercept(
				MethodCall.invoke(AbstractClass.class.getConstructor())
					.onSuper()
					.andThen(FieldAccessor.ofField(INVOCATION_HANDLER_FIELD).setsArgumentAt(0))
			)
			// AND TRAP ALL METHODS EXCEPT CONSTRUCTORS AND FINALIZER
			.method(
				ElementMatchers.noneOf(
					ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()
				)
			)
			// AND DELEGATE CALL TO OUR INVOCATION HANDLER STORED IN PRIVATE FIELD OF THE CLASS
			.intercept(MethodDelegation.toField(INVOCATION_HANDLER_FIELD))
			// NOW CREATE THE BYTE-CODE
			.make()
			// AND LOAD IT IN CURRENT CLASSLOADER
			.load(DuplicateMethodNameAndSignatureTest.class.getClassLoader())
			// RETURN
			.getLoaded();
```

But I might wait for the next release where it's going to be fixed, as you wrote.

**Comment by raphw** [comment]
Yes, the error only goes away after the patch in Byte Buddy. But once you used the patched version you'd get a new one that can be fixed using the suggested fix.

**Comment by raphw** [comment]
Fixed in the latest release.
