### ISSUE TITLE
Concurrent Bazel test runs silently fail to install ByteBuddy agent

### ISSUE THREAD

**Issue by fmeum** [raphw/byte-buddy#1111]
I am transitively using ByteBuddy through [mockk](https://github.com/mockk/mockk) in a Bazel project and observed tests to fail when they are run in parallel by [Bazel's test runner](https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/junit/runner/BazelTestRunner.java) due to `ByteBuddyAgent.install()` silently returning `null` in all but one of the parallel test runs. On the mockk side, this issue is being tracked as https://github.com/mockk/mockk/issues/627, but I tracked it down to ultimately being caused by this underlying issue.

@raphw This might just as well be a bug in Bazel (or a generally impossible thing to do, cleanly attaching an agent multiple times in parallel), but it is an issue that I would be very interested in hearing your thoughts on. Let me know if I can provide any help from the Bazel side.

A reproducing script which assumes that [Bazelisk](https://github.com/bazelbuild/bazelisk) is installed, which in turn downloads and runs Bazel:
```
#!/usr/bin/env bash

cat << EOF > .bazelversion
4.2.1
EOF

cat << EOF > WORKSPACE
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "net_bytebuddy_byte_buddy_agent",
    artifact = "net.bytebuddy:byte-buddy-agent:1.11.15",
)

maven_jar(
    name = "junit_junit",
    artifact = "junit:junit:4.12",
)
EOF

cat << EOF > BUILD
java_test(
    name = "test",
    srcs = ["TestByteBuddyAgent.java"],
    test_class = "TestByteBuddyAgent",
    deps = [
        "@net_bytebuddy_byte_buddy_agent//jar",
        "@junit_junit//jar",
    ],
)
EOF

cat << EOF > TestByteBuddyAgent.java
import net.bytebuddy.agent.ByteBuddyAgent;
import org.junit.Test;

import static org.junit.Assert.assertNotEquals;

public class TestByteBuddyAgent {

    @Test
    public void testByteBuddyAgent() {
        assertNotEquals(ByteBuddyAgent.install(), null);
    }
}
EOF

# Passes (single test)
bazelisk test //:test
# Passes (two tests running serially)
bazelisk test //:test --runs_per_test=2 --local_test_jobs=1
# Fails (two tests running in parallel, one fails)
bazelisk test //:test --runs_per_test=2
```

The logs from the failing test run:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.197
There was 1 failure:
1) testByteBuddyAgent(TestByteBuddyAgent)
java.lang.AssertionError: Values should be different. Actual: null
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failEquals(Assert.java:185)
        at org.junit.Assert.assertNotEquals(Assert.java:161)
        at org.junit.Assert.assertNotEquals(Assert.java:175)
        at TestByteBuddyAgent.testByteBuddyAgent(TestByteBuddyAgent.java:10)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
        at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-09-16 13:55:37 --
```

**Comment by raphw** [comment]
That's unexpected. If the value is `null`, Byte Buddy runs an attachment which, if fails, runs an installation which should throw an exception if it fails. I will need to see if I can run your script with some additional output from a snapshot and see where things go wrong. Thanks for the detailed report!

**Comment by fmeum** [comment]
Thanks for looking into it!

You can change the content of `BUILD` to 
```starlark
java_test(
    name = "test",
    srcs = ["TestByteBuddyAgent.java"],
    test_class = "TestByteBuddyAgent",
    deps = [
        ":byte_buddy_agent",
        # "@net_bytebuddy_byte_buddy_agent//jar",
        "@junit_junit//jar",
    ],
)

java_import(
    name = "byte_buddy_agent",
    jars = [
        "byte_buddy_agent.jar",
    ]
)
```
to have the test pick up a manually built `byte_buddy_agent.jar` in the same directory.

Note that the Bazel test runner [does play some tricks with ClassLoaders](https://github.com/bazelbuild/bazel/blob/11066c7731b5a16f2f11db93f6716a1595650aad/src/java_tools/junitrunner/java/com/google/testing/junit/runner/PersistentTestRunner.java#L49).

**Comment by raphw** [comment]
From a first look, it seems as if the `VirtualMachine` API is not working as expected: https://docs.oracle.com/javase/7/docs/jdk/api/attach/spec/com/sun/tools/attach/VirtualMachine.html

The problem is that the attachment runs ok, saying that the JVM indicates that the agent execution (that registers the `Instrumentation` instance) was successful, but nevertheless no such instance is found. From debugging manually, it is obvious that the agentmain method of the targeted jar is never executed in the parallel case.

I wonder if Bazle is doing some JVMTI in the parallel case and corrupts things for later runs. I'll try to adjust the example to not even involve Byte Buddy for a better reproduction.

**Comment by raphw** [comment]
It would be interesting what the outcome of this build would be:

```java

import com.sun.tools.attach.VirtualMachine;

import java.io.InputStream;
import java.lang.instrument.Instrumentation;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;

public class Sample {

    public static void main(String[] args) throws Exception {
        Path agent = Files.createTempFile("myagent", ".jar");

        Manifest manifest = new Manifest();
        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
        manifest.getMainAttributes().put(new Attributes.Name("Agent-Class"), Sample.class.getName());

        try (JarOutputStream outputStream = new JarOutputStream(Files.newOutputStream(agent), manifest)) {
            outputStream.putNextEntry(new JarEntry(Sample.class.getName().replace('.', '/') + ".jar"));
            try (InputStream input = Sample.class.getResourceAsStream(Sample.class.getSimpleName() + ".class")) {
                byte[] buff = new byte[1024];
                int length;
                while ((length = input.read(buff)) != -1) {
                    outputStream.write(buff, 0, length);
                }
            }
            outputStream.closeEntry();
        }

        long pid = ProcessHandle.current().pid();

        VirtualMachine vm = VirtualMachine.attach(Long.toString(pid));

        vm.loadAgent(agent.toAbsolutePath().toString());

        vm.detach();
    }

    public static void agentmain(String s, Instrumentation inst) {
        System.out.println("This should be printed!");
    }
}
```

This should reach the printed line in each case but apparently this cannot be built due to the module setup.

This makes me wonder: maybe the JVM is not configured with the right modules? Might it be related to that?

**Comment by raphw** [comment]
It does not even recognize `java.lang.ProcessHandle` as a valid type. I wonder if there's a custom JDK involved.

**Comment by fmeum** [comment]
Bazel uses a modified Azul JDK for compilation, but by default runs tests with the local JVM specified by `JAVA_HOME`.

**Comment by fmeum** [comment]
I can compile and run this test:
```java
import org.junit.Test;
import net.bytebuddy.agent.ByteBuddyAgent;

import com.sun.tools.attach.VirtualMachine;

import java.io.InputStream;
import java.lang.instrument.Instrumentation;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;

import static org.junit.Assert.assertNotEquals;

public class TestByteBuddyAgent {

    public void setUpAgent() throws Exception {
        Path agent = Files.createTempFile("myagent", ".jar");

        Manifest manifest = new Manifest();
        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
        manifest.getMainAttributes().put(new Attributes.Name("Agent-Class"), TestByteBuddyAgent.class.getName());

        try (JarOutputStream outputStream = new JarOutputStream(Files.newOutputStream(agent), manifest)) {
            outputStream.putNextEntry(new JarEntry(TestByteBuddyAgent.class.getName().replace('.', '/') + ".jar"));
            try (InputStream input = TestByteBuddyAgent.class.getResourceAsStream(TestByteBuddyAgent.class.getSimpleName() + ".class")) {
                byte[] buff = new byte[1024];
                int length;
                while ((length = input.read(buff)) != -1) {
                    outputStream.write(buff, 0, length);
                }
            }
            outputStream.closeEntry();
        }

        long pid = ProcessHandle.current().pid();

        VirtualMachine vm = VirtualMachine.attach(Long.toString(pid));

        vm.loadAgent(agent.toAbsolutePath().toString());

        vm.detach();
    }

    @Test
    public void testByteBuddyAgent() throws Exception {
        setUpAgent();
    }

    public static void agentmain(String s, Instrumentation inst) {
        System.out.println("This should be printed!");
    }
}
```

It fails (even with a single run) and produces:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.124
There was 1 failure:
1) testByteBuddyAgent(TestByteBuddyAgent)
java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:57)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at TestByteBuddyAgent.setUpAgent(TestByteBuddyAgent.java:40)
	at TestByteBuddyAgent.testByteBuddyAgent(TestByteBuddyAgent.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-09-17 10:33:12 --
```

Bazel uses the following JDK to execute the test:
```
❯ java --version
openjdk 15.0.3 2021-04-20
OpenJDK Runtime Environment (build 15.0.3+3-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 15.0.3+3-Ubuntu-1, mixed mode, sharing)
```

**Comment by fmeum** [comment]
If I run this with:
```
bazel test //:test --jvmopt=-Djdk.attach.allowAttachSelf=true
```
the test passes and the message is printed. 

Something very interested happens when I additionally pass `--runs_per_test=2`: Both runs pass, but one has the `agentmain` message printed twice, the other not at all:
```
Run 1:
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
-----------------------------------------------------------------------------
JUnit4 Test Runner
.
Time: 0.118

OK (1 test)


BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-09-17 10:39:06 --

Run 2:
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
-----------------------------------------------------------------------------
JUnit4 Test Runner
.This should be printed!
This should be printed!

Time: 0.211

OK (1 test)


BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-09-17 10:39:06 --
```

**Comment by raphw** [comment]
So weird. For a better test, could you try:

```
import java.io.InputStream;
import java.lang.instrument.Instrumentation;
import java.lang.management.ManagementFactory;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.ThreadLocalRandom;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;

public class Sample {

    private static volatile String value;

    public static void main(String[] args) throws Exception {
        String control = Integer.toString(ThreadLocalRandom.current().nextInt());

        Path agent = Files.createTempFile("myagent", ".jar");

        Manifest manifest = new Manifest();
        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
        manifest.getMainAttributes().put(new Attributes.Name("Agent-Class"), Sample.class.getName());

        try (JarOutputStream outputStream = new JarOutputStream(Files.newOutputStream(agent), manifest)) {
            outputStream.putNextEntry(new JarEntry(Sample.class.getName().replace('.', '/') + ".jar"));
            try (InputStream input = Sample.class.getResourceAsStream(Sample.class.getSimpleName() + ".class")) {
                byte[] buff = new byte[1024];
                int length;
                while ((length = input.read(buff)) != -1) {
                    outputStream.write(buff, 0, length);
                }
            }
            outputStream.closeEntry();
        }

        String name = ManagementFactory.getRuntimeMXBean().getName();
        String pid = name.substring(0, name.indexOf('@'));

        Class<?> vmType = Class.forName("com.sun.tools.attach.VirtualMachine");
        Object vm = vmType.getMethod("attach", String.class).invoke(null, pid);

        vmType.getMethod("loadAgent", String.class, String.class).invoke(vm, agent.toAbsolutePath().toString(), control);

        vmType.getMethod("detach").invoke(vm);

        if (!control.equals(value)) {
            throw new RuntimeException("Expected " + control + " got " + value);
        }
    }

    public static void agentmain(String s, Instrumentation inst) {
        value = s;
    }
}
```

Still not sure why the build fails for me.

**Comment by raphw** [comment]
Yes, I got it running now and get an error without Byte Buddy in the picture. This is very weird that it does not work in direct violation to the contract. Likely some issue in Bazle.

**Comment by fmeum** [comment]
I can confirm that your last test case fails in the same way as my original reproducer when run in parallel. 
However, the test case requires me to pass `--jvmopt=-Djdk.attach.allowAttachSelf=true` to Bazel or it already fails when executed with a single run. This was different with my original reproducer calling `ByteBuddy.install`, which passed as a single run without setting this JVM option. Do you have an idea why the two reproducers differ in this regard?

Thank you very much for the detailed analysis in any case, I will file an issue at the Bazel repo.

**Comment by raphw** [comment]
Yes, Byte Buddy works around the restriction by creating a new process to run the code. If the restriction is lifted by the command line, Byte Buddy more or less runs the same code as in the sample. as it yields the same result, to simplify the test case, I rather used the option in the reproducer.

If you can, please link the ticket you create. I also improved the error handling in Byte Buddy such that null is no longer returned.

**Comment by fmeum** [comment]
I delved deeper and found the root cause to be that Bazel's sandboxing makes multiple JVMs run with the same process ID and `/tmp` dir, which results in a collision between the [sockets used by VirtualMachine](https://github.com/openjdk/jdk/blob/7c9868c0b3c9bd3d305e71f91596190813cdccce/src/jdk.attach/linux/classes/sun/tools/attach/VirtualMachineImpl.java#L279). A proper workaround is to ensure that the sandboxes use isolated `/tmp` directories: https://github.com/bazelbuild/bazel/issues/3236#issuecomment-587752609.

**Comment by raphw** [comment]
Brilliant, thanks for digging!

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/pull/20136 is the fix in Bazel 7 and later. Each sandbox gets its own `/tmp` that isn't shared with the host.
