### ISSUE TITLE
IllegalStateException on Android with activeProguard on versions 1.11.1 and higher

### ISSUE THREAD

**Issue by slorper** [raphw/byte-buddy#1114]
I am creating a Bytebuddy class with the following code snippet:
```
Class<?> dynamicType = new ByteBuddy()
                .subclass(service.getClass())
                .method(ElementMatchers.named("isEnabled"))
                .intercept(FixedValue.value(false))
                .make()
                .load(service.getClass().getClassLoader(), strategy)
                .getLoaded();
```

But on Android, when codeShrinkage is active, the code throws an exception at the make(step).

```
java.lang.IllegalStateException: Could not invoke proxy: Method not available on current VM: java.lang.reflect.Executable.c []
at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$f.a(JavaDispatcher.java:1068)
at net.bytebuddy.utility.dispatcher.JavaDispatcher$i.invoke(JavaDispatcher.java:1139)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at X8.$Proxy7.c(Unknown Source)
at X8.d$d.size(ParameterList.java:226)
at X8.d$f.size(ParameterList.java:596)
at X8.d$a.f1(ParameterList.java:105)
at X8.a$a.l0(MethodDescription.java:894)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$a$b.e(MethodGraph.java:922)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$a$c.e(MethodGraph.java:1107)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.e(MethodGraph.java:634)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.a(MethodGraph.java:596)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.b(MethodGraph.java:615)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.e(MethodGraph.java:629)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.a(MethodGraph.java:596)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.b(MethodGraph.java:615)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.e(MethodGraph.java:629)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.d(MethodGraph.java:567)
at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$a.c(MethodGraph.java:465)
at net.bytebuddy.dynamic.scaffold.MethodRegistry$b.b(MethodRegistry.java:471)
at net.bytebuddy.dynamic.scaffold.subclass.a.h(SubclassDynamicTypeBuilder.java:213)
at net.bytebuddy.dynamic.scaffold.subclass.a.b(SubclassDynamicTypeBuilder.java:204)
at net.bytebuddy.dynamic.a$a$a.c(DynamicType.java:3658)
at net.bytebuddy.dynamic.a$a$a$b.c(DynamicType.java:3896)
```

**Comment by raphw** [comment]
The problem here is that Byte Buddy is locating methods by the name of the dispatcher method. After obfuscation, the methods are no longer matching up with the method that is intended to be targeted. A workaround is that Byte Buddy can add annotations to explicitly name all targets. This can be automated via a build plugin.

This can be done within the next two releases, I already implemented it on master, but it requires the plugin to be available within Byte Buddy to bootstrap itself.
