### ISSUE TITLE
SkyWalking faces a break in byte-buddy upgrade from 1.10.19 to latest 1.11.16

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#1115]
Hi 

This upgrade operation is initiated in https://github.com/apache/skywalking-java/pull/30, which doesn't show any compiling level issue. But after I submitted pull request, and some issues show up in the plugin tests.
Those plugin tests are really loading the latest agent(depend on 1.11.16) and running a real service. 

According to this CI logs, https://github.com/apache/skywalking-java/pull/30/checks?check_run_id=3661574946

```
  Error: 9-21 09:36:37:414] [ERROR] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175) - Servlet.service() for servlet [dispatcherServlet] in context with path [/jdk-http-scenario] threw exception [Handler dispatch failed; nested exception is java.lang.ExceptionInInitializerError] with root cause
  java.lang.ClassNotFoundException: org/apache/skywalking/apm/dependencies/net/bytebuddy/implementation/LoadedTypeInitializer
  	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_102]
  	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_102]
  	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137) ~[skywalking-agent.jar:8.8.0-SNAPSHOT]
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
  	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
  	at sun.net.www.http.HttpClient.<clinit>(HttpClient.java:163) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[?:1.8.0_102]
  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_102]
  	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_102]
  	at org.apache.skywalking.apm.testcase.jdkhttp.controller.CaseController.testcase(CaseController.java:46) ~[classes!/:?]
```

As I check locally, `org/apache/skywalking/apm/dependencies/net/bytebuddy/implementation/LoadedTypeInitializer` is in the shaded package. You also could download it from our CI cached artifacts, https://github.com/apache/skywalking-java/suites/3826509443/artifacts/94739312

The test application's source codes are here, https://github.com/apache/skywalking-java/tree/main/test/plugin/scenarios/jdk-http-scenario, which is compiled through JDK1.8

**Comment by wu-sheng** [comment]
I noticed it imported `edu.umd.cs.findbugs.annotations.SuppressFBWarnings`, and used in `Compound`.
Is this a `mis-import` or some dependency issue?

**Comment by raphw** [comment]
Should not be a problem as annotations are ignored if their type is not present.

There's sn ubderlying java.lang.ExceptionInInitializerError in the class that cannot be loaded which causes the ClassNotFound exception. Could you extract that root cause?

**Comment by wu-sheng** [comment]
> java.lang.ClassNotFoundException: org/apache/skywalking/apm/dependencies/net/bytebuddy/implementation/LoadedTypeInitializer

I think this is the root. Do you expect more than this?

**Comment by raphw** [comment]
I think I understand the problem. Can you try running from master? I fixed the likely reason there.

**Comment by wu-sheng** [comment]
OK, let me give a try locally.

**Comment by wu-sheng** [comment]
@raphw It works. I will wait for your next release, do you have any plan?

**Comment by raphw** [comment]
Some time this week!
