### ISSUE TITLE
When extending exception `fillInStackTrace` throws NullPointerException

### ISSUE THREAD

**Issue by novoj** [raphw/byte-buddy#1123]
I know this use-case is a little bit weird, but our developer needs to workaround problem in third party library by extending exceptions that are produced by this library and add some additional data to them. Generated class throws NullPointerException in constructor in the place where super class calls native logic in `fillInStackTrace`.

Test case that demonstrates this problem is as follows:

``` java
public class ExceptionExtensionTest {

	@Test
	public void shouldNotFailExtendingException() throws NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
		final Class<? extends IllegalArgumentException> exceptionExtension = new ByteBuddy()
			.subclass(IllegalArgumentException.class)
			.defineField("handler", CallHandler.class, Modifier.PRIVATE + Modifier.FINAL)
			.defineConstructor(Modifier.PUBLIC)
			.withParameters(CallHandler.class, String.class, Throwable.class)
			.intercept(
				MethodCall
					// CALL DEFAULT (NON-ARG) CONSTRUCTOR ON SUPERCLASS
					.invoke(IllegalArgumentException.class.getConstructor(String.class, Throwable.class))
					.onSuper()
					.withArgument(1, 2)
					.andThen(FieldAccessor.ofField("handler").setsArgumentAt(0))
			)
			.method(ElementMatchers.noneOf(ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()))
			.intercept(MethodDelegation.toField("handler"))
			.make()
			.load(ExceptionExtensionTest.class.getClassLoader())
			.getLoaded();
		final Constructor<? extends IllegalArgumentException> constructor = exceptionExtension.getConstructor(CallHandler.class, String.class, Throwable.class);
		final IllegalArgumentException resultExtension = constructor.newInstance(new CallHandler(), "Test", new RuntimeException("Whatever"));
		assertNotNull(resultExtension);
	}

	public static class CallHandler {

		@RuntimeType
		public Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			return superMethod.call();
		}

	}

}
```

I tried to simplify the original scenario as much as possible. The problem doesn't occur when delegation logic is skipped - i.e. when these lines are removed, test case works:

``` java
.method(ElementMatchers.noneOf(ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()))
.intercept(MethodDelegation.toField("handler"))
```

**Comment by novoj** [comment]
I probably found out where the problem lies while sleeping :)

It's probably the same situation I encountered yesterday when trying to instantiate proxies (with similar setup) that called some method of the class in the constructor. The scenario is as follows:

- extended class first calls super constructor AND THEN initializes `handler` field with the `CallHandler`
- super constructor calls a method i the class
- ByteBuddy delegates the call to the `handler` field - but this is not yet initialized with the handler
- NPE is thrown

I suppose this would be the same scenario but the call is hidden inside native method somehow.
Is there any way how to say to ByteBuddy to delegate method to the handler only if it's not null (otherwise delegate call to super)? I didn't find the way myself.

Thanks for help.

**Comment by raphw** [comment]
You could try to pass `TypeResolutionStrategy.Active` to the `make` method of the dynamic type. This will make the type self-initialize in its class initializer before any code is run.

For your case, you would normally create a "private" constructor that only you use, and then set the field after. You are right about your conclusion otherwise.

**Comment by novoj** [comment]
Unfortunatelly this doesn't help:

``` java
.make(new TypeResolutionStrategy.Active())
```

The error stays the same.

As I don't have the superclass `exception` under the control I can't add or rely on non-args constructor. Isn't there any possibility how to say that:

```
.intercept(MethodDelegation.toField("handler").orWhenNull(MethodCall.invokeSuper()))
```

Or I'm not sure whether it would help because changing the lines to:

```
.method(ElementMatchers.noneOf(ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()))
.intercept(MethodCall.invokeSuper())
```

To test at least part of the hypothesis I get:

```
java.lang.IllegalStateException: Cannot invoke default method on public boolean java.lang.Object.equals(java.lang.Object)

	at net.bytebuddy.implementation.DefaultMethodCall$Appender.apply(DefaultMethodCall.java:217)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:710)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:695)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:602)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5811)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2193)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3658)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3896)
```

**Comment by raphw** [comment]
The active strategy only helps if you define static fields inline, then they will be set prior to running any code but in your case this does indeed not help. What you would need to do for the behavior you are looking for is to define a static dispatcher and delegate manually such as:

	public static class CallHandler {
		@RuntimeType
		public static Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@FieldValue("handler") CallHandler handler,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
                  if (handler == null) {
                    return superMethod.call();
                  } else {
                    return handler.interceptMethodCall(...);
                  }
		}

		public Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			return superMethod.call();
		}
	}

**Comment by novoj** [comment]
To summarize - the code now looks like this:

``` java
public class ExceptionExtensionTest {

	@Test
	public void shouldNotFailExtendingException() throws NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
		final Class<? extends IllegalArgumentException> exceptionExtension = new ByteBuddy()
			.subclass(IllegalArgumentException.class)
			.defineField("handler", CallHandler.class, Modifier.PRIVATE + Modifier.FINAL)
			.defineConstructor(Modifier.PUBLIC)
			.withParameters(CallHandler.class, String.class, Throwable.class)
			.intercept(
				MethodCall
					// CALL DEFAULT (NON-ARG) CONSTRUCTOR ON SUPERCLASS
					.invoke(IllegalArgumentException.class.getConstructor(String.class, Throwable.class))
					.onSuper()
					.withArgument(1, 2)
					.andThen(FieldAccessor.ofField("handler").setsArgumentAt(0))
			)
			.method(ElementMatchers.noneOf(ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()))
			.intercept(MethodDelegation.toField("handler"))
			.make()
			.load(ExceptionExtensionTest.class.getClassLoader())
			.getLoaded();
		final Constructor<? extends IllegalArgumentException> constructor = exceptionExtension.getConstructor(CallHandler.class, String.class, Throwable.class);
		final IllegalArgumentException resultExtension = constructor.newInstance(new CallHandler(), "Test", new RuntimeException("Whatever"));
		assertNotNull(resultExtension);
	}

	public static class CallHandler {
		@RuntimeType
		public static Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@FieldValue("handler") CallHandler handler,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			if (handler == null) {
				System.out.println("A");
				return superMethod.call();
			} else {
				System.out.println("B");
				return superMethod.call();
			}
		}

		public Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			System.out.println("C");
			return superMethod.call();
		}
	}

}
```

I added silly debug lines that would print whatever was called and always delegate to super method - just to see what's happening. Now I'm getting this error:

```
java.lang.IllegalArgumentException: None of [protected void java.lang.Object.finalize() throws java.lang.Throwable, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException, public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll(), public java.lang.Object com.fg.registration.business.user.authentication.ExceptionExtensionTest$CallHandler.interceptMethodCall(java.lang.Object,java.lang.reflect.Method,java.util.concurrent.Callable,java.util.concurrent.Callable,java.lang.Object[]) throws java.lang.Throwable] allows for delegation from public synchronized java.lang.Throwable java.lang.Throwable.fillInStackTrace()

	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1351)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:710)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:695)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:602)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5811)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2193)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3903)
```

I'm terribly sorry for taking your time.

**Comment by raphw** [comment]
You need to delegate to the static method by: `MethodDelegation.to(Handler.class)`, not by delegating to the instance.

**Comment by novoj** [comment]
**Thank you very much, it works now.**

For anyone in similar situation. The correct solution to the problem is following:

``` java
public class ExceptionExtensionTest {

	@Test
	public void shouldNotFailExtendingException() throws NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
		final Class<? extends IllegalArgumentException> exceptionExtension = new ByteBuddy()
			.subclass(IllegalArgumentException.class)
			.defineField("handler", CallHandler.class, Modifier.PRIVATE + Modifier.FINAL)
			.defineConstructor(Modifier.PUBLIC)
			.withParameters(CallHandler.class, String.class, Throwable.class)
			.intercept(
				MethodCall
					// CALL DEFAULT (NON-ARG) CONSTRUCTOR ON SUPERCLASS
					.invoke(IllegalArgumentException.class.getConstructor(String.class, Throwable.class))
					.onSuper()
					.withArgument(1, 2)
					.andThen(FieldAccessor.ofField("handler").setsArgumentAt(0))
			)
			.method(ElementMatchers.noneOf(ElementMatchers.isFinalizer(), ElementMatchers.isConstructor()))
			.intercept(MethodDelegation.to(CallHandler.class))
			.make()
			.load(ExceptionExtensionTest.class.getClassLoader())
			.getLoaded();
		final Constructor<? extends IllegalArgumentException> constructor = exceptionExtension.getConstructor(CallHandler.class, String.class, Throwable.class);
		final IllegalArgumentException resultExtension = constructor.newInstance(new CallHandler(), "Test", new RuntimeException("Whatever"));
		assertNotNull(resultExtension);
	}

	public static class CallHandler {
		@RuntimeType
		public static Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@FieldValue("handler") CallHandler handler,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			if (handler == null) {
				System.out.println("A");
				return superMethod.call();
			} else {
				System.out.println("B");
				return superMethod.call();
			}
		}

		public Object interceptMethodCall(
			@This Object proxy,
			@Origin Method method,
			@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
			@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
			@AllArguments Object[] args
		) throws Throwable {
			System.out.println("C");
			return superMethod.call();
		}
	}

}
```

Thank you very much for your support. The real problem was in my lack of knowledge - not in ByteBuddy of course :)

**Comment by raphw** [comment]
Thanks for documenting your solution. There should certainly be better documentation. I am working on that one!
