### ISSUE TITLE
Can't attach with Linux Kernel 5.15

### ISSUE THREAD

**Issue by matejdro** [raphw/byte-buddy#1126]
When attempting to use MockK with ByteBuddy 1.11.19, I'm getting following exception:

```
java.lang.IllegalStateException: Could not self-attach to current VM using external process
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:695)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:626)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:606)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:558)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:535)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:127)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:33)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:186)
	... 2 more
```

After some troubleshooting I've downloaded bytebuddy source and modified [Attacher](https://github.com/raphw/byte-buddy/blob/167f409d13e637df81bb8ab63822343082f0f00f/byte-buddy-agent/src/main/java/net/bytebuddy/agent/Attacher.java#L83) to print the exception instead of eating it and I got the following exception:

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:112)
	at net.bytebuddy.agent.Attacher.main(Attacher.java:82)
Caused by: java.io.IOException: Invalid argument
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.read(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl$SocketInputStream.read(VirtualMachineImpl.java:260)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:328)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:192)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:94)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	... 6 more
```

This is with

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7)
OpenJDK 64-Bit Server VM (build 11.0.12+7, mixed mode)
Linux 5.15.0-1-MANJARO #1 SMP PREEMPT Sun Sep 26 21:53:21 UTC 2021 x86_64 GNU/Linux
```

Any ideas what could be the cause? What do I need to do to get more info that would help to solve this issue?

**Comment by raphw** [comment]
That's not an expected outcome. It is difficult to say what the issue is. Do you have multiple JVMs installed? Possibly, you are cross attaching from an incompatible VM.

To work around this, you can allow self attachment by setting `-Djdk.attach.allowAttachSelf=true` on the command line.
