### ISSUE TITLE
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast TaintObject

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1133]
1、I want  give java.lang.String  add my define  interface
interface Taint{
boolean isTaint;
}

2、I  use byteBuddy redifine  java.lang.String and   save  modify  builder to  file .but  when I   convert  it   occur   java.lang.ClassCastException: java.lang.String cannot be cast TaintObject
```
 new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .type(ElementMatchers.named("java.lang.String")).transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
								builder=builder.implement(TaintObject.class).defineMethod("isTainted", boolean.class, Visibility.PUBLIC)
                                .intercept(MethodDelegation.to(AddMethod.class));
                        return builder;
                    }
                }).installOn(instrumentation);

public class AddMethod {
    public static boolean isTainted() {
        return true;
    }
}
```

error  occur  when  i  use
String returned;
Taint ii=(Taint)returned.isTaint();

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.taint.api.Taint


thanks  give  some advices?
```

**Comment by raphw** [comment]
Hi, you can redefine the code within methods by redefinition, this is correct. You can however not change the shape of these methods in any way, for example by adding interfaces.
