### ISSUE TITLE
Not able to add field in a class

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#1143]
Using javaagent and bytebuddy library for instrumentaiton. I have a use case for adding a class level variable. So i wrote sampe test program to check it out if it is possible.

		
```
                new AgentBuilder.Default()
				.type(named("com.test.wrapper.jdbc.FieldTest"))
				.transform(new Transformer() {
					@Override
					public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
						return builder
								.defineField("_id", int.class, Visibility.PUBLIC);
					}
				})
				.installOn(inst);
		new AgentBuilder.Default().ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
				.with(new AgentBuilder.Listener.Filtering(
						new StringMatcher("com.test.wrapper.jdbc.FieldTest", StringMatcher.Mode.EQUALS_FULLY),
						AgentBuilder.Listener.StreamWriting.toSystemOut()))
				.type(named("com.test.wrapper.jdbc.FieldTest"))
				.transform(new Transformer.ForAdvice().include(ProbeAgent.class.getClassLoader())
						.advice(ElementMatchers.named("print"),
								"com.test.instrumentation.advice.db.TestStatementExecuteInterceptor"))
				.installOn(inst);
```

public class FieldTest {
    public void print() {
        System.out.println("Filed test class method");
    }
}

Advice method

```
    @Advice.OnMethodEnter
    public static void intercept(@Advice.This Object thiz, @Advice.FieldValue("_id") int _id) throws Exception {
        System.out.println("xxxxxxxxxx"+ _id); 

    }
```

I am calling just new FieldTest.print()

I am getting following error.

[Byte Buddy] DISCOVERY com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]
[Byte Buddy] ERROR com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]
java.lang.IllegalStateException: Cannot locate field named _id for class com.test.wrapper.jdbc.FieldTest
	at net.bytebuddy.asm.Advice$OffsetMapping$ForField$Unresolved.resolve(Advice.java:2177)
	at net.bytebuddy.asm.Advice$OffsetMapping$ForField.resolve(Advice.java:2121)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.doApply(Advice.java:7718)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter$WithDiscardedEnterType.doApply(Advice.java:7810)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.apply(Advice.java:7679)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:7388)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1123)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:7382)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:9430)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:49)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:62)
	at net.bytebuddy.jar.asm.Label.accept(Label.java:358)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1824)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1284)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3397)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:245)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10123)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10833)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10780)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at com.test.wrapper.jdbc.Test.main(Test.java:10)
[Byte Buddy] COMPLETE com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]

I took reference from this link https://stackoverflow.com/questions/58485870/how-to-add-a-field-to-an-existing-instance-with-bytebuddy
@raphw Any thoughts?

**Comment by raphw** [comment]
The second transformer is likely applied first. Try switching it around. Generally, I do not recommend to create such distributed dependencies.

**Comment by amar1019** [comment]
In that case, how do we achieve this without distributed dependency if we are not sure which transformer kicks in first

**Comment by raphw** [comment]
Can't you add the field definition to the same transformer?

**Comment by amar1019** [comment]
```
		new AgentBuilder.Default()
				.with(new AgentBuilder.Listener.Filtering(
						new StringMatcher("com.test.wrapper.jdbc.FieldTest", StringMatcher.Mode.EQUALS_FULLY),
						AgentBuilder.Listener.StreamWriting.toSystemOut()))
				.type(named("com.test.wrapper.jdbc.FieldTest"))
				.transform(new Transformer() {
					@Override
					public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
						System.out.println("entered into transform");
						return builder
								.defineField("_id", int.class, Visibility.PUBLIC)
								.method(ElementMatchers.named("print"))
								.intercept(Advice.to(TestStatementExecuteInterceptor.class));
					}
				})
				.installOn(inst);
```


**I tried that. I have added print statement inside transform. Its didn't get printed. But I got** 

[Byte Buddy] DISCOVERY com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]
[Byte Buddy] IGNORE com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]
[Byte Buddy] COMPLETE com.test.wrapper.jdbc.FieldTest [null, null, loaded=false]

**Comment by amar1019** [comment]
I missed one basic thing that it will ignore classes by boot loader. I did not add ignore option. I was adding the class in the bootclasspath for my local testing. Thanks @raphw
