### ISSUE TITLE
Threadpool instrumentation - java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#1144]
I am using threadpool instrumentation in my code for context switch. When the application is trying to start elasticsearch process, it is failing to do so. My code -

```
		new AgentBuilder.Default().ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
				.type(hasSuperType(named("java.util.concurrent.ExecutorService")))
				.transform(new Transformer.ForAdvice().include(Agent.class.getClassLoader())
						.advice(ElementMatchers.named("execute").or(ElementMatchers.named("submit"))
										.and(ElementMatchers.takesArgument(0, Runnable.class)),
								"com.xxx.instrumentation.advice.threadpool.ExecutorServiceRunnableAdvice"))
				.installOn(inst);

		new AgentBuilder.Default().ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
				.type(hasSuperType(named("java.util.concurrent.ExecutorService")))
				.transform(new Transformer.ForAdvice().include(Agent.class.getClassLoader())
						.advice(ElementMatchers.named("submit")
										.and(ElementMatchers.takesArgument(0, Callable.class)),
								"com.xxx.instrumentation.advice.threadpool.ExecutorServiceCallableAdvice"))
				.installOn(inst);
```

Exception - 

```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:2048)
	at java.base/java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1937)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.<clinit>(EsExecutors.java)
```

Code for DirectExecutorService

```
private static final class DirectExecutorService extends AbstractExecutorService {
        @SuppressForbidden(reason = "properly rethrowing errors, see EsExecutors.rethrowErrors")
        DirectExecutorService() {
        }

        public void shutdown() {
            throw new UnsupportedOperationException();
        }

        public List<Runnable> shutdownNow() {
            throw new UnsupportedOperationException();
        }

        public boolean isShutdown() {
            return false;
        }

        public boolean isTerminated() {
            return false;
        }

        public boolean awaitTermination(long timeout, TimeUnit unit) {
            throw new UnsupportedOperationException();
        }

        public void execute(Runnable command) {
            command.run();
            EsExecutors.rethrowErrors(command);
        }
    }
```

@raphw Why do you think it is failing to start the process?

**Comment by raphw** [comment]
Does you advice look up some method via origin? This can trigger sensitive methods which your JVMs security manager prohibits. Avoid sensitive methods, add a policy for the security manager or instrument the code that executes the security check to allow for your code.

**Comment by amar1019** [comment]
To verify it, i have removed all of my code in my advice. Still it throws the same error. My advice

```
public class ExecutorServiceCallableAdvice {

    @Advice.OnMethodEnter
    public static <T> void before(@Advice.Argument(value=0,readOnly=false) Callable<T> task) {
        
    }
}
```

**Comment by amar1019** [comment]
After adding the listener, i got the following output.

```
Byte Buddy] DISCOVERY org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
[Byte Buddy] TRANSFORM org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
[Byte Buddy] COMPLETE org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
[Byte Buddy] DISCOVERY org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
[Byte Buddy] TRANSFORM org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
[Byte Buddy] COMPLETE org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService [java.net.URLClassLoader@2b91004a, unnamed module @7c83e668, loaded=false]
```

and got **java.io.StreamCorruptedException: invalid type code: 5B**

**Comment by raphw** [comment]
Some VMs make special use of the output stream for communicating. Maybe if you write to a file or something.

**Comment by amar1019** [comment]
However adding redefinition and retransformation helped

```
with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE
.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
.with(AgentBuilder.TypeStrategy.Default.REDEFINE)
```

I thought these were only needed when retransforming already loaded classes. In this case, i am trying to instrument which is not loaded yet. Can you please try to explain me how it worked

**Comment by raphw** [comment]
They are. You are likely benefitting from the disabled initialization strategy. This way a class does no longer check for self-initialization what indeed resolves the system class loader.
