### ISSUE TITLE
agentmain  has  NullPointerException

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1146]
Exception in thread "Attach Listener" java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:515)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:537)
Agent failed to start!

```
 public static void agentmain(String args, Instrumentation instrumentation) {
        System.out.println("[Agent] In agentmain method");
        // 返回的ClassFileTransformer 可以调用reset方法，
        ResettableClassFileTransformer transformer = new AgentBuilder.Default()
                // 声明使用redefine
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                // 大多数vm都要求不能增加或者删除原有的方法
                .disableClassFormatChanges()
                // debug Instrumentation 过程
                .with(AgentBuilder.Listener.StreamWriting.toSystemOut()).type(ElementMatchers.nameContains("TimerDemo"))
                .transform((builder, typeDescription, classLoader, module) -> builder
                        .visit(Advice.to(TimerByteBuddyAdvice.class).on(ElementMatchers.named("doSomething")))
                )

                .installOn(instrumentation);

     
        // 重置
        System.out.println("[Agent] resetting ");
        transformer.reset(instrumentation, AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);

    }
```

I test   bytebuddy  1.11.22   and  1.12.0  is not  works

**Comment by raphw** [comment]
From the stack it seems like you are maybe missing some info in your agents manifest?

What JVM version are you using?

**Comment by cor0ps** [comment]
![image](https://user-images.githubusercontent.com/13083624/141020258-e627a4ce-6adb-4d40-a5d1-5d7b081692fe.png)
 I use this

**Comment by cor0ps** [comment]
maybe  java   home    set  problem
