### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by liudantop** [raphw/byte-buddy#1147]
java.lang.IllegalArgumentException: Unsupported class file major version 60
   at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:196)
        at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:177)
        at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:163)
        at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
        at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:681)
        at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:667)
        at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:747)
        at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:845)
        at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
        at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getInterfaces(TypeDescription.java:8056)
        at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.getInterfaces(TypeDescription.java:4894)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$WithEagerNavigation.getInterfaces(TypeDescription.java:6393)
        at net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:66)
        at net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:31)
        at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
        at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
        at net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)

**Comment by raphw** [comment]
You'll have to upgrade BB to a newer version. The one you are using does not support Java 16 yet.

**Comment by raphw** [comment]
I improved the error message, too.
