### ISSUE TITLE
how  to solve  No compatible attachment provider is available

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1148]
why  occurs  this  problems?

when  I  use   IDEA  run   main code  have  0 error?
```
public static void main(String[] args){
        String agentFilePath = "byte-agent.jar";

        File agentFile = new File(agentFilePath);
        try{
            System.out.println("Attaching to target jvm with pid:");
            ByteBuddyAgent.attach(agentFile.getAbsoluteFile(), "24612");

            System.out.println("Attached to target jvm and loaded agent successfully");
        }catch(Exception e){
            throw new RuntimeException(e);
        }
```
this  I dian run  is  ok，but  i   maven  a  jar maybe  has  these  problems?

```
\target>java -jar instrument-attacher-bytebuddy.jar
Attaching to target jvm with pid:
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: No compatible attachment provider is available
        at info.wufc.tutorials.javainstrument.ByteBuddyAgentLoader.main(ByteBuddyAgentLoader.java:19)
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:622)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:293)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:258)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:240)
        at info.wufc.tutorials.javainstrument.ByteBuddyAgentLoader.main(ByteBuddyAgentLoader.java:15)

\target>java -cp instrument-attacher-bytebuddy.jar  info.wufc.tutorials.javainstrument.ByteBuddyAgentLoader
Attaching to target jvm with pid:
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: No compatible attachment provider is available
        at info.wufc.tutorials.javainstrument.ByteBuddyAgentLoader.main(ByteBuddyAgentLoader.java:19)
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:622)

```

**Comment by raphw** [comment]
What VM are you using? Some few do not support attachment. What you can try is to add JNA to the class path. Byte Buddy will then attempt an emulation of the attachment API.

**Comment by cor0ps** [comment]
openjdk version "1.8.0_262"

**Comment by cor0ps** [comment]
debug  found  reasons:
![image](https://user-images.githubusercontent.com/13083624/141976197-66d670af-6385-46a7-81a3-b6e9c586caa6.png)

not  found   
![image](https://user-images.githubusercontent.com/13083624/141976261-e782d087-e948-43f4-aa80-490dc44b6b63.png)

**Comment by cor0ps** [comment]
and  i  think  classloader  ucp path  not  include   tools.jar   path   so   lead to    ClassNotFoundException

**Comment by cor0ps** [comment]
https://stackoverflow.com/questions/51707812/adding-com-sun-tools-jar-in-classpath-of-jar

i   solve  this  problem   .

**Comment by cor0ps** [comment]
I   add  tools.jar  to    classpath ，now  error 

java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@3fee733d
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:633)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:293)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:258)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:240)
        at com.taint.install.Installer.main(Installer.java:38)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:628)
        ... 4 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203)
        ... 10 more

**Comment by raphw** [comment]
It seems like you are using a JRE, not a JDK. This is an internal error. It should not be required to add anything to the classpath for using this.
