### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Could not locate class file for  Advice

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1156]
when  I  use instrumentation.appendToBootstrapClassLoaderSearch  myAgent.jar

happens   these  error

Caused by: java.lang.IllegalStateException: Could not locate class file for com.taint.advice.MethodAdvice
        at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:118)
        at net.bytebuddy.asm.Advice.to(Advice.java:355)
        at net.bytebuddy.asm.Advice.to(Advice.java:327)
        at net.bytebuddy.asm.Advice.to(Advice.java:304)
        at net.bytebuddy.asm.Advice.to(Advice.java:293)
        at com.taint.agent.ByteBuddyTransformer.<clinit>(ByteBuddyTransformer.java:26)
        ... 8 more

code structe:
![image](https://user-images.githubusercontent.com/13083624/142384477-6c86c483-581f-45e8-badf-025f0ca47acd.png)

I  uses  this   way   beacuse   ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst).inject(map);   not  work  to  annymous  class

how  i  solve  this   ?

**Comment by cor0ps** [comment]
not a  question

**Comment by raphw** [comment]
I take it that you solved this by yourself?
