### ISSUE TITLE
Modify the return value of a method

### ISSUE THREAD

**Issue by bairamovazat** [raphw/byte-buddy#1172]
Hi!

I need to modify the return value of a method. Could someone please help me with this ?

I have a Service class. This class has a private getUser() method. 

```
public class Service {

    private User getUser() {
        ...
    }

    private boolean checkRole() {
        return this.getUser().getRole().equals("test");
    }
}
```

I need to modify the User class after the getUser() method is called.
Something like this:

```
new ByteBuddy()
                .redefine(typePool.describe("com.example.Service").resolve(),
                        ClassFileLocator.ForClassLoader.ofSystemLoader())
                .method(named("getUser"))
                .intercept(MethodDelegation.to(UserInterceptor.class))
                .make()
                .load(ClassLoader.getSystemClassLoader(),
                        ClassLoadingStrategy.Default.INJECTION);
```

```
public class UserInterceptor{

    public static User getUser(User returnValue) {
        returnValue.setRole("test");
        return returnValue;
    }
}
```

I would be very grateful for your help.

Regards,
Azat

**Comment by raphw** [comment]
Inject a parameter `@SuperCall Callable<User>` into your interceptor method.

**Comment by bairamovazat** [comment]
Thank you for your reply! 

If I add the @SuperCall annotation, the error will occur.

```
Exception in thread "main" java.lang.IllegalArgumentException: None of [public static com.example.User com.example.UserInterceptor.getUser(java.util.concurrent.Callable) throws java.lang.Exception] allows for delegation from private com.example.User com.example.Service.getUser()
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1344)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:709)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:694)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:5350)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1513)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3918)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2192)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
	at com.example.Main.main(Main.java:24)

Process finished with exit code 1
```

**Comment by raphw** [comment]
You'd need to choose *rebase* rather then *redefine*.

**Comment by bairamovazat** [comment]
Perhaps I have a problem in other parts of the code ... 
I am attaching the full code below:

```
package com.example;

public class Service {

    private User getUser() {
        return new User(1, "one");
    }

    public void test() {
        System.out.println(getUser());
    }

}

// ---------------------- //

package com.example;

public class User {

    private int id;
    private String role;

    public User(int id, String role) {
        this.id = id;
        this.role = role;
    }

    public int getId() {
        return id;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}

// ---------------------- //

package com.example;

import net.bytebuddy.implementation.bind.annotation.SuperCall;

import java.util.concurrent.Callable;

public class UserInterceptor {

    public static User getUser(@SuperCall Callable<User> c) throws Exception {
        User returnValue = c.call();
        returnValue.setRole("test");
        return returnValue;
    }

}

// ---------------------- //

package com.example;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.pool.TypePool;

import static net.bytebuddy.matcher.ElementMatchers.named;

public class Main {

    public static void main(String[] args) {
        ByteBuddyAgent.install();

        TypePool typePool = TypePool.Default.ofSystemLoader();

        new ByteBuddy()
                .redefine(typePool.describe("com.example.Service").resolve(),
                        ClassFileLocator.ForClassLoader.ofSystemLoader())
                .method(named("getUser"))
                .intercept(MethodDelegation.to(UserInterceptor.class))
                .make()
                .load(ClassLoader.getSystemClassLoader(),
                        ClassLoadingStrategy.Default.INJECTION);

        new Service().test();

    }
}


```

**Comment by bairamovazat** [comment]
Thanks! 
After changing to redefine, everything worked! 

Regards,
Azat

**Comment by bairamovazat** [comment]
I got the error again after I tried to test this code on WebSphere.

```
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for com.example.service
        at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162)

```

Could this error be related to WebSphere? 
And how can it be resolved ? 

Thank you very much for your help.

Regards,
Azat

**Comment by raphw** [comment]
I assume that you are using the wrong class loader. WebSphere is likely using a more complicated hierarchy.

So when you are using `ClassFileLocator.ForClassLoader.ofSystemLoader()`, you likely need to find a class loader of a surrounding class via `SomeClass.class.getClassLoader()`.

**Comment by bairamovazat** [comment]
I changed ClassLoader everywhere, including this line "TypePool typePool = TypePool.Default.ofSystemLoader();".

And after that everything worked.
```
public static void main(String[] args) {
        ByteBuddyAgent.install();

        ClassLoader classLoader = Main.class.getClassLoader();
        TypePool typePool = TypePool.Default.of(classLoader );

        new ByteBuddy()
                .redefine(typePool.describe("com.example.Service").resolve(),
                        ClassFileLocator.ForClassLoader.of(classLoader))
                .method(named("getUser"))
                .intercept(MethodDelegation.to(UserInterceptor.class))
                .make()
                .load(classLoader ,ClassLoadingStrategy.Default.INJECTION);

        new Service().test();

    }
```

Thanks for the quick help !
