### ISSUE TITLE
Ah，ClassInjector.UsingInstrumentation.of  not  support inner class 

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1173]
```
 public static ThreadLocal<Stack<TraceItem>> stacks = new ThreadLocal() {
        @Override
        protected Stack<TraceItem> initialValue() {
            return new Stack<>();
        }
    };

    public static ThreadLocal<LinkedList<TraceItem>> calls = new ThreadLocal() {
        @Override
        protected LinkedList<TraceItem> initialValue() {
            return new LinkedList<>();
        }
    };

```

bytebuddy  same  error  not  support   inner class,but  how  i  solve  this  problem

flowtaint caught exception: java.lang.NoClassDefFoundError: com/taint/agent/xAgent$1

**Comment by raphw** [comment]
You need to inject all classes if multiple classes are referring to each other. This includes inner classes.

**Comment by cor0ps** [comment]
I  use   instrumentation.appendToBootstrapClassLoaderSearch(agentFile);
put all my class into ,but   error has :

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
**_Caused by: java.lang.IllegalStateException: Could not locate class file for com.taint.callgraph.CallRecorder_**
	at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:118)
	at net.bytebuddy.dynamic.ClassFileLocator$ForClassLoader.read(ClassFileLocator.java:369)
	at com.taint.agent.FlowTaintClassLoader.injectBootstrapClasses(FlowTaintClassLoader.java:140)
	at com.taint.agent.FlowTaintAgent.init(FlowTaintAgent.java:103)
	at com.taint.agent.FlowTaintAgent.premain(FlowTaintAgent.java:92)
```

**Comment by cor0ps** [comment]
OK
