### ISSUE TITLE
Type Validation fails for GenericContainer

### ISSUE THREAD

**Issue by serkan-ozal** [raphw/byte-buddy#1185]
Hi,

When type validation is not disabled, it fails while transforming TestContainers's `GenericContainer` because of `@Nullable` annotated `workingDirectory` field (https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L179).

```
Failed to handle org.testcontainers.containers.GenericContainer for transformation on classloader sun.misc.Launcher$AppClassLoader@18b4aac2: java.lang.IllegalStateException: Illegal type annotations on class java.lang.String for class org.testcontainers.containers.GenericContainer
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1683)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:520)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11757)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11692)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11405)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12092)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12032)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11597)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

What might be the reason? And is there any workaround other than disabling type validation?

Thanks in advance.

**Comment by raphw** [comment]
I'd need to reproduce this to see why the validation fails. Possibly, the JVM version does not support type annotations?

You can however disable validation by defining an explicit `ByteBuddy` for your agent builder (via its constructor) where you set `.with(TypeValidation.DISABLED)`. For performance reasons, this is recommended anyways.

**Comment by serkan-ozal** [comment]
The TestContainers library class file version is `52` (Java 8) and I am running/testing my agent on both JDK 8 and JDK 11. So type validation fails on both JDK versions.

**Comment by raphw** [comment]
Does not seem to be a problem with the current BB version:

```
new ByteBuddy().redefine(GenericContainer.class).make();
```

validates the type as expected.

**Comment by serkan-ozal** [comment]
Hmm, weird. I am using the latest version `1.12.6` and build the agent as following:
```
            new AgentBuilder.Default(
                    new ByteBuddy().
                            with(TypeValidation.ENABLED).
                            ignore(new LatentMatcher.Resolved<>(isDefaultFinalizer()))
                    ).
                    disableClassFormatChanges().
                    with(NoOp.INSTANCE).
                    with(AgentBuilder.TypeStrategy.Default.REDEFINE).
                    with(RedefinitionStrategy.RETRANSFORMATION).
                    with(new TransformLoggingListener()).
                    ignore(ElementMatchers.any(), ClassLoaderMatchers.skipClassLoader()).
                    or(ElementMatchers.nameStartsWith("scala.")).
                    or(ElementMatchers.nameStartsWith("kotlin.")).
                    or(ElementMatchers.nameStartsWith("android.")).
                    or(ElementMatchers.nameStartsWith("com.sun.proxy")).
                    or(ElementMatchers.nameStartsWith("ch.qos.logback")).
                    or(ElementMatchers.nameStartsWith("net.bytebuddy")).
                    or(ElementMatchers.nameStartsWith("io.opentracing"));
```

**Comment by serkan-ozal** [comment]
Not sure whether it is related to the issue;

When the validation is triggered from my agent (and fails), the field type is shown like this:
<img width="934" alt="Screen Shot 2022-01-05 at 13 26 15" src="https://user-images.githubusercontent.com/3143425/148202388-74f1e7f1-70d8-4ea0-a7bc-110ee27eb8b4.png">

But, when I do it (succeeds) by just 
```
new ByteBuddy().redefine(GenericContainer.class).make();
```
It looks like this:
<img width="938" alt="Screen Shot 2022-01-05 at 13 26 41" src="https://user-images.githubusercontent.com/3143425/148202500-2d227dc3-8a88-4243-bf69-d57997a150e2.png">

**Comment by serkan-ozal** [comment]
The `Nullable` annotation is from JetBrains annotations (`org.jetbrains.annotations`) and doesn't have `ElementType.TYPE_USE`:

```java
package org.jetbrains.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Documented
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.LOCAL_VARIABLE})
public @interface Nullable {
    String value() default "";
}
```

**Comment by serkan-ozal** [comment]
Seems that latest version of `org.jetbrains.annotations.Nullable` has `ElementType.TYPE_USE`

**Comment by raphw** [comment]
I assume that that's the issue. The type is compiled against an annotation with TYPE_USE but then it turns out that this annotation is not present when Byte Buddy is recompiling the type. The JVM (and Byte Buddy) normally suppresses broken annotations but it seems like the JVM also filters "misplaced" annotations. Byte Buddy's type pool should probably do the same.

**Comment by serkan-ozal** [comment]
Thanks for the help. Closing the issue as it is caused by very old version (released in 2013) of JetBrains annotations library and the problem is not valid for newer versions after 2015 which is fair enough in practice.
