### ISSUE TITLE
Byte Buddy + DexGuard obfuscation

### ISSUE THREAD

**Issue by abelthefirst** [raphw/byte-buddy#1189]
Hello! This question appears from the discussion here - https://github.com/Guardsquare/proguard/issues/50. My situation is that I have a library, which is obfuscated with DexGuard and `-encryptstrings` option. Everything works on a real device, however UTs in the app module fail with the

`
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at net.bytebuddy.utility.visitor.StackAwareMethodVisitor.drainStack(StackAwareMethodVisitor.java:149)
	at net.bytebuddy.asm.Advice$AdviceVisitor$WithExitAdvice.onVisitInsn(Advice.java:10821)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitInsn(ExceptionTableSensitiveMethodVisitor.java:321)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2213)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1514)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
`

Without the `-encryptstrings` option everything works just fine. The complete demonstrator can be found here - https://github.com/abelthefirst/ProGuardFun. Building a release version of the **lib** module requires a DexGuard license, prebuilts are in the _precompiled-lib_ folder (one with encryptstrings enabled and one without). Any help would be appreciated!

**Comment by raphw** [comment]
Could you attach a class file here where this error occurs? I would need to have a look.

Also: make sure that you are using the latest version of BB.

**Comment by abelthefirst** [comment]
Sure thing! [Service.class.zip](https://github.com/raphw/byte-buddy/files/7869101/Service.class.zip). Byte Buddy's version is 1.12.5.

**Comment by raphw** [comment]
Thanks, I could produce this locally, I will look into what is missing.

**Comment by raphw** [comment]
I solved the problem on master and will do a release tonight.
