### ISSUE TITLE
java.security.AccessControlException: access denied under JavaWebStart

### ISSUE THREAD

**Issue by markusschaefer** [raphw/byte-buddy#1196]
When using Byte Buddy in an application, that is deployed as Java Webstart application the SecurityManager denies all access when a MethodDelegation Interceptor is used in the stack.

java.security.AccessControlException: access denied ("java.util.PropertyPermission" "user.dir" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.sun.javaws.security.JavaWebStartSecurity.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
	at java.lang.System.getProperty(System.java:717)
	at test2.Execute.toStringDelegate(Execute.java:24)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$MXwenXf3.toString(Unknown Source)
	at test2.Execute.run(Execute.java:20)
	at test.Main.main(Main.java:9)

public class Execute
{
	public static void run() throws InstantiationException, IllegalAccessException
	{
		Class<?> dynamicType = new ByteBuddy()
			.subclass(Object.class)
			.method(ElementMatchers.named("toString"))
			.intercept(MethodDelegation.to(Execute.class))
			.make()
			.load(Execute.class.getClassLoader())
			.getLoaded();

		System.out.println(dynamicType.newInstance().toString());
	}

	public static String toStringDelegate() {
		return "Hello Java Webstart "+ System.getProperty("user.dir");
	}
}

**Comment by raphw** [comment]
Try specifying an explicit `ClassLoadingStrategy`. For example:

     ClassLoadingStrategy.Default.WRAPPER.withProtectionDomain(Execute.class.getProtectionDomain())

By default, classes are loaded "non-privileged".

**Comment by markusschaefer** [comment]
thanks a lot. It's working with an explicit `ClassLoadingStrategy`.
