### ISSUE TITLE
Error when redefining an enum and visiting it with a modifier

### ISSUE THREAD

**Issue by Olipro** [raphw/byte-buddy#1201]
I came across a curious error when an enum is visited to change its modifiers when `.make()` is called - bear in mind however that I am supplying my own typepool implementation.

Anyhow, given an enum with the fully qualified path `foo.MyEnum`, my TypePool is queried for `Lfoo.MyEnum;` - I've worked around the problem by aliasing it as both `foo.MyEnum` and `Lfoo.MyEnum;` in my TypePool - however, is this something you're supposed to do and I simply missed a crucial piece of documentation? It seems odd to me.

Notably, when visiting other types, they all query my TypePool with the regular `foo.MyType` format

**Comment by raphw** [comment]
That does sound like a bug. Can you post a stack trace to show from where this query is made? I assume that the descriptor is used rather than the binary name.

**Comment by Olipro** [comment]
Here you go:

```Could not locate type for: Lbar.MakePublic4;
java.lang.IllegalStateException: Could not locate type for: Lbar.MakePublic4;
	at net.bytebuddy.asm.TypeReferenceAdjustment$TypeReferenceClassVisitor.visitEnd(TypeReferenceAdjustment.java:307)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitEnd(TypeWriter.java:5222)
	at net.bytebuddy.utility.visitor.MetadataAwareClassVisitor.visitEnd(MetadataAwareClassVisitor.java:325)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:748)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3951)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2213)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3654)```

**Comment by Olipro** [comment]
If you have trouble pinning it down, you can also grab https://github.com/Olipro/Interceptify and remove lines 76-77 from `src/main/java/net/uptheinter/interceptify/internal/ClassExposer.java` and run the corresponding test to reproduce it.

**Comment by raphw** [comment]
Thanks, I identified the issue, it's a faulty resolution of an internal name of an array type to the internal name of the component type. This is now fixed on master. I am doing a new release tonight.
