### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by ekaterinadimitrova2** [raphw/byte-buddy#1221]
Hi,
I am working to upgrade cassandra to support Java 17.
We are dependent on byte-buddy so I updated bytebuddy to the latest version here - https://github.com/ekaterinadimitrova2/cassandra/blob/16895-v3/build.xml#L137
but I see these errors in our failing tests:
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:195)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:176)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:162)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3394)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:217)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:120)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
	at org.apache.cassandra.distributed.test.FailureLoggingTest$BBRequestFailures.install(FailureLoggingTest.java:141)
	at org.apache.cassandra.distributed.shared.AbstractBuilder$1.initialise(AbstractBuilder.java:312)
	at org.apache.cassandra.distributed.impl.AbstractCluster$Wrapper.newInstance(AbstractCluster.java:246)
	at org.apache.cassandra.distributed.impl.AbstractCluster$Wrapper.<init>(AbstractCluster.java:235)
	at org.apache.cassandra.distributed.Cluster.newInstanceWrapper(Cluster.java:43)
	at org.apache.cassandra.distributed.Cluster.newInstanceWrapper(Cluster.java:34)
	at org.apache.cassandra.distributed.impl.AbstractCluster.newInstanceWrapperInternal(AbstractCluster.java:549)
	at org.apache.cassandra.distributed.impl.AbstractCluster.<init>(AbstractCluster.java:504)
	at org.apache.cassandra.distributed.Cluster.<init>(Cluster.java:38)
	at org.apache.cassandra.distributed.shared.AbstractBuilder.createWithoutStarting(AbstractBuilder.java:158)
	at org.apache.cassandra.distributed.shared.AbstractBuilder.start(AbstractBuilder.java:140)
	at org.apache.cassandra.distributed.test.FailureLoggingTest.setUpCluster(FailureLoggingTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	
I updated also asm to 9.2, for reference the same build file here - https://github.com/ekaterinadimitrova2/cassandra/blob/16895-v3/build.xml#L135. I hope you can advise me as this is a blocker for me. Thank you in advance

**Comment by ekaterinadimitrova2** [comment]
Thank you for the quick response. On further investigation I noticed that Mockito was dependent on older bytebuddy version and when I updated it, everything works now.
