### ISSUE TITLE
Incorrect delegation/return object conversion

### ISSUE THREAD

**Issue by PhantomYdn** [raphw/byte-buddy#1225]
Hello, Rafael, 

Please consider the following test case:
```java
@Test
	public void testDelegation2() throws Exception {
		DelegateMe obj = new DelegateMe(100);
		assertEquals(100, obj.getNumber());
		assertEquals(101, obj.getNumberPlusOneWithMethod());
		assertEquals(101, obj.getNumberPlusOneDirect());
		
		DynamicType.Loaded<?> loaded = new ByteBuddy()
                .subclass(obj.getClass())
                .implement(IDelegateAware.class)
                .method(not(isNative()))
                .intercept(MethodDelegation.toMethodReturnOf("get$delegate"))
                .defineField("$delegate", Object.class, Opcodes.ACC_PRIVATE)
				.method(isDeclaredBy(IDelegateAware.class)
							.and(isAbstract()))
				.intercept(FieldAccessor.ofField("$delegate"))
                .make()
                .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER);
		
		DelegateMe delegator =  (DelegateMe)loaded.getLoaded().newInstance();
		((IDelegateAware)delegator).set$delegate(obj);
		assertTrue(obj==((IDelegateAware)delegator).get$delegate());
		System.out.println("Number: "+delegator.getNumber());
		assertEquals(100, obj.getNumber());
		assertEquals(100, delegator.getNumber());  //FAILING HERE!
		assertEquals(101, delegator.getNumberPlusOneWithMethod());
		assertEquals(101, delegator.getNumberPlusOneDirect());
	}

	public static interface IDelegateAware {
		public Object get$delegate();
		public void set$delegate(Object delegate);
	}
	
	public static class DelegateMe {
		
		private int number;
		
		public DelegateMe() {
			this(0);
		}
		
		public DelegateMe(int number) {
			this.number = number;
		}
		
		public int getNumber() {
			System.out.println("GetNumber Invoked! Number is "+number);
			return number;
		}
		
		public int getNumberPlusOneWithMethod() {
			return getNumber()+1;
		}
		
		public int getNumberPlusOneDirect() {
			return number+1;
		}
	}
```

Please help to understand why this testcase is failing on marked above line with the following message:

```
java.lang.AssertionError: expected:<100> but was:<1466073198>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
```

Running on OpenJDK 8.

**Comment by raphw** [comment]
Delegation is not the right approach for this, it normally uses a few methods - often just one - to intercept many methods.

You want to invoke methods directly, and you need to cast the type as it is Object:

    .intercept(MethodCall.invokeSelf().onMethodCall(MethodCall.invoke(named("get$delegate")))
      .withAllArguments()
      .withAssigner(Assigner.DEFAULT, Assigner.Typing.DYNAMIC))

**Comment by PhantomYdn** [comment]
Thank you @raphw!
In other words: MethodDelegate - delegates invokations to particular "selected" method on target "carrier". And as in my case: `getNumber()` was mapped to `hashCode()`... Btw, Is there any "tracing mode" which helps to figure out what and what is trying to be mapped?

Thank you for the working snippet!
