### ISSUE TITLE
what's different from bewteen builder.visit and builder.method

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#124]
what's different from bewteen builder.visit and builder.method
i describe this problem in [https://github.com/raphw/byte-buddy/issues/109](url)

my project is [https://github.com/dragontree101/byte-buddy-agent-example.git](url)

`.type(nameStartsWith("redis.clients.jedis").and(not(isInterface())).and(not(isStatic())))
            .transform(new RedisTransformer(redisInterceptor))`
is use builder.method(..) it works

but

`.type(nameStartsWith("redis.clients.jedis").and(not(isInterface())).and(not(isStatic())))
        .transform(new RedisAdviceTransformer())`
is use builder.visit(...)  it doesn't work

and throw 
`onError:redis.clients.jedis.Jedis
java.lang.NoClassDefFoundError: redis/clients/jedis/Connection
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at net.bytebuddy.description.method.MethodList$ForLoadedType.<init>(MethodList.java:90)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:7414)
	at net.bytebuddy.asm.Advice.to(Advice.java:227)
	at net.bytebuddy.asm.Advice.to(Advice.java:211)
	at net.bytebuddy.asm.Advice.to(Advice.java:188)
	at net.bytebuddy.asm.Advice.to(Advice.java:177)
	at com.dragon.study.bytebuddy.AbstractAdviceTransformer.transform(AbstractAdviceTransformer.java:30)
	at net.bytebuddy.agent.builder.AgentBuilder$Transform`

thanks

**Comment by raphw** [comment]
This is most likely a class loader issue. The difference is: If you are loading a Java agent, it is loaded on the class path. If your application is however loaded by an application server and not on the class path (i.e. `redis.clients.jedis.Connection.class.getClassLoader() != ClassLoader.getSystemClassLoader()`), the Java agent cannot locate the Jedis connection and the above error is thrown. In order to avoid this, you need to add the Jedis dependency to your Java agent.

**Comment by dragontree101** [comment]
thanks very much
