### ISSUE TITLE
The example in "Working with unloaded classes" is wrong.

### ISSUE THREAD

**Issue by diguage** [raphw/byte-buddy#1293]
The example in "Working with unloaded classes" is wrong.

```java
class MyApplication {
  public static void main(String[] args) {
    TypePool typePool = TypePool.Default.ofSystemLoader();
    Class bar = new ByteBuddy()
      .redefine(typePool.describe("foo.Bar").resolve(), // do not use 'Bar.class'
                ClassFileLocator.ForClassLoader.ofSystemLoader())
      .defineField("qux", String.class) // we learn more about defining fields later
      .make()
      .load(ClassLoader.getSystemClassLoader());
    assertThat(bar.getDeclaredField("qux"), notNullValue());
  }
}
```

**Comment by raphw** [comment]
How so? What is wrong with it?

**Comment by diguage** [comment]
```java
Class bar = new ByteBuddy()
      .redefine(typePool.describe("foo.Bar").resolve(), // do not use 'Bar.class'
                ClassFileLocator.ForClassLoader.ofSystemLoader())
      .defineField("qux", String.class) // we learn more about defining fields later
      .make()
      .load(ClassLoader.getSystemClassLoader()); // It returns net.bytebuddy.dynamic.DynamicType.Loaded, not Class.
```

If invoke `getLoaded()` method, then return the `Class`. But it throws an exception:

```java
Class<?> loadedClass = new ByteBuddy()
        .redefine(typePool.describe("foo.Bar").resolve(), // do not use 'Bar.class'
                ClassFileLocator.ForClassLoader.ofSystemLoader())
        .defineField("qux", String.class)
        .make()
        .load(ClassLoader.getSystemClassLoader())
        .getLoaded(); // invoke the method to return Class. But the code throws Exception in thread "main" java.lang.IllegalStateException: Class already loaded: class foo.Bar
```

The log:

```java
Exception in thread "main" java.lang.IllegalStateException: Class already loaded: class foo.Bar
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.load(ByteArrayClassLoader.java:362)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:367)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6154)
	at com.diguage.cafe.jiadao.Test6.main(Test6.java:26)
```


```bash
$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment Corretto-8.332.08.1 (build 1.8.0_332-b08)
OpenJDK 64-Bit Server VM Corretto-8.332.08.1 (build 25.332-b08, mixed mode)

byte-buddy.version: 1.12.12
```

**Comment by raphw** [comment]
I assume that you loaded the class somewhere in `com.diguage.cafe.jiadao.Test6.main`. There's a unit test to check that this works in Byte Buddy.

**Comment by diguage** [comment]
@raphw OK, let me research it.

**Comment by diguage** [comment]
I found the test example: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/ByteBuddyTutorialExamplesTest.java#L155

The test example invokes `.getLoaded()`:

![image](https://user-images.githubusercontent.com/2121467/182425093-8b7a0fd7-de78-474f-9526-e395b1b75ce9.png)

**Comment by diguage** [comment]
There is one more difference:

![image](https://user-images.githubusercontent.com/2121467/182427049-020d9f47-192a-4a08-8313-5e5533445836.png)

![image](https://user-images.githubusercontent.com/2121467/182427121-c488529d-bda4-4ee1-9fe4-e38d852e109f.png)

**Comment by raphw** [comment]
I commented on your PR also. The test is different to keep it repeatable on the same VM. That's probably why this glitched through. Try the system loader with the `INJECT` strategy, then I think this would work.

**Comment by Jason-purse** [comment]
That being the case, whether the tutorial can correspond to a specific version of byteBuddy, I think this is a good thing, if the sentence does not go smoothly, please forgive me for using google translate.
