### ISSUE TITLE
TypePool.DefaultDoDescribe should catch IOException and return Resolution.Illegal

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#130]
On a (possibly very old JVM) we observed this problem:

```
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
        at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
        at java.util.jar.JarFile.getEntry(JarFile.java:240)
        at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1005)
        at sun.misc.URLClassPath$JarLoader.findResource(URLClassPath.java:983)
        at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
        at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1088)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1304)
        at net.bytebuddy.dynamic.ClassFileLocator$ForClassLoader.locate(ClassFileLocator.java:307)
        at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1081)
        at net.bytebuddy.pool.TypePool$AbstractBase.describe(TypePool.java:383)
        at net.bytebuddy.pool.TypePool$AbstractBase$Hierarchical.describe(TypePool.java:440)
```

Either the TypePool doDescribe or the ForClassLoader.locate() should in my opinion catch ehtis error and return Illegal.
This can't be handled gracefully and the best option for users would be to "skip" whatever they wanted to do with the type, because it cannot be found.
Note that IOException is caught, but IllegalStateException is not, which is why this bubbles up.

**Comment by raphw** [comment]
After discussing, this turned out to have a different root cause.
