### ISSUE TITLE
OnMethodExit return value cannot be overwritten -> wrong negation in net.bytebuddy.asm.Advice$OffsetMapping$ForReturnValue$Factory.make(Advice.java:3613)

### ISSUE THREAD

**Issue by roeltje25** [raphw/byte-buddy#1300]
Hi,

I think I found a typo in the bytbuddy code. It seemed I could not get to work an advice that would overwrite the return value of a method.  Like this:
```java
static class Advisor
    {
        @OnMethodExit(onThrowable = IllegalStateException.class, inline = true)
        public static void fix_getContextualStorage(@Thrown IllegalStateException ise,
                @Return(readOnly = true) ContextualStorage returnValue,
                @Argument(1) boolean createIfExists) throws Exception
        {
            if( createIfExists )
                throw ise;
            else
                returnValue = null; 
        }
    }
```
Then I received an exception like this:
```
08:49:38,550 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 84) MSC000001: Failed to start service jboss.deployment.unit."ROOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".undertow-deployment: java.lang.ExceptionInInitializerError
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:90)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:92)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112)
        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:186)
        at org.jboss.as.weld@26.1.1.Final//org.jboss.as.weld.injection.WeldInjectionContext.produce(WeldInjectionContext.java:46)
        at org.jboss.as.weld@26.1.1.Final//org.jboss.as.weld.injection.WeldManagedReferenceFactory.create(WeldManagedReferenceFactory.java:55)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.ComponentInstantiatorInterceptor.processInvocation(ComponentInstantiatorInterceptor.java:67)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:26)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@26.1.1.Final//org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@26.1.1.Final//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:141)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
        at org.jboss.as.ee@26.1.1.Final//org.jboss.as.ee.component.ComponentRegistry$ComponentManagedReferenceFactory.getReference(ComponentRegistry.java:163)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$6.createInstance(UndertowDeploymentInfoService.java:1239)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.ManagedListener.start(ManagedListener.java:48)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.ApplicationListeners.start(ApplicationListeners.java:159)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:210)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:105)
        at org.wildfly.extension.undertow@26.1.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
        ... 8 more
Caused by: java.lang.IllegalStateException: Cannot write return value for java.lang.Object arg2 in read-only context
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$OffsetMapping$ForReturnValue$Factory.make(Advice.java:3613)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Resolved$AbstractBase.<init>(Advice.java:7828)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Delegating$Resolved.<init>(Advice.java:9529)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Delegating$Resolved$ForMethodExit.<init>(Advice.java:10218)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Delegating$Resolved$ForMethodExit$WithExceptionHandler.<init>(Advice.java:10388)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Delegating$Resolved$ForMethodExit.of(Advice.java:10261)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice$Dispatcher$Delegating.asMethodExit(Advice.java:9500)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice.to(Advice.java:360)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice.to(Advice.java:330)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice.to(Advice.java:307)
        at deployment.ROOT.war//net.bytebuddy.asm.Advice.to(Advice.java:296)
        at deployment.ROOT.war//com.vaadin.cdi.context.RouteScopedBooBooFixer.<clinit>(RouteScopedBooBooFixer.java:48)

```
I looked up the code and it seems there is a problem there. the second part of the first condition should not be negated right? if it is readonly then there should be an exception, but here it negates that condition!
```java
     public OffsetMapping make(ParameterDescription.InDefinedShape target,
                                          AnnotationDescription.Loadable<Return> annotation,
                                          AdviceType adviceType) {
                    if (adviceType.isDelegation() && !annotation.getValue(RETURN_READ_ONLY).resolve(Boolean.class)) {
                        throw new IllegalStateException("Cannot write return value for " + target + " in read-only context");
                    } else {
                        return new ForReturnValue(target.getType(), annotation);
                    }
                }
```

**Comment by roeltje25** [comment]
Okay I fixed the issue and understand now how the Code in Advice.java works... It is actually correct I see now.
my adjusted code is now: 
```java
static class Advisor
    {
        @OnMethodExit(onThrowable = IllegalStateException.class, inline = true)
        public static void fix_getContextualStorage(@Thrown(readOnly = false) IllegalStateException ise,
                @Return(readOnly = false) ContextualStorage returnValue,
                @Argument(1) boolean createIfExists) throws Exception
        {
            if( !createIfExists )
            {
                ise = null;
                returnValue = null; // in bytebuddy interceptors we can override the return value this way
            }
        }
    }
```
