### ISSUE TITLE
NoSuchTypeException: Cannot resolve type description for org.apache.spark.internal.Logging

### ISSUE THREAD

**Issue by anlong465** [raphw/byte-buddy#1318]
Based upon bytebuddy, I had developed one instrument framework (similar with SkyWalking), which is working fine to intercept with hundreds of class methods. 

But recently I had met some problems to intercept some spark/hive class, for example the below HiveClientImpl.scala (https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala ). Such HiveClientImpl.class just implements the interface org.apache.spark.internal.Logging. 

If I intercepts HiveClientImpl, it would report error "NoSuchTypeException: Cannot resolve type description for org.apache.spark.internal.Logging" in System.out .

```
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for org.apache.spark.internal.Logging
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1074)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8294)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:7920)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1692)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1648)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3611)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:714)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:636)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:518)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:472)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11362)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11298)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11016)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:11690)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:11637)
	at java.security.AccessController.doPrivileged(AccessController.java:708)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11205)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:443)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:313)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1.doLoadClass(IsolatedClientLoader.scala:260)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1.loadClass(IsolatedClientLoader.scala:252)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
	at org.apache.spark.sql.hive.client.HiveClientImpl.newState(HiveClientImpl.scala:164)
	at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:129)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:309)

```

In order to resolve such issue:

-  I had tried "resubmission", 

```
             AgentBuilder builder = new AgentBuilder.Default();
            if (resubmission) {
                ScheduledExecutorService scheduledExecutorService = Executors.newSingleThreadScheduledExecutor();
                builder = builder.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                        .withResubmission(new AgentBuilder.RedefinitionStrategy.ResubmissionScheduler() {
                            @Override
                            public boolean isAlive() {
                                return true;
                            }

                            @Override
                            public Cancelable schedule(final Runnable job) {
                                return new Cancelable.ForFuture(scheduledExecutorService.scheduleWithFixedDelay(job, 1, 1, TimeUnit.SECONDS));
                            }
                        }).resubmitImmediate();
            }

            builder.type(getClassMatcher())
                    .transform(getTransformer())
                    .with(listener)
                    .installOn(instrumentation);

```

well, along with such resubmission logic, such error of "NoSuchTypeException: Cannot resolve type description" just disappears, but the expected interceptor didn't work at all without any error or warning.

- Furthermore, I had enhanced the listener, so that after the exception stack of NoSuchTypeException had been printed out, I tried to load the class once again when error happens,

```
    protected final static AgentBuilder.Listener listener = new AgentBuilder.Listener.Adapter() {
        @Override
        public void onError(String s, ClassLoader classLoader, JavaModule javaModule, boolean b, Throwable throwable) {

            throwable.printStackTrace();

            testClassLoading(classLoader, s);
            if (s.contains("HiveClientImpl")) {
                testClassLoading(classLoader, "org.apache.spark.internal.Logging");
            }
        }
        private void testClassLoading(ClassLoader classLoader, String s) {
            try {
                Class.forName(s, false, classLoader);
                System.out.println("success load class [" + s + "] by " + classLoader);
            } catch (ClassNotFoundException e) {
                System.out.println("failed to load class [" + s + "] by " + classLoader);
            }
        }

    };

```
Well, from SystemOut I could know that the related classloader could successfully load those classes.

```
success load class [org.apache.spark.sql.hive.client.HiveClientImpl$] by org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@c39f8511
success load class [org.apache.spark.internal.Logging] by org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@c39f8511

```

I know it might be caused by the isolated ClassLoader (org.apache.spark.sql.hive.client.IsolatedClientLoader), for example, I could intercept org.apache.spark.sql.hive.client.HiveClient, but I failed to intercept org.apache.spark.sql.hive.client.HiveClientImpl. Anyway, any suggestion for such net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException issue?

**Comment by raphw** [comment]
`resubmitImmediate` can be a bit brutal if you instrument many classes. Attempt a resubmit on error only.

The error occurs when Byte Buddy cannot find a class file for a class that is referenced in some manner. Normally this happens for optional types or if a class loader cannot reference a class file.

**Comment by anlong465** [comment]
Highly appreciated for your timely response.

1) actually, before I created this issue, I had tried many different ways, such as resubmitOnError(), resubmitImmediate(), etc. all are the same: such NoSuchTypeException disappears, but the expected interception doesn't happen. And a couple of hours ago, I had retried with resubmitOnError() again, no difference.

2) For the comment of "The error occurs when Byte Buddy cannot find a class file for a class", could you please explain more detail? who cannot find a class file? So far, the related ClassLoader could load such class. You mean that Byte Buddy needs the class file, not only the class object loaded by the related classloader?

**Comment by raphw** [comment]
As for (1) - Did you register a logger on your resubmission? Did you configure your agent manifest to support retransformation? Worst case, you'd need to set some breakpoints to see what is happening.

As for (2) - Byte Buddy calls `classLoader.getResource("some/location/MyClass.class")` to resolve the class file of `some.location.MyClass`. This way, Byte Buddy can for example match a class hierarchy without loading classes what would break the Java agent's premise if it loaded classes while instrumenting them. If this call does not return a given class file, the error you observe is happening.

**Comment by dogourd** [comment]
Maybe he wants a Method.Compiler implementation like this to skip these errors?
```java
@Override
    public MethodGraph.Linked compile(TypeDefinition typeDefinition, TypeDescription viewPoint) {
        LinkedHashMap<MethodDescription.SignatureToken, MethodGraph.Node> nodes = new LinkedHashMap<MethodDescription.SignatureToken, MethodGraph.Node>();
        for (MethodDescription methodDescription : typeDefinition.getDeclaredMethods()
            .filter(
                // ignores all methods which refer to unknown types
                failSafe(
                    isVirtual()
                        .and(not(isBridge()))
                        .and(isVisibleTo(viewPoint))
                        .and(hasParameters(whereNone(hasType(not(isVisibleTo(viewPoint))))))
                )
            )
        ) {
            nodes.put(methodDescription.asSignatureToken(), new MethodGraph.Node.Simple(methodDescription));
        }
        return new MethodGraph.Linked.Delegation(new MethodGraph.Simple(nodes), MethodGraph.Empty.INSTANCE, Collections.<TypeDescription, MethodGraph>emptyMap());
    }
```

**Comment by anlong465** [comment]
Thanks Rafael for your timely comments:
(1) I had added the below logger, not sure if it is the logger for resubmission; I also configure my agent MANIFEST.MF to add property "Can-Retransform-Classes" as true.

```
                builder = builder.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                        .with(AgentBuilder.RedefinitionStrategy.Listener.StreamWriting.toSystemOut())

```
well, those changes don't work.

(2) Thanks for clarification: how to resolve class file. After some tests and I realized that:
- there is no issue to load class via Class.forName(className, false, classLoader);
- but it is failed to resolve class file via classLoader.getResource("some/location/MyClass.class") even after Class.forName(className, false, classLoader)

so, I guess it is caused by the IsolatedClassLoader, for example, for the purpose of isolation, such  IsolatedClassLoader implements its own loadClass() method, but it doesn't override getResource() method. That is the reason why it could load class but fail to resolve class file.

I will enhance such IsolatedClassLoader firstly

**Comment by raphw** [comment]
Yes, I assume that this class loader is not fully implemented in the regard that it does not know how to look up class files. 

You can attempt to transform classes only after they are loaded if they fail before. You can set up a "resubmission" for this after you set the retransformation as above.

**Comment by anlong465** [comment]
Thanks Rafael. 

Yes, the root cause is the isolated class loader doesn't implement the classloader.getResource() method. I had fixed this issue by:
1) based upon the isolated class loader's related jars and parent, I create one new URLClassLoader which discards the isolation,
2) based upon the new URLClassLoader, I create one new ClassFileLocator:  ClassFileLocator.ForClassLoader.of(classloader)
3) and then add in the new ClassFileLocator into AgentBuilder.

Now, the actual interception result just behaviors as the expected. So, this issue could be closed, and thanks again for your time and guideline.

BTW, could you tell me more detail: how to transform classes only after they are loaded if they fail before?

**Comment by raphw** [comment]
As for your question: this would be the "resubmission" mechanism that is applies after the retransformation registration.

**Comment by anlong465** [comment]
Thanks again for clarification
