### ISSUE TITLE
Support redefine typevariable

### ISSUE THREAD

**Issue by kerler** [raphw/byte-buddy#132]
Dear Sir,

For below class "Version":

`  
  public abstract class Version<T> {
    private T data;
    public T getData() {return this.data;}
    void setData(T data) {this.data = data;}
  }
`

When execute below code using byte buddy 1.3.18, the 'make()' throw IllegalStateException. If replace the "T" in below code with "S", then no problem. Could you please change byte buddy so that the below code can work well?

`new ByteBuddy().redefine(Version.class).typeVariable("T", SomeClass.class).make();`

====The exception thrown by "make()"====

`Exception in thread "main" java.lang.IllegalStateException: size = 2
	at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findVariable(TypeVariableSource.java:125)
	at net.bytebuddy.description.TypeVariableSource$AbstractBase.findVariable(TypeVariableSource.java:123)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1973)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1898)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable$Symbolic.accept(TypeDescription.java:5555)
	at net.bytebuddy.description.method.MethodDescription$Latent.getReturnType(MethodDescription.java:1089)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:641)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:862)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1059)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:569)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:502)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:423)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:489)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:164)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2570)`

Thanks,
Baogang

**Comment by raphw** [comment]
First of all, you should upgrade your Byte Buddy version. The current error message would be:

> java.lang.IllegalStateException: Duplicate type variable symbol 'T' for class Version

I am looking into a possibility of allowing refinements for type variables. It is not an easy feature as it requires locating all uses of this type variable. Also consider that generics are a compile-time feature; i.e. the runtime does not behave differently after adding the variable, it would however effect libraries that explicitly parse the information.

**Comment by raphw** [comment]
Fixed on master. The `DynamicType.Builder` now declares a method `transform(ElementMatcher, Transformer)` that allows the transformation of existing type variables.
