### ISSUE TITLE
How to tell byte-buddy to load libjnidispatch.so from -Djava.library.path?

### ISSUE THREAD

**Issue by vaukai** [raphw/byte-buddy#1321]
On [Gentoo](https://packages.gentoo.org/packages/dev-java/byte-buddy) we are facing a test problem:
Is there a way for telling byte-buddy to load `libjnidispatch.so` from `-Djava.library.path` instead from the `.jar` file?
```
debug: -Djava.library.path=/usr/lib64/jna-4/
debug: org.junit.runner.JUnitCore
debug: net.bytebuddy.agent.AttacherTest
debug: net.bytebuddy.agent.ByteBuddyAgentAgentProviderTest
debug: net.bytebuddy.agent.ByteBuddyAgentAttachmentProviderTest
debug: net.bytebuddy.agent.ByteBuddyAgentInstallationTest
debug: net.bytebuddy.agent.ByteBuddyAgentTest
debug: net.bytebuddy.agent.InstallerTest
debug: net.bytebuddy.agent.VirtualMachineAttachmentTest
debug: net.bytebuddy.agent.VirtualMachineForHotSpotTest
debug: net.bytebuddy.agent.VirtualMachineForOpenJ9Test
JUnit version 4.13.2-SNAPSHOT
........................E.E.E.E........................
Time: 1.365
There were 4 failures:
1) testSystemProperties(net.bytebuddy.agent.VirtualMachineAttachmentTest)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.bytebuddy.agent.VirtualMachineAttachmentTest.testSystemProperties(VirtualMachineAttachmentTest.java:64)
	... 11 trimmed
Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path (target/test-classes:byte-buddy.jar:byte-buddy-agent.jar:byte-buddy.jar:/usr/share/asm-9/lib/asm.jar:/usr/share/asm-9/lib/asm-tree.jar:/usr/share/asm-9/lib/asm-analysis.jar:/usr/share/asm-9/lib/asm-commons.jar:/usr/share/asm-9/lib/asm-util.jar:/usr/share/findbugs-annotations/lib/findbugs-annotations.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/jna-4/lib/jna.jar:/usr/share/jna-4/lib/jna-platform.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/mockito-4/lib/mockito.jar:/usr/share/asm-9/lib/asm.jar:/usr/share/asm-9/lib/asm-tree.jar:/usr/share/asm-9/lib/asm-analysis.jar:/usr/share/asm-9/lib/asm-commons.jar:/usr/share/asm-9/lib/asm-util.jar:/usr/share/byte-buddy/lib/byte-buddy-agent.jar:/usr/share/byte-buddy/lib/byte-buddy.jar:/usr/share/objenesis/lib/objenesis.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar)
```

**Comment by raphw** [comment]
I just added a property `net.bytebuddy.test.jnapath` which you can set on the command line with Maven:

    mvn -Dnet.bytebuddy.test.jnapath=/usr/lib64/jna-4/ test

This should be picked up by JNA under running the tests.

**Comment by vaukai** [comment]
@raphw thanks for the your fast action. I'll give it a try.

**Comment by raphw** [comment]
I also added a rule to not run JNA related tests if JNA cannot be loaded. JNA is an optional extension of the attachment API, so Byte Buddy can be used most of the time even without supporting it.

**Comment by vaukai** [comment]
> I also added a rule to not run JNA related tests if JNA cannot be loaded. JNA is an optional extension of the attachment API, so Byte Buddy can be used most of the time even without supporting it.
 
Just tested with `1.12.17` in https://github.com/gentoo/gentoo/pull/27371 and it all seems to work.
However, I'm getting confused about `JNA not available` in the [test output](https://github.com/raphw/byte-buddy/files/9623775/byte-buddy-1.12.17-testlog.txt).

```
JUnit version 4.13.2-SNAPSHOT
........................Sep 22, 2022 9:52:31 AM net.bytebuddy.test.utility.JnaRule$NoOpStatement evaluate
INFO: Omitting test case: JNA not available
.Sep 22, 2022 9:52:31 AM net.bytebuddy.test.utility.JnaRule$NoOpStatement evaluate
INFO: Omitting test case: JNA not available
.Sep 22, 2022 9:52:31 AM net.bytebuddy.test.utility.JnaRule$NoOpStatement evaluate
INFO: Omitting test case: JNA not available
.Sep 22, 2022 9:52:31 AM net.bytebuddy.test.utility.JnaRule$NoOpStatement evaluate
INFO: Omitting test case: JNA not available
...............................Sep 22, 2022 9:52:31 AM net.bytebuddy.test.utility.IntegrationRule$NoOpStatement evaluate
```

**Comment by raphw** [comment]
This implies that Byte Buddy failed to invoke a simple JNA code snippet and does then ignore the tests that use JNA.
