### ISSUE TITLE
Transforming methods in abstract classes

### ISSUE THREAD

**Issue by kctang** [raphw/byte-buddy#137]
Hi! Firstly, thanks for this awesome library!

I am creating a javaagent with this definition:

```java
new Default().
        with(makeDebugListener()).
        type(nameStartsWith("com.foo.mypackage")).
        and(not(isInterface())).
//                and(not(ElementMatchers.<TypeDescription>isAbstract())).
        transform(makeMyTransformer()).
        installOn(inst);

// makeMyTransformer returns this
return new Transformer() {
    @Override
    public DynamicType.Builder<?> transform(
            DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader
    ) {
        return builder.method(nameContainsIgnoreCase("someMethod")).
                intercept(MethodDelegation.to(MyInterceptor.class));
    }
};
```

Managed to get the codes running and transforming based on `MyInterceptor`. So cool!

However, I noticed abstract classes are throwing exceptions (from the `Listener`):

```text
java.lang.IllegalArgumentException: None of [public static void demo.xxx.MyProfileInterceptor.log(java.lang.reflect.Method,java.util.concurrent.Callable) throws java.lang.Exception] allows for delegation from public java.lang.String com.yyy.AbstractAaaBbb.doSomeMethodBlah
()
        at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.process(MethodDelegationBinder.java:881)
        at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1225)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:564)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:498)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor.visitEnd(TypeWriter.java:3135)
        at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
```

I tried adding `and(not(ElementMatchers.<TypeDescription>isAbstract()))` that I commented out above but it did not work.

Any idea?

**Comment by raphw** [comment]
You are currently exluding abstract classes and interfaces. It seems to me that you would like to exclude abstract methods.

In this case, you should narrow down your method matcher, not your type matcher.
