### ISSUE TITLE
ByteBuddy and Quarkus native exception

### ISSUE THREAD

**Issue by imperatorx** [raphw/byte-buddy#1370]
When calling make() i got an exception:

```
Caused by: java.lang.IllegalStateException: size = 0
        at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:139)
        at net.bytebuddy.implementation.InvocationHandlerAdapter.apply(InvocationHandlerAdapter.java:255)
        at net.bytebuddy.implementation.InvocationHandlerAdapter$ForInstance$Appender.apply(InvocationHandlerAdapter.java:404)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:730)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:715)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:622)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:6043)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4050)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3734)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3986)
```

I'm extending a base class and defining an additional field and overriding all method calls, basically like a JPA lazy entity proxy. I've registered the base class, the new field's type and the interface the class implements for reflection as a quarkus build item, so reflection data is present in the native image.

If using ByteBuddy at runtime in GraalVM is not possible yet, is it feasible to run ByteBuddy at build time instead of runtime (quarkus deployment module, as I'm writing a quarkus extension) and somehow write the generated class somehow as a .class file to disk?

**Comment by imperatorx** [comment]
I went the way of AOT class generation, but hit a problem, even in **regular JVM** mode:

When I generate the class at runtime, and load it with 
```
createProxy(originalClass)
  .load(Thread.currentThread().getContextClassLoader())
  .getLoaded();
```
It works, but when I generate the bytecode at build time using the exact same method, include it as a GeneratedClassBuildItem in quarkus and load it at runtime using:

`Class.forName("proxy.class.name", true, Thread.currentThread().getContextClassLoader())`

The class is loaded, but throws when trying to invoke a method: `java.lang.NullPointerException: Cannot invoke "java.lang.reflect.InvocationHandler.invoke(Object, java.lang.reflect.Method, Object[])" because "my.class.name_Proxy.invocationHandler$bqqrcb1" is null` as all the invocationhandlers are null.

What am I doing wrong here?

**Comment by imperatorx** [comment]
Looks like the class initialization is dependent on the framework (to set the static variables with the interceptors), so I went with javassist .
