### ISSUE TITLE
IllegalStateException when running a web Application with a bytebuddy java agent 

### ISSUE THREAD

**Issue by avinash-fk** [raphw/byte-buddy#1372]
When running a web application built using dropwizard and lombok, the following error is noticed for multiple classes.

[Byte Buddy] ERROR com.xxxx.xxxx.xxx.x.xxxxRequest [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=false]
java.lang.IllegalStateException: Unexpected type reference on method: 19
	at net.bytebuddy.pool.TypePool$Default$TypeExtractor$MethodExtractor.visitTypeAnnotation(TypePool.java:8198)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1213)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:679)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:391)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1176)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1160)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1240)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1338)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getDeclaredAnnotations(TypeDescription.java:8101)
	at net.bytebuddy.matcher.DeclaringAnnotationMatcher.matches(DeclaringAnnotationMatcher.java:48)
	at net.bytebuddy.matcher.DeclaringAnnotationMatcher.matches(DeclaringAnnotationMatcher.java:27)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1292)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:9983)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:9996)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:10252)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:10584)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10889)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10836)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.findClasses(OReflectionHelper.java:124)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.findClasses(OReflectionHelper.java:121)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.findClasses(OReflectionHelper.java:121)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.findClasses(OReflectionHelper.java:121)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.findClasses(OReflectionHelper.java:121)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.getClassesFor(OReflectionHelper.java:79)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.performScan(ClasspathScanner.java:108)
	at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.<init>(ClasspathScanner.java:50)
	at ru.vyarus.dropwizard.guice.module.GuiceyInitializer.<init>(GuiceyInitializer.java:77)
	at ru.vyarus.dropwizard.guice.GuiceBundle.initialize(GuiceBundle.java:116)
	at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:134)
	at com.xxxx.xxxx.xxx.ManagerApplication.initialize(ManagerApplication.java:67)
	at io.dropwizard.Application.run(Application.java:88)
	at com.xxxx.xxxx.xxx.ManagerApplication.main(ManagerApplication.java:55)

Bytebuddy version is 1.12.6. What would be causing this issues ?

**Comment by raphw** [comment]
Annotations of type `0x13` describe a field reference which cannot appear on a type. Older javac compilers issued this type by mistake which is why Byte Buddy handles this gracefully in newer versions.

All you need to do is update.

**Comment by raphw** [comment]
Annotations of type `0x13` describe a field reference which cannot appear on a type. Older javac compilers issued this type by mistake which is why Byte Buddy handles this gracefully in newer versions.

All you need to do is update.
