### ISSUE TITLE
Can not transform method that have generic array parameters

### ISSUE THREAD

**Issue by ghzdw** [raphw/byte-buddy#1392]
hi:
   the bytebuddy version that i used  is 1.12.10. like title say, when i try to transform method that have generic array parameters, transform is not effective,by add AgentBuilder.Listener to debug, it print 

> java.lang.NullPointerException: null
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reducing.onGenericArray(TypeDescription.java:2328)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reducing.onGenericArray(TypeDescription.java:2283)

in onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) method.
simplified  code like below:
1. agent entry  code:
```
public class AgentDemo {
    public static void premain(String args, Instrumentation instrumentation) {
        new AgentBuilder.Default()
                .type(named("com.zhao.util.StrUtil"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder
                                .method(isStatic())
                                .intercept(FixedValue.nullValue());
                    }
                })
                .with(new ByteBuddyListener())
                .installOn(instrumentation);
    }
}
```
2. the code of business class com.zhao.util.StrUtil : 
```
public class StrUtil {
    /**
     * tips: both join(final Z... elements) and join(final Z[] elements)
     * can not transformed by bytebuddy
     */
    // public static <Z> String join(final Z... elements) {
    public static <Z> String join(final Z[] elements) {
        return "joinResult";
    }
}
```
3. the code of ByteBuddyListener : 
```
public class ByteBuddyListener implements AgentBuilder.Listener {
    @Override
    public void onDiscovery(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {
    }

    @Override
    public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded, DynamicType dynamicType) {
    }

    @Override
    public void onIgnored(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded) {
    }

    @Override
    public void onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) {
        log.error("onError when enhance class name:{}",typeName,throwable);
    }

    @Override
    public void onComplete(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {
    }
}
```
all related code as above.

**Comment by raphw** [comment]
Before I look into it, could you try with the most recent version of Byte Buddy?
