### ISSUE TITLE
ClassNotFoundException: java/sql/Statement 

### ISSUE THREAD

**Issue by jayrrrrr** [raphw/byte-buddy#1416]
hi，
     I came across an error，cause an exception when I use "java/sql/Statement" in jdk 11，but jdk 8 doesn t have this problem.
     I was very confused for this.

//this my exception log.
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ClassNotFoundException: java/sql/Statement
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
```

and  I found a strange phenomenon

``` 
   @Advice.OnMethodEnter
    public static void enter(@Advice.Origin Method method, @Advice.AllArguments Object[] args) {
        try {

            Class<?> aClass = Class.forName("java.sql.Statement");
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
        //do something.
    }
```
That doesn't work.

but when i use  ClassLoader.getSystemClassLoader().loadClass() it is work
``` 
   @Advice.OnMethodEnter
    public static void enter(@Advice.Origin Method method, @Advice.AllArguments Object[] args) {
          try {
            ClassLoader.getSystemClassLoader().loadClass("java.sql.Statement");
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
        //do something.
    }
```
The above issues are only present in the jdk 9 and above versions.

**Comment by raphw** [comment]
Since JDK9, SQL values are on the platform loader which are not visible on the boot loader. This is expected with the system loader being a child of the platform loader.
