### ISSUE TITLE
After open the {SW AGENT CACHE CLASS}, is still an error 【net. Bytebuddy. Pool. TypePool $$NoSuchTypeException Resolution: Cannot resolve type description for org.apache.thrift.TServiceClient$auxiliary$JnOx25xa】

### ISSUE THREAD

**Issue by RTxin** [raphw/byte-buddy#1419]
First Problem

- I used Skywalking and another Agent made with Bytebuddy library at the same time on my Application
- The order is 'Skywalking' first and then 'Another agent'
- After `TypePool$Resolution$NoSuchTypeException` is initially reported, the `SW AGENT CACHE CLASS` is enabled, which greatly reduces the amount of errors reported, but some classes still report errors
- Strangely, when using Arthas to check the byte code, it will pass through the `Transform` again. At this time, it will look at the enhancement, but the` TasynClientAdvice.tasynclientConStructructivity#OnConStrut` cannot be executed.
- Even `@Advice.OnMethodExit(inline = true)` does not catch an exception with or without [parameter supress]
- What confused me even more was that when I was ready to provide a reproducible demo, the demo worked

**Here is the bytecode from Arthas：**
```java
       public TAsyncClient(TProtocolFactory protocolFactory, TAsyncClientManager manager, TNonblockingTransport transport) {
/*33*/     this(protocolFactory, manager, transport, 0L);
       }
       public TAsyncClient(TProtocolFactory tProtocolFactory, TAsyncClientManager tAsyncClientManager, TNonblockingTransport tNonblockingTransport, long l) {
           TAsyncClient tAsyncClient = this;
           TProtocolFactory tProtocolFactory2 = tProtocolFactory;
           TAsyncClientManager tAsyncClientManager2 = tAsyncClientManager;
           TNonblockingTransport tNonblockingTransport2 = tNonblockingTransport;
           long l2 = l;
           tAsyncClient(tProtocolFactory2, tAsyncClientManager2, tNonblockingTransport2, l2, null);
           delegate$ggg83t1.intercept(tAsyncClient, new Object[]{tProtocolFactory2, tAsyncClientManager2, tNonblockingTransport2, l2});
           try {
               TAsynClientAdvice.TAsyncServiceClientConstructInterceptor.onConstruct(this, new Object[]{tProtocolFactory, tAsyncClientManager, tNonblockingTransport, l});
           }
           catch (Throwable throwable) {}
       }
       /*
        * WARNING - void declaration
        */
       private /* synthetic */ TAsyncClient(TProtocolFactory tProtocolFactory, TAsyncClientManager tAsyncClientManager, TNonblockingTransport tNonblockingTransport, long l, auxiliary.WHuSnmrx wHuSnmrx) {
           void timeout;
           void transport;
           void manager;
           void protocolFactory;
/*37*/     this.___protocolFactory = protocolFactory;
/*38*/     this.___manager = manager;
/*39*/     this.___transport = transport;
/*40*/     this.___timeout = timeout;
       }
```
**This is the configuration of demo：**
He can be enhanced normally
```java
public class MyClass {

    @Advice.OnMethodExit(
            suppress = Throwable.class,
            inline = false)
    public static void onConstruct(
            @Advice.This(optional = true) Object objInst,
            @Advice.AllArguments(typing = Assigner.Typing.DYNAMIC) Object[] allArguments) {
        System.out.println("TAsyncClient object has been constructed");
    }

    public static void premain(String agentArgs, Instrumentation inst) {
        final ByteBuddy byteBuddy = new ByteBuddy()
                .with(TypeValidation.of(false))
                .with(FailSafeDeclaredMethodsCompiler.INSTANCE);
        new AgentBuilder.Default(byteBuddy)
                .disableClassFormatChanges()
                .type(named("org.apache.thrift.async.TAsyncClient"))
                .transform((builder, typeDescription, classLoader, module) ->
                        builder.visit(Advice.to(MyClass.class).on(isConstructor()))
                )
                .installOn(inst);
    }
}
```

**This is the real agent configuration:**
```java
final ByteBuddy byteBuddy = new ByteBuddy()
                    .with(TypeValidation.of(false))
                    .with(FailSafeDeclaredMethodsCompiler.INSTANCE);
AgentBuilder builder = new Default(byteBuddy)
                    .disableClassFormatChanges()
                    .with(RedefinitionStrategy.RETRANSFORMATION)
                    .with(AgentBuilder.RedefinitionStrategy.BatchAllocator.ForFixedSize.ofSize(1))
                    .with(RedefinitionStrategy.DiscoveryStrategy.Reiterating.INSTANCE)
                    .with(AgentBuilder.LambdaInstrumentationStrategy.DISABLED)
```
**The following is the exception information: **
```java
 Execption: thirdparty.net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for org.apache.thrift.TServiceClient$auxiliary$JnOx25xa
	at thirdparty.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162)
	at thirdparty.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1074)
	at thirdparty.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8301)
	at thirdparty.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
	at thirdparty.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
	at thirdparty.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7781)
	at thirdparty.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
	at thirdparty.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
	at thirdparty.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at thirdparty.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
	at thirdparty.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
	at thirdparty.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48)
	at thirdparty.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27)
	at thirdparty.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48)
	at thirdparty.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26)
	at thirdparty.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
	at thirdparty.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49)
	at thirdparty.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28)
	at thirdparty.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:144)
	at thirdparty.net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at thirdparty.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:506)
	at thirdparty.net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11741)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11677)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11395)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12069)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12016)
	at java.security.AccessController.doPrivileged(Native Method)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11584)
	at instrumentation.CodeBarrierTransformerDecorator$CodeBarrierResettableClassFileTransformer.transform(CodeBarrierTransformerDecorator.java:45)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.getDeclaredMethods(Class.java:2003)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:367)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:207)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:189)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:128)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1077)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:567)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.yihua.thrift.ThriftClientApplication.main(ThriftClientApplication.java:10)
```
I hope you can reply to me at your leisure！Thanks!

**Comment by raphw** [comment]
These types are added by Byte Buddy as they are needed, but they cannot be resolved from the class loader from another agent's perspective. At the same time, it should be safe to ignore these methods. You can wrap matchers in `ElementMatchers.failSafe` to exclude them.

**Comment by RTxin** [comment]
> 
thank you for your reply!
Yes, as you said, I have tried to enhance the `TServiceClient` classes by loading `Another Agent` with a custom classloader.The same problems that we mentioned earlier will arise.
I'm not sure if I've described my question very clearly, if you don't understand something, please let me know, I will try to describe it as clear as possible!
Thanks again!

**Comment by RTxin** [comment]
`    public MethodGraph.Linked compile(TypeDefinition typeDefinition, TypeDescription viewPoint) {
        for (MethodDescription methodDescription : typeDefinition.getDeclaredMethods()
            .filter(
                // ignores all methods which refer to unknown types
                failSafe(
                    isVirtual()
                        .and(not(isBridge()))
                        .and(isVisibleTo(viewPoint))
                        .and(hasParameters(whereNone(hasType(not(isVisibleTo(viewPoint))))))
                )
            )
        ) {
            //todo something
        }
        return new MethodGraph.Linked.Delegation(.....);
    }`

**Comment by raphw** [comment]
It seems like you are not using it though, considering the stack trace?

**Comment by dogourd** [comment]
@raphw 
Hello, Rafael. I just added breakpoints and did some debugging on this issue. From the above stack trace, it appears that the exception was thrown from `MethodRegistry#prepare`.
```java
for (MethodDescription methodDescription : CompoundList.of(
                    instrumentedType.getDeclaredMethods().filter(not(isVirtual()).and(relevanceMatcher)),
                    new MethodDescription.Latent.TypeInitializer(instrumentedType))) {
    for (Entry entry : entries) {
        if (entry.resolve(instrumentedType).matches(methodDescription)) {
            implementations.put(methodDescription, entry.asPreparedEntry(instrumentedType, methodDescription, methodDescription.getVisibility()));
            break;
        }
    }
    methods.add(methodDescription);
}
``` 
Here's what's happening:   
for the `org.apache.thrift.server.TServer`, by default, it has one constructor:
```java
protected TServer(AbstractServerArgs args) {
    processorFactory_ = args.processorFactory;
    serverTransport_ = args.serverTransport;
    inputTransportFactory_ = args.inputTransportFactory;
    outputTransportFactory_ = args.outputTransportFactory;
    inputProtocolFactory_ = args.inputProtocolFactory;
    outputProtocolFactory_ = args.outputProtocolFactory;
}
``` 
The first agent enhanced it using bytebuddy and used some auxiliary types internally. When this class is passed to the second agent for processing, `MethodRegistry#prepare` will be called and it will invoke `InstrumentedType#getDeclaredMethods`. At this point, it will likely see two constructors as shown below:
```java
protected TServer(AbstractServerArgs abstractServerArgs) {
    TServer tServer = this;
    AbstractServerArgs abstractServerArgs2 = abstractServerArgs;
    tServer(abstractServerArgs2, null);
    // enhance by first agent.
    delegate$6386i10.intercept((Object)tServer, new Object[]{abstractServerArgs2});
}
private /* synthetic */ TServer(AbstractServerArgs args, auxiliary.Ig29GTq8 ig29GTq8) {
    /*117*/     this.stopped_ = false;
    /*120*/     this.processorFactory_ = args.processorFactory;
    /*121*/     this.serverTransport_ = args.serverTransport;
    /*122*/     this.inputTransportFactory_ = args.inputTransportFactory;
    /*123*/     this.outputTransportFactory_ = args.outputTransportFactory;
    /*124*/     this.inputProtocolFactory_ = args.inputProtocolFactory;
    /*125*/     this.outputProtocolFactory_ = args.outputProtocolFactory;
}
``` 
However, when it reaches `instrumentedType.getDeclaredMethods().filter(not(isVirtual()).and(relevanceMatcher))`, attempting to check the parameter visibility of the second constructor will disrupt the execution and cause the target type to be unable to be enhanced. The logic here seems to be out of the user's control at present, should we consider adding failsafe or skip synthetic methods?

**Comment by raphw** [comment]
You are right, such methods should just be ignored as they cannot be resolved properly anyways.

**Comment by wspray** [comment]
hello, I wonder if this issue have been solved, because recently i have the very same issue in my project.

**Comment by raphw** [comment]
I think this issue was stale, therefore I closed it.
