### ISSUE TITLE
When change from JDK 11 to 17, throw UnsupportedOperationException

### ISSUE THREAD

**Issue by nevermore18** [raphw/byte-buddy#1445]
1. I want to enhance a method called **get** in **org.junit.platform.launcher.core.LauncherConfigurationParameters.java** as below:
```java
    public Optional<String> get(String key) {
        return Optional.ofNullable(this.getProperty(key));
    }
```
2. And I use byte-buddy to write this:
```java
    private static final String LAUNCHER_CLASS = "org.junit.platform.launcher.core.LauncherConfigurationParameters";

    private void enhanceCucumberDefaultConfig() throws ClassNotFoundException {
        Class<?> configClass = Class.forName(LAUNCHER_CLASS);
        new ByteBuddy()
                .redefine(configClass)
                .method(named("get")
                        .and(isDeclaredBy(configClass))
                        .and(returns(Optional.class)))
                .intercept(MethodDelegation.to(CucumberConfigEditor.class))
                .make()
                .load(getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
    }
```

3. This is CucumberConfigEditor.class which I want to intercept:
```java
public class CucumberConfigEditor {

    @RuntimeType
    public static Object intercept(@Argument(0) String key, @This Object current) throws Exception {
        String originalValue = "test";

        return Optional.ofNullable(originalValue);
    }
}
```
4. I use JDK 11 and byte-buddy 1.11.0, it can work well, but when I just change to JDK 17, an error occurs:
```java
java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1013)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1142)
	at net.bytebuddy.dynamic.loading.$Proxy17.retransformClasses(Unknown Source)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$2.apply(ClassReloadingStrategy.java:408)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.load(ClassReloadingStrategy.java:236)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6154)
```

**Comment by raphw** [comment]
Try registering `VisibilityBridgeStrategy.Default.NEVER` in your `ByteBuddy` instance. This disables that Byte Buddy attempts to "upgrade" bridge methods.

**Comment by nevermore18** [comment]
I try to register VisibilityBridgeStrategy.Default.NEVER, unfortunately still this error in JDK 17. 
```java
    private void enhanceCucumberDefaultConfig() throws ClassNotFoundException {
        Class<?> configClass = Class.forName(LAUNCHER_CLASS);
        new ByteBuddy()
                .with(VisibilityBridgeStrategy.Default.NEVER)
                .redefine(configClass)
                .method(named("get")
                        .and(isDeclaredBy(configClass))
                        .and(returns(Optional.class)))
                .intercept(MethodDelegation.to(CucumberConfigEditor.class))
                .make()
                .load(getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
    }
```

**Comment by raphw** [comment]
You can set the net.bytebuddy.dump system property to a folder. Then use the javap tool to see where the classes differ.

**Comment by nevermore18** [comment]
Yeah, I use JDK 17 and use javap to see the classes.
1. org.junit.platform.launcher.core.LauncherConfigurationParameters-original.1685112425947.class
```java
    public Optional<String> get(String key) {
        return Optional.ofNullable(this.getProperty(key));
    }
```
2. org.junit.platform.launcher.core.LauncherConfigurationParameters.1685112425947.class
```java
    public Optional<String> get(String var1) {
        return (Optional)CucumberConfigEditor.intercept(var1, this); // it did change
    }
```
3. CucumberConfigEditor.java
```java
    public class CucumberConfigEditor {
    
        @RuntimeType
        public static Object intercept(@Argument(0) String key, @This Object current) throws Exception {
            String originalValue = "test";
    
            return Optional.ofNullable(originalValue);
        }
    }
```
4. When I use JDK 11 and create a breakpoint at CucumberConfigEditor.java, it can enter the breakpoint, but just change it to JDK 17, it cannot.
5. it throw error at
```java
.load(getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
```
```java
java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method
```

**Comment by raphw** [comment]
It claims that there is a deleted method. I would need to dee the entire classes.

**Comment by nevermore18** [comment]
There are all the classes:
```java
 java.io.Serializable. 1685112426403.class java.o.Serializable-original.1685112426403.class  
 java.lang.ClassLoader$ByteBuddyAccessor$CbnSUHmk.1685112426140.class java.lang.Object.1685112426249.class 
 java.lang.Object-original.1685112426249.class java.til.EventObject.1685112426404.class java.til.EventObject- 
 original.1685112426404.class net.bytebuddy.mirror.AccessibleObject.1685112426107.class 
 net.bytebuddy.mirror.AccessibleObject-original.1685112426107.class 
 org.junit.platform.launcher.core.LauncherConfigurationParameters.1685112425947.class 
 org.junit.platform.launcher.core.LauncherConfigurationParameters-original.1685112425947.class 
 org.mockito.internal.til.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$FOisKzZY.1685112426194.class 
 org.springframework.context.Application Event.1685112426420.class org.springframework.context.ApplicationEvent- 
 original.1685112426420.class org.springframework.test.context.event.BeforeTestClassEvent.1685112426418.class 
 org.springframework.test.context.event.BeforeTestClassEvent-original.1685112426418.class 
 org.springframework.test.context.event.TestContextEvent.1685112426411.class 
 org.springframework.test.context.event.TestContextEvent-original.1685112426411.class
```
 org.junit.platform.launcher.core.LauncherConfigurationParameters-original.1685112425947.class 
```java
package org.junit.platform.launcher.core;

import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Properties;
import java.util.Set;
import org.junit.platform.commons.logging.Logger;
import org.junit.platform.commons.logging.LoggerFactory;
import org.junit.platform.commons.util.ClassLoaderUtils;
import org.junit.platform.commons.util.Preconditions;
import org.junit.platform.commons.util.ToStringBuilder;
import org.junit.platform.engine.ConfigurationParameters;

class LauncherConfigurationParameters implements ConfigurationParameters {
    private static final Logger logger = LoggerFactory.getLogger(LauncherConfigurationParameters.class);
    private final List<ParameterProvider> providers;

    static Builder builder() {
        return new Builder((1)null);
    }

    private LauncherConfigurationParameters(List<ParameterProvider> providers) {
        this.providers = providers;
    }

    public Optional<String> get(String key) {
        return Optional.ofNullable(this.getProperty(key));
    }

    public Optional<Boolean> getBoolean(String key) {
        return this.get(key).map(Boolean::parseBoolean);
    }

    public int size() {
        return this.providers.stream().mapToInt(ParameterProvider::size).sum();
    }

    private String getProperty(String key) {
        Preconditions.notBlank(key, "key must not be null or blank");
        return (String)this.providers.stream().map((parameterProvider) -> {
            return parameterProvider.getValue(key);
        }).filter(Objects::nonNull).findFirst().orElse((Object)null);
    }

    public String toString() {
        return (new ToStringBuilder(this)).append("lookups", this.providers).toString();
    }

    private static Properties loadClasspathResource(String configFileName) {
        Properties props = new Properties();

        try {
            ClassLoader classLoader = ClassLoaderUtils.getDefaultClassLoader();
            Set<URL> resources = new LinkedHashSet(Collections.list(classLoader.getResources(configFileName)));
            if (!resources.isEmpty()) {
                if (resources.size() > 1) {
                    logger.warn(() -> {
                        return String.format("Discovered %d '%s' configuration files in the classpath; only the first will be used.", resources.size(), configFileName);
                    });
                }

                URL configFileUrl = (URL)resources.iterator().next();
                logger.config(() -> {
                    return String.format("Loading JUnit Platform configuration parameters from classpath resource [%s].", configFileUrl);
                });
                URLConnection urlConnection = configFileUrl.openConnection();
                urlConnection.setUseCaches(false);
                InputStream inputStream = urlConnection.getInputStream();

                try {
                    props.load(inputStream);
                } catch (Throwable var10) {
                    if (inputStream != null) {
                        try {
                            inputStream.close();
                        } catch (Throwable var9) {
                            var10.addSuppressed(var9);
                        }
                    }

                    throw var10;
                }

                if (inputStream != null) {
                    inputStream.close();
                }
            }
        } catch (Exception var11) {
            logger.warn(var11, () -> {
                return String.format("Failed to load JUnit Platform configuration parameters from classpath resource [%s].", configFileName);
            });
        }

        return props;
    }
}
```
org.junit.platform.launcher.core.LauncherConfigurationParameters.1685112425947.class 
```java
package org.junit.platform.launcher.core;

import com.sap.s4hana.eureka.test.cucumber.biz.initial.CucumberConfigEditor;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Properties;
import java.util.Set;
import org.junit.platform.commons.logging.Logger;
import org.junit.platform.commons.logging.LoggerFactory;
import org.junit.platform.commons.util.ClassLoaderUtils;
import org.junit.platform.commons.util.Preconditions;
import org.junit.platform.commons.util.ToStringBuilder;
import org.junit.platform.engine.ConfigurationParameters;

class LauncherConfigurationParameters implements ConfigurationParameters {
    private static final Logger logger = LoggerFactory.getLogger(LauncherConfigurationParameters.class);
    private final List<ParameterProvider> providers;

    static Builder builder() {
        return new Builder((1)null);
    }

    private LauncherConfigurationParameters(List<ParameterProvider> providers) {
        this.providers = providers;
    }

    public Optional<String> get(String var1) {
        return (Optional)CucumberConfigEditor.intercept(var1, this);
    }

    public Optional<Boolean> getBoolean(String key) {
        return this.get(key).map(Boolean::parseBoolean);
    }

    public int size() {
        return this.providers.stream().mapToInt(ParameterProvider::size).sum();
    }

    private String getProperty(String key) {
        Preconditions.notBlank(key, "key must not be null or blank");
        return (String)this.providers.stream().map((parameterProvider) -> {
            return parameterProvider.getValue(key);
        }).filter(Objects::nonNull).findFirst().orElse((Object)null);
    }

    public String toString() {
        return (new ToStringBuilder(this)).append("lookups", this.providers).toString();
    }

    private static Properties loadClasspathResource(String configFileName) {
        Properties props = new Properties();

        try {
            ClassLoader classLoader = ClassLoaderUtils.getDefaultClassLoader();
            Set<URL> resources = new LinkedHashSet(Collections.list(classLoader.getResources(configFileName)));
            if (!resources.isEmpty()) {
                if (resources.size() > 1) {
                    logger.warn(() -> {
                        return String.format("Discovered %d '%s' configuration files in the classpath; only the first will be used.", resources.size(), configFileName);
                    });
                }

                URL configFileUrl = (URL)resources.iterator().next();
                logger.config(() -> {
                    return String.format("Loading JUnit Platform configuration parameters from classpath resource [%s].", configFileUrl);
                });
                URLConnection urlConnection = configFileUrl.openConnection();
                urlConnection.setUseCaches(false);
                InputStream inputStream = urlConnection.getInputStream();

                try {
                    props.load(inputStream);
                } catch (Throwable var10) {
                    if (inputStream != null) {
                        try {
                            inputStream.close();
                        } catch (Throwable var9) {
                            var10.addSuppressed(var9);
                        }
                    }

                    throw var10;
                }

                if (inputStream != null) {
                    inputStream.close();
                }
            }
        } catch (Exception var11) {
            logger.warn(var11, () -> {
                return String.format("Failed to load JUnit Platform configuration parameters from classpath resource [%s].", configFileName);
            });
        }

        return props;
    }
}
```

**Comment by nevermore18** [comment]
And I found a strange place, it indeed deleted some methods:
1.  net.bytebuddy.mirror.AccessibleObject-original.1685112426107.class
```java
import java.lang.annotation.Annotation;
import java.lang.invoke.MethodHandle;
import java.lang.ref.WeakReference;
import java.security.AccessController;
import jdk.internal.access.SharedSecrets;
import jdk.internal.misc.VM;
import jdk.internal.reflect.CallerSensitive;
import jdk.internal.reflect.Reflection;
import jdk.internal.reflect.ReflectionFactory;
import sun.security.action.GetPropertyAction;
import sun.security.util.SecurityConstants;

public class AccessibleObject implements AnnotatedElement {
    boolean override;
    static final ReflectionFactory reflectionFactory;
    volatile Object accessCheckCache;
    private static volatile boolean printStackWhenAccessFails;
    private static volatile boolean printStackPropertiesSet;

    static void checkPermission() {
        SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            sm.checkPermission(SecurityConstants.ACCESS_PERMISSION);
        }

    }

    @CallerSensitive
    public static void setAccessible(AccessibleObject[] array, boolean flag) {
        checkPermission();
        int var4;
        if (flag) {
            Class<?> caller = Reflection.getCallerClass();
            array = (AccessibleObject[])array.clone();
            AccessibleObject[] var3 = array;
            var4 = array.length;

            for(int var5 = 0; var5 < var4; ++var5) {
                AccessibleObject ao = var3[var5];
                ao.checkCanSetAccessible(caller);
            }
        }

        AccessibleObject[] var7 = array;
        int var8 = array.length;

        for(var4 = 0; var4 < var8; ++var4) {
            AccessibleObject ao = var7[var4];
            ao.setAccessible0(flag);
        }

    }

    @CallerSensitive
    public void setAccessible(boolean flag) {
        checkPermission();
        this.setAccessible0(flag);
    }

    boolean setAccessible0(boolean flag) {
        this.override = flag;
        return flag;
    }

    @CallerSensitive
    public final boolean trySetAccessible() {
        checkPermission();
        if (this.override) {
            return true;
        } else if (!Member.class.isInstance(this)) {
            return this.setAccessible0(true);
        } else {
            Class<?> declaringClass = ((Member)this).getDeclaringClass();
            if (declaringClass == Class.class && this instanceof Constructor) {
                return false;
            } else {
                return this.checkCanSetAccessible(Reflection.getCallerClass(), declaringClass, false) ? this.setAccessible0(true) : false;
            }
        }
    }

    void checkCanSetAccessible(Class<?> caller) {
    }

    final void checkCanSetAccessible(Class<?> caller, Class<?> declaringClass) {
        this.checkCanSetAccessible(caller, declaringClass, true);
    }

    private boolean checkCanSetAccessible(Class<?> caller, Class<?> declaringClass, boolean throwExceptionIfDenied) {
        if (caller == MethodHandle.class) {
            throw new IllegalCallerException();
        } else {
            Module callerModule = caller.getModule();
            Module declaringModule = declaringClass.getModule();
            if (callerModule == declaringModule) {
                return true;
            } else if (callerModule == Object.class.getModule()) {
                return true;
            } else if (!declaringModule.isNamed()) {
                return true;
            } else {
                String pn = declaringClass.getPackageName();
                int modifiers;
                if (this instanceof Executable) {
                    modifiers = ((Executable)this).getModifiers();
                } else {
                    modifiers = ((Field)this).getModifiers();
                }

                boolean isClassPublic = Modifier.isPublic(declaringClass.getModifiers());
                if (isClassPublic && declaringModule.isExported(pn, callerModule)) {
                    if (Modifier.isPublic(modifiers)) {
                        return true;
                    }

                    if (Modifier.isProtected(modifiers) && Modifier.isStatic(modifiers) && this.isSubclassOf(caller, declaringClass)) {
                        return true;
                    }
                }

                if (declaringModule.isOpen(pn, callerModule)) {
                    return true;
                } else if (throwExceptionIfDenied) {
                    String msg = "Unable to make ";
                    if (this instanceof Field) {
                        msg = msg + "field ";
                    }

                    msg = msg + this + " accessible: " + declaringModule + " does not \"";
                    if (isClassPublic && Modifier.isPublic(modifiers)) {
                        msg = msg + "exports";
                    } else {
                        msg = msg + "opens";
                    }

                    msg = msg + " " + pn + "\" to " + callerModule;
                    InaccessibleObjectException e = new InaccessibleObjectException(msg);
                    if (printStackTraceWhenAccessFails()) {
                        e.printStackTrace(System.err);
                    }

                    throw e;
                } else {
                    return false;
                }
            }
        }
    }

    private boolean isSubclassOf(Class<?> queryClass, Class<?> ofClass) {
        while(queryClass != null) {
            if (queryClass == ofClass) {
                return true;
            }

            queryClass = queryClass.getSuperclass();
        }

        return false;
    }

    String toShortString() {
        return this.toString();
    }

    /** @deprecated */
    @Deprecated(
        since = "9"
    )
    public boolean isAccessible() {
        return this.override;
    }

    @CallerSensitive
    public final boolean canAccess(Object obj) {
        if (!Member.class.isInstance(this)) {
            return this.override;
        } else {
            Class<?> declaringClass = ((Member)this).getDeclaringClass();
            int modifiers = ((Member)this).getModifiers();
            if (Modifier.isStatic(modifiers) || !(this instanceof Method) && !(this instanceof Field)) {
                if (obj != null) {
                    throw new IllegalArgumentException("non-null object for " + this);
                }
            } else {
                if (obj == null) {
                    throw new IllegalArgumentException("null object for " + this);
                }

                if (!declaringClass.isAssignableFrom(obj.getClass())) {
                    throw new IllegalArgumentException("object is not an instance of " + declaringClass.getName());
                }
            }

            if (this.override) {
                return true;
            } else {
                Class<?> caller = Reflection.getCallerClass();
                Class targetClass;
                if (this instanceof Constructor) {
                    targetClass = declaringClass;
                } else {
                    targetClass = Modifier.isStatic(modifiers) ? null : obj.getClass();
                }

                return this.verifyAccess(caller, declaringClass, targetClass, modifiers);
            }
        }
    }

    /** @deprecated */
    @Deprecated(
        since = "17"
    )
    protected AccessibleObject() {
    }

    public <T extends Annotation> T getAnnotation(Class<T> annotationClass) {
        throw new UnsupportedOperationException("All subclasses should override this method");
    }

    public boolean isAnnotationPresent(Class<? extends Annotation> annotationClass) {
        return super.isAnnotationPresent(annotationClass);
    }

    public <T extends Annotation> T[] getAnnotationsByType(Class<T> annotationClass) {
        throw new UnsupportedOperationException("All subclasses should override this method");
    }

    public Annotation[] getAnnotations() {
        return this.getDeclaredAnnotations();
    }

    public <T extends Annotation> T getDeclaredAnnotation(Class<T> annotationClass) {
        return this.getAnnotation(annotationClass);
    }

    public <T extends Annotation> T[] getDeclaredAnnotationsByType(Class<T> annotationClass) {
        return this.getAnnotationsByType(annotationClass);
    }

    public Annotation[] getDeclaredAnnotations() {
        throw new UnsupportedOperationException("All subclasses should override this method");
    }

    private boolean isAccessChecked(Class<?> caller, Class<?> targetClass) {
        Object cache = this.accessCheckCache;
        return cache instanceof Cache ? ((Cache)cache).isCacheFor(caller, targetClass) : false;
    }

    private boolean isAccessChecked(Class<?> caller) {
        Object cache = this.accessCheckCache;
        if (cache instanceof WeakReference<Class<?>> ref) {
            return ref.refersTo(caller);
        } else {
            return false;
        }
    }

    final void checkAccess(Class<?> caller, Class<?> memberClass, Class<?> targetClass, int modifiers) throws IllegalAccessException {
        if (!this.verifyAccess(caller, memberClass, targetClass, modifiers)) {
            IllegalAccessException e = Reflection.newIllegalAccessException(caller, memberClass, targetClass, modifiers);
            if (printStackTraceWhenAccessFails()) {
                e.printStackTrace(System.err);
            }

            throw e;
        }
    }

    final boolean verifyAccess(Class<?> caller, Class<?> memberClass, Class<?> targetClass, int modifiers) {
        if (caller == memberClass) {
            return true;
        } else {
            if (targetClass != null && Modifier.isProtected(modifiers) && targetClass != memberClass) {
                if (this.isAccessChecked(caller, targetClass)) {
                    return true;
                }
            } else if (this.isAccessChecked(caller)) {
                return true;
            }

            return this.slowVerifyAccess(caller, memberClass, targetClass, modifiers);
        }
    }

    private boolean slowVerifyAccess(Class<?> caller, Class<?> memberClass, Class<?> targetClass, int modifiers) {
        if (caller == null) {
            return Reflection.verifyPublicMemberAccess(memberClass, modifiers);
        } else if (!Reflection.verifyMemberAccess(caller, memberClass, targetClass, modifiers)) {
            return false;
        } else {
            Object cache = targetClass != null && Modifier.isProtected(modifiers) && targetClass != memberClass ? java.lang.reflect.AccessibleObject.Cache.protectedMemberCallerCache(caller, targetClass) : new WeakReference(caller);
            this.accessCheckCache = cache;
            return true;
        }
    }

    private static boolean printStackTraceWhenAccessFails() {
        if (!printStackPropertiesSet && VM.initLevel() >= 1) {
            String s = GetPropertyAction.privilegedGetProperty("sun.reflect.debugModuleAccessChecks");
            if (s != null) {
                printStackWhenAccessFails = !s.equalsIgnoreCase("false");
            }

            printStackPropertiesSet = true;
        }

        return printStackWhenAccessFails;
    }

    AccessibleObject getRoot() {
        throw new InternalError();
    }

    static {
        SharedSecrets.setJavaLangReflectAccess(new ReflectAccess());
        reflectionFactory = (ReflectionFactory)AccessController.doPrivileged(new ReflectionFactory.GetReflectionFactoryAction());
    }
}

```
3. net.bytebuddy.mirror.AccessibleObject.1685112426107.class
```java
public class AccessibleObject implements AnnotatedElement {
    boolean override;
    static final ReflectionFactory reflectionFactory;
    volatile Object accessCheckCache;
    private static volatile boolean printStackWhenAccessFails;
    private static volatile boolean printStackPropertiesSet;
}
```

**Comment by nevermore18** [comment]
JDK 11:
> java.io.Serializable.1685173209578.class
> java.io.Serializable-original.1685173209578.class
> java.lang.ClassLoader$ByteBuddyAccessor$Pe5WJSqh.1685173207552.class
> java.lang.Object.1685173208133.class
> java.lang.Object-original.1685173208133.class
> java.util.EventObject.1685173209554.class
> java.util.EventObject-original.1685173209554.class
> org.junit.platform.engine.support.hierarchical.NodeExecutionAdvisor.1685173206417.class
> org.junit.platform.engine.support.hierarchical.NodeExecutionAdvisor-original.1685173206417.class
> org.junit.platform.launcher.core.LauncherConfigurationParameters.1685173206176.class
> org.junit.platform.launcher.core.LauncherConfigurationParameters-original.1685173206176.class
> org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$1eMjCmhE
> org.springframework.context.ApplicationEvent.1685173209480.class
> org.springframework.context.ApplicationEvent-original.1685173209480.class
> org.springframework.test.context.event.BeforeTestClassEvent.1685173209646.class
> org.springframework.test.context.event.BeforeTestClassEvent-original.1685173209646.class
> org.springframework.test.context.event.TestContextEvent.1685173209634.class
> org.springframework.test.context.event.TestContextEvent-original.1685173209634.class

JDK 17: 

> java.io.Serializable.1685112426403.class 
> java.io.Serializable-original.1685112426403.class java.lang.ClassLoader$ByteBuddyAccessor$CbnSUHmk.1685112426140.class
java.lang.Object.1685112426249.class
java.lang.Object-original.1685112426249.class
java.til.EventObject.1685112426404.class
java.til.EventObject-original.1685112426404.class
net.bytebuddy.mirror.AccessibleObject.1685112426107.class
net.bytebuddy.mirror.AccessibleObject-original.1685112426107.class org.junit.platform.launcher.core.LauncherConfigurationParameters.1685112425947.class org.junit.platform.launcher.core.LauncherConfigurationParameters-original.1685112425947.class org.mockito.internal.til.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$FOisKzZY.1685112426194.class org.springframework.context.Application Event.1685112426420.class
org.springframework.context.ApplicationEvent-original.1685112426420.class org.springframework.test.context.event.BeforeTestClassEvent.1685112426418.class org.springframework.test.context.event.BeforeTestClassEvent-original.1685112426418.class org.springframework.test.context.event.TestContextEvent.1685112426411.class org.springframework.test.context.event.TestContextEvent-original.1685112426411.class


We can see the diff is that 

> org.junit.platform.engine.support.hierarchical.NodeExecutionAdvisor.1685173206417.class
> org.junit.platform.engine.support.hierarchical.NodeExecutionAdvisor-original.1685173206417.class

> net.bytebuddy.mirror.AccessibleObject.1685112426107.class
> net.bytebuddy.mirror.AccessibleObject-original.1685112426107.class

**Comment by nevermore18** [comment]
https://github.com/jacoco/jacoco/issues/1470
Thanks, it's related to jacoco and I fix it!

**Comment by wakaleo** [comment]
> [jacoco/jacoco#1470](https://github.com/jacoco/jacoco/issues/1470)
> Thanks, it's related to jacoco and I fix it!

@nevermore18 Could you explain how you fixed this issue?

**Comment by nevermore18** [comment]
@wakaleo  See https://github.com/jacoco/jacoco/issues/1357
```gradle
tasks.withType(Test) {
    jacoco.includes = ['com.test.memusage.*']
```
