### ISSUE TITLE
Error when combining native-image with byte-buddy (About Nexus).

### ISSUE THREAD

**Issue by yswdqz** [raphw/byte-buddy#1460]
Hi, first of all, thank you for your outstanding work !
Recently, I tried to get the SkyWalking javaagent and native-image to work together, but I ran into a few problems:
![image](https://github.com/raphw/byte-buddy/assets/74546965/24e160ce-a67f-49d5-8698-139d0d615b8e)
`java.security.Permissions`  is set to run-time-initialize by graalvm, however `net.bytebuddy.dynamic.Nexus` must be at build-time-initialize. how do I fix it?
By the way, if I set `.disableClassFormatChanges()`, it will be fixed, But we also need ClassFormatChanges.

The text of the error is as follows: 
```
com.oracle.svm.core.util.UserError$UserException: No instances of java.io.FilePermission are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.io.FilePermission.
Detailed message:
Trace: Object was reached by
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@6ee25723: E:\gitee\yswdqz\testAgent\target\testAgent-1.0-SNAPSHOT-shaded.jar=("java.io.Fil...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@787dc920: [Ljava.util.concurrent.ConcurrentHashMap$Node;@787dc920
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@65b15609: {E:\gitee\yswdqz\testAgent\target\testAgent-1.0-SNAPSHOT-shaded.jar=("java.io.Fi...
  reading field java.io.FilePermissionCollection.perms of constant
    java.io.FilePermissionCollection@17fee13c: java.io.FilePermissionCollection@17fee13c (
 ("java.io.FilePermission" "E:\gitee...
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@7fcd3894: class java.io.FilePermission=java.io.FilePermissionCollection@17fee13c (
 ("java...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@83ba4d: [Ljava.util.concurrent.ConcurrentHashMap$Node;@83ba4d
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@2a7b18c2: {class java.io.FilePermission=java.io.FilePermissionCollection@17fee13c (
 ("jav...
  reading field java.security.Permissions.permsMap of constant
    java.security.Permissions@63317d4c: java.security.Permissions@63317d4c (
 ("java.io.FilePermission" "E:\gitee\yswdqz...
  reading field java.security.ProtectionDomain.permissions of constant
    java.security.ProtectionDomain@4fe01805: ProtectionDomain  (file:/E:/gitee/yswdqz/testAgent/target/testAgent-1.0-SNAPSHOT...
  reading field org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.protectionDomain of constant
    org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection@28aaf36a: org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInject...
  reading field org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.classInjector of constant
    org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer@70bb5d35: org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$...
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@72d77a82: Nexus{name='okhttp3.internal.ws.RealWebSocket$2', classLoaderHashCode=1280603381...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@3ad7073a: [Ljava.util.concurrent.ConcurrentHashMap$Node;@3ad7073a
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@1ada2a92: {Nexus{name='okhttp3.RealCall', classLoaderHashCode=1280603381, identification=-...
  scanning root java.util.concurrent.ConcurrentHashMap@1ada2a92: {Nexus{name='okhttp3.RealCall', classLoaderHashCode=1280603381, identification=-... embedded in
    org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.register(Nexus.java:168)

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by raphw** [comment]
I'm not aware that Skywalking could work with a Java agent. It would need the premain method to run, and there is no trigger for it.

**Comment by raphw** [comment]
You can. Set `-Dnet.bytebuddy.nexus.disabled=true`.
