### ISSUE TITLE
I want to ask a question, how to redefine class in jar file

### ISSUE THREAD

**Issue by SuperDubbo** [raphw/byte-buddy#1470]
I am now using byte-buddy to encounter a problem in the project, that is, when I run the program directly with idea, I can redefine the static method of the class normally, and achieve the desired effect. After I package the springboot project into a jar, execute the jar -jar demo. jar, but the following error stack will be prompted.
java.lang.IllegalStateException: Could not locate class file for com.hz.util.MyCollectionUtil
        at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:122) ~[byte-buddy-1.14.5.jar!/:na]
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4009) ~[byte-buddy-1.14.5.jar!/:na]
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224) ~[byte-buddy-1.14.5.jar!/:na]
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4050) ~[byte-buddy-1.14.5.jar!/:na]
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3734) ~[byte-buddy-1.14.5.jar!/:na]
        at com.hz.demo.aop.AppInterceptorConfig.modify(AppInterceptorConfig.java:37) [demo-web-0.0.1-SNAPSHOT.jar!/:na]
        at com.hz.demo.aop.AppInterceptorConfig.run(AppInterceptorConfig.java:24) [demo-web-0.0.1-SNAPSHOT.jar!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) [spring-boot-2.6.13.jar!/:2.6.13]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:766) [spring-boot-2.6.13.jar!/:2.6.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.6.13.jar!/:2.6.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.13.jar!/:2.6.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.13.jar!/:2.6.13]
        at com.hz.demo.DemoApplication.main(DemoApplication.java:10) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [demo-start-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [demo-start-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [demo-start-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [demo-start-0.0.1-SNAPSHOT.jar:na]

**Comment by SuperDubbo** [comment]
The demo project has three modules, which are as follows:
     <modules>
         <module>demo-start</module>
         <module>demo-web</module>
         <module>demo-service</module>
     </modules>
The MyCollectionUtil class is placed in demo-service.
com.hz.util.MyCollectionUtil.java 
`package com.hz.util;

import java.util.ArrayList;
import java.util.List;

/**
 * @author huangzhu
 * @since 2023/7/1 09:58
 */
public class MyCollectionUtil {


    public static List<String> getCollection(Integer x){
        List<String> result = new ArrayList<>();
        if(Integer.valueOf(1).equals(x)){
            result.add("A");
            result.add("B");
            result.add("C");
        }else{
            result.add("A");
            result.add("B");
            result.add("C");
        }
        return result;
    }
}
`

**Comment by SuperDubbo** [comment]
The complete demo project engineering code is attached, I hope to help you solve it, God bless you
[demo.zip](https://github.com/raphw/byte-buddy/files/11924548/demo.zip)

**Comment by raphw** [comment]
Spring Boot packages class files differently, under a subfolder within the jar. You would then need to implement a `ClassFileLocator` that reads that location instead of the regular location, I would assume. This locator needs to be provided to `Advice` as a second argument.

**Comment by SuperDubbo** [comment]
> Spring Boot packages class files differently, under a subfolder within the jar. You would then need to implement a `ClassFileLocator` that reads that location instead of the regular location, I would assume. This locator needs to be provided to `Advice` as a second argument.

I have tried many time. But fail.Can you guide me and give some examples

**Comment by raphw** [comment]
You probably need to blend locators. You can try to combine them by using a `ClassFileLocator.Compound`. To this loader, you'd need to provide the current locator, plus one resolving the class loader, using `ClassFileLocator.ForClassLoader`.

**Comment by SuperDubbo** [comment]
> You probably need to blend locators. You can try to combine them by using a `ClassFileLocator.Compound`. To this loader, you'd need to provide the current locator, plus one resolving the class loader, using `ClassFileLocator.ForClassLoader`.

I followed this idea at the beginning, but I need to recurse the contents of the jar continuously. I plan to use the net.bytebuddy.dynamic.ClassFileLocator.ForJarFile#of method you wrote to practice after traversing the jar, but the sub-jar inside the jar does not It supports direct file access, so it is troublesome, and I don’t know how to change it

’‘’
package com.hz.demo.aop;

import lombok.extern.slf4j.Slf4j;
import net.bytebuddy.build.HashCodeAndEqualsPlugin;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.utility.StreamDrainer;
import org.springframework.boot.SpringApplication;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.core.io.support.ResourcePatternResolver;
import sun.net.www.protocol.jar.URLJarFile;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarFile;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;

/**
 * @author huangzhu
 * @since 2023/7/3 09:23
 */
@HashCodeAndEqualsPlugin.Enhance
@Slf4j
public class SpringBootClassFileLocator implements ClassFileLocator {

    @Override
    public Resolution locate(String name) throws IOException {
        return null;
    }

    @Override
    public void close() throws IOException {

    }

    public static ClassFileLocator ofDefaultPath() throws IOException {
        String basePath= SpringBootClassFileLocator.class.getResource("/").getPath();
        log.info("basePath:{}",basePath);
        List<ClassFileLocator> classFileLocators = new ArrayList<ClassFileLocator>();
        if(basePath!=null &&basePath.contains("BOOT-INF")){

            String matchPattern = ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX+"/BOOT-INF/*/*.*";
            log.info("matchPattern:{}",matchPattern);
            // 2. 返回指定路径下所有的资源对象（子目录下的资源对象）
            ResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = resourcePatternResolver.getResources(matchPattern);
            for (Resource resource : resources) {
                // 3. 获取文件名称
                String fileFlag = resource.getFilename();
                ClassFileLocator classFileLocator=transform(resource);
                if(classFileLocator!=null){
                    classFileLocators.add(classFileLocator);
                }
                log.info("fileFlag:{}",fileFlag);
            }
        }else{
            classFileLocators.add(ClassFileLocator.ForClassLoader.ofPlatformLoader());
        }
        return new Compound(classFileLocators);
    }

    private static ClassFileLocator transform(Resource resource) throws IOException {
        InputStream inputStream =null;
        try{
            inputStream = resource.getInputStream();
            log.info("transform:{}",resource.getFilename());
            if(inputStream!=null){
                if(resource.getFilename().endsWith("jar")){
                    inputStream = resource.getInputStream();
                    File tempFile = File.createTempFile("temp/"+resource.getFilename(), ".jar");
                    Files.copy(inputStream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    return ClassFileLocator.ForJarFile.of(tempFile);
                }else if(resource.getFilename().endsWith("class")){
                    return null;
                }
            }
        }finally {
            if(inputStream != null){
                inputStream.close();
            }
        }
        return null;
    }
}


‘’‘

**Comment by SuperDubbo** [comment]
’‘’
package com.hz.demo.aop;

import lombok.extern.slf4j.Slf4j;
import net.bytebuddy.build.HashCodeAndEqualsPlugin;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.utility.StreamDrainer;
import org.springframework.boot.SpringApplication;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.core.io.support.ResourcePatternResolver;
import sun.net.www.protocol.jar.URLJarFile;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarFile;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;

/**
 * @author huangzhu
 * @since 2023/7/3 09:23
 */
@HashCodeAndEqualsPlugin.Enhance
@Slf4j
public class SpringBootClassFileLocator implements ClassFileLocator {

    @Override
    public Resolution locate(String name) throws IOException {
        return null;
    }

    @Override
    public void close() throws IOException {

    }

    public static ClassFileLocator ofDefaultPath() throws IOException {
        String basePath= SpringBootClassFileLocator.class.getResource("/").getPath();
        log.info("basePath:{}",basePath);
        List<ClassFileLocator> classFileLocators = new ArrayList<ClassFileLocator>();
        if(basePath!=null &&basePath.contains("BOOT-INF")){

            String matchPattern = ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX+"/BOOT-INF/*/*.*";
            log.info("matchPattern:{}",matchPattern);
            // 2. 返回指定路径下所有的资源对象（子目录下的资源对象）
            ResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = resourcePatternResolver.getResources(matchPattern);
            for (Resource resource : resources) {
                // 3. 获取文件名称
                String fileFlag = resource.getFilename();
                ClassFileLocator classFileLocator=transform(resource);
                if(classFileLocator!=null){
                    classFileLocators.add(classFileLocator);
                }
                log.info("fileFlag:{}",fileFlag);
            }
        }else{
            classFileLocators.add(ClassFileLocator.ForClassLoader.ofPlatformLoader());
        }
        return new Compound(classFileLocators);
    }

    private static ClassFileLocator transform(Resource resource) throws IOException {
        InputStream inputStream =null;
        try{
            inputStream = resource.getInputStream();
            log.info("transform:{}",resource.getFilename());
            if(inputStream!=null){
                if(resource.getFilename().endsWith("jar")){
                    inputStream = resource.getInputStream();
                    File tempFile = File.createTempFile("temp/"+resource.getFilename(), ".jar");
                    Files.copy(inputStream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    return ClassFileLocator.ForJarFile.of(tempFile);
                }else if(resource.getFilename().endsWith("class")){
                    return null;
                }
            }
        }finally {
            if(inputStream != null){
                inputStream.close();
            }
        }
        return null;
    }
}


’‘’

**Comment by dogourd** [comment]
Since you can already get `Class<MyCollectionUtil>` through `MyCollectionUtil.class`, why not try `ClassFileLocator.ForClassLoader.of(MyCollectionUtil.class.getClassLoader())` directly?

**Comment by SuperDubbo** [comment]
> 

I tried it like this, it still gives an error

**Comment by SuperDubbo** [comment]
> Since you can already get `Class<MyCollectionUtil>` through `MyCollectionUtil.class`, why not try `ClassFileLocator.ForClassLoader.of(MyCollectionUtil.class.getClassLoader())` directly?

I tried it like this, it still gives an error

**Comment by raphw** [comment]
I wonder how the app can function to begin with if the class loader cannot resolve class files. I assume that your advice and the instrumented class are on different class loaders? In this case, you should be able to use a compound with the instrumented class's class loader and the advice's class loader.

**Comment by dogourd** [comment]
Did you use Maven to repackage it after making the changes? I received the demo2 project, made the following modifications, repackaged it, and it runs fine.
```java
private void modify(){
        try{
            log.info("执行AppInterceptorConfig start");
            ByteBuddyAgent.install();
            new ByteBuddy()
                    .redefine(MyCollectionUtil.class,
//                            change here
//                            ClassFileLocator.ForJarFile
//                                    .ofClassPath(MyCollectionUtil.class.getProtectionDomain().getCodeSource().getLocation().getFile()))
                              ClassFileLocator.ForClassLoader.of(MyCollectionUtil.class.getClassLoader()))
                    .visit(Advice.to(MyCollectionUtilStaticMethodInterceptor.class)
                            .on(ElementMatchers.named("getCollection")))
                    .make()
                    .load(Thread.currentThread().getContextClassLoader(), ClassReloadingStrategy.fromInstalledAgent())
                    .getLoaded();
            log.info("执行AppInterceptorConfig end");
        }catch (Exception e){
            log.error("AppInterceptorConfig", e);
        }
    }
```

**Comment by SuperDubbo** [comment]
> 

Finally ok, the code is as follows, is it possible to officially add SpringBootClassFileLocator as the official jar method that supports springboot?

’‘’
@HashCodeAndEqualsPlugin.Enhance
@Slf4j
public class SpringBootClassFileLocator implements ClassFileLocator {

    @Override
    public Resolution locate(String name) throws IOException {
        return null;
    }

    @Override
    public void close() throws IOException {

    }

    public static ClassFileLocator ofDefaultPath() throws IOException {
        String basePath= SpringBootClassFileLocator.class.getResource("/").getPath();
        List<ClassFileLocator> classFileLocators = new ArrayList<ClassFileLocator>();
        classFileLocators.add(ClassFileLocator.ForClassLoader.ofSystemLoader());
        if(basePath!=null &&basePath.contains("BOOT-INF")){
            String matchPattern = ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX+"/BOOT-INF/**/*.jar";
            ResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = resourcePatternResolver.getResources(matchPattern);
            for (Resource resource : resources) {
                ClassFileLocator classFileLocator=transform(resource);
                if(classFileLocator!=null){
                    classFileLocators.add(classFileLocator);
                }

            }
        }else{
            classFileLocators.add(ClassFileLocator.ForClassLoader.ofPlatformLoader());
        }
        return new Compound(classFileLocators);
    }

    private static ClassFileLocator transform(Resource resource) throws IOException {
        try (InputStream inputStream = resource.getInputStream()) {
            if (inputStream != null) {
                if (resource.getFilename().endsWith("jar")) {
                    File tempFile = File.createTempFile("temp/jar/" + resource.getFilename(), ".jar");
                    Files.copy(inputStream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    return ForJarFile.of(tempFile);
                }
            }
        }
        return null;
    }
}
‘’‘

**Comment by SuperDubbo** [comment]
> I wonder how the app can function to begin with if the class loader cannot resolve class files. I assume that your advice and the instrumented class are on different class loaders? In this case, you should be able to use a compound with the instrumented class's class loader and the advice's class loader.

Finally ok, the code is as follows, is it possible to officially add SpringBootClassFileLocator as the official jar method that supports springboot?

**Comment by SuperDubbo** [comment]
```
@HashCodeAndEqualsPlugin.Enhance
@Slf4j
public class SpringBootClassFileLocator implements ClassFileLocator {

    @Override
    public Resolution locate(String name) throws IOException {
        return null;
    }

    @Override
    public void close() throws IOException {

    }

    public static ClassFileLocator ofDefaultPath() throws IOException {
        String basePath= SpringBootClassFileLocator.class.getResource("/").getPath();
        List<ClassFileLocator> classFileLocators = new ArrayList<ClassFileLocator>();
        classFileLocators.add(ClassFileLocator.ForClassLoader.ofSystemLoader());
        if(basePath!=null &&basePath.contains("BOOT-INF")){
            String matchPattern = ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX+"/BOOT-INF/**/*.jar";
            ResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = resourcePatternResolver.getResources(matchPattern);
            for (Resource resource : resources) {
                ClassFileLocator classFileLocator=transform(resource);
                if(classFileLocator!=null){
                    classFileLocators.add(classFileLocator);
                }

            }
        }else{
            classFileLocators.add(ClassFileLocator.ForClassLoader.ofPlatformLoader());
        }
        return new Compound(classFileLocators);
    }

    private static ClassFileLocator transform(Resource resource) throws IOException {
        try (InputStream inputStream = resource.getInputStream()) {
            if (inputStream != null) {
                if (resource.getFilename().endsWith("jar")) {
                    File tempFile = File.createTempFile("temp/jar/" + resource.getFilename(), ".jar");
                    Files.copy(inputStream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    return ForJarFile.of(tempFile);
                }
            }
        }
        return null;
    }
}
```

**Comment by SuperDubbo** [comment]
> 

It's very strange, it was not possible before, but it is also possible according to what you said, thank you

**Comment by SuperDubbo** [comment]
> Did you use Maven to repackage it after making the changes? I received the demo2 project, made the following modifications, repackaged it, and it runs fine.
> 
> ```java
> private void modify(){
>         try{
>             log.info("执行AppInterceptorConfig start");
>             ByteBuddyAgent.install();
>             new ByteBuddy()
>                     .redefine(MyCollectionUtil.class,
> //                            change here
> //                            ClassFileLocator.ForJarFile
> //                                    .ofClassPath(MyCollectionUtil.class.getProtectionDomain().getCodeSource().getLocation().getFile()))
>                               ClassFileLocator.ForClassLoader.of(MyCollectionUtil.class.getClassLoader()))
>                     .visit(Advice.to(MyCollectionUtilStaticMethodInterceptor.class)
>                             .on(ElementMatchers.named("getCollection")))
>                     .make()
>                     .load(Thread.currentThread().getContextClassLoader(), ClassReloadingStrategy.fromInstalledAgent())
>                     .getLoaded();
>             log.info("执行AppInterceptorConfig end");
>         }catch (Exception e){
>             log.error("AppInterceptorConfig", e);
>         }
>     }
> ```

It's very strange, it was not possible before, but it is also possible according to what you said, thank you

**Comment by tonyfalabella** [comment]
@SuperDubbo and @dogourd is it possible to post a copy of your full jar file with all the mods including how you repacked the jar using Maven?
