### ISSUE TITLE
IllegalStateException at AndroidClassLoadingStrategy with the latest Android SDK 34

### ISSUE THREAD

**Issue by viterigor** [raphw/byte-buddy#1487]
Hey all,

I have the following errors when trying to run tests in android project with the latest Android 14 Beta 5.1 **(compile and target SDK 34 version)**. With Android 13 **(compile and target SDK 33 version)** everything works fine. 

Google introduced Dynamic Code Loading in Android 14, I assume it may be related to the DCL and ByteBuddy. I don't use dynamically-loaded files in my project. 

Could you please help to identify the root cause of this issue?

```
Underlying exception : java.lang.IllegalStateException: Cannot invoke BaseDexClassLoader#addDexPath(String, boolean)

Caused by: java.lang.IllegalStateException: Cannot invoke BaseDexClassLoader#addDexPath(String, boolean)
at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting$Dispatcher$ForAndroidPVm.loadDex(AndroidClassLoadingStrategy.java:779) 
at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting.doLoad(AndroidClassLoadingStrategy.java:648)
2023-07-19 15:52:22.141  6552-6614  TestRunner             com.test.example.android  E  	
at net.bytebuddy.android.AndroidClassLoadingStrategy.load(AndroidClassLoadingStrategy.java:145) 
at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting.load(AndroidClassLoadingStrategy.java:641) 
at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100) 
at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6154)
at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:268) 
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0$org-mockito-internal-creation-bytebuddy-TypeCachingBytecodeGenerator(TypeCachingBytecodeGenerator.java:47)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$$ExternalSyntheticLambda0.call(Unknown Source:4) 
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153) 
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175) 
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377) 
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40) 
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77) 	
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43) 
at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.createMock(AndroidByteBuddyMockMaker.java:39)                                                                                        	
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)                                                                           	
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)                                                                           	
at org.mockito.Mockito.mock(Mockito.java:1964)
at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:66) 
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:27) 
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:24) 
at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:45)
at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:73) 
at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:74) 
at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:48) 
at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:82) 
at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:100)
                                                                                                    
Caused by: java.lang.SecurityException: Writable dex file '/data/user/0/com.test.example.android/cache/345345dsf.jar' is not allowed.                                                                                             	
at dalvik.system.DexFile.openDexFileNative(Native Method)                                                                             	
at dalvik.system.DexFile.openDexFile(DexFile.java:406)                                                                                        	
at dalvik.system.DexFile.<init>(DexFile.java:128)                                                                                          	
at dalvik.system.DexFile.<init>(DexFile.java:101)                                                                                         	
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)                                                                               	
at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
at dalvik.system.DexPathList.addDexPath(DexPathList.java:220)
at dalvik.system.BaseDexClassLoader.addDexPath(BaseDexClassLoader.java:287) 
at java.lang.reflect.Method.invoke(Native Method)                                                             
at  net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting$Dispatcher$ForAndroidPVm.loadDex(AndroidClassLoadingStrategy.java:770)
```

**Comment by raphw** [comment]
Can you build and try master? I made the file read-only now.

**Comment by viterigor** [comment]
Hi @raphw,

I am using the mockito library in my tests, which uses bytebuddy. I cloned the bytebuddy repo, generated a JAR, added it as a library to my Android project., excluded bytebuddy from mockito. However, my project doesn't compile, this process seems a little bit complicated to me. Maybe do you have any other ideas how to check? 

Thank you.

**Comment by viterigor** [comment]
I will try and get back. Thanks!

**Comment by raphw** [comment]
Can you give it another go? Seems like Java's "read only" API does not set posix file permissions correctly.

**Comment by viterigor** [comment]
Thank you for the provided solution. It isn't working and the logs look really strange. 

```
Underlying exception : java.lang.IllegalArgumentException: Could not create type
... 35 more

Caused by: java.lang.IllegalArgumentException: Could not create type
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:155)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.createMock(AndroidByteBuddyMockMaker.java:39)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
at org.mockito.Mockito.mock(Mockito.java:1964)
at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:66)
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:27)
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:24)
at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:45)
at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:73)
at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:74)
at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:48)
at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:82)
at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:100)
... 35 more

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/dx/dex/DexOptions;
at net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeDefault(AndroidClassLoadingStrategy.java:375)
at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting.<init>(AndroidClassLoadingStrategy.java:737)
at org.mockito.android.internal.creation.AndroidLoadingStrategy.resolveStrategy(AndroidLoadingStrategy.java:39)
at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:270)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0$org-mockito-internal-creation-bytebuddy-TypeCachingBytecodeGenerator(TypeCachingBytecodeGenerator.java:47)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$$ExternalSyntheticLambda0.call(Unknown Source:4)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
... 54 more

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.dx.dex.DexOptions" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~32423fdsfdfsfsdf==/com.xxxxx-42344dsfsf==/xxxx.apk", zip file "/data/app/~~345345dffsdf==/com.xxxxx-443232fsfddsf==/xxxx.apk"],nativeLibraryDirectories=[/data/app/~~2345234dvsdfsd==/com.xxxxx-34343sffsdfsdfsdf==/lib/arm64, /data/app/~~32423dsfggdfg==/com.xxxxx-234234sdgsfsf==/lib/arm64, /data/app/~~5xrFWclAXh4bhnoKWtAF5w==/com.xxxxx-324243dfgdfg==/base.apk!/lib/arm64-v8a, /data/app/~~23432dsgfsdfsdf==/com.xxxxx-34342dfsfsf==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]

at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by raphw** [comment]
That is strange. The class should be part of the dependency. Is it included at runtime? Probably, the class loader cannot see it, but I would not know why. Possibly, this is a bug in an early access API?

**Comment by viterigor** [comment]
Sorry for the late reply.

> That is strange. The class should be part of the dependency. Is it included at runtime? Probably, the class loader cannot see it, but I would not know why.

I am not sure whether com.android.dx.dex.DexOptions is included at runtime or not. android.test.* libs are added as dependencies in my android project.

> Possibly, this is a bug in an early access API?

I assume it isn't a bug in an early access API, it is platform stability which means that the developer APIs are final.  

According to Google's documentation all dynamically-loaded files must be marked as read-only. However, I believe Google may not provide comprehensive details on implementation:

```
File jar = new File("DYNAMICALLY_LOADED_FILE.jar");
try (FileOutputStream os = new FileOutputStream(jar)) {
    // Set the file to read-only first to prevent race conditions
    jar.setReadOnly();
    // Then write the actual file content
} catch (IOException e) { ... }
PathClassLoader cl = new PathClassLoader(jar, parentClassLoader);
```

**Comment by raphw** [comment]
I changed the file to be read-only, but the latest error message indicates another problem?

**Comment by viterigor** [comment]
It is working. Thank you for your assistance!
