### ISSUE TITLE
Cannot resolve type description for

### ISSUE THREAD

**Issue by SuperDubbo** [raphw/byte-buddy#1497]
@raphw Hello, when I use byte-buddy to run this segment program, this exception error message is reported. May I ask where it is used incorrectly? It is ok for me to run the Main method directly in the idea. But when the program is typed into a running jar file and java -jar xxx.jar is executed, this exception message will be reported.
Please tell me how to handle this situation.
```
        ByteBuddyAgent.install();
        TypePool typePool = TypePool.Default.ofSystemLoader();
        ByteBuddy byteBuddy=new ByteBuddy();
        byteBuddy
                .redefine(typePool.describe("cn.xx.abc.domain.od.itg.cache.OdRouteE").resolve(),
                        ClassFileLocator.ForClassLoader.ofSystemLoader())
                .visit(Advice.to(OdRouteEMethodInterceptor.class).on(ElementMatchers.named("checkUpDownTime"))).make()
                .load(Thread.currentThread().getContextClassLoader(), ClassLoadingStrategy.Default.INJECTION).getLoaded();
```
OdRouteEMethodInterceptor.java
```
public class OdRouteEMethodInterceptor {
    @Advice.OnMethodExit
    public static void enter(@Advice.This Object currentInstance, @Advice.Return(readOnly = false) boolean flag) {
        OdRouteE odRouteE = ((OdRouteE)currentInstance);
        long curTime = NowTimeMockComponent.getNowSeconds() * 1000;
        if (curTime >= odRouteE.getUpTime().getTime() && curTime < odRouteE.getDownTime().getTime()) {
            flag = true;
        }
        flag = false;
    }
}

```
```
java.lang.IllegalStateException: Cannot resolve type description for cn.xxx.abc.domain.od.itg.cache.OdRouteE
        at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
        at cn.xxx.abc.simulate.aop.mock.buddy.ByteBuddyAspect.initialize(ByteBuddyAspect.java:35)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at cn.xxx.abc.web.PricingApplication.main(PricingApplication.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
```

**Comment by SuperDubbo** [comment]
If I change the code to the following, another error will be reported.

```
        ByteBuddyAgent.install();
        TypePool typePool = TypePool.Default.ofSystemLoader();
        ByteBuddy byteBuddy=new ByteBuddy();
        byteBuddy
                .redefine(OdRouteE.class,
                        ClassFileLocator.ForClassLoader.of(OdRouteE.class.getClassLoader()))
                .visit(Advice.to(OdRouteEMethodInterceptor.class).on(ElementMatchers.named("checkUpDownTime"))).make()
                .load(Thread.currentThread().getContextClassLoader(), ClassLoadingStrategy.Default.INJECTION).getLoaded();
```
```
Cannot inject already loaded type: class cn.xxx.abc.domain.od.itg.cache.OdRouteE
```

**Comment by SuperDubbo** [comment]
I have solved this problem, thanks! Please help close this issue @raphw
