### ISSUE TITLE
how  use  advice  at  system class

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1519]
Hi,author, I  want to use advice only print  system class  like  java.lang.ProcessBuilder 

this is  my code
```

AgentBuilder.Transformer processBuilderTransformer =
 (builder, typeDescription, classLoader, javaModule, protectionDomain) -> builder
                .constructor(ElementMatchers.any()) // match  all  construtors
      
                .intercept(Advice.to(ProcessBuilderAdvice.class));

 new AgentBuilder.Default()
               
                .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
 .type(ElementMatchers.nameMatches("java.lang.ProcessBuilder"))
                .transform(processBuilderTransformer);

```
this  way  is not work ，how  can  I  solve  it

**Comment by raphw** [comment]
By default, Byte Buddy ignores the boot class path. If you want to instrument boot classes, you need to define a custom ignore matcher via ignore.

**Comment by cor0ps** [comment]
thanks   I user   new AgentBuilder.Default().ignore(none())   solve this  problems.

**Comment by cor0ps** [comment]
now  i  want   advice  java.lang.ProcessBuilder init method
```
  AgentBuilder.Transformer processBuilderTransformer = (builder, typeDescription, classLoader, javaModule, protectionDomain) -> builder
                //.method(ElementMatchers.nameContainsIgnoreCase("start"))
                .constructor(ElementMatchers.any())
                //委托
                .intercept(Advice.to(ProcessBuilderAdvice.class));


public class ProcessBuilderAdvice {

    @Advice.OnMethodEnter
    public static void execEnter(@Advice.Origin Method method, @Advice.AllArguments Object[] args) {
    ///only  system.out.print args
}


```


but  has error!!!


```
java.lang.IllegalStateException: Cannot call super (or default) method for public java.lang.ProcessBuilder(java.util.List)
        at net.bytebuddy.implementation.SuperMethodCall$Appender.apply(SuperMethodCall.java:133)
        at net.bytebuddy.asm.Advice$Appender$EmulatingMethodVisitor.resolve(Advice.java:12130)
        at net.bytebuddy.asm.Advice$Appender.apply(Advice.java:12083)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:730)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:715)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:5502)

```

**Comment by raphw** [comment]
You need to apply it via the visit method, not as an interceptor.
