### ISSUE TITLE
Use advice api with spring boot throw IllegalAccessError 

### ISSUE THREAD

**Issue by XhstormR** [raphw/byte-buddy#1533]
The byte buddy version I am using is 1.14.8. I tried to use `AgentBuilder.Transformer.ForAdvice` to enhance the Tomcat class in Spring Boot. But I found that when I run spring boot, if I directly call the agentmain method for transformer class, it shows transformer successfully, but when accessing the http endpoint of Spring boot, an IllegalAccessError will be reported. However, if I start spring boot, first access the http endpoint, and then run the agentmain method, it will work perfectly fine.

I found many related issues on the Internet, such as https://github.com/raphw/byte-buddy/issues/1010. I know it is because SpringBoot defines a LaunchedURLClassLoader. The class injected by our agentmain is in the App Bootstrap ClassLoader, they belong to different ClassLoader; and spring boot jar and my agent jar has both included and used same version kotlin standard library dependency, so the jvm will throw LinkageError and IllegalAccessError.

I saw some possible solutions like:
1. let LaunchedURLClassLoader also load these classes,
2. maybe use `ClassInjector.UsingLookup` or `ClassLoadingStrategy.UsingLookup`.
3. minimal the core classes and load into the bootstrap classloader. for other classes, loaded into another normal standalone classloader which loaded other agent classes.

But I don't know how to achieve these goals using byte buddy's API to work properly, Can you help me out?

AgentMain.kt code:
```kotlin
fun agentmain(args: String, inst: Instrumentation) {
    val clazz = "org.apache.catalina.core.clazz"
    val method = "method"

    val advice = Advice
        .withCustomMapping()
        .bind(clazz<Value>(), args)

    AgentBuilder.Default()
        .with(AgentBuilder.Listener.StreamWriting.toSystemOut().withErrorsOnly())
        .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
        .type(ElementMatchers.named(clazz))
        .transform(AgentBuilder.Transformer.ForAdvice(advice).advice(ElementMatchers.named(method), TracingAdvice::class.name))
        .installOn(inst)
}

```

Spring Boot log:
```

2023-09-23 18:26:20.208  INFO 8388 --- [nio-8080-exec-4] i.g.x.m.w.config.handler.RequestLogger   : [GET /api/event, client=127.0.0.1]
2023-09-23 18:26:20.214 ERROR 8388 --- [nio-8080-exec-4] i.g.x.m.w.config.advice.ExceptionAdvice  : ---Exception Handler--- HOST: 127.0.0.1, USER: null, URL: GET /api/event, ERROR: Handler dispatch failed; nested exception is java.lang.IllegalAccessError: failed to access class kotlin.sequences.SequencesKt__SequencesKt$generateSequence$2 from class kotlin.sequences.SequencesKt__SequencesKt (kotlin.sequences.SequencesKt__SequencesKt$generateSequence$2 is in unnamed module of loader 'app'; kotlin.sequences.SequencesKt__SequencesKt is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62)
2023-09-23 18:26:20.236  WARN 8388 --- [nio-8080-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler io.github.xhstormr.masker.web.config.advice.ExceptionAdvice#handleException(Exception)

java.lang.IllegalAccessError: failed to access class kotlin.sequences.SequencesKt__SequencesKt$generateSequence$2 from class kotlin.sequences.SequencesKt__SequencesKt (kotlin.sequences.SequencesKt__SequencesKt$generateSequence$2 is in unnamed module of loader 'app'; kotlin.sequences.SequencesKt__SequencesKt is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62)
        at kotlin.sequences.SequencesKt__SequencesKt.generateSequence(Sequences.kt:662)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.typeConstructor$notFoundClass(TypeDeserializer.kt:151)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.typeConstructor(TypeDeserializer.kt:175)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:91)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:137)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.type(TypeDeserializer.kt:68)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.valueParameters(MemberDeserializer.kt:340)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.loadFunction(MemberDeserializer.kt:217)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.computeFunctions(DeserializedMemberScope.kt:276)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.access$computeFunctions(DeserializedMemberScope.kt:228)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.getContributedFunctions(DeserializedMemberScope.kt:329)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.addFunctionsAndPropertiesTo(DeserializedMemberScope.kt:360)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:115)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:277)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:276)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:287)
        at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:50)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:58)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:162)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:162)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)

2023-09-23 23:39:38.218 ERROR 1899 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.LinkageError: loader constraint violation: when resolving method 'kotlin.sequences.Sequence kotlin.sequences.SequencesKt.generateSequence(kotlin.jvm.functions.Function0)' the class loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62 of the current class, kotlin/reflect/jvm/internal/impl/serialization/deserialization/descriptors/DeserializedMemberScope$OptimizedImplementation, and the class loader 'app' for the method's defining class, kotlin/sequences/SequencesKt__SequencesKt, have different Class objects for the type kotlin/jvm/functions/Function0 used in the signature (kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62, parent loader 'app'; kotlin.sequences.SequencesKt__SequencesKt is in unnamed module of loader 'app')] with root cause

java.lang.LinkageError: loader constraint violation: when resolving method 'kotlin.sequences.Sequence kotlin.sequences.SequencesKt.generateSequence(kotlin.jvm.functions.Function0)' the class loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62 of the current class, kotlin/reflect/jvm/internal/impl/serialization/deserialization/descriptors/DeserializedMemberScope$OptimizedImplementation, and the class loader 'app' for the method's defining class, kotlin/sequences/SequencesKt__SequencesKt, have different Class objects for the type kotlin/jvm/functions/Function0 used in the signature (kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5d099f62, parent loader 'app'; kotlin.sequences.SequencesKt__SequencesKt is in unnamed module of loader 'app')
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.computeFunctions(DeserializedMemberScope.kt:584) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.access$computeFunctions(DeserializedMemberScope.kt:228) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$functions$1.invoke(DeserializedMemberScope.kt:251) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.getContributedFunctions(DeserializedMemberScope.kt:329) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.addFunctionsAndPropertiesTo(DeserializedMemberScope.kt:360) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:115) ~[kotlin-reflect-1.9.10.jar!/:1.9.10-release-459]
```

**Comment by raphw** [comment]
Can you add your advice class?

**Comment by XhstormR** [comment]
@raphw 
below is Tracing.kt:
```kotlin
object Tracing {

    @JvmStatic
    @Advice.OnMethodEnter(skipOn = Advice.OnNonDefaultValue::class)
    fun trace(@Advice.AllArguments args: Array<Any>, @Value pass: String): Boolean {
        val request = args[0] as HttpServletRequest
        val response = args[1] as HttpServletResponse

        val pass = request.getHeader(pass)
        val success = pass != null

        if (success) {
           //....
        }
        return success
    }
}

annotation class Value {}
```

**Comment by raphw** [comment]
Advice should be written in Java as not all surrounding classes can be resolved when requirng the Kotlin standard library.

**Comment by XhstormR** [comment]
Thanks for your help. In the end, I solved this problem by using URLClassloader alone to load the core agent jar to avoid polluting the original application's Classloader.

Reference:
1. https://github.com/alibaba/arthas/blob/master/arthas-agent-attach/src/main/java/com/taobao/arthas/agent/attach/AttachArthasClassloader.java
2. https://github.com/gaoxingliang/tracing-research/blob/main/bootstrap/src/main/java/com/zoomphant/agent/trace/boost/StandaloneAgentClassloader.java
