### ISSUE TITLE
Question：Error when use maven plugin

### ISSUE THREAD

**Issue by twogoods** [raphw/byte-buddy#1622]
I want to modify class when compile
```
        <plugins>
            <plugin>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy-maven-plugin</artifactId>
                <version>1.14.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <transformations>
                        <transformation>
                            <groupId>xxx</groupId>
                            <artifactId>xxx</artifactId>
                            <version>${revision}</version>
                            <plugin>org.xxx.TestPlugin</plugin>
                        </transformation>
                    </transformations>
                </configuration>
            </plugin>
```
exception is

```
Caused by: java.lang.AbstractMethodError: org.xxx.Generator.wrap(Lnet/bytebuddy/description/type/TypeDescription;Lnet/bytebuddy/jar/asm/ClassVisitor;Lnet/bytebuddy/implementation/Implementation$Context;Lnet/bytebuddy/pool/TypePool;Lnet/bytebuddy/description/field/FieldList;Lnet/bytebuddy/description/method/MethodList;II)Lnet/bytebuddy/jar/asm/ClassVisitor;
	at net.bytebuddy.asm.AsmVisitorWrapper$Compound.wrap(AsmVisitorWrapper.java:746)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.visit(TypeWriter.java:5004)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:569)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4014)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4057)
	at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4893)
	at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4850)
	at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.accept(Plugin.java:3902)
	at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4697)
	at net.bytebuddy.build.maven.ByteBuddyMojo.apply(ByteBuddyMojo.java:468)
	... 23 more
```

code:
```
public class TestPlugin implements Plugin {
    @Override
    public DynamicType.Builder<?> apply(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassFileLocator classFileLocator) {
            Generator generator = new Generator();
            return builder.visit(generator);
    }
}

public class Generator implements AsmVisitorWrapper {

    @Override
    public ClassVisitor wrap(
            TypeDescription instrumentedType,
            ClassVisitor classVisitor,
            Implementation.Context implementationContext,
            TypePool typePool,
            FieldList<FieldDescription.InDefinedShape> fields,
            MethodList<?> methods,
            int writerFlags,
            int readerFlags) {
        return new GenerateMethods(classVisitor);
    }
```

class `AsmVisitorWrapper` load by same classloader, why get AbstractMethodError ?

**Comment by raphw** [comment]
That is not clear to me from the example you provide.

Could you try to debug this by `mvnDebug`? You could intercept the method within the stack and see what the problem is.

**Comment by twogoods** [comment]
@raphw    here is a sample [bytebuddy-maven-plugin-test](https://github.com/twogoods/bytebuddy-maven-plugin-test/tree/main).  
api contains bytebuddy build plugin, dependency has buddy and asm; demo build with byte-buddy-maven-plugin

`mvn -X  clean package` will see error

**Comment by raphw** [comment]
This is merely a consequence of an underlying: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor. Maven swallows this cause.

Do not use *byte-buddy-dep* but *byte-buddy*. Then use `ClassVisitorFactory` to bridge between different shading concepts of ASM.
