### ISSUE TITLE
(Question)change org.h2.Driver failure, when use byte-buddy in main class, Why?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#165]
I use following byte-buddy api  to change 'org.h2.Driver' source code.
```java
newClassBuilder = newClassBuilder
				.defineField(contextAttrName,
						EnhancedClassInstanceContext.class, ACC_PRIVATE)
				.constructor(any())
				.intercept(
						SuperMethodCall.INSTANCE.andThen(MethodDelegation.to(
								new ClassConstructorInterceptor(interceptor))
								.appendParameterBinder(
										FieldProxy.Binder.install(
												FieldGetter.class,
												FieldSetter.class))));
```

This Code works in javaagent's premain. But when I use this code in main class,  it is failure.
I run code like following 
```java
newClassBuilder.make().load(ClassLoader.getSystemClassLoader(),ClassLoadingStrategy.Default.INJECTION).getLoaded();
```
it trigger expcetion:
```shell
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:105)
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:75)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4523)
	at com.ai.cloud.skywalking.plugin.TracingBootstrap.main(TracingBootstrap.java:52)
	at test.ai.cloud.skywalking.plugin.h2.H2JDBCTest.testMySqlJDBC(H2JDBCTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.lang.NullPointerException
	at org.h2.Driver.<init>(Driver.java)
	at org.h2.Driver.classInitializer$AptLBoLS(Driver.java:36)
	at org.h2.Driver.<clinit>(Driver.java)
	... 35 more
```

I think it's caused by static field is h2.Drvier:
```java
public class Driver implements java.sql.Driver {
    private static final Driver INSTANCE = new Driver();
```

But why? How can I use byte-buddy in main class to avoid this problem?

**Comment by raphw** [comment]
The problem is that you are delegating to an instance (`new ClassConstructorInterceptor(interceptor)`). This instance needs to be set within the class which can typically only be done **after** the class was initialized. Therefore, the field value is `null` during the initializer initialization.

The easiest resolution would probably to activate active resolution by:
```java
newClassBuilder.make(TypeResolutionStrategy.ACTIVE)
```

**Comment by wu-sheng** [comment]
What does active resolution mean?  I know 'Driver INSTANCE' need to be initialized after the class was initialized, but why TypeResolutionStrategy.ACTIVE can solve the problem? I can't fully understand the comments on 'TypeResolutionStrategy.ACTIVE' as following, it says initializers are executed **before** . **initializers** means **class was initialized**? I'm confused.
```java
    /**
     * A type resolution strategy that applies all {@link LoadedTypeInitializer} as a part of class loading using reflection. This implies that the initializers
     * are executed <b>before</b> (as a first action of) a type initializer is executed.
     */
    enum Active implements TypeResolutionStrategy {
```
I write this codes to intercept constructor or method. There are other ways to do this?

**Comment by raphw** [comment]
The problem is as follows: In order to call your instance of `ClassConstructorInterceptor`, the instrumented `Driver` class needs to know about this instance. For this, Byte Buddy adds a `static` field of type `ClassConstructorInterceptor` to `Driver`. Every time, a constructor is executed, it reads this field's value and invokes the interception method on it.

Typically, Byte Buddy uses reflection to set this field after creating the class. However, when reflection is used, the VM initializes the class reflected upon. This triggers this instance creation:
```java
private static final Driver INSTANCE = new Driver();
```
As you instrumented the constructor, this results in a `NullPointerException` as Byte Buddy has not yet set the field's value which is now `null`.

In order to avoid this, the `ACTIVE` type resolution rewrites the class something like this:
```java
private static final Driver INSTANCE;
static {
  ByteBuddyNexus.initialize(Driver.class);
  INSTANCE = new Driver();
}
```
This way, Byte Buddy can set the field before the `new Driver()` call is made, successfully intercepting the constructor.

**Comment by wu-sheng** [comment]
Thanks. I have understand the solution. My require is to intercept the Constructor, in order to get params. Is any other ways to do? 
In my project, I can't know whether the target classes have a field of instance to itself, the only thing i can do is : add 'TypeResolutionStrategy.ACTIVE' to all target classes's builder.
Is this the right thing to do? If yes, why this strategy is not default?

**Comment by raphw** [comment]
As you say, it is the default for the agent builder. The assumption is that you know the classes you manually redefine by name. Therefore, you should know their properties. 

The active strategy adds a type initializer to the class. It is not given you want that which is why its not the default.

**Comment by wu-sheng** [comment]
Ok, thanks.

**Comment by raphw** [comment]
As for alternative ways to do it: add a static interceptor and you do not need it.

**Comment by wu-sheng** [comment]
How to add a static interceptor? I do not find the documents.
I need to intercept constructor, instance method and static instance method In order to get method name and parameters.
Can you give me a demonstration?  I can use static methods to intercept if necessary.

**Comment by raphw** [comment]
You would do something like: `MethodDelegation.to(ClassConstructorInterceptor.class)` - for this, the interceptor needs to be stateless.
