### ISSUE TITLE
Unexpected remainder on the operand stack: -1

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#166]
While instrumenting some classes using `AgentBuilder` and `Advice API`, the following error appears:
```
java.lang.IllegalStateException: Unexpected remainder on the operand stack: -1
	at net.bytebuddy.utility.StackAwareMethodVisitor.drainStack(StackAwareMethodVisitor.java:139)
	at net.bytebuddy.asm.Advice$AdviceVisitor$WithExitAdvice.onVisitInsn(Advice.java:1704)
	at net.bytebuddy.utility.ExceptionTableSensitiveMethodVisitor.visitInsn(ExceptionTableSensitiveMethodVisitor.java:288)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3018)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1617)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:198)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:5945)
```
I have prepared a small [reproducer for this problem](https://github.com/raphw/byte-buddy/files/404412/byte-buddy-test.zip).

**Comment by raphw** [comment]
Found and fixed the error on master. You can use Jitpack if you need the fix already. I will release a new version soon.

**Comment by orange-buffalo** [comment]
Great, thanks a lot for such a prompt fix!

**Comment by orange-buffalo** [comment]
Recently I have discovered couple of more cases where this problem is reproduced, although most of such issues were fixed in latest versions.

For example, when using test code provided in issue description, instrumentation of  `org.hsqldb.lib.LongDeque` from 
```xml
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>2.3.4</version>
    </dependency>
```
fails with the same error message.

**Comment by raphw** [comment]
Thanks for the report, I will look into it. The reason for this problem is a rather new feature where Byte Buddy discovers atypical byte code that does not allow for instrumentation. This is typically caused by broken tools or old compilers. Byte Buddy tries to fix the byte code in such cases whereas it would have created illegal byte code previously (the same problem goes with Javassist). The problem is that it sometimes tries to fix legal byte code where I have simply overseen a legal pattern. This just FYI.

**Comment by orange-buffalo** [comment]
Thank you for explanation. I can imagine how many different variations exist for these cases and that covering them all is far not a simple task.

**Comment by raphw** [comment]
I fixed the issue on master.

**Comment by orange-buffalo** [comment]
With this fix all the similar errors in my application are resolved. Thank you!
