### ISSUE TITLE
com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.

### ISSUE THREAD

**Issue by wuxindao** [raphw/byte-buddy#1674]
com.googlecode.aviator.code.asm asm error 

`java.lang.ExceptionInInitializerError: null
        at com.googlecode.aviator.AviatorEvaluator.getInstance(AviatorEvaluator.java:112) ~[na:na]
        at com.googlecode.aviator.AviatorEvaluator.<clinit>(AviatorEvaluator.java:61) ~[na:na]
        at com.sh.game.server.system.base0.condition.ConditionsHandler.init(ConditionsHandler.java:34) ~[bootstrap-server.exe:na]
        at com.sh.game.server.Context.start(Context.java:146) ~[bootstrap-server.exe:na]
        at com.sh.game.bootstrap.ServerBootstrap.main(ServerBootstrap.java:25) ~[bootstrap-server.exe:na]
        at com.sh.game.bootstrap.NativeBootstrap2.main(NativeBootstrap2.java:34) ~[bootstrap-server.exe:na]
        at java.base@21.0.3/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH) ~[na:na]
Caused by: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
        at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:781) ~[na:na]
        at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:438) ~[na:na]
        at com.googlecode.aviator.code.LambdaGenerator.getResult(LambdaGenerator.java:424) ~[na:na]
        at com.googlecode.aviator.code.LambdaGenerator.getLmabdaBootstrap(LambdaGenerator.java:189) ~[na:na]
        at com.googlecode.aviator.code.OptimizeCodeGenerator.onLambdaBodyEnd(OptimizeCodeGenerator.java:781) ~[na:na]
        at com.googlecode.aviator.code.LambdaGenerator.onLambdaBodyEnd(LambdaGenerator.java:472) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.ifStatement(ExpressionParser.java:1944) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1655) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1881) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.forStatement(ExpressionParser.java:1817) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1662) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1881) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.lambda(ExpressionParser.java:821) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.fnStatement(ExpressionParser.java:1293) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1684) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1863) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1134) ~[na:na]
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1148) ~[na:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1543) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1504) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1462) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalFunctions(AviatorEvaluatorInstance.java:1083) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalLibs(AviatorEvaluatorInstance.java:1059) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadLib(AviatorEvaluatorInstance.java:932) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluatorInstance.<init>(AviatorEvaluatorInstance.java:1121) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.AviatorEvaluator$StaticHolder.<clinit>(AviatorEvaluator.java:102) ~[na:na]
        ... 7 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
        at java.base@21.0.3/java.lang.ClassLoader.defineClass(ClassLoader.java:274) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.parser.AviatorClassLoader.defineClass(AviatorClassLoader.java:32) ~[bootstrap-server.exe:na]
        at com.googlecode.aviator.code.asm.ClassDefiner.defineClassByClassLoader(ClassDefiner.java:91) ~[na:na]
        at com.googlecode.aviator.code.asm.ClassDefiner.defineClass(ClassDefiner.java:85) ~[na:na]
        at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:766) ~[na:na]
        ... 32 common frames omitted
java.lang.ExceptionInInitializerError
        at com.googlecode.aviator.AviatorEvaluator.getInstance(AviatorEvaluator.java:112)
        at com.googlecode.aviator.AviatorEvaluator.<clinit>(AviatorEvaluator.java:61)
        at com.sh.game.server.system.base0.condition.ConditionsHandler.init(ConditionsHandler.java:34)
        at com.sh.game.server.Context.start(Context.java:146)
        at com.sh.game.bootstrap.ServerBootstrap.main(ServerBootstrap.java:25)
        at com.sh.game.bootstrap.NativeBootstrap2.main(NativeBootstrap2.java:34)
        at java.base@21.0.3/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
        at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:781)
        at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:438)
        at com.googlecode.aviator.code.LambdaGenerator.getResult(LambdaGenerator.java:424)
        at com.googlecode.aviator.code.LambdaGenerator.getLmabdaBootstrap(LambdaGenerator.java:189)
        at com.googlecode.aviator.code.OptimizeCodeGenerator.onLambdaBodyEnd(OptimizeCodeGenerator.java:781)
        at com.googlecode.aviator.code.LambdaGenerator.onLambdaBodyEnd(LambdaGenerator.java:472)
        at com.googlecode.aviator.parser.ExpressionParser.ifStatement(ExpressionParser.java:1944)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1655)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1881)
        at com.googlecode.aviator.parser.ExpressionParser.forStatement(ExpressionParser.java:1817)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1662)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1881)
        at com.googlecode.aviator.parser.ExpressionParser.lambda(ExpressionParser.java:821)
        at com.googlecode.aviator.parser.ExpressionParser.fnStatement(ExpressionParser.java:1293)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1684)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1863)
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1134)
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1148)
        at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1543)
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1504)
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1462)
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalFunctions(AviatorEvaluatorInstance.java:1083)
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalLibs(AviatorEvaluatorInstance.java:1059)
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadLib(AviatorEvaluatorInstance.java:932)
        at com.googlecode.aviator.AviatorEvaluatorInstance.<init>(AviatorEvaluatorInstance.java:1121)
        at com.googlecode.aviator.AviatorEvaluator$StaticHolder.<clinit>(AviatorEvaluator.java:102)
        ... 7 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130)
        at java.base@21.0.3/java.lang.ClassLoader.defineClass(ClassLoader.java:274)
        at com.googlecode.aviator.parser.AviatorClassLoader.defineClass(AviatorClassLoader.java:32)
        at com.googlecode.aviator.code.asm.ClassDefiner.defineClassByClassLoader(ClassDefiner.java:91)
        at com.googlecode.aviator.code.asm.ClassDefiner.defineClass(ClassDefiner.java:85)
        at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:766)`

**Comment by raphw** [comment]
Not sure how this relates to Byte Buddy?
