### ISSUE TITLE
Can I create an abstract class with byte buddy?

### ISSUE THREAD

**Issue by uvwild** [raphw/byte-buddy#19]
I need to create some abstract  Mixin classes for a package of our framework persistent objects so I can use the jackson framework to serialize them. Are there any examples about how to create an abstract class so I can reference it in the JacksonObjectMapper as a Mixin Class?
`objectMapper.addMixInAnnotations(POJO.class, POJOMixin.class);`

Or am I screwed due to classloader issues?
Sample Class:

    public abstract class JacksonItemMixin {
        @JsonCreator
        protected JacksonItemMixin(@JsonProperty("objId") final Long objId) {
        }
    }

The code I have so far:

            Annotation methodAnnotation = JacksonItemMixin.class.getDeclaredConstructor(Long.class).getAnnotation(JsonCreator.class);
            Annotation parameterAnnotation = JacksonItemMixin.class.getDeclaredConstructor(Long.class).getParameterAnnotations()[0][0];
            Class<?> dynamicType = new ByteBuddy().withModifiers(TypeManifestation.ABSTRACT)
                                                  .subclass(Object.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
                                                  .name(declaringClass.getCanonicalName().concat("MixIn"))
                                                  .defineConstructor(Arrays.<Class<?>>asList(Long.class), Visibility.PROTECTED)
                                                  .withoutCode()
                                                  .annotateMethod(methodAnnotation)
                                                  .annotateParameter(0, parameterAnnotation)
                                                  .make()
                                                  .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                                                  .getLoaded();
            dynamicType.newInstance();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            assert (false);
        } catch (InstantiationException e) {
            e.printStackTrace();
            assert (true);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
            assert (false);
        }

However this thows this Exception:

    java.lang.IllegalStateException: Exception on invoking loader method
    	at    net.bytebuddy.dynamic.loading.ClassLoaderByteArrayInjector.inject(ClassLoaderByteArrayInjector.java:142)
	at net.bytebuddy.dynamic.loading.ClassLoaderByteArrayInjector.inject(ClassLoaderByteArrayInjector.java:107)
	at net.bytebuddy.dynamic.ClassLoadingStrategy$Default$5.load(ClassLoadingStrategy.java:144)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:2944)
	at de.idealo.core.factory.CachingItemFactoryTest.createMixinFor(CachingItemFactoryTest.java:293)
	at de.idealo.core.factory.CachingItemFactoryTest.testClassScanning(CachingItemFactoryTest.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassFormatError: Method <init> in class de/pinuts/core/CatalogItemMixIn has illegal modifiers: 0x404
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at net.bytebuddy.dynamic.loading.ClassLoaderByteArrayInjector$ClassLoadingAction.run(ClassLoaderByteArrayInjector.java:320)
	at net.bytebuddy.dynamic.loading.ClassLoaderByteArrayInjector$ClassLoadingAction.run(ClassLoaderByteArrayInjector.java:290)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.dynamic.loading.ClassLoaderByteArrayInjector.inject(ClassLoaderByteArrayInjector.java:127)
	... 32 more
`

**Comment by raphw** [comment]
Calling `withoutCode` creates an abstract method and a constructor cannot be `abstract`. Instead, you would need to call the `Object` class's default constructor. For this, you would need to implement approriate byte code. You can do this by creating a simple `Instrumentation`:

```
TypeDescription objectType = new TypeDescription.ForLoadedType(Object.class);
new Instrumentation.Simple(
  MethodVariableAccess.forType(objectType).loadFromIndex(0), 
  MethodInvocation.invoke(objectType.getDeclaredMethods().filter(isConstructor()).getOnly())
    .special(objectType));
```

I recognize this use case and that this should be easier. I will add a utility instrumentation that makes this a one-liner in the future.

**Comment by uvwild** [comment]
Thanks mate. It was working in the end: 
Find all annotated classes:
```java
    public static Set<Constructor> getSQLInjectedItemSubClassCtors() {
        Predicate<String> filter = new FilterBuilder().include("mycore.legacy.*")
                                                    .include("myother.legacy.core.*");
        Reflections reflections = new Reflections(new ConfigurationBuilder().filterInputsBy(filter)
                             .setScanners(
                                   new SubTypesScanner().filterResultsBy(filter), 
                                   new MethodAnnotationsScanner().filterResultsBy( filter), 
                                   new MethodParameterScanner()).setUrls( ClasspathHelper.forClassLoader()));
        Set<Constructor> annotated = reflections.getConstructorsAnnotatedWith(SQLInject.class);
        return annotated;
    }
```
Then create the mixin for them:
```java
    public static Class<?> createMixinFor(final Class declaringClass) {
        assert(declaringClass != null);
        try {
            Annotation methodAnnotation = JacksonItemMixin.class.getDeclaredConstructor(Long.class).getAnnotation(JsonCreator.class);
            assert(methodAnnotation != null);
            Annotation parameterAnnotation = JacksonItemMixin.class.getDeclaredConstructor(Long.class).getParameterAnnotations()[0][0];
            assert(parameterAnnotation != null);
            LOG.debug("Annotation: {}",parameterAnnotation.annotationType());
            TypeDescription objectType = new TypeDescription.ForLoadedType(Object.class);
            Instrumentation instrumentation = new Instrumentation.Simple(MethodVariableAccess.forType(objectType).loadFromIndex(0), MethodInvocation.invoke(
                objectType.getDeclaredMethods().filter(ElementMatchers.isConstructor()).getOnly()).special(objectType), MethodReturn.VOID);
            Class<?> dynamicType = new ByteBuddy().withModifiers(TypeManifestation.ABSTRACT)
                                                  .subclass(Object.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
                                                  .name(declaringClass.getCanonicalName().concat("MixIn"))
                                                  .defineConstructor(Arrays.<Class<?>>asList(Long.class), Visibility.PROTECTED)
                                                  .intercept(instrumentation)
                                                  .annotateMethod(methodAnnotation)
                                                  .annotateParameter(0, parameterAnnotation)
                                                  .make()
                                                  .load(CachingItemFactory.class.getClassLoader(), ClassLoadingStrategy.Default.CHILD_FIRST_PERSISTENT)
                                                  .getLoaded();
            LOG.debug("created Mixin {} for {}", dynamicType, declaringClass);
            assert(dynamicType.getDeclaredConstructor(Long.class) != null);
            assert(dynamicType.getDeclaredConstructor(Long.class).getAnnotation(JsonCreator.class) != null);
            assert(dynamicType.getDeclaredConstructor(Long.class).getParameterAnnotations()[0][0] != null);
            return dynamicType;
        } catch (NoSuchMethodException nme) {
            LOG.error("createMixinFor: ", nme);
        }
        return null;
    }
```
Finally, use jackson mapper to apply this all:
```java
        objectMapper = new ObjectMapper();
        // use generated Mixin Classes
        Set<Constructor> ctors = getSQLInjectedItemSubClassCtors();
        for (Constructor ctor : ctors) {
            // add mixin annotations for inheritance relationships
            Class<?> persistenceClass = ctor.getDeclaringClass();
            objectMapper.addMixInAnnotations(persistenceClass, createMixinFor(persistenceClass));
        }
```

**Comment by raphw** [comment]
Great, I would like to keep this issue open until I had the time to implement an instrumentation that makes this impler.

**Comment by uvwild** [comment]
Oops sorry didn't want to disturb your work flow....

**Comment by raphw** [comment]
No worries. I appreciate the clean-up and the feedback. This just serves me as a reminder.

**Comment by raphw** [comment]
I implemented a `MethodCall` instrumentation that is included in the next version of Byte Buddy. You can then create the instrumentation by:

```java
MethodCall.invoke(Object.class.getDeclaredConstructor())
```

This instrumentation also allows you to hand over parameters if you wanted to call a constructor that takes parameters.

**Comment by raphw** [comment]
This instrumentation is now implemented in the latest version and pushed to Maven Central.
