### ISSUE TITLE
Lambda's - Error while trying to retrieve bytecode of instance method reference 

### ISSUE THREAD

**Issue by csoroiu** [raphw/byte-buddy#205]
I created a small test for the issue I am facing:
Basically i try to get the bytecode of generated lambda classes.
At the end of the code below is the code I used to extract the bytecode.

From the test class below the method `testFailingPublicInstanceMethodReference` is failing with `NoClassDefFoundError`. It looks like **ByteBuddy**'s code altered the generated code, but I might be wrong. The error is:
```
java.lang.NoClassDefFoundError: FailingResolveInstanceMethodReferenceTest$$Lambda$1
	at FailingResolveInstanceMethodReferenceTest$$Lambda$1/864237698.get$Lambda(Unknown Source)
	at FailingResolveInstanceMethodReferenceTest.getPublicInstanceMethodReference(FailingResolveInstanceMethodReferenceTest.java:19)
	at FailingResolveInstanceMethodReferenceTest.testFailingPublicInstanceMethodReference(FailingResolveInstanceMethodReferenceTest.java:14)
	...
Caused by: java.lang.ClassNotFoundException: FailingResolveInstanceMethodReferenceTest$$Lambda$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
Also, the test `testFailingPrivateInstanceMethodReference` is failing in **Oracle's retransformClasses** code with VerifyError:
```
java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at net.bytebuddy.dynamic.ClassFileLocator$AgentBased.locate(ClassFileLocator.java:1172)
	at Extractor.getByteCodeOf(FailingResolveInstanceMethodReferenceTest.java:103)
	at FailingResolveInstanceMethodReferenceTest.testFailingPrivateInstanceMethodReference(FailingResolveInstanceMethodReferenceTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
```

The code that reproduces the issue is:
I was using **jdk8_u102 on Windows 10 64bit** machine and **ByteBuddy 1.4.33, 1.5.0 and 1.5.1**, and i have the same issue. All the other 3 tests in the file are fine. 
I hope I am doing everything right. I am new to using code instrumentation.

```java
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import org.junit.Test;

import java.io.IOException;
import java.lang.instrument.Instrumentation;
import java.util.function.Function;

public class FailingResolveInstanceMethodReferenceTest {
    @Test
    public void testFailingPublicInstanceMethodReference() throws IOException {
        //NoClassDefFoundError at the second getInstanceMethodReference call
        Extractor.getByteCodeOf(getPublicInstanceMethodReference().getClass());
        Extractor.getByteCodeOf(getPublicInstanceMethodReference().getClass());
    }

    public Function<Person, String> getPublicInstanceMethodReference() {
        return this::getPersonName_public; //NoClassDefFoundError here at the second getInstanceMethodReference call
    }

    public String getPersonName_public(Person p) {
        return p.getName();
    }

    @Test
    public void testFailingPrivateInstanceMethodReference() throws IOException {
        //Test fails on the following line with VerifyError
        Extractor.getByteCodeOf(getPrivateInstanceMethodReference().getClass());
        Extractor.getByteCodeOf(getPrivateInstanceMethodReference().getClass());
    }

    public Function<Person, String> getPrivateInstanceMethodReference() {
        return this::getPersonName_private;
    }

    // This method needs to be private
    private String getPersonName_private(Person p) {
        return p.getName();
    }

    @Test
    public void testStaticMethodReference() throws IOException {
        Extractor.getByteCodeOf(getStaticMethodReference().getClass());
        Extractor.getByteCodeOf(getStaticMethodReference().getClass());
    }

    public Function<Person, String> getStaticMethodReference() {
        return FailingResolveInstanceMethodReferenceTest::getPersonNameStatic;
    }

    private static String getPersonNameStatic(Person p) {
        return p.getName();
    }

    @Test
    public void testInnerClassMethodReference() throws IOException {
        Extractor.getByteCodeOf(getInnerClassMethodReference().getClass());
        Extractor.getByteCodeOf(getInnerClassMethodReference().getClass());
    }

    public Function<Person, String> getInnerClassMethodReference() {
        return Person::getName;
    }

    @Test
    public void testConstructorReference() throws IOException {
        Extractor.getByteCodeOf(getConstructorReference().getClass());
        Extractor.getByteCodeOf(getConstructorReference().getClass());
    }

    public Function<String, Integer> getConstructorReference() {
        return Integer::new;
    }

    @Test
    public void testLambdaFunction() throws IOException {
        Extractor.getByteCodeOf(getLambdaFunction().getClass());
        Extractor.getByteCodeOf(getLambdaFunction().getClass());
    }

    public Function<Person, String> getLambdaFunction() {
        return (person) -> '[' + person.getName() + ']';
    }


    private /*static*/ class Person {
        private final String name = "Alice Bob";

        private String getName() {
            return name;
        }
    }
}

class Extractor {
    private static final Instrumentation instrumentation = ByteBuddyAgent.install();

    static byte[] getByteCodeOf(Class<?> lambda) throws IOException {
        System.out.println("Getting bytecode of " + lambda.getName());
        ClassFileLocator locator = ClassFileLocator.AgentBased.of(instrumentation, lambda);
        TypeDescription.ForLoadedType desc = new TypeDescription.ForLoadedType(lambda);
        ClassFileLocator.Resolution resolution = locator.locate(desc.getName());
        byte[] bytes = resolution.resolve();
        System.out.println("Done getting bytecode of " + lambda.getName());
        return bytes;
    }
}
```

**Comment by raphw** [comment]
To be honest, this very much looks like a bug in the JVM. I have not tried this extraction mode on lambda expressions in a while but I can easily reproduce this behavior:

```java
class Foo {
    void notFoundAfterRetransform() throws Exception {
        Instrumentation instrumentation = ByteBuddyAgent.install();
        instrumentation.addTransformer((loader, className, classBeingRedefined, protectionDomain, classfileBuffer) -> null, true); // No-op

        instrumentation.retransformClasses(fooHolder().getClass()); // instrumentation.isModifiableClass(type) == true

        fooHolder().getClass();
    }

  void verifierErrorOnRetransform() throws Exception {
        Instrumentation instrumentation = ByteBuddyAgent.install();
        instrumentation.addTransformer((loader, className, classBeingRedefined, protectionDomain, classfileBuffer) -> null, true); // No-op

        instrumentation.retransformClasses(barHolder().getClass()); // instrumentation.isModifiableClass(type) == true
    }

    Function<?, ?> fooHolder() {
        return this::foo;
    }

    public Object foo(Object p) {
        return null;
    }

    Function<?, ?> barHolder() {
        return this::bar;
    }

    private Object bar(Object p) {
        return null;
    }
}

**Comment by MyRealityCoding** [comment]
😮

**Comment by csoroiu** [comment]
@raphw I know you shouldn't mess up with lambda's. I only take the generated bytecode to detect the signature of the method reference. I used it in some [custom](https://github.com/csoroiu/lambdamatchers) hamcrest based matcher for display purposes only and it is targeted only for unit tests.
Thanks

**Comment by csoroiu** [comment]
Also, the **NoClassDefFoundError** is more annoying than **VerifyError** because the class is already broken and one cannot recover from the issue.

**Comment by raphw** [comment]
I agree that the use case can be meaningful. I submitted a bug, let's hope it gets fixed.

**Comment by csoroiu** [comment]
Can you provide the openjdk bug url? I want to follow up on that.

**Comment by raphw** [comment]
I will post it once it passed Q&A and gets a number.

**Comment by csoroiu** [comment]
Looks like is similar if not same as [JDK-8145964 - NoClassDefFound error in transforming lambdas](https://bugs.openjdk.java.net/browse/JDK-8145964) referred by stackoverflow question: [Transforming lambdas in Java 8](http://stackoverflow.com/q/34162074/2749648).
So, most likely, I need to wait for java 9 and #164 to get it working properly.

Thanks a lot!

**Comment by raphw** [comment]
Ok, I now remember when dealing with this the last time, sorry for forgetting this.
