### ISSUE TITLE
com.android.dx.dex.DexOptions class not found

### ISSUE THREAD

**Issue by originx** [raphw/byte-buddy#212]
Hello,

I am trying to add ByteBuddy to a JGiven project (BDD framework) so it can be used during Instrumentation tests.
https://github.com/originx/JGiven
gradlew clean :jgiven-android-test:connectedAndroidTest

The challenge was to get the context of the tested application instead of the instrumentation apk, which seems to work, but I get following exception during AndroidClassLoadingStrategy creation:

`java.lang.NoClassDefFoundError: com.android.dx.dex.DexOptions
at net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeDefault(AndroidClassLoadingStrategy.java:225)
at net.bytebuddy.android.AndroidClassLoadingStrategy.<init>(AndroidClassLoadingStrategy.java:95)
at com.tngtech.jgiven.integration.android.AndroidScenarioExecutor.createStageClass(AndroidScenarioExecutor.java:41)
at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.addStage(StandaloneScenarioExecutor.java:242)
at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
at com.tngtech.jgiven.junit.ScenarioExecutionRule.starting(ScenarioExecutionRule.java:124)
at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:86)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)`

Do you have any hints for me what could cause such behavior?

**Comment by raphw** [comment]
To me it seems as if you are missing the `dx-1.7.jar` when running the tests. The `AndroidClassLoader` has a dependency on Android's DX-compiler.

**Comment by originx** [comment]
You are right, closely inspecting it some strange gradle issue was happening, adding the dx on the compile path solved the issue.

Although I got a different (unrelated) error now:
adding empty constructors does not help.
`
java.lang.RuntimeException: Error while trying to create an instance of class class com.tngtech.jgiven.android.example.ExampleInstrumentedTest$GivenSomeState
at com.tngtech.jgiven.integration.android.AndroidScenarioExecutor.createStageClass(AndroidScenarioExecutor.java:46)
at com.tngtech.jgiven.impl.StandaloneScenarioExecutor.addStage(StandaloneScenarioExecutor.java:235)
at com.tngtech.jgiven.impl.Scenario.initialize(Scenario.java:98)
at com.tngtech.jgiven.impl.ScenarioBase.performInitialization(ScenarioBase.java:91)
at com.tngtech.jgiven.impl.ScenarioBase.startScenario(ScenarioBase.java:74)
at com.tngtech.jgiven.junit.ScenarioExecutionRule.starting(ScenarioExecutionRule.java:124)
at com.tngtech.jgiven.junit.ScenarioExecutionRule$1.evaluate(ScenarioExecutionRule.java:86)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.InstantiationException: can't instantiate class com.tngtech.jgiven.android.example.ExampleInstrumentedTest$GivenSomeState$ByteBuddy$VF8nBNSh; no empty constructor
at java.lang.Class.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1319)
at com.tngtech.jgiven.integration.android.AndroidScenarioExecutor.createStageClass(AndroidScenarioExecutor.java:43)`

This is my instance creation:
`  methodInterceptor.enableMethodHandling(true);
            T result = new ByteBuddy()
                    .subclass(stepsClass, ConstructorStrategy.Default.IMITATE_SUPER_CLASS)
                    .method(any())
                    .intercept(MethodDelegation.to(methodInterceptor))
                    .make()
                    .load(context.getClassLoader(),
                            new  AndroidClassLoadingStrategy(ContextCompat.getCodeCacheDir(context)))
                    .getLoaded()
                    .newInstance();`

And this is the inner class bytebuddy is trying to initialize:

`  public class GivenSomeState extends Stage<GivenSomeState> {

        public GivenSomeState some_state() {
            return self();
        }
    }`

thanks for your time

**Comment by raphw** [comment]
I assume that you are defining an inner class which never defines a no-argument constructor. Try adding the `static` keyword where the outer instance does not become an implicit constructor argument.

The error is neither related to Byte Buddy. Try calling `getDeclaredConstructor().newInstance()` instead which probably throws a `NoSuchMethodException`. (Calling `.newInstance()` directly was deprecated in Java 9 for this reason.)
