### ISSUE TITLE
how to combine bytebuddy with newrelic?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#213]
i use bytebuddy 1.5.4 version  and use springboot 1.4.1
before i create a `AgentInitializer`  class to implements  `ApplicationContextInitializer` interface to init bytebuddy

code is
```
ByteBuddyAgent.install();
new AgentBuilder.Default().with(DebugListener.getListener())
        //jersey
        .type(named("org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher"))
        .transform(new JerseyAdviceTransformer())
        //mysql
        .type(named("com.mysql.jdbc.MysqlIO"))
        .transform(new MysqlAdviceTransformer())
        .installOnByteBuddyAgent();
```
and i use `java -jar app.jar` to startup my application

now i want to add newrelic's agent, to report some appliction's performers
i can use `java -javaagent:/path/to/newrelic.jar -jar app.jar` to startup my application. but has a lot of error message like:
```
onError:com.newrelic.agent.tracers.OtherRootTracer
java.lang.IllegalStateException: Cannot resolve type description for com.newrelic.agent.bridge.ExitTracer
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:149)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1386)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:7580)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7145)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7168)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7152)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7168)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7152)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7168)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7146)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:7168)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:7146)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:7178)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:28)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:10)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1029)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:7104)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:7114)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:7422)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:7746)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:7715)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:7680)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1200(AgentBuilder.java:7467)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8105)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8055)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:7606)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.newrelic.agent.instrumentation.InstrumentationImpl.startTracer(InstrumentationImpl.java:262)
	at com.newrelic.agent.instrumentation.InstrumentationImpl.createTracer(InstrumentationImpl.java:124)
	at akka.actor.ActorCell.invoke(ActorCell.scala)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
how can i solve this error?

how can i  use bytebuddy's api not use -javaagent command to startup newrelic??

thanks very much.

**Comment by raphw** [comment]
You can simply ignore such types by setting up an appropriate matcher:
```
agentBuilder.ignore(nameStartsWith("net.bytebuddy.")
    .nameStartsWith("com.newrelic."))
    .or(any(), isBootstrapLoader())
```
The above matcher ignores any type belonging to Byte Buddy, New Relic or the JVM.

**Comment by dragontree101** [comment]
thanks, i add `ignore` code, the error message not to print.
how can i use NewRelic's jar use bytebuddy's api rather than -javaagent? 
because of we startup application use `java -jar app.jar` command, but i don't want to add `-javaagent` command on startup, i'm not found any way can remove `-javaagent` command.

**Comment by raphw** [comment]
You can look into the new relic jars manifest and locate the premain class and method. Invoke this method upon startup using reflection and provide the argument and instrumentation instance.

**Comment by dragontree101** [comment]
sorry my response is late,  i find new relic jars manifest, it want to read a yml file (normal new relic use -javaagent to start up), and this file in my uber's jar (i use springboot), so new relic jar can not read this yml and throw exception :( 
maybe it not byte buddy's question...

**Comment by raphw** [comment]
You would probably need to extract the agent and the yml file to the file system. I do not know how New Relic works but this should emulate it.
