### ISSUE TITLE
NullPointerException when running with RoboelectricTestRunner

### ISSUE THREAD

**Issue by benmarten** [raphw/byte-buddy#216]
I am using ByteBuddy to proxy an Adapter of List or Recycler view. As far as my manual tests go everything works. Now I'm trying to write unit tests for it, but it fails with this exception:

	java.lang.NullPointerException
		at dalvik.system.DexFile.__constructor__(DexFile.java:101)
		at dalvik.system.DexFile.<init>(DexFile.java)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:265)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
		at dalvik.system.DexPathList.__constructor__(DexPathList.java:109)
		at dalvik.system.DexPathList.<init>(DexPathList.java)
		at dalvik.system.BaseDexClassLoader.__constructor__(BaseDexClassLoader.java:48)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java)
		at net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeClassLoader(AndroidClassLoadingStrategy.java:274)
		at net.bytebuddy.android.AndroidClassLoadingStrategy.load(AndroidClassLoadingStrategy.java:134)
		at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:73)
		at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4525)
		at com.leanplum.internal.uieditor.LeanplumListenerSwizzler.swizzleRecyclerViewAdapter(LeanplumListenerSwizzler.java:103)
		at com.leanplum.LeanplumListenerSwizzlerTest.testSwizzleRecyclerViewAdapter(LeanplumListenerSwizzlerTest.java:59)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
		at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
		at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)

Line 103 is the .load() method:

	    Class<?> proxyAdapter = new ByteBuddy(ClassFileVersion.JAVA_V6)
	        .subclass(RecyclerView.Adapter.class)
	        .method(ElementMatchers.named("onBindViewHolder"))
	        .intercept(MethodDelegation.to(interceptingAdapter))
	        .make()
	        .load(activity.getClass().getClassLoader(), classLoadingStrategy)
	        .getLoaded();

ClassLoader and classLoadingStrategy are not null:
![screen shot 2016-11-21 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/5960238/20503143/34992c18-aff6-11e6-8a83-7de1f5e482b6.jpg)
![screen shot 2016-11-21 at 2 24 00 pm](https://cloud.githubusercontent.com/assets/5960238/20503145/37a00d1e-aff6-11e6-918c-dd7835885dbd.jpg)

**Comment by raphw** [comment]
If this only happens in your test, I do not think this is a problem with Byte Buddy but rather with Robolectric. The latter library mocks the Android environment and I assume that its a problem with how they mimic Android.

I can have a look if you create a reproduction that I can build and run.

**Comment by raphw** [comment]
Did you make any progress on this?

**Comment by benmarten** [comment]
Ok, finally got a sample project for you: https://github.com/benmarten/RecyclerViewAdapterTest/
Appreciate your help! Thanks

**Comment by raphw** [comment]
I looked a bit into this and it seems like Robolectric defines a field `libcore/io/Libcore.os:Llibcore/io/Os` which is `null` but should not be. I assume that Robolectric has limited support for Dex class loaders. The way that Robolectric works is that it uses a custom class loader where - at runtime - it replaces the stub implementations of the Dalvik API by its custom logic. What you really see is an exception within Robolectric. I am sure that they can fix this problem. This has nothing to do with Byte Buddy.

**Comment by benmarten** [comment]
Ok thanks for you help, I will see if i can write tests for this without it or open an issue with roboelectric.

**Comment by raphw** [comment]
My pleasure. You should be able to file the same issue with them. They can compare why this does not work with Robolectrics vs. an Android machine and identify the difference.
