### ISSUE TITLE
Proxying RecyclerView$Adapter fails

### ISSUE THREAD

**Issue by benmarten** [raphw/byte-buddy#217]
I am trying to intercept methods from an RecyclerView$Adapter:

	    Class<?> proxyAdapter = new ByteBuddy(ClassFileVersion.JAVA_V6)
	        .subclass(RecyclerView.Adapter.class)
	        .method(ElementMatchers.named("onBindViewHolder"))
	        .intercept(MethodDelegation.to(interceptingAdapter))
	        .make()
	        .load(activity.getClass().getClassLoader(), classLoadingStrategy)
	        .getLoaded();

where intercepting adapter is:

    public class LeanplumRecyclerViewAdapter extends RecyclerView.Adapter {

Intercepting works, but when actually setting the adapter it fails:

	E/Leanplum: Cannot invoke method via reflection., method android.support.v7.widget.RecyclerView.setAdapter argument 1 has type android.support.v7.widget.RecyclerView$Adapter, got java.lang.Class<android.support.v7.widget.RecyclerView$Adapter$ByteBuddy$Q3LCrdMu>

Any ideas?

**Comment by raphw** [comment]
It seems to me as if you are providing the method with a `Class` instance rather than an actual isntance.

You still need to call something like `proxyAdapter.newInstance()` before handing it as an argument.

**Comment by raphw** [comment]
I am closing this for now. Feel free to reopen the ticket if you have further questions.

**Comment by benmarten** [comment]
Yep, `proxyAdapter.newInstance()` solved that problem! Thanks for the hint ;)

Running into this error now:

	E/AndroidRuntime: FATAL EXCEPTION: main
	                  Process: com.example.sashohadzhiev.recyclevievtest, PID: 7238
	                  java.lang.AbstractMethodError: abstract method "int android.support.v7.widget.RecyclerView$Adapter.getItemCount()"
	                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3170)
	                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3067)
	                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
	                      at android.view.View.layout(View.java:17637)
	                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
	                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
	                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
	                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
	                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	                      at android.view.Choreographer.doFrame(Choreographer.java:621)
	                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	                      at android.os.Handler.handleCallback(Handler.java:751)
	                      at android.os.Handler.dispatchMessage(Handler.java:95)
	                      at android.os.Looper.loop(Looper.java:154)
	                      at android.app.ActivityThread.main(ActivityThread.java:6119)
	                      at java.lang.reflect.Method.invoke(Native Method)
	                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Any ideas?

**Comment by raphw** [comment]
Well, Byte Buddy only implements Java code. Javac does not allow implementing a class with missing methods but Byte Buddy does, as this might be what you want. You need to implement the missing methods in your subclass.

**Comment by benmarten** [comment]
Right, I got this error sorted out too, by giving it a concrete implementation of that abstract class.

Now I'm having one last issue, though:

        .subclass(LeanplumRecyclerViewAdapter.class)
        .method(ElementMatchers.named("onBindViewHolder"))
        .intercept(MethodDelegation.to(interceptingAdapter))

should only intercept the `onBindViewHolder` method, but its also intercepting the other methods of the LeanplumRecyclerViewAdapter.class, e.g. `getItemCount`

LeanplumRecyclerViewAdapter  is simply extending from RecyclerView.Adapter and implementing its methods... any ideas?

Any ideas?

**Comment by benmarten** [comment]
Just a quick feedback. Got this working now. Pretty much like in this example project: https://github.com/benmarten/RecyclerViewAdapterTest/
