### ISSUE TITLE
[Android] On pre-Nougat devices, NPE occurs while building MultipleParentClassLoader

### ISSUE THREAD

**Issue by tmurakami** [raphw/byte-buddy#240]
ByteBuddy 1.5.12

Code:
```java
package com.example.bytebuddyandroid_multipleparentclassloader;

import android.app.Activity;
import android.os.Bundle;

import net.bytebuddy.dynamic.loading.MultipleParentClassLoader;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        new MultipleParentClassLoader.Builder()
                // Append multiple ClassLoaders
                .append(new ClassLoader() {}).append(new ClassLoader() {})
                .build();
    }
}
```

StackTrace (Logcat):
```
12-28 19:28:01.128  3661  3661 E AndroidRuntime: FATAL EXCEPTION: main
12-28 19:28:01.128  3661  3661 E AndroidRuntime: Process: com.example.bytebuddyandroid_multipleparentclassloader, PID: 3661
12-28 19:28:01.128  3661  3661 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bytebuddyandroid_multipleparentclassloader/com.example.bytebuddyandroid_multipleparentclassloader.MainActivity}: java.lang.NullPointerException: parentLoader == null && !nullAllowed
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: Caused by: java.lang.NullPointerException: parentLoader == null && !nullAllowed
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at java.lang.ClassLoader.<init>(ClassLoader.java:210)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at java.lang.ClassLoader.<init>(ClassLoader.java:202)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at net.bytebuddy.dynamic.loading.MultipleParentClassLoader.<init>(MultipleParentClassLoader.java:44)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder.build(MultipleParentClassLoader.java:276)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at com.example.bytebuddyandroid_multipleparentclassloader.MainActivity.onCreate(MainActivity.java:17)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
12-28 19:28:01.128  3661  3661 E AndroidRuntime: 	... 9 more
```

Reason:
Prior to Android 7.0 'Nougat', ClassLoader(ClassLoader) constructor does not accept null parentLoader.
https://android.googlesource.com/platform/libcore/+/android-6.0.1_r77/libart/src/main/java/java/lang/ClassLoader.java#201
https://android.googlesource.com/platform/libcore/+/android-6.0.1_r77/libart/src/main/java/java/lang/ClassLoader.java#208

Android Nougat which is OpenJDK-based or later, this problem does not occur.

**Comment by raphw** [comment]
I added an additional constructor to `MultipleParentClassLoader` where you can supply an explicit parent. Did you encounter this problem when using Mockito on Android by any chance?

**Comment by tmurakami** [comment]
> Did you encounter this problem when using Mockito on Android by any chance?

I have not used mockito-android yet.
However, I have encountered this when creating my [DexMockito](https://github.com/tmurakami/dexmockito) library that is an alternative to dexmaker-mockito.

**Comment by raphw** [comment]
I added an additional builder method to `MultipleParentClassLoader` that allows to define an explicit parent. I will include this in the next release and also update Mockito to use this. Thanks for the report!
