### ISSUE TITLE
[Android] Suggestion: Support to generate proxies for package-private classes

### ISSUE THREAD

**Issue by tmurakami** [raphw/byte-buddy#249]
Byte Buddy Android 1.6.1

AndroidClassLoadingStrategy generates a proxy class using a DexClassLoader instance that is different from the class loader of the superclass, and so it is not possible to generate proxies for package-private classes.

```java
package com.example.myapplication;

class Foo {
}
```
```java
package com.example.myapplication;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.android.AndroidClassLoadingStrategy;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        new ByteBuddy()
                .subclass(Foo.class)
                .make()
                .load(Foo.class.getClassLoader(), new AndroidClassLoadingStrategy(getDir("test", Context.MODE_PRIVATE)));
    }
}
```
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.IllegalStateException: Cannot load class com.example.myapplication.Foo$ByteBuddy$e9Nnr4xU
    ...
 Caused by: java.lang.IllegalAccessError: superclass not accessible
    at dalvik.system.DexFile.defineClass(Native Method)
    at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
    at dalvik.system.DexPathList.findClass(DexPathList.java:315)
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:58)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:217) 
    at net.bytebuddy.android.AndroidClassLoadingStrategy.load(AndroidClassLoadingStrategy.java:140) 
    at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:78) 
    at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4532) 
    at com.example.myapplication.MainActivity.onCreate(MainActivity.java:17) 
    at android.app.Activity.performCreate(Activity.java:5008) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
    at android.app.ActivityThread.access$600(ActivityThread.java:130) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:137) 
    at android.app.ActivityThread.main(ActivityThread.java:4745) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
    at dalvik.system.NativeStart.main(Native Method) 
```

I think that this problem will be solved by using [dalvik.system.DexFile](https://developer.android.com/reference/dalvik/system/DexFile.html) instead of DexClassLoader.

### Usage
```java
// Open a Dex file.
DexFile df = DexFile.loadDex(classesZipPath, classesDexPath, 0);
// Associate the class with the specified class loader (just like ClassLoader#defineClass in Java).
// If the class cannot be loaded, null is returned.
Class<?> c = df.loadClass(className, classLoader);
if (c != null) {
    ...
}
```

Please note that DexFile#loadDex(String, String, int) was added in Android 1.5 (API 3).

**Comment by raphw** [comment]
Fixed on master.

**Comment by benmarten** [comment]
I think I'm running into a similar issue:

java.lang.IllegalAccessError: Class com.leanplum.testproj.MessagesListActivity$1myAdapter extended by class com.leanplum.testproj.MessagesListActivity$1myAdapter$ByteBuddy$LXZEB1pL is inaccessible (declaration of 'com.leanplum.testproj.MessagesListActivity$1myAdapter$ByteBuddy$LXZEB1pL' appears in /data/data/com.leanplum.testproj/app_leanplumClassDir/odonpM2g.jar)

Is this related, hence fixed on master?

**Comment by raphw** [comment]
Its fixed in the newest version. There is now and injecting and a wrapping strategy for android.

**Comment by benmarten** [comment]
Hm, I'm running into this issue now again, with 1.6.2 and 1.6.9:

```
E/[ERROR] java.lang.IllegalAccessError: Class com.android.internal.widget.ActionBarView$2 extended by class com.android.internal.widget.ActionBarView$2$ByteBuddy$VrLPYyDu is inaccessible (declaration of 'com.android.internal.widget.ActionBarView$2$ByteBuddy$VrLPYyDu' appears in /data/user/0/com.leanplum.testproj/app_leanplumClassDir/vtMqN5RI.jar)
```

      LeanplumOnClickListenerInterceptor interceptor = new LeanplumOnClickListenerInterceptor(
          originalOnClickListener);
      Class<?> proxyAdapterClass = new ByteBuddy(ClassFileVersion.JAVA_V6)
          .subclass(originalOnClickListener.getClass())
          .method(named("onClick"))
          .intercept(MethodDelegation.to(interceptor))
          .make()
          .load(activity.getClass().getClassLoader(), classLoadingStrategy)
          .getLoaded();
      onClickListener = (View.OnClickListener) UnsafeLoader
          .allocateIdenticalInstance(proxyAdapterClass, originalOnClickListener);


The error is thrown at `.load` any idea whats wrong?

**Comment by raphw** [comment]
Did it work in between?

**Comment by tmurakami** [comment]
@benmarten Is this what you want to create proxy?
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/com/android/internal/widget/ActionBarView.java#149

If so, I think that the class loader for `originalOnClickListener` is different from the argument given to `load()`.
If the two class loaders are different, non-public proxies cannot be created.

**Comment by raphw** [comment]
If this is the case, this is indeed impossible, the JVM does not allow it and there is no way around it.
