### ISSUE TITLE
Custom bind can't work

### ISSUE THREAD

**Issue by liuxianbing** [raphw/byte-buddy#256]
I using advice with CustomMapping ,Advice.DynamicValue.ForFixedValue .  
**and my advice methods is in the Transformer java file

but after i separate the advice methods to a single file(LogAdvice.java),it works fine**

 bellow is my code

private Advice.WithCustomMapping registerDynamicValues() {
    List<ApmmonitorDynamicValue<?>> dynamicValues = getDynamicValues();
    Advice.WithCustomMapping withCustomMapping = Advice.withCustomMapping();
    for (ApmmonitorDynamicValue dynamicValue : dynamicValues) {
      withCustomMapping = withCustomMapping.bind(dynamicValue.getAnnotationClass(), dynamicValue);
    }
    return withCustomMapping;
  }

class ProfilerDynamicValue extends ApmmonitorDynamicValue<ProfilerSignature> {

  @Override
  public Class<ProfilerSignature> getAnnotationClass() {
    return ProfilerSignature.class;
  }

  @Override
  protected Object doResolve(TypeDescription instrumentedType, MethodDescription instrumentedMethod,
      InDefinedShape target, Loadable<ProfilerSignature> annotation, Assigner assigner,
      boolean initialized) {
    return ....;
  }
}

@Advice.OnMethodEnter
  public static long enter(@ProfilerSignature String param) 

here is the error
java.lang.IllegalStateException: Cannot assign void to class java.lang.Object
        at net.bytebuddy.asm.Advice$Dispatcher$OffsetMapping$ForReturnValue.resolve(Advice.java:4026)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodExit.apply(Advice.java:6040)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:5592)
        at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
        at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
        at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.doApply(Advice.java:5586)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodExit$AdviceMethodInliner.apply(Advice.java:6138)
        at net.bytebuddy.asm.Advice$AdviceVisitor$WithExitAdvice.onUserEnd(Advice.java:7834)
        at net.bytebuddy.asm.Advice$AdviceVisitor.visitMaxs(Advice.java:7575)
        at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
        at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
        at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
        at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3102)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1693)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:7754)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:8224)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8189)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1100(AgentBuilder.java:7976)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8614)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8564)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8115)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

i use 1.5.7 version

**Comment by raphw** [comment]
The error message suggests that you are trying to create advice for a method returning `void` where you expect a non-void type via `@Advice.Return`.

**Comment by his1devil** [comment]
> The error message suggests that you are trying to create advice for a method returning `void` where you expect a non-void type via `@Advice.Return`.

Thank you raphw, it's worked.
BR
