### ISSUE TITLE
interceptor not work

### ISSUE THREAD

**Issue by godlike110** [raphw/byte-buddy#257]
when i use byte-buddy to build javaagent, it's don't work. would you tell me why.
my Interceptor code:

`
public class AccessInterceptor {

    @RuntimeType
    public static Object intercept(@Origin Method method,
                                   @SuperCall Callable<?> callable) throws Exception {
        Logger logger = LoggerFactory.getLogger(method.getName());
        System.out.println("start!");
        logger.info("start!!");
        long start = System.currentTimeMillis();
        try {
            return callable.call();
        } finally {
            System.out.println(method + " took " + (System.currentTimeMillis() - start));
            logger.info(method + " took " + (System.currentTimeMillis() - start));
        }
    }

}

`

my agent class ls ：
`

public class AccessAgent {

    public static Logger logger = LoggerFactory.getLogger(AccessAgent.class);
    public static void premain(String arguments,
                               Instrumentation instrumentation) {
        System.out.println("==============================agent start!======================================");
        logger.info("==============================agent start!======================================");
        new AgentBuilder.Default()
                .type(ElementMatchers.nameEndsWith("Controller"))
                .transform(new AgentBuilder.Transformer() {
                               @Override
                               public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription type, ClassLoader classLoader, JavaModule module) {
                                   System.out.println(type.asBoxed().getSimpleName());
                                   return builder.method(ElementMatchers.any())
                                           .intercept(MethodDelegation.to(AccessInterceptor.class));
                               }
                           }
                ).installOn(instrumentation);
        System.out.println("==============================agent end!======================================");
    }

}

`

Java cmd is : java -javaagent:statistics-agent-1.0.0-SNAPSHOT-full.jar -jar gcard-api-access-1.0.0-SNAPSHOT.jar 

start log:
![image](https://cloud.githubusercontent.com/assets/7553400/22098368/e305ad92-de60-11e6-9881-a50f4ac3cdd2.png)

but when a call a rest controller, the is no log added to the called method,why.

![image](https://cloud.githubusercontent.com/assets/7553400/22098408/1216f7c6-de61-11e6-9056-de9c9f922287.png)

**Comment by raphw** [comment]
I tried the following example which works without a problem:

```java
public static void main(String[] args) {
  premain("", ByteBuddyAgent.install());
  new SampleController().foo();
}

public static void premain(String arguments, Instrumentation instrumentation) {
  System.out.println("==============================agent start!======================================");
  new AgentBuilder.Default()
      .type(ElementMatchers.nameEndsWith("Controller"))
      .transform(new AgentBuilder.Transformer() {
        @Override
        public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
            TypeDescription type,
            ClassLoader classLoader,
            JavaModule module) {
        System.out.println(type.asBoxed().getSimpleName());
        return builder.method(ElementMatchers.any()).intercept(MethodDelegation.to(AccessInterceptor.class));
      }
    }
  ).installOn(instrumentation);
  System.out.println("==============================agent end!======================================");
  }

public static class AccessInterceptor {

  @RuntimeType
  public static Object intercept(@Origin Method method, @SuperCall Callable<?> callable) throws Exception {
    System.out.println("start!");
    long start = System.currentTimeMillis();
    try {
      return callable.call();
    } finally {
      System.out.println(method + " took " + (System.currentTimeMillis() - start));
    }
  }
}

public static class SampleController {
  public void foo() {
    System.out.println("foo");
  }
}
```

Maybe there is something wrong with your class loader composition? You can always register a `AgentBuilder.Listener.StreamWriting` to see what is going wrong.

**Comment by godlike110** [comment]
i have used you code,but there is still not work, the result run in IDEA is below, how to use StreamWriting。
<img width="1247" alt="default" src="https://cloud.githubusercontent.com/assets/7553400/22140834/d2a20a80-df29-11e6-81e9-48d81052fbf7.png">

**Comment by raphw** [comment]
I have run this exact code in IntelliJ and it worked. I assume that you change something as you for example added the logger call.

You can register a listener with:
```java
agentBuilder = agentBuilder.with(AgentBuilder.Listener.StreamWriting.toSystemOut());
```

I assume that you are loading your type prematurely. In this case, your listener does not report the type that you are looking for.

**Comment by godlike110** [comment]
i have add the AgentBuilder.Listener.StreamWriting and see the error code below, how can i do with id.

`
==============================agent start!======================================
==============================agent end!======================================
SampleController
[Byte Buddy] ERROR com.gop.agent.statistics.utils.HelloMain$SampleController [sun.misc.Launcher$AppClassLoader@2f78743b, null, loaded=false]
java.lang.IllegalArgumentException: None of [net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$Record@4ec53efa] allows for delegation from public void com.gop.agent.statistics.utils.HelloMain$SampleController.foo()
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:827)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1035)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:614)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:603)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:3899)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2894)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1612)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:7700)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:8092)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8055)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:7842)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8401)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8351)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:7981)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.gop.agent.statistics.utils.HelloMain.main(HelloMain.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
[Byte Buddy] COMPLETE com.gop.agent.statistics.utils.HelloMain$SampleController [sun.misc.Launcher$AppClassLoader@2f78743b, null, loaded=false]
foo

Process finished with exit code 0
`

**Comment by raphw** [comment]
You are using `Advice.Origin` instead of `Origin` in your code.

**Comment by godlike110** [comment]
my code is below, the Origin annotation is wrong ?:

`

package com.gop.agent.statistics.interceptor;

import net.bytebuddy.asm.Advice;
import net.bytebuddy.implementation.bind.annotation.Origin;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import net.bytebuddy.jar.asm.commons.Method;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.Callable;

/**
 * Created by wenzhiwei on 17/1/18.
 */
public class AccessInterceptor {

    @RuntimeType
    public static Object intercept(@Origin Method method,
                                   @SuperCall Callable<?> callable) throws Exception {
        Logger logger = LoggerFactory.getLogger(method.getName());
        System.out.println("start!");
        logger.info("start!!");
        long start = System.currentTimeMillis();
        try {
            return callable.call();
        } finally {
            System.out.println(method + " took " + (System.currentTimeMillis() - start));
            logger.info(method + " took " + (System.currentTimeMillis() - start));
        }
    }

}


`

**Comment by raphw** [comment]
There are two `Origin` annotations, one is only to be used with the `Advice` component which you are not using. In your screenshot above, you are using it and this also explains the error message you get.

**Comment by godlike110** [comment]
i have changed it, to the other annotation , but still has error below, i dont't know why.

![image](https://cloud.githubusercontent.com/assets/7553400/22199741/23df235a-e197-11e6-8b7b-1d0c8f884894.png)

`
==============================agent start!======================================
==============================agent end!======================================
SampleController
[Byte Buddy] ERROR com.gop.agent.statistics.utils.HelloMain$SampleController [sun.misc.Launcher$AppClassLoader@2f78743b, null, loaded=false]
java.lang.IllegalStateException: The net.bytebuddy.jar.asm.commons.Method arg0 method's 0 parameter is annotated with a Origin annotation with an argument not representing a Class, Method, Constructor, String, int, MethodType or MethodHandle type
	at net.bytebuddy.implementation.bind.annotation.Origin$Binder.bind(Origin.java:121)
	at net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$DelegationProcessor$Handler$Bound.bind(TargetMethodAnnotationDrivenBinder.java:697)
	at net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$Record.bind(TargetMethodAnnotationDrivenBinder.java:119)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:821)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1035)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:614)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:603)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:3899)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2894)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1612)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)


`

**Comment by raphw** [comment]
This time, you are importing the wrong `Method` type, you want `java.lang.reflect.Method`, not the ASM representation. Please read the error message.

**Comment by godlike110** [comment]
got it ,thanks very much!  you are so kind.

**Comment by godlike110** [comment]
the agent start success, but it gose wrong, when running.
`
[2017-01-23 18:40:55:756] [http-nio-8632-exec-10] [ERROR] - org.apa.cat.cor.Con.[To.[lo.[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.gop.agent.statistics.interceptor.AccessInterceptor.intercept(Ljava/lang/reflect/Method;Ljava/util/concurrent/Callable;)Ljava/lang/Object;] with root cause
java.lang.NoSuchMethodError: com.gop.agent.statistics.interceptor.AccessInterceptor.intercept(Ljava/lang/reflect/Method;Ljava/util/concurrent/Callable;)Ljava/lang/Object;
	at springfox.documentation.swagger.web.ApiResourceController.uiConfiguration(ApiResourceController.java) ~[springfox-swagger-common-2.5.0.jar!/:2.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) ~[spring-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]


`

my java class is below:

`

public class AccessInterceptor {

    @RuntimeType
    public static Object intercept(@Origin Method method,
                                   @SuperCall Callable<?> callable) throws Exception {
        Logger logger = LoggerFactory.getLogger(method.getName());
        System.out.println("start!");
        logger.info("start!!");
        long start = System.currentTimeMillis();
        try {
            return callable.call();
        } finally {
            System.out.println(method + " took " + (System.currentTimeMillis() - start));
            logger.info(method + " took " + (System.currentTimeMillis() - start));
        }
    }

}


`

**Comment by raphw** [comment]
I assume that your agent is running on a different class loader then your application. Any instrumented class needs to be able to resolve the interceptor class.

You might need to inline the code by using `Advice` as a visitor or you need to add your interceptor classes to the bootstrap class loader by using `Instrumentation::appendToBootstrapSearch`.

**Comment by godlike110** [comment]
i have dealed with it successful, thank you.
