### ISSUE TITLE
How to Work with tomcat 

### ISSUE THREAD

**Issue by liuxianbing** [raphw/byte-buddy#260]
my tomcat version 8.0.26  bytebuddy 1.6.1
after i startup the tomcat application, use agentmain method with jvm attach

@Advice.OnMethodEnter
  public static long enter() {
    return System.currentTimeMillis();
  }

after start the agent, aslo the AgentBuilder.RawMatcher has match my application class,but it does not inject the code to my web application

why?

**Comment by raphw** [comment]
By doing the above you do not add any code with an effect. Attempt to debug your code by trying something like adding a `System.out::println` and see if it works.

You should also add a `AgentBuilder.Listener.StreamWriting::toSystemOutput` to see if your types get enhanced the way you want it.

From the little code you provide, I cannot say anything further from what is wrong.

**Comment by liuxianbing** [comment]
sorry , here is the code

 final ByteBuddy byteBuddy =
        new ByteBuddy().with(TypeValidation.of(ApmConfiguration.getInstance().debug));
    // .with(MethodGraph.Empty.INSTANCE);
    return new AgentBuilder.Default(byteBuddy).with(binaryLocator)
        .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION).with(new AgentBuilder.Listener() {
          @Override
          public void onComplete(String arg0, ClassLoader arg1, JavaModule arg2) {
            // System.out.println("onComplete:" + arg0);
          }

          @Override
          public void onError(String arg0, ClassLoader arg1, JavaModule arg2, Throwable arg3) {
            System.out.println(arg3.getMessage() + "onError:" + arg0);
            arg3.printStackTrace();
          }

          @Override
          public void onIgnored(TypeDescription arg0, ClassLoader arg1, JavaModule arg2) {}

          @Override
          public void onTransformation(TypeDescription arg0, ClassLoader arg1, JavaModule arg2,
              DynamicType arg3) {
            System.out.println("onTransformation:" + arg0.getName());
          }
        }).ignore(any(), timed("classloader", "bootstrap", isBootstrapClassLoader()))
        .or(any(), timed("classloader", "reflection", isReflectionClassLoader()))
        .or(any(),
            timed("classloader", "apm-call-site",
                classLoaderWithName("org.codehaus.groovy.runtime.callsite.CallSiteClassLoader")))
        .or(any(), new IsIgnoredClassLoaderElementMatcher())
        .or(timed("type", "global-exclude",
            nameStartsWith("java").or(nameStartsWith("com.sun.")).or(nameStartsWith("sun."))
                .or(nameStartsWith("jdk.")).or(nameStartsWith("org.aspectj."))
                .or(nameStartsWith("org.groovy.")).or(nameStartsWith("com.p6spy."))
                .or(nameStartsWith("net.bytebuddy."))
                .or(nameStartsWith("org.slf4j.").and(not(nameStartsWith("org.slf4j.impl."))))
                .or(nameContains("javassist")).or(nameContains(".asm."))
                .or(nameStartsWith("com.github.apm")
                    .and(not(nameContains("Test").or(nameContains("benchmark")))))))
        .disableClassFormatChanges().type(ElementMatchers.nameStartsWith("com.jingoal.dc.koala.web.controller"))
        .transform(new AgentBuilder.Transformer() {
          @Override
          public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription,
              ClassLoader arg2) {
            try {
              return builder.visit(Advice.to(LoggingAdvice.class).on(nameStartsWith("do")));
            } catch (Exception e) {
              e.printStackTrace();
            }
            return null;
          }
        }).asDecorator();

And LoggingAdvice is

@Advice.OnMethodEnter
  public static long enter() {
    return System.currentTimeMillis();
  }

  @Advice.OnMethodExit(onThrowable = Throwable.class)
  public static void exit(@Advice.Thrown Throwable t, @Advice.Origin("#m") String methodName,
      @Advice.Origin("#t") String classType, @Advice.Origin("#s") String signature,
      @Advice.Enter long startTime,
      @Advice.Return(typing = Assigner.Typing.DYNAMIC) Object returnObj) {
    long spendTime = System.currentTimeMillis() - startTime;
    System.out.println(classType + "-" + methodName + "***");
    PrometheusMetricsModule.calLate(spendTime, classType, methodName, signature);
    if (null != t) {
      PrometheusMetricsModule.errorCounter(classType, methodName, signature, t);
    }
    if (slowTime > 0 && spendTime >= slowTime) {
      writeSlowTime(classType, methodName, signature, returnObj.toString(), spendTime);
    }
  }

my web application is using spring mvc,which is deployed into the tomcat server
after i startup the tomcat, i get the jvm pid, and then attach my agent app to the running jvm

bellow is my web application

package com.jingoal.dc.koala.web.controller;
@Controller
@SessionAttributes("login")
@RequestMapping(value = "/login")
public class LoginController{
@RequestMapping("/doLogin")
  public String doLogin(@RequestParam(required = false) String inputId,
      @RequestParam(required = false) String inputPassword, Model model) {
....
}
}

and after i attach the agent to the running application,my agent listener aslo print

onTransformation:com.jingoal.dc.koala.web.controller.LoginController

is there someing different with the situation when came with spring web application?

Hope get some help, thanks!!!
forgive my poor English

**Comment by raphw** [comment]
There is a chance that your application class loaders cannot see the your advice types such as `PrometheusMetricsModule`. Application containers such as Tomcat often shield their deployed applications from the system class path on which the agent is loaded.

What I would recommend you is to start out with a very simple advice that does not rely on any foreign types but only, for example, prints to the console. If this works, it is a class loader issue.

A common strategy is to add such required infrastructure types to the bootstrap class loader in a specific jar via the `Instrumentation` interface. This makes those types universally visible to all class loaders.

**Comment by liuxianbing** [comment]
if i do not use byte buddy , just with a very simple asm advice, like this

public static void premain(String args, Instrumentation inst) {
  try {
      inst.appendToBootstrapClassLoaderSearch(new JarFile(
          AgentLauncher.class.getProtectionDomain().getCodeSource().getLocation().getFile()));
    } catch (IOException e1) {
    }
    Class<?>[] classes = inst.getAllLoadedClasses();
    inst.addTransformer(new InjectMonitorClassTransform(), true);
    for (Class c : classes) {
      if (c.getName().contains("com.jingoal.dc.koala.web.controller.LoginController")) {//just one java file for expamle
        try {
          inst.retransformClasses(c);
        } catch (UnmodifiableClassException e) {
          e.printStackTrace();
        }
      }
    }
}

class InjectMonitorClassTransform implements ClassFileTransformer {
  public InjectMonitorClassTransform() {}

  @Override
  public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined,
      ProtectionDomain protectionDomain, byte[] classfileBuffer)
      throws IllegalClassFormatException {
    
    if (className != null
        && className.contains("com/jingoal/dc/koala/web/controller/LoginController")) {
     
      ClassReader reader = new ClassReader(classfileBuffer);
      
      ClassWriter writer = new ClassWriter(reader, ClassWriter.COMPUTE_MAXS);
     
      reader.accept(new TimeClassVisitor(writer, className), 8);
  
      return writer.toByteArray();
    } else {
      return null;
    }
  }

}


class TimeClassVisitor extends ClassVisitor {
  private String className;

  public TimeClassVisitor(ClassVisitor cv, String className) {
    super(Opcodes.ASM5, cv);
    this.className = className;
  }

 
  @Override
  public MethodVisitor visitMethod(int access, final String name, String desc, String signature,
      String[] exceptions) {
    MethodVisitor mv = cv.visitMethod(access, name, desc, signature, exceptions);
  
    if (!name.equals("<init>") && mv != null) {
      mv = new AdviceAdapter(Opcodes.ASM5, mv, access, name, desc) {
        
        @Override
        public void onMethodEnter() {
          // 相当于com.blueware.agent.TimeUtil.setStartTime();
          this.visitMethodInsn(Opcodes.INVOKESTATIC, "com/github/apm/agent/TimeUtil",
              "setStartTime", "()V", false);
        }

       
        @Override
        public void onMethodExit(int opcode) {
         
          this.visitMethodInsn(Opcodes.INVOKESTATIC, "com/github/apm/agent/TimeUtil", "setEndTime",
              "()V", false);
         
          this.visitLdcInsn(className);
         
          this.visitLdcInsn(name);
         com.blueware.agent.TimeUtil.getExclusiveTime("com/blueware/agent/TestTime","testTime");
          this.visitMethodInsn(Opcodes.INVOKESTATIC, "com/github/apm/agent/TimeUtil",
              "getExclusiveTime", "(Ljava/lang/String;Ljava/lang/String;)J", false);
        }
      };
    }
    return mv;
  }
}

public class TimeUtil {
  private static long startTime;
  private static long endTime;

  public TimeUtil() {}

  public static long getStartTime() {
    return startTime;
  }

  public static void setStartTime() {
    startTime = System.currentTimeMillis();
  }

  public static long getEndTime() {
    return endTime;
  }

  public static void setEndTime() {
    endTime = System.currentTimeMillis();
  }

  public static long getExclusiveTime(String className, String methodName) {
    long exclusive = getEndTime() - getStartTime();
    System.out.println(className.replace("/", ".") + "." + methodName + " exclusive:" + exclusive);
    return exclusive;
  }
}

int tomcat/bin catalina.sh set JAVA_OPTS -javaagent:apm_agent.jar  
and after i startup tomcat using  ,print error message 


24-Jan-2017 15:50:01.046 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/dc/apache-tomcat-8.0.26/webapps/ROOT
24-Jan-2017 15:50:03.995 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping#0' defined in URL [file:/home/dc/apache-tomcat-8.0.26/webapps/ROOT/WEB-INF/classes/spring/spring-server.xml]: Initialization of bean failed; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/jingoal/dc/koala/web/controller/LoginController.initRedirectPage(Ljava/lang/String;Lorg/springframework/ui/Model;)Ljava/lang/String; @85: areturn
  Reason:
    Type long_2nd (current frame, stack[2]) is not assignable to reference type
  Current Frame:
    bci: @85
    flags: { }
    locals: { 'com/jingoal/dc/koala/web/controller/LoginController', 'java/lang/String', 'org/springframework/ui/Model', 'java/lang/String', '[Ljava/lang/String;' }
    stack: { 'java/lang/String', long, long_2nd }
  Bytecode:
    0x0000000: b802 1bbb 002e 592b b800 30b7 0036 4e2d
    0x0000010: 1239 b600 3b3a 042a b400 3f12 43b9 0045
    0x0000020: 0200 c600 342a b400 3f12 43b9 0045 0200
    0x0000030: c000 4bb6 004d 1904 0332 1251 b600 3b04
    0x0000040: 32b6 0053 9900 1212 57b8 021e 1302 1f13
    0x0000050: 0225 b802 24b0 2c12 592b b900 5b03 0057
    0x0000060: 1261 b802 1e13 021f 1302 25b8 0224 b0  
  Stackmap Table:
    append_frame(@86,Object[#46],Object[#106])

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4729)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1101)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/jingoal/dc/koala/web/controller/LoginController.initRedirectPage(Ljava/lang/String;Lorg/springframework/ui/Model;)Ljava/lang/String; @85: areturn
  Reason:
    Type long_2nd (current frame, stack[2]) is not assignable to reference type
  Current Frame:
    bci: @85
    flags: { }
    locals: { 'com/jingoal/dc/koala/web/controller/LoginController', 'java/lang/String', 'org/springframework/ui/Model', 'java/lang/String', '[Ljava/lang/String;' }
    stack: { 'java/lang/String', long, long_2nd }
  Bytecode:
    0x0000000: b802 1bbb 002e 592b b800 30b7 0036 4e2d
    0x0000010: 1239 b600 3b3a 042a b400 3f12 43b9 0045
    0x0000020: 0200 c600 342a b400 3f12 43b9 0045 0200
    0x0000030: c000 4bb6 004d 1904 0332 1251 b600 3b04
    0x0000040: 32b6 0053 9900 1212 57b8 021e 1302 1f13
    0x0000050: 0225 b802 24b0 2c12 592b b900 5b03 0057
    0x0000060: 1261 b802 1e13 021f 1302 25b8 0224 b0  
  Stackmap Table:
    append_frame(@86,Object[#46],Object[#106])

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:571)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:488)
        at org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping.determineUrlsForHandlerMethods(DefaultAnnotationHandlerMapping.java:178)
        at org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping.determineUrlsForHandler(DefaultAnnotationHandlerMapping.java:124)
        at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.detectHandlers(AbstractDetectingUrlHandlerMapping.java:79)
        at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.initApplicationContext(AbstractDetectingUrlHandlerMapping.java:58)
        at org.springframework.context.support.ApplicationObjectSupport.initApplicationContext(ApplicationObjectSupport.java:120)
        at org.springframework.web.context.support.WebApplicationObjectSupport.initApplicationContext(WebApplicationObjectSupport.java:76)
        at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:74)
        at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:119)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:94)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        ... 24 more
Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping#0' defined in URL [file:/home/dc/apache-tomcat-8.0.26/webapps/ROOT/WEB-INF/classes/spring/spring-server.xml]: Initialization of bean failed; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/jingoal/dc/koala/web/controller/LoginController.initRedirectPage(Ljava/lang/String;Lorg/springframework/ui/Model;)Ljava/lang/String; @85: areturn
  Reason:
    Type long_2nd (current frame, stack[2]) is not assignable to reference type
  Current Frame:
    bci: @85
    flags: { }
    locals: { 'com/jingoal/dc/koala/web/controller/LoginController', 'java/lang/String', 'org/springframework/ui/Model', 'java/lang/String', '[Ljava/lang/String;' }
    stack: { 'java/lang/String', long, long_2nd }
  Bytecode:
    0x0000000: b802 1bbb 002e 592b b800 30b7 0036 4e2d
    0x0000010: 1239 b600 3b3a 042a b400 3f12 43b9 0045
    0x0000020: 0200 c600 342a b400 3f12 43b9 0045 0200
    0x0000030: c000 4bb6 004d 1904 0332 1251 b600 3b04
    0x0000040: 32b6 0053 9900 1212 57b8 021e 1302 1f13
    0x0000050: 0225 b802 24b0 2c12 592b b900 5b03 0057
    0x0000060: 1261 b802 1e13 021f 1302 25b8 0224 b0  
  Stackmap Table:
    append_frame(@86,Object[#46],Object[#106])

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4729)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1101)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/jingoal/dc/koala/web/controller/LoginController.initRedirectPage(Ljava/lang/String;Lorg/springframework/ui/Model;)Ljava/lang/String; @85: areturn
  Reason:
    Type long_2nd (current frame, stack[2]) is not assignable to reference type
  Current Frame:
    bci: @85
    flags: { }
    locals: { 'com/jingoal/dc/koala/web/controller/LoginController', 'java/lang/String', 'org/springframework/ui/Model', 'java/lang/String', '[Ljava/lang/String;' }
    stack: { 'java/lang/String', long, long_2nd }
  Bytecode:
    0x0000000: b802 1bbb 002e 592b b800 30b7 0036 4e2d
    0x0000010: 1239 b600 3b3a 042a b400 3f12 43b9 0045
    0x0000020: 0200 c600 342a b400 3f12 43b9 0045 0200
    0x0000030: c000 4bb6 004d 1904 0332 1251 b600 3b04
    0x0000040: 32b6 0053 9900 1212 57b8 021e 1302 1f13
    0x0000050: 0225 b802 24b0 2c12 592b b900 5b03 0057
    0x0000060: 1261 b802 1e13 021f 1302 25b8 0224 b0  
  Stackmap Table:
    append_frame(@86,Object[#46],Object[#106])

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:571)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:488)
        at org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping.determineUrlsForHandlerMethods(DefaultAnnotationHandlerMapping.java:178)
        at org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping.determineUrlsForHandler(DefaultAnnotationHandlerMapping.java:124)
        at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.detectHandlers(AbstractDetectingUrlHandlerMapping.java:79)
        at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.initApplicationContext(AbstractDetectingUrlHandlerMapping.java:58)
        at org.springframework.context.support.ApplicationObjectSupport.initApplicationContext(ApplicationObjectSupport.java:120)
        at org.springframework.web.context.support.WebApplicationObjectSupport.initApplicationContext(WebApplicationObjectSupport.java:76)
        at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:74)
        at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:119)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:94)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        ... 24 more
24-Jan-2017 15:50:06.612 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
24-Jan-2017 15:50:06.613 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
24-Jan-2017 15:50:06.618 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
24-Jan-2017 15:50:06.618 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
24-Jan-2017 15:50:06.619 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
24-Jan-2017 15:50:06.621 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/dc/apache-tomcat-8.0.26/webapps/ROOT has finished in 5,575 ms
24-Jan-2017 15:50:06.623 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Jan-2017 15:50:06.627 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8443"]
24-Jan-2017 15:50:06.627 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
24-Jan-2017 15:50:06.628 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 5858 ms
