### ISSUE TITLE
Getting 'None of [XXX] allows for delegation from YYY' when using retransformation strategy

### ISSUE THREAD

**Issue by YoannBuch** [raphw/byte-buddy#272]
I want to retransform already loaded classes so I configured the agent builder this way:

```
        AgentBuilder agentBuilder = new AgentBuilder.Default()
                .disableClassFormatChanges()
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new MyListener());
```

```
        agentBuilder
            .type(named("com.Foo"))
            .transform(new AgentBuilder.Transformer() {
                @Override
                public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {

                    return builder
                            .method(isDeclaredBy(typeDescription))
                            .intercept(
                                    MethodDelegation
                                            .withDefaultConfiguration()
                                            .filter(not(isDeclaredBy(Object.class)))
                                            .to(new MyInterceptor()));
                }
            })
            .installOn(instrumentation);
    }
```

```
    public class MyInterceptor {

        @RuntimeType
        public Object intercept(@SuperCall Callable<?> zuper) throws Exception {

            System.out.println("intercept");

            return zuper.call();
        }
    }
```

But I'm getting this error:

```
java.lang.IllegalArgumentException: None of [net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$Record@ae08d92d] allows for delegation from public static void com.Foo.foo()
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:827)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1035)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:614)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:603)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:3912)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2894)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1612)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2677)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8092)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:8484)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8447)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:8234)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8793)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8743)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8373)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
...

```
If I understand things correctly it means that we couldn't find a target method in `MyInterceptor` for  method `com.Foo.foo`

```
public static void foo() { }
```

However with the default config everything is working fine:

```
AgentBuilder agentBuilder = new AgentBuilder.Default();
```

Any ideas?

**Comment by raphw** [comment]
With specifying the `REDEFINE` strategy, you do not longer rebase the original method (meaning, retaining the original code of `foo`). Therefore, `foo`'s original implementation is discarded in favor of your new one. 

You probably want to advice the `foo` method. Look into the `Advice` component and apply it as a visitor via `DynamicType.Builder::visit`.

**Comment by YoannBuch** [comment]
I used `Advice` and it worked pretty well! I don't know why I was reluctant to use it because it meets all my requirements, for now.

It's taking ~7 seconds to retransform ~130 classes. Is it normal? Instrumenting these classes at first load  felt a lot faster.

**Comment by raphw** [comment]
Retransformation is a quite expensive operation, unfortunately. The JVM must lock all classes, replace all references and do a lot of maintenance to apply a retransformation. You can measure the difference by supplying a proxy for the `Instrumentation` interface where you implement `retransformClasses` as a no-op.

As for Byte Buddy, good `ignore` matchers where you exclude everything but your target namespace often does the job. Byte Buddy only parses class files if it absoloutly has to. Also, you can supply a `MethodGraph.Compiler.ForDeclaredMethods` to `ByteBuddy` to avoid parsing a class's class hierarchy. This way, you can however not properly add classes.

**Comment by YoannBuch** [comment]
Too bad retransformation is that slow. I had a couple of ideas where I could use it.

One was to remove the instrumentation to decrease the overhead when it is no longer needed (my target namespace is generally quite big: all the classes of the running application and optionally some of its dependencies), and re-instrumenting when it is needed again (possibly using a different target namespace). But to be honest I have never really measured the overhead and maybe it is acceptable for my use case. By the way, does `Advice` gives me better performance (speed) than "classic" method delegation?

The other idea was to remove the instrumentation from "noisy" methods. I noticed that a few methods make up most of the captured calls. If I remove the instrumentation from them I could drastically reduce the amount of calls I have to capture and therefore the overhead. I don't know which methods are the noisy ones prior to execution therefore I have to detect them on the fly and remove the instrumentation from them one by one (and as fast as possible). So how can I tell ByteBuddy to remove a transformation done on a specific class? (vs all classes like `ResettableClassFileTransformer.reset` does)

Once I removed the instrumentation from that class I would reapply the instrumentation on all the methods of this class but the noisy method. Again this should happen fast, but hopefully retransforming just one class is fast.

**Comment by raphw** [comment]
The JVM's JIT is doing the exact optimizations that you are proposing. I do not think that you can do any better here and you are also forcing the JIT to discard and recompile any code upon a retransformation. 

As for removal: You cannot tell Byte Buddy to only remove certrain retransformations. In this case, you would have to manage the installation process yourself by using `makeRaw`. But remember: retransformation is not for performance improvements. You will not get anywhere with this!

**Comment by YoannBuch** [comment]
Ok, well that's good to know before I waste more time down that path :)

Thanks again!
