### ISSUE TITLE
Error: None of ... allows for delegation from ...

### ISSUE THREAD

**Issue by nickgrealy** [raphw/byte-buddy#276]
Hi,

First of all, thanks for `byte-buddy`! I'm just getting up to speed, and I'm getting the following issue, and I'm not sure what it means?

```
[Byte Buddy] ERROR java.net.HttpURLConnection [null, null, loaded=false]
java.lang.IllegalArgumentException: None of [net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$Record@863140d4] allows for delegation from public abstract void java.net.URLConnection.connect() throws java.io.IOException
```

I *think* it means, that my `@RuntimeType` method/interceptor doesn't match the signature for the `public abstract void java.net.URLConnection.connect() throws java.io.IOException` method?

I've tried setting it to return void however, and I'm still getting the issue. Could you please provide a nudge in the right direction? (even if you're pointing me to the docs)

**Here's the code:**

```Java
public static void main(String[] args) throws Exception {
	premain(null, ByteBuddyAgent.install());
	HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
	System.out.println(urlConnection.getResponseCode());
}

public static void premain(String arg, Instrumentation inst) throws Exception {
	File temp = Files.createTempDirectory("tmp").toFile();

	ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst).inject(Collections.singletonMap(
			new TypeDescription.ForLoadedType(MyInterceptor.class),
			ClassFileLocator.ForClassLoader.read(MyInterceptor.class).resolve()));

	new AgentBuilder.Default()
			.with(AgentBuilder.Listener.StreamWriting.toSystemError())
			.ignore(nameStartsWith("net.bytebuddy."))
			.enableBootstrapInjection(inst, temp)
			.type(ElementMatchers.nameContains("java.net."))
			.transform((builder, typeDescription, classLoader, module) ->
					builder.method(any()).intercept(MethodDelegation.to(MyInterceptor.class)))
			.installOn(inst);
}

public static class MyInterceptor {

	@RuntimeType
	public static Object intercept(@Origin Method method, @SuperCall Callable<?> zuper) throws Exception {
		System.out.println("Intercepted >> " + method.toGenericString());
		return zuper.call();
	}
}
```
Kind Regards, Nick

**Comment by raphw** [comment]
You probably want to match all non-abstract methods: `method(not(isAbstract()))`. Otherwise, Byte Buddy requires an original implementation due to `@SuperCall`.

I would however recommend you to not use a `MethodDelegation` when instrumenting bootstrap classes. Rather use the `Advice` component, the JVM might not resolve added methods correctly.  It also saves you from the bootstrap injection.

**Comment by nickgrealy** [comment]
Thanks @raphw, I've had a play with the `ElementMatchers`, and updated the example to use `Advice`. I've now got the following code catching all(?) possible pointcuts - very nice 🍻 ! (thanks)

**A few questions:**

1. Is the below code your preferred/suggested way of "capturing all possible pointcuts", or is there a better way?
2. Further to the original issue, I've found that if any Interceptor's method signatures don't match the targeted method 100%, bytebuddy is very unforgiving - it will log an error (only if configured), the error tends to be rather cryptic IMO (e.g. `Cannot represent static ... as given method constant`) and **no** interceptors will execute (even the correctly configured ones)
    1. is there a way to make bytebuddy still run the interceptors that do match?
    2. is there a way to make bytebuddy more lenient in it's method signature matching? (e.g. `@Advice.This(optional = false) Object thiz` still threw errors for the `Static`/`Initializer`/`ConstructorInterceptors` (error logged/thrown when `thiz` was used in the method - see stacktrace below))

Ideally, I'd love to provide a single Interceptor method, and have only the parameters relevant to the method/constructor/static/initializer under advice, populated (non-relevant params are simply null).

**Here's the updated code:**

```Java
public static void main(String[] args) throws Exception {
	premain(null, ByteBuddyAgent.install());
	HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
	System.out.println(urlConnection.getResponseCode());
}

public static void premain(String arg, Instrumentation inst) throws Exception {
	new AgentBuilder.Default()
			// .with(AgentBuilder.Listener.StreamWriting.toSystemError())
			.ignore(nameStartsWith("net.bytebuddy."))
			.type(ElementMatchers.nameContains("java.net."))
			.transform((builder, td, cl, m) -> builder.visit(Advice.to(MyGeneralInterceptor.class).on(not(isStatic()).and(not(isConstructor())))))
			.transform((builder, td, cl, m) -> builder.visit(Advice.to(MyStaticInterceptor.class).on(isStatic().and(not(isTypeInitializer())).and(not(isConstructor())))))
			.transform((builder, td, cl, m) -> builder.visit(Advice.to(MyInitializerInterceptor.class).on(isTypeInitializer())))
			.transform((builder, td, cl, m) -> builder.visit(Advice.to(MyConstructorInterceptor.class).on(isConstructor())))
			.installOn(inst);
}

public static class MyGeneralInterceptor {
	@Advice.OnMethodEnter
	public static void enter(@Advice.Origin Method method, @Advice.This Object thiz) {
		System.out.println("Intercepted Normal >> " + method);
	}
}

public static class MyStaticInterceptor {
	@Advice.OnMethodEnter
	public static void enter(@Advice.Origin Method method) {
		System.out.println("Intercepted Static >> " + method);
	}
}

public static class MyInitializerInterceptor {
	@Advice.OnMethodEnter
	public static void enter(@Advice.Origin("#t.#m") String method) {
		System.out.println("Intercepted Initia >> " + method);
	}
}

public static class MyConstructorInterceptor {
	@Advice.OnMethodEnter
	public static void enter(@Advice.Origin Constructor method) {
		System.out.println("Intercepted Constr >> " + method);
	}
}
```

**Error on optional `thiz` usage:**

```
java.lang.NullPointerException
	at net.bytebuddy.implementation.bytecode.constant.DefaultValue.of(DefaultValue.java:66)
	at net.bytebuddy.asm.Advice$Dispatcher$OffsetMapping$Target$ForDefaultValue.resolveRead(Advice.java:1742)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$CodeTranslationVisitor.visitVarInsn(Advice.java:5504)
	at net.bytebuddy.jar.asm.MethodVisitor.visitVarInsn(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.doApply(Advice.java:4764)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter$AdviceMethodInliner.apply(Advice.java:5088)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:6545)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:34)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:47)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2910)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1628)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8128)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:8520)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8483)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:8270)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8829)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:8779)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:8409)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.net.Socket.getInputStream(Socket.java:911)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:642)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
```

**Comment by raphw** [comment]
You have found a bug when resolving optional `this` parameters. I just fixed that bug on master. My unit tests did not capture this as the instrumented type's declaring type and the methods declaring type was accidentally identical.

 As for creating a general interceptor, you can use the Java 8 `Executable` abstraction to capture both `Constructor` and `Method` objects. For static initializers, you do however need to fallback to a `String` as the JVM does not offer a constant to represent initializers. Alternatively, you can offer two advice classes as before and add a conditional advice specification as you do currently.

I already fixed the bug on the master branch. Consider using JITPack if it stops you from progressing. The fix will be part of the next release.
