### ISSUE TITLE
question about error Exception in thread "main" java.lang.IllegalStateException: Duplicate field definition

### ISSUE THREAD

**Issue by publicocean0** [raphw/byte-buddy#287]
Hi i have a exception and i dont know hot to solve. 
I have  a class A. 
I might intercept setters, getters. In addition it might implement additional abstract method Id().

My first problem is how to route to the right interceptor method. 

Exception in thread "main" java.lang.IllegalStateException: Duplicate field definition for public static com.itiboss.tests.Interceptor com.itiboss.tests.A$ByteBuddy$3r0jzLil.delegate$efcs330
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:817)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:465)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:162)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:155)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2662)
	at com.itiboss.tests.Test2.a(Test2.java:54)
	at com.itiboss.tests.Test2.main(Test2.java:61)
```

public class Interceptor {
		    ID id;
		public ID id() {
			return id;
		}
		public void setters(@This Object thiz,@Origin Method method,@AllArguments Object... args) {
			System.out.println(thiz+" "+method+args); 
		}
	    @RuntimeType
		public Object getters(@This Object thiz,@Origin Method method,@SuperCall Callable<?> zuper) throws Exception {
			System.out.println(thiz+" "+method);
			return zuper.call();
		}
	}

	public Class generateClass() {
		Interceptor i=new Interceptor(args...);
		return new ByteBuddy().subclass(A.class).implement(IExtendedA.class)
					.method(ElementMatchers.isGetter()).intercept(MethodDelegation.withEmptyConfiguration()
                        .withBinders(TargetMethodAnnotationDrivenBinder.ParameterBinder.DEFAULTS)
                        .withResolvers(MethodNameEqualityResolver.INSTANCE, BindingPriority.Resolver.INSTANCE)
                        .filter(ElementMatchers.named("setters")).to(i))
				.method(ElementMatchers.isGetter()).intercept(MethodDelegation.withEmptyConfiguration()
                        .withBinders(TargetMethodAnnotationDrivenBinder.ParameterBinder.DEFAULTS)
                        .withResolvers(MethodNameEqualityResolver.INSTANCE, BindingPriority.Resolver.INSTANCE)
                        .filter(ElementMatchers.named("getters")).to(i))
				.method(ElementMatchers.isSetter()).intercept(MethodDelegation.to(i)).make().load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER).getLoaded();

	}

```

**Comment by raphw** [comment]
By specifying delegation by `.to(i)`, Byte Buddy needs to compute a determinate field name as you do not provide one. The name is derived from the hash value of the delegate. As you use different configuration, Byte Buddy does not treat the delegators as equal while the value is. Provide an explicit field name or use a `toField` delegation whilst providing the value manually to avoid this. Look at the overloaded delegation types provided by `MethodDelegation`.
