### ISSUE TITLE
java.lang.IllegalStateException: size = 0 with option LambdaInstrumentationStrategy

### ISSUE THREAD

**Issue by gunlee01** [raphw/byte-buddy#289]
Hi.
I have a problem with the option `LambdaInstrumentationStrategy`.
How can I solve it?

I tested the byte-buddy version 1.6.9 and 1.6.12 but the situation is the same.
I think this error is occurred when a lambda expression is inferred as `Supplier`.

Thank you all.

## error stack 1
```
java.lang.IllegalStateException: size = 0
	at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108) ~[na:na]
	at net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory$LambdaMethodImplementation.appender(AgentBuilder.java:5927) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:199) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:175) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:672) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:163) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:155) ~[na:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560) ~[na:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2662) ~[na:na]
	at net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory.make(AgentBuilder.java:5751) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at net.bytebuddy.agent.builder.LambdaFactory.invoke(LambdaFactory.java:163) ~[na:na]
	at net.bytebuddy.agent.builder.LambdaFactory.make(LambdaFactory.java:204) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java) ~[na:1.8.0_25]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:289) ~[na:1.8.0_25]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:296) ~[na:1.8.0_25]
	at java.util.stream.FindOps.makeRef(FindOps.java:58) ~[na:1.8.0_25]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_25]
	at org.springframework.http.MediaTypeFactory.getMediaType(MediaTypeFactory.java:118) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.accept.PathExtensionContentNegotiationStrategy.getMediaTypeForResource(PathExtensionContentNegotiationStrategy.java:158) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.accept.ServletPathExtensionContentNegotiationStrategy.getMediaTypeForResource(ServletPathExtensionContentNegotiationStrategy.java:106) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.getMediaType(ResourceHttpRequestHandler.java:515) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:348) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:964) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:856) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841) ~[spring-webmvc-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1441) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.12.jar:8.5.12]
```

## code occurring the exception above
```java
@GetMapping("exToList")
        public String exToList() {
            List<Foo> fooList = new ArrayList<>();
            fooList.add(new Foo("a", 1));
            fooList.add(new Foo("b", 2));
            fooList.add(new Foo("c", 3));
            fooList.add(new Foo("d", 4));
            fooList.add(new Foo("e", 5));
            fooList.add(new Foo("f", 6));

            List<Foo> foo2List = fooList.stream().skip(2).limit(3).collect(Collectors.toList());

            System.out.println(foo2List);

            return foo2List.toString();
        }
```

## error stack 2 (another case)
```
java.lang.IllegalStateException: size = 0
	at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108) ~[na:na]
	at net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory$LambdaMethodImplementation.appender(AgentBuilder.java:5927) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:199) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:175) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:672) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:163) ~[na:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:155) ~[na:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560) ~[na:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2662) ~[na:na]
	at net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory.make(AgentBuilder.java:5751) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at net.bytebuddy.agent.builder.LambdaFactory.invoke(LambdaFactory.java:163) ~[na:na]
	at net.bytebuddy.agent.builder.LambdaFactory.make(LambdaFactory.java:204) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java) ~[na:1.8.0_25]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:289) ~[na:1.8.0_25]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:296) ~[na:1.8.0_25]
	at java.util.stream.FindOps.makeRef(FindOps.java:58) ~[na:1.8.0_25]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_25]
	at org.springframework.http.MediaTypeFactory.getMediaType(MediaTypeFactory.java:118) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.accept.PathExtensionContentNegotiationStrategy.getMediaTypeForResource(PathExtensionContentNegotiationStrategy.java:158) ~[spring-web-5.0.0.BUILD-20170324.220352-22.jar:5.0.0.BUILD-SNAPSHOT]
...
...
```

### The error occurs when doing with 'Supplier'
```
[scouter bytebuddy before getBytes] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;
[scouter lambda hook] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;

[scouter bytebuddy before getBytes] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;
[scouter lambda hook] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;

[scouter bytebuddy before getBytes] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;
[scouter lambda hook] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;

[scouter bytebuddy before getBytes] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;
[scouter lambda hook] compare - (Ljava/lang/Object;Ljava/lang/Object;)I - get$Lambda - ()Ljava/util/Comparator;

[scouter bytebuddy before getBytes] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;
[scouter lambda hook] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;

[scouter bytebuddy before getBytes] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;
[scouter lambda hook] queryFrom - (Ljava/time/temporal/TemporalAccessor;)Ljava/lang/Object; - get$Lambda - ()Ljava/time/temporal/TemporalQuery;

[scouter bytebuddy before getBytes] get - ()Ljava/lang/Object; - get$Lambda - ()Ljava/util/function/Supplier;

java.lang.IllegalStateException: size = 0
	at scouter.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108) ~[na:na]
	at scouter.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory$LambdaMethodImplementation.appender(AgentBuilder.java:6919) ~[na:na]
	at scouter.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:218) ~[na:na]
	at scouter.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:196) ~[na:na]
	at scouter.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:766) ~[na:na]
	at scouter.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:87) ~[na:na]
	at scouter.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:82) ~[na:na]
	at scouter.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2621) ~[na:na]
	at scouter.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2722) ~[na:na]
	at scouter.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory.make(AgentBuilder.java:6678) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at scouter.bytebuddy.agent.builder.LambdaFactory.invoke(LambdaFactory.java:128) ~[na:na]
	at scouter.bytebuddy.agent.builder.LambdaFactory.make(LambdaFactory.java:152) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java) ~[na:1.8.0_25]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:289) ~[na:1.8.0_25]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:296) ~[na:1.8.0_25]
	at java.util.stream.Collectors.toList(Collectors.java:230) ~[na:1.8.0_25]
	at gunlee.example.servlet.async3.MyApp3$ExController.exToList(MyApp3.java:45) ~[classes/:na]
```
## the code logging (AgentBuilder class)
```java
                System.out.println("[scouter bytebuddy before getBytes] "
                        + lambdaMethodName + " - "
                        + lambdaMethod.getDescriptor() + " - "
                        + LAMBDA_FACTORY + " - "
                        + factoryMethod.getDescriptor()
                );
                byte[] classFile = builder.make().getBytes();
                
                for (ClassFileTransformer classFileTransformer : classFileTransformers) {
                    try {
                        byte[] transformedClassFile = classFileTransformer.transform(targetType.getClassLoader(), lambdaClassName.replace('.', '/'), NOT_PREVIOUSLY_DEFINED, targetType.getProtectionDomain(), classFile);
                        classFile = transformedClassFile == null ? classFile : transformedClassFile;
                    } catch (Throwable ignored) {
                    }
                }

                System.out.println("[scouter lambda hook] "
                        + lambdaMethodName + " - "
                        + lambdaMethod.getDescriptor() + " - "
                        + LAMBDA_FACTORY + " - "
                        + factoryMethod.getDescriptor()
```

**Comment by raphw** [comment]
Seems like a bug.

Just FYI, with Java 9, instrumenting lambda expressions will most likely no longer work as the mechanism gets restricted.

**Comment by gunlee01** [comment]
Hi. @raphw 

Java 9. It's very unhappy news. 
I saw your mail threads about lambda expression implementation.
I think that java must provide useful way to instrument lambda expression.

Good job.

**Comment by raphw** [comment]
Seems like this is related to a lambda expression that references a constructor as a method reference such as `Collectors.toList()`. Should be an easy fix.

**Comment by raphw** [comment]
Fixed on master.
