### ISSUE TITLE
Java 9 compatibility 

### ISSUE THREAD

**Issue by GotoFinal** [raphw/byte-buddy#295]
Seems that between build 153 and 166 of jdk 9 (jigsaw) something changed as byte-buddy (version `1.6.13`) fails to inject:
(also package of Module class was changed, not sure if this is already updated, from `java.lang.reflect.Module` to `java.lang.Module`)
```
[01:55:10 WARN]: Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@f15400bb
[01:55:10 WARN]: 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:366)
[01:55:10 WARN]: 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:332)
[01:55:10 WARN]: 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:300)
[01:55:10 WARN]: 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:286)
[01:55:10 WARN]: 	at org.diorite.inject.Injection.<clinit>(Injection.java:40)
[01:55:10 WARN]: 	... 3 more
[01:55:10 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[01:55:10 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:55:10 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:55:10 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:55:10 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:563)
[01:55:10 WARN]: 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:353)
[01:55:10 WARN]: 	... 7 more
[01:55:10 WARN]: Caused by: java.io.IOException: Can not attach to current VM
[01:55:10 WARN]: 	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
[01:55:10 WARN]: 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:48)
[01:55:10 WARN]: 	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
[01:55:10 WARN]: 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
[01:55:10 WARN]: 	... 12 more
```

**Comment by GotoFinal** [comment]
After some small debug, seems that oracle blocked attach for this same VM by default.... and there need to be special flag to allow this.

// class HotSpotVirtualMachine
```java
    private static final boolean ALLOW_ATTACH_SELF;
// some code
    static {
        String s = VM.getSavedProperty("jdk.attach.allowAttachSelf");
        ALLOW_ATTACH_SELF = (s != null) && !"false".equals(s);
    }
    // some code
        if (!ALLOW_ATTACH_SELF && (pid == 0 || pid == CURRENT_PID)) {
            throw new IOException("Can not attach to current VM");
        }
```

**Comment by raphw** [comment]
Hi, thanks for reporting this. Adding this flag was discussed on the mailing list but was discarded as a bad idea for Java 9 to be set to true by default. I expect this flag to not be set in future releases.

Then again, this hack is not too bad to offer as an attempt to make the installation process work out of the box. For many users, this might just work at least for test environments where this is intended. I do however consider to just start a new VM process to attach the agent from there. Its a bit of a dirty hack but the whole self-attachment is a bit tricky to begin with, despite its usefulness.

**Comment by GotoFinal** [comment]
but it isn't also perfect, if other code will load `HotSpotVirtualMachine` before you will change this flag it will fail ;/

You might try to use other VM to attach agent and remove that check in `HotSpotVirtualMachine` so then you can again use it from this same VM. (I did not test if that will work)

**Comment by raphw** [comment]
I will check the source to see if there is a way around, therefore I think that I will go for the "secondary VM hack" to ease the migration for test frameworks that rely on this feature. Long term, people will probably need to set the flag but there needs to be a short-time solution that is less disruptive.

**Comment by raphw** [comment]
`ByteBuddyAgent.install()` does now detect Java 9 VMs where self-attachment is forbidden and creates a helper process to attach from there. This was already added to master and will be included in the next release.
