### ISSUE TITLE
Supplying ByteBuddy agent as command line parameter for Tomcat 8 fails to start up

### ISSUE THREAD

**Issue by rDarge** [raphw/byte-buddy#309]
I'm using Apache Tomcat 8.5.11 with jdk 1.8.0_121

I'm trying to get my Agent working with my web application, but every time I start the Tomcat server, it immediately crashes with the following exception: 
```
02-Jun-2017 16:58:38.945 SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw error
 java.lang.ExceptionInInitializerError
	at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.<clinit>(GlobalResourcesLifecycleListener.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1190)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1458)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:578)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:629)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494)
Caused by: java.lang.NullPointerException
	at org.apache.tomcat.util.modeler.Registry.loadDescriptors(Registry.java:660)
	at org.apache.catalina.mbeans.MBeanUtils.createRegistry(MBeanUtils.java:546)
	at org.apache.catalina.mbeans.MBeanUtils.<clinit>(MBeanUtils.java:71)
	... 28 more

java.lang.ExceptionInInitializerError
	at org.apache.catalina.mbeans.GlobalResourcesLifecycleListener.<clinit>(GlobalResourcesLifecycleListener.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:117)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1190)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1458)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:578)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:629)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494)
Caused by: java.lang.NullPointerException
	at org.apache.tomcat.util.modeler.Registry.loadDescriptors(Registry.java:660)
	at org.apache.catalina.mbeans.MBeanUtils.createRegistry(MBeanUtils.java:546)
	at org.apache.catalina.mbeans.MBeanUtils.<clinit>(MBeanUtils.java:71)
	... 28 more
```

I've debugged to the area throwing the exception and found that the ClassLoader used to try and retrieve the MBeanUtil class is resolved as null

```
/**
     * Create and configure (if necessary) and return the registry of
     * managed object descriptions.
     * @return the singleton registry
     */
    public static synchronized Registry createRegistry() {

        if (registry == null) {
            registry = Registry.getRegistry(null, null);
            ClassLoader cl = MBeanUtils.class.getClassLoader(); //Resolves to null, bad time later
```

My command line argument looks like this:

`-javaagent:C:\myapp\build\libs\my-agent.jar`

My agent class looks like this: 

```
public class TraceAgent {

    public static void premain(String arg, Instrumentation instrumentation) {
        System.out.println("Test");
        new AgentBuilder.Default()
                .type(ElementMatchers.isSubTypeOf(Game.class))
                .transform((builder, typeDescription, classloader, module) -> builder.method(ElementMatchers.any())
                        .intercept(MethodDelegation.to(GameInterceptor.class)
                                .andThen(SuperMethodCall.INSTANCE)))
            .installOn(instrumentation);
    }
}
```

and GameInterceptor looks like this:

```
public class GameInterceptor {
    private static final Logger LOG = LoggerFactory.getLogger(GameInterceptor.class);

    private static final String DELIMITER = ", ";

    public static void logGameChanged(@Origin Method method) {
        String output = new StringJoiner(DELIMITER)
                .add(method.getClass().getCanonicalName())
                .add(method.getName())
                .toString();
        LOG.trace(output);
    }
}
```

My jar manifest looks like this:

```
Manifest-Version: 1.0
Implementation-Title: ClassLogger
Premain-Class: com.adventureRancher.trace.TraceAgent
Implementation-Version: 1
Can-Redefine-Classes: true
Can-Retransform-Classes: true
Can-Set-Native-Method-Prefix: true
Boot-Class-Path: /apache-tomcat-8.5.11/bin/bootstrap.jar /apache-tomca
 t-8.5.11/bin/tomcat-juli.jar my-agent.jar
```
and the jar includes the sources to the Game classes and dependencies.

I'm running out of ideas as to what I can do to fix this, do you have any suggestions? 

Thank you for your help, you rock

**Comment by raphw** [comment]
Have you tried using Advice rather than a MethodDelegation? Tomcat is sometimes difficult with respect to class loaders.

**Comment by rDarge** [comment]
I haven't tried that, but I have tried commenting out my new AgentBuilder() code just leaving my System.out.println call (with no method delegations) to ensure that the agent was loading, and I still get the same error.

**Comment by rDarge** [comment]
I think I figured it out - I'm using the following gradle code to build my agent's JAR file:

```
task fatJar(type: Jar) {
    zip64 true
    archiveName = "${rootProject.name}-trace-agent.jar"
    manifest {
        attributes(
                'Premain-Class': 'com.adventureRancher.trace.TraceAgent',
                'Boot-Class-Path': "/apache-tomcat-8.5.11/bin/bootstrap.jar /apache-tomcat-8.5.11/bin/tomcat-juli.jar ${rootProject.name}-trace-agent.jar",
                'Can-Redefine-Classes': 'true',
                'Can-Retransform-Classes': 'true',
                'Can-Set-Native-Method-Prefix': 'true',
                'Implementation-Title': "ClassLogger",
                'Implementation-Version': rootProject.version
        )
    }

    from {
//        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    } with jar
}
```

The line I commented out was pulling in some necessary dependencies for my interceptor, particularly my Game class and my SLF4J libraries. Unfortunately, it also pulled in some of the Tomcat libraries including MBeanUtils, which is probably why Tomcat cannot resolve the ClassLoader normally in it's native code.

I'm not sure how to pare down the configurations quite yet, but I'll be looking into that more next.

**Comment by raphw** [comment]
Glad you figured it out!

**Comment by raphw** [comment]
FYI: https://stackoverflow.com/questions/2928548/make-mavens-surefire-show-stacktrace-in-console
