### ISSUE TITLE
Why can't add interceptor for  dynamic implement interface?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#316]
First, I run a simple demo by the `FixedValue`, you provided, it works.
```java
newClassBuilder = newClassBuilder.defineField(CONTEXT_ATTR_NAME, Object.class, ACC_PRIVATE)
            .implement(EnhancedInstance.class)
            .method(named("_getSkyWalkingDynamicFiled"))
                .intercept(FixedValue.nullValue());
```

But when I use my own interceptor, it fails
```java
        newClassBuilder = newClassBuilder.defineField(CONTEXT_ATTR_NAME, Object.class, ACC_PRIVATE)
            .implement(EnhancedInstance.class)
            .method(named("_getSkyWalkingDynamicFiled"))
            .intercept(MethodDelegation.withDefaultConfiguration()
                    .withBinders(
                        FieldProxy.Binder.install(FieldGetter.class, FieldSetter.class)
                    )
                    .to(EnhancedInstanceFieldGetter.class));


public class EnhancedInstanceFieldGetter {
    @RuntimeType
    public Object intercept(
            @FieldProxy(ClassEnhancePluginDefine.CONTEXT_ATTR_NAME) FieldGetter dynamicFieldGetter) {
        return dynamicFieldGetter.getValue();
    }
}
```

The error logs:
```
java.lang.IllegalArgumentException: None of [] allows for delegation from public abstract java.lang.Object org.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance._getSkyWalkingDynamicFiled()
	at org.skywalking.apm.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:829)
	at org.skywalking.apm.dependencies.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1034)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:620)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:609)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:526)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor.visitEnd(TypeWriter.java:3854)
	at org.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at org.skywalking.apm.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8902)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9303)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9266)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9044)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9622)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9572)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9191)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by wu-sheng** [comment]
Found a way out. Can you confirm is this the right way? @raphw 
```java
        /**
         * alter class source code.<br/>
         *
         * new class need:<br/>
         * 1.Add field, name {@link #CONTEXT_ATTR_NAME}.
         * 2.Add a field accessor for this field.
         *
         */
        newClassBuilder = newClassBuilder.defineField(CONTEXT_ATTR_NAME, Object.class, ACC_PRIVATE)
            .implement(EnhancedInstance.class)
            .intercept(FieldAccessor.ofField(CONTEXT_ATTR_NAME));
```

**Comment by raphw** [comment]
Yes, this is a shortcut for defining an interceptor for all methods that are declared by this interface (but not already overridden by the subclass if any).

**Comment by geektcp** [comment]
@wu-sheng bytebuddy 支持拦截一个接口的实现类吗？
