### ISSUE TITLE
"java.lang.VerifyError: Inconsistent stackmap frames at branch target" with passing array to vararg constructor

### ISSUE THREAD

**Issue by KnutHR** [raphw/byte-buddy#318]
This happens only under some combination of conditions. I have 2 independent lines of code, just 1 of the lines don't trigger the issue, but including both does. Seems Object[][] and Object[] is being confused.

```
public class FlexiKey {
	public Object[] objects;
	public FlexiKey(Object ... args) {
		objects = args;
	}
}

...
public static<K,V> Map<K,V> executeMap(...) {
	...
	for(Object[] o1 : queryResults) {
		...
		Object[] keys = new Object[keyCount];
		...
		//Object test = new FlexiKey(keys);				// a) error in combo with b)

		//K key = keyCount > 1 ? (K)new FlexiKey(o1[0]) : (K)keys[0];	// b) not error

		//K key = keyCount > 1 ? (K)new FlexiKey(keys) : (K)keys[0];	// c) this line causes the issue individually
		...
	}
...
}
```

```
Underlying exception : java.lang.IllegalArgumentException: Could not create type
	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:107)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:55)
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:82)
	... 30 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:140)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
	at org.powermock.api.mockito.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:50)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:116)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:69)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:46)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:192)
	... 33 more
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 1007
Exception Details:
  Location:
    no/.../DatabaseComponent.executeMap(Lno/.../DynamicQuery;Z)Ljava/util/Map; @1007: iload
  Reason:
    Type '[Ljava/lang/Object;' (current frame, locals[10]) is not assignable to '[[Ljava/lang/Object;' (stack map, locals[10])
  Current Frame:
    bci: @937
    flags: { }
    locals: { 'no/.../DynamicQuery', integer, '[Z', '[[Ljava/lang/Object;', 'java/util/HashMap', '[Ljava/lang/Object;', integer, integer, '[[Ljava/lang/Object;', integer, '[Ljava/lang/Object;', integer, top, 'java/lang/Object', top, top, 'java/lang/Object' }
    stack: { }
  Stackmap Frame:
    bci: @1007
    flags: { }
    locals: { 'no/.../DynamicQuery', integer, '[Z', '[[Ljava/lang/Object;', 'java/util/HashMap', '[Ljava/lang/Object;', integer, integer, '[[Ljava/lang/Object;', integer, '[[Ljava/lang/Object;', integer, top, 'java/lang/Object', top, top, 'java/lang/Object' }
    stack: { }
  Bytecode:
    0x0000000: b80d 3f4d 12da b800 dd13 0670 05bd 0004
    0x0000010: 5903 2a53 5904 0000 0000 1b36 0e01 3a0d
    0x0000020: 013a 0f12 6db8 0036 04bd 0004 5903 bb00
    0x0000030: 1659 150e b700 7053 1272 b800 3cb8 0042
    0x0000040: 3a10 1910 b200 46a5 0044 1910 c100 4899
    0x0000050: 0026 b800 4e12 6db8 0036 1204 01b6 0054
    0x0000060: b600 5801 b600 5cc0 0016 3a0f 2c11 0dfc
    0x0000070: 0454 a700 1019 10c0 0016 3a0f 2c11 0dfd
    0x0000080: 0454 2c11 0dfe 0454 a700 14bb 0016 5915
    0x0000090: 0eb7 0070 3a0f 2c11 0dff 0454 190f 5313
    0x00000a0: 0672 b800 3c13 019e b800 e64e 2d01 3a0d
    0x00000b0: 013a 0e19 0d12 e8b8 00dd 12e9 12ea b800
    0x00000c0: 36b8 00ee 3a0f 190f b200 46a6 0011 b200
...
```

**Comment by raphw** [comment]
Does this happen with PowerMock? Maybe its an error in their code. Can you create a reproduction of this issue?

**Comment by raphw** [comment]
I am closing the issue. If you can provide more information, I am happy to open it again.

**Comment by KnutHaraldR** [comment]
From what I remember, this was an issue with Powermock and using certain names like start/end, if you named your methods the same as internal Powermock names, it got this error.
