### ISSUE TITLE
TypeDescription.Latent missing override?

### ISSUE THREAD

**Issue by kaeluka** [raphw/byte-buddy#320]
I asked a question on stackoverflow (https://stackoverflow.com/questions/44870944/byte-buddy-generate-classes-with-cyclic-types) about generating classes that use each other's types.

The suggested workaround -- until a fix is released -- was to subclass TypeDescription.Latent, overriding two methods. A fix is, AFAICT, already committed (0e032447feeba29a0331e1815c3c8fb2a8f4fb5f)

This I ran into a similar problem today. What I tried to do was to generate a class that uses *its own* type internally, again using `Latent`.

A minimal example of the problem is trying to generate a class like this one:

```
final class A { public A next; }
```
My attempt to do that looks like this:

```
package some.package;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.annotation.AnnotationList;
import net.bytebuddy.description.modifier.ModifierContributor;
import net.bytebuddy.description.modifier.TypeManifestation;
import net.bytebuddy.description.modifier.Visibility;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.jar.asm.Opcodes;

import java.util.LinkedList;
import java.util.List;

class TypeDescrFix extends TypeDescription.Latent {
    TypeDescrFix(final String name, final int modifiers, final Generic superClass, final List<? extends Generic> interfaces) {
        super(name, modifiers, superClass, interfaces);
    }

    @Override
    public int getSegmentCount() {
        return 0;
    }

    @Override
    public TypeDescription getDeclaringType() {
        return null;
    }

    @Override
    public AnnotationList getDeclaredAnnotations() {
        return new AnnotationList.Empty();
    }
}

public class ByteBuddyHello {

    public static void main(String[] args) {
        try {
            final ByteBuddy bb = new ByteBuddy();
            final TypeDescription.Latent typeDescrA = new TypeDescrFix("A", 0, null, new LinkedList<TypeDescription.Generic>());
            final Object a = bb
                    .subclass(Object.class)
                    .name("A")
                    .modifiers(ModifierContributor.Resolver.of(Visibility.PUBLIC, TypeManifestation.FINAL).resolve())
                    .defineField("next", typeDescrA, Opcodes.ACC_PUBLIC)
                    .make()
                    .load(ByteBuddyHello.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                    .getLoaded().newInstance();
            System.out.println(a.toString());
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }
}
```

If I run this, I get the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: Cannot resolve declared type of a latent type description: class A
	at net.bytebuddy.description.type.TypeDescription$Latent.getDeclaringType(TypeDescription.java:7613)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType$ForErasure.getOwnerType(TypeDescription.java:3529)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForDetachment.onSimpleType(TypeDescription.java:1743)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onNonGenericType(TypeDescription.java:1580)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForDetachment.onNonGenericType(TypeDescription.java:1708)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3364)
	at net.bytebuddy.description.field.FieldDescription$Token.accept(FieldDescription.java:486)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.withField(InstrumentedType.java:456)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Adapter$FieldDefinitionAdapter.materialize(DynamicType.java:3159)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2661)
	at some.package.playground.ByteBuddyHello.main(ByteBuddyHello.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

The `TypeDescrFix` class is the workaround suggested on stackoverflow. I found a workaround for this specific instance, by also overriding `getDeclaringType` to return `null`. In the minimal example above, the crash goes away if I comment out the override in the `TypeDescrFix` class. This works for me, but it may not be a good solution -- it might break some specifications that I'm not aware of. AFAICT, the recent fix (0e032447feeba29a0331e1815c3c8fb2a8f4fb5f) does not override the method accordingly.

**Comment by raphw** [comment]
You are right, I need to assure that the latent type description does not define a declaring type. All in all, the `TypeDescription.Latent` use is a bit of a hack. I start consider to remove it alltogether.

Better, you are using `InstrumentedType.Default` which has a factory for creating such a type.

**Comment by raphw** [comment]
I decided to not extend the latent type description which was not really intended for such use. Rather construct an `InstrumentedType` which is itself a `TypeDescription` and offers a convenient builder API for describing any type.
