### ISSUE TITLE
Trouble instrumenting java.io.File constructor

### ISSUE THREAD

**Issue by ChaosData** [raphw/byte-buddy#324]
Hi,

I seem to be running into issues when attempting to intercept a `java.io.File` constructor with both the `AgentBuilder` and normal `ByteBuddy` APIs. In the case of the former, it doesn't appear to find the class at all, and with the latter I get some cryptic exceptions. For reference, I'm using Byte Buddy `1.7.1`.

```Java
@Advice.OnMethodEnter
static void enter(@Advice.This File self, @Advice.Argument(value = 0) String path) {    
  System.out.println("file constructor called!");
}
```

```Java
AsmVisitorWrapper getVisitor() {
  try {
    return Advice.to(this.getClass()).on(
      ElementMatchers.is(File.class.getConstructor(String.class))
    );
  } catch (Throwable t) {
    t.printStackTrace();
    return null;
  }
}
```

```Java
      AsmVisitorWrapper visitor = this.getVisitor();
      if (visitor == null) {
        return;
      }

      new AgentBuilder.Default()
      .disableClassFormatChanges()
      .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
      .ignore(ElementMatchers.none())
      .type(ElementMatchers.is(File.class))
      .transform((builder, _cl, _td, _mod) -> builder.visit(visitor))
      .installOnByteBuddyAgent();
```

```Java
      AsmVisitorWrapper visitor = this.getVisitor();
      if (visitor == null) {
        return;
      }

      new ByteBuddy()
      .with(Implementation.Context.Disabled.Factory.INSTANCE)
      .redefine(File.class)
      .visit(visitor)
      .make()
      .load(File.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
```

```
Caused by: java.lang.IllegalStateException: Cannot map this reference for static method or constructor start: public java.io.File(java.lang.String)
	at net.bytebuddy.asm.Advice$OffsetMapping$ForThisReference.resolve(Advice.java:1759)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.apply(Advice.java:5655)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:5414)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.doApply(Advice.java:5408)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter$AdviceMethodInliner.apply(Advice.java:5735)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:7201)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:34)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:47)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2559)
```

Do you have any ideas of what might be causing these behaviors?

Thanks.

**Comment by CodingFabian** [comment]
Advice.OnMethodEnter cannot reference Advice.This, this is documented in the Javadoc of Advice.This

It is also in the exception:
"Cannot map this reference for static method or constructor start"

At the beginning of the constructor "this" does not yet exist. it only works at the end of the constructor.

**Comment by raphw** [comment]
As Fabian states, what you are trying to do is not allowed by the VM. There is no way to reference `this` at the method entry.
