### ISSUE TITLE
Could not redefine interface method with custom type

### ISSUE THREAD

**Issue by dzebleckis** [raphw/byte-buddy#335]
Hello,

I might be missing something obvious, however it seems that there is a problem when redefining method withing interface. Suppose I do have classes 
```
package example;
public interface Model {

    default boolean get() {
        return false;
    }

}
```
```
      TypePool typePool = TypePool.Default.ofClassPath();

      new ByteBuddy(ClassFileVersion.JAVA_V8)
            .redefine(
                    typePool.describe("example.Model").resolve(),
                    ClassFileLocator.ForClassLoader.ofClassPath()

            )
            .method(named("get"))
            .intercept(FixedValue.value(false))
            .make()
            .load(ClassLoader.getSystemClassLoader());
 
```

then everything works ok, but if I change to

```
package example;
public interface Model {

    default ReturnType get() {
        return new ReturnType();
    }

}
```

```
package example;
public class ReturnType {
}
```

and 

```
        TypePool typePool = TypePool.Default.ofClassPath();

        new ByteBuddy(ClassFileVersion.JAVA_V8)
            .redefine(
                    typePool.describe("ru.lamoda.akka_openapi.Model").resolve(),
                    ClassFileLocator.ForClassLoader.ofClassPath()

            )
            .method(named("get"))
            .intercept(FixedValue.value(new ReturnType()))
            .make()
            .load(ClassLoader.getSystemClassLoader());

```

then i get exception 
```
Exception in thread "main" java.lang.IllegalStateException: Cannot only define public, static, final field 'value$qlo9th1' for interface type
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$ForInterface.assertField(TypeWriter.java:2225)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$Compound.assertField(TypeWriter.java:2565)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor.visitField(TypeWriter.java:1885)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$FieldPool$Record$ForImplicitField.apply(TypeWriter.java:187)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor.visitEnd(TypeWriter.java:3851)
[error] 	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
[error] 	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
[error] 	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
[error] 	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
[error] 	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
[error] 	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2559)
[error] 	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2661)
[error] 	at ru.lamoda.akka_openapi.TestMain.main(TestMain.java:25)
```

I've tried to use `InvocationHandlerAdapter.of(...).withoutMethodCache()` but that didn't helped, is there is any workaround to disable field creation?

**Comment by raphw** [comment]
When you use `FixedValue.value(new ReturnType())`, Byte Buddy has to add a field to store this value in the transformed class. The problem is that an interface cannot contain such a field which must be non-final as Byte Buddy needs to assign after the class loading.

If you really want to do return the value, you could use a `MethodDelegation` to a static method that returns this instance somehow. This way, the reference is fetched from somewhere else without the interface requiring the addition of a non-final field.
