### ISSUE TITLE
The method with two same Exception!

### ISSUE THREAD

**Issue by IluckySi** [raphw/byte-buddy#347]
**Hi, My friends:**
**When I use byte-buddy for com.googlecode.xmemcached, I find a exception:**
```
java.lang.IllegalStateException: Duplicate exception type class net.rubyeye.xmemcached.exception.MemcachedException for private final java.lang.Object net.rubyeye.xmemcached.XMemcachedClient.fetch0(java.lang.String,byte[],net.rubyeye.xmemcached.command.CommandType,long,net.rubyeye.xmemcached.transcoders.Transcoder) throws java.lang.InterruptedException,java.util.concurrent.TimeoutException,net.rubyeye.xmemcached.exception.MemcachedException,net.rubyeye.xmemcached.exception.MemcachedException
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:950)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:465)
	at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:176)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8905)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
```

**The following is the XmemcachedClient Code:**, the fetch0 method has two same Exception:
```
private final <T> Object fetch0(final String key, final byte[] keyBytes,
			final CommandType cmdType, final long timeout,
			Transcoder<T> transcoder) throws InterruptedException,
			TimeoutException, MemcachedException, MemcachedException {
```

**I aso find the bytebuddy code:**, not allow a method have  same exception.
```
net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:950)
 Set<TypeDescription.Generic> exceptionTypes = new HashSet<Generic>();
                for (TypeDescription.Generic
 exceptionType : methodDescription.getExceptionTypes()) {
                    if (!exceptionTypes.add(exceptionType)) {
                        throw new IllegalStateException("Duplicate exception type " + exceptionType + " for " + methodDescription);
                    } else if (!exceptionType.accept(Generic.Visitor.Validator.EXCEPTION)) {
                        throw new IllegalStateException("Illegal exception type " + exceptionType + " for " + methodDescription);
                    } else if (!exceptionType.accept(Generic.Visitor.Validator.ForTypeAnnotations.INSTANCE)) {
                        throw new IllegalStateException("Illegal type annotations on " + exceptionType + " for " + methodDescription);
                    } else if (!methodDescription.isSynthetic() && !exceptionType.asErasure().isVisibleTo(this)) {
                        throw new IllegalStateException("Invisible exception type " + exceptionType + " for " + methodDescription);
                    }
                }
```
Can I have a best choice for this question? Thank you!

**Comment by wu-sheng** [comment]
Hi @raphw , this issue also comes from Skywalking APM team. Although the xmemcached team merged pr, but still many released versions have the same version. So, I sincerely hope you can provide a solution or patch to solve this. Thanks.

**Comment by raphw** [comment]
I wonder how they got this to happen, javac would not create such code. 

You can (and should) turn validation of in production systems. You can do so by: `new ByteBuddy().with(TypeValidation.DISABLED)`.

**Comment by wu-sheng** [comment]
This is from google xmemcached client library team. IMO, even you.write such codes, compiler should remove that for you. But actually it did't. strange, right?

**Comment by IluckySi** [comment]
@raphw  If I use new ByteBuddy().with(TypeValidation.DISABLED). bytebuddy will skip validate？ skip the following code？right？
 ```
Set<TypeDescription.Generic> exceptionTypes = new HashSet<Generic>();
                for (TypeDescription.Generic
 exceptionType : methodDescription.getExceptionTypes()) {
                    if (!exceptionTypes.add(exceptionType)) {
                        throw new IllegalStateException("Duplicate exception type " + exceptionType + " for " + methodDescription);
                    } else if (!exceptionType.accept(Generic.Visitor.Validator.EXCEPTION)) {
                        throw new IllegalStateException("Illegal exception type " + exceptionType + " for " + methodDescription);
                    } else if (!exceptionType.accept(Generic.Visitor.Validator.ForTypeAnnotations.INSTANCE)) {
                        throw new IllegalStateException("Illegal type annotations on " + exceptionType + " for " + methodDescription);
                    } else if (!methodDescription.isSynthetic() && !exceptionType.asErasure().isVisibleTo(this)) {
                        throw new IllegalStateException("Invisible exception type " + exceptionType + " for " + methodDescription);
                    }
                }
```

**Comment by raphw** [comment]
Yes.

**Comment by wu-sheng** [comment]
Hi @raphw , even I think this is not the right coding way. But I run a test, seem it is legal to do so.

Here is my sample code:
```
    @RequestMapping("/serviceA/rest")
    @ResponseBody
    String home() throws Exception, Exception {
        logger.info("Business service log in SpringController.home().");

        FrontSiteBusinessLogic dom = new FrontSiteBusinessLogic();
        return dom.callByOKHTTP3().toString();
    }
}
```

And I run `javap -v` for this class, here is a result:
```
  java.lang.String home() throws java.lang.Exception, java.lang.Exception;
    Code:
       0: getstatic     #2                  // Field logger:Lorg/apache/log4j/Logger;
       3: ldc           #3                  // String Business service log in SpringController.home().
       5: invokevirtual #4                  // Method org/apache/log4j/Logger.info:(Ljava/lang/Object;)V
       8: new           #5                  // class com/huawei/devcloud/demo/frontsite/FrontSiteBusinessLogic
      11: dup
      12: invokespecial #6                  // Method com/huawei/devcloud/demo/frontsite/FrontSiteBusinessLogic."<init>":()V
      15: astore_1
      16: aload_1
      17: invokevirtual #7                  // Method com/xxx/yyyyy/demo/frontsite/FrontSiteBusinessLogic.callByOKHTTP3:()Ljava/lang/String;
      20: invokevirtual #8                  // Method java/lang/String.toString:()Ljava/lang/String;
      23: areturn

```

You can see, compiler allowed duplicate exceptions in a singe method. So, IMHO, this should a bug. Can you fix this for us? Thanks.

**Comment by raphw** [comment]
You are right, I have fixed this on master and will include the fix in the next release. Thanks for reporting!
