### ISSUE TITLE
IllegalStateException: Invisible parameter type of kotlin.jvm.internal.DefaultConstructorMarker

### ISSUE THREAD

**Issue by henrik242** [raphw/byte-buddy#350]
I have a Kotlin class:
```
open class SomeClass(val cheese: String = "brie") {
    fun foo() = "bar"
}
```
... and a Spock test:
```
class SomeClassTest extends Specification {

    def "should be able to mock"() {
      given:
        def someMock = Mock(SomeClass)
        someMock.foo() >> "cheese"

      expect: "that we actually can mock it"
        someMock.cheese == "brie"
        someMock.foo() == "cheese"
    }
}
```
... using the following Gradle dependencies:
```
testCompile(
    "org.spockframework:spock-core:1.1-groovy-2.4",
    "net.bytebuddy:byte-buddy:1.7.5",
)
```
Running the test gives me:
```
java.lang.IllegalArgumentException: Could not create type

	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:140)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:108)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:65)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:51)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:296)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:286)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:105)
	at no.finn.travel.shared.common.kotlin.OpenTest.should be able to mock #subject(OpenTest.groovy:11)
Caused by: java.lang.IllegalStateException: Invisible parameter type of kotlin.jvm.internal.DefaultConstructorMarker arg2 for public no.finn.travel.shared.common.kotlin.SomeClass$SpockMock$bAkOnnH5(java.lang.String,int,kotlin.jvm.internal.DefaultConstructorMarker)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:925)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:465)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:162)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:155)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2639)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2741)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory$1.call(ProxyBasedMockFactory.java:113)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory$1.call(ProxyBasedMockFactory.java:110)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	... 13 more
```

The test works without the byte-buddy dependency.

**Comment by raphw** [comment]
Byte Buddy complains that the type is not visible to the proxy class and it probably is not. I will have another look at this but Spock should probably not run the validation in the first place to work around this issue.

**Comment by henrik242** [comment]
@raphw Cool! Would you like me to create a test project, or are you good?

**Comment by raphw** [comment]
If you find the time I will happily take it!

**Comment by henrik242** [comment]
@raphw Here you go: https://github.com/henrik242/kotlin-bytebuddy-spock

**Comment by henrik242** [comment]
@raphw  Any progress? :)

**Comment by raphw** [comment]
Its on my agenda and I hope to find some time next week!

**Comment by raphw** [comment]
This seems like a bug in Kotlin. Its compiler creates a synthetic constructor:
public synthetic <init>(Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;

The `DefaultConstructorMarker` type is package-private and therefore not visible to `SomeClass$SpockMock`. According to the spec, this is not legal as you must not refer to classes that are not visible to a class but the JVM is sometimes more forgiving like in this case.

The javac compiler does a similar thing but creates an anonymous type in the same package of the class it creates. The Kotlin compiler should do the same thing or make the default marker type public (whilst it could still retain the class's constructor public.)

**Comment by mibac138** [comment]
[Kotlin issue for future reference](https://youtrack.jetbrains.com/issue/KT-20869)

**Comment by raphw** [comment]
Tracked in Kotlin and can be avoided by not validating.

**Comment by wakaleo** [comment]
> Tracked in Kotlin and can be avoided by not validating.

Is something you can do when creating the proxy class through ByteBuddy? I can't see any obvious API options.

**Comment by raphw** [comment]
Yes, simply use `new ByteBuddy().with(TypeValidation.DISABLED)` and it will just do without asking.
