### ISSUE TITLE
Unknown Java version 10

### ISSUE THREAD

**Issue by sdfelts** [raphw/byte-buddy#351]
java.lang.IllegalArgumentException: Unknown Java version: 10
                at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
                at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:357)
                at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
                at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)
                ... 18 more

Of course, the plan is for the next release to become 18.3/18.9 so these need to be handled too.  For now, it seems these should behave like JDK9 until proven otherwise.

**Comment by raphw** [comment]
I will wait a bit until there is a bit more know about the version number handling. It will become a bit of a pain in the ass to handle non-numeric versions in this API but I will figure something out.

Thanks for reminding me!
