### ISSUE TITLE
ArrayIndexOutOfBoundsException when rebasing class

### ISSUE THREAD

**Issue by krullert** [raphw/byte-buddy#352]
When using bytebuddy to reload a JPA enhanced class (via a DataNucleus enhancer),
It throws a java.lang.ArrayIndexOutOfBoundsException (the binaryRepresentation is an already modified byte code representation using ASM v4x).

```
java.lang.ArrayIndexOutOfBoundsException: 375

	at net.bytebuddy.jar.asm.ClassReader.readLabel(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2639)
```

```
final ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();

final Class<?> buddyClass = new ByteBuddy(ClassFileVersion.JAVA_V7)
		.rebase(loadedClass, ClassFileLocator.Simple.of(unitName, enhancedBytes))
		.make()
		.load(contextClassLoader)
		.getLoaded();
```

Was wondering if this is a bad usage of the api, or the error is correct but ambigious.

Thanks in advance.

**Comment by raphw** [comment]
This looks like the previously generated byte code is a bit messy as this is an exception thrown druing reading the class by ASM. If you can, could you create a reproduction and submit it to the ASM issue tracker? They can probably fix that!
