### ISSUE TITLE
Can't create a dynamic subclass of a inner class

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#361]
Here is my sample codes:

```java
public class ModuleBProvider extends ModuleProvider {
    public class Business1 implements BaseModuleB.ServiceBBusiness1 {

    }

    public class Business2 implements BaseModuleB.ServiceBBusiness2 {

    }

    @Test
    public void test() throws IllegalAccessException, InstantiationException {
        Business1 business = new Business1();

        new ByteBuddy().subclass(Business1.class)
            .implement(TracedService.class)
            .method(getDefaultMatcher()).intercept(
            MethodDelegation.withDefaultConfiguration().to(new ServiceMetricCollector())
        ).make().load(getClass().getClassLoader()
        ).getLoaded().newInstance();
    }

    private ElementMatcher<? super MethodDescription> getDefaultMatcher() {
        return not(isStatic().or(named("getClass")).or(named("hashCode")).or(named("equals")).or(named("clone"))
            .or(named("toString")).or(named("notify")).or(named("notifyAll")).or(named("wait")).or(named("finalize")));

    }
}
```

The inner class clearly has a empty constructor, but 
```
java.lang.InstantiationException: org.skywalking.apm.collector.core.module.ModuleBProvider$Business1$ByteBuddy$X8VNxmFr

	at java.lang.Class.newInstance(Class.java:427)
	at org.skywalking.apm.collector.core.module.ModuleBProvider.test(ModuleBProvider.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoSuchMethodException: org.skywalking.apm.collector.core.module.ModuleBProvider$Business1$ByteBuddy$X8VNxmFr.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 23 more

```

**Comment by wu-sheng** [comment]
If the parent class is a common one, like this, it works.

```java
public class TestService implements Service {
}
```

**Comment by wu-sheng** [comment]
```pom
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.7.6</version>
        </dependency>
```

**Comment by raphw** [comment]
Inner classes are just synthetic sugar for a class that takes its outer class as an implicit constructor parameter to make the instance available. You can also see that in the javap output.

**Comment by wu-sheng** [comment]
thanks. i forget to run javap.
