### ISSUE TITLE
Can't resolve type description, when Byte-buddy works with groovy

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#373]
Hi raphw. Skywalking is facing an error when our agent runs in an application based on groovy tech-stack. `Cannot resolve type description for org.ofbiz.service.engine.GroovyBaseScript` exception occurs. I guess the reason is Byte-buddy did some checks for classes, or groovy enging compiling output classes contains something unexpected.

* Exception
```
ERROR 2017-11-10 11:30:01 SkyWalkingAgent :  Failed to enhance class org.miniofbiz.example.person.PersonEvents 
java.lang.IllegalStateException: Cannot resolve type description for org.ofbiz.service.engine.GroovyBaseScript
	at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:134)
	at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
	at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:6976)
	at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3328)
	at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:277)
	at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:248)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:35)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:15)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1210)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:8771)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:8782)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:9019)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:9339)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at groovy.lang.GroovyClassLoader.access$400(GroovyClassLoader.java:63)
	at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:500)
	at groovy.lang.GroovyClassLoader$ClassCollector.onClassNode(GroovyClassLoader.java:517)
	at groovy.lang.GroovyClassLoader$ClassCollector.call(GroovyClassLoader.java:521)
	at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:822)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1055)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:212)
	at org.ofbiz.base.util.GroovyUtil.parseClass(GroovyUtil.java:153)
	at org.ofbiz.base.util.GroovyUtil.getScriptClassFromLocation(GroovyUtil.java:125)
	at org.ofbiz.webapp.event.GroovyEventHandler.invoke(GroovyEventHandler.java:115)
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696)
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421)
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke$original$YGFi1Ovu(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardWrapperValve.invoke$original$YGFi1Ovu$accessor$puHjJXD9(StandardWrapperValve.java)
	at org.apache.catalina.core.StandardWrapperValve$auxiliary$KXD8kUyl.call(Unknown Source)
	at org.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:92)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

* `GroovyBaseScript` class:
```groovy

import org.ofbiz.base.util.Debug;
import org.ofbiz.service.ServiceUtil
import org.ofbiz.service.ExecutionServiceException

abstract class GroovyBaseScript extends Script {
    public static final String module = GroovyBaseScript.class.getName();

    Map runService(String serviceName, Map inputMap) throws ExecutionServiceException {
        if (!inputMap.userLogin) {
            inputMap.userLogin = this.binding.getVariable('parameters').userLogin;
        }
        Map result = binding.getVariable('dispatcher').runSync(serviceName, inputMap);
        if (ServiceUtil.isError(result)) {
            throw new ExecutionServiceException(ServiceUtil.getErrorMessage(result))
        }
        return result;
    }

    Map makeValue(String entityName) throws ExecutionServiceException {
        return result = binding.getVariable('delegator').makeValue(entityName);
    }

    Map findOne(String entityName, Map inputMap) {
        Map genericValue = binding.getVariable('delegator').findOne(entityName, inputMap, true);
        // TODO: get the list of pk fields from the map and use them only
        return genericValue;
    }

    List findList(String entityName, Map inputMap) {
        List genericValues = binding.getVariable('delegator').findByAnd(entityName, inputMap, null, false);
        // TODO: get the list of entity fields from the map and use them only
        return genericValues;
    }

    def success(String message) {
        // TODO: implement some clever i18n mechanism based on the userLogin and locale in the binding
        if (this.binding.hasVariable('request')) {
            // the script is invoked as an "event"
            if (message) {
                this.binding.getVariable('request').setAttribute("_EVENT_MESSAGE_", message)
            }
            return 'success';
        } else {
            // the script is invoked as a "service"
            if (message) {
                return ServiceUtil.returnSuccess(message);
            } else {
                return ServiceUtil.returnSuccess();
            }
        }
    }
    Map failure(String message) {
        // TODO: implement some clever i18n mechanism based on the userLogin and locale in the binding
        if (message) {
            return ServiceUtil.returnFailure(message);
        } else {
            return ServiceUtil.returnFailure();
        }
    }
    def error(String message) {
        // TODO: implement some clever i18n mechanism based on the userLogin and locale in the binding
        if (this.binding.hasVariable('request')) {
            // the script is invoked as an "event"
            if (message) {
                this.binding.getVariable('request').setAttribute("_ERROR_MESSAGE_", message)
            }
            return 'error';
        } else {
            if (message) {
                return ServiceUtil.returnError(message);
            } else {
                return ServiceUtil.returnError();
            }
        }
    }
    def logInfo(String message) {
        Debug.logInfo(message, module);
    }
    def logWarning(String message) {
        Debug.logWarning(message, module);
    }
    def logError(String message) {
        Debug.logError(message, module);
    }
}
```

**And this error occurs AGAIN** in [drools](https://github.com/kiegroup/drools) , which manipulates classes by asm.

```
ERROR 2017-11-08 16:14:45 SkyWalkingAgent : Failed to enhance class com.xu.drools.Rule_22146222303DefaultConsequenceInvoker
java.lang.IllegalStateException: Cannot resolve type description for org.drools.core.rule.builder.dialect.asm.ConsequenceStub
```

The origin issues from skywalking: https://github.com/OpenSkywalking/skywalking/issues/578 https://github.com/OpenSkywalking/skywalking/issues/555 . (Chinese descriptions, sorry)

**Comment by raphw** [comment]
It seems like it is not possible to read the class file for `org.ofbiz.service.engine.GroovyBaseScript`. Byte Buddy is asked to instrument all classes that have a certain super type and for this purpose, it needs to read all class files that are involved in a class's hierarchy.

With the mentioned class, in order to apply the check, it is necessary to parse its class file to find the class's super types. Without that information, Byte Buddy cannot check what super types the class has and answer the matching request.

To resolve this, you can either check how to better extract class files from specific types of class loaders (by default, the class loader is queried using `getResourceAsStream`) or you can handle the error by adding another matcher that excludes the type explicitly or by some other criteria. You can also wrap the matcher to suppress the exception.

**Comment by wu-sheng** [comment]
I am not sure how.to wrap the matcher to suppress the exception.Can you give me something more explicit or some examples?

**Comment by raphw** [comment]
The easiest way is to use `ElementMatchers.failSafe(...)` but this swallows the exception. Maybe you want to log the error and then you would need to implement something similar yourself.

**Comment by wu-sheng** [comment]
I found `ElementMatchers.failSafe(...)`, but how can I log the exception? Can't find the callback.

**Comment by wu-sheng** [comment]
I think I get the point.

**Comment by wu-sheng** [comment]
Implement my own `FailSafeMatcher` would help.

**Comment by raphw** [comment]
I also think that is the best solution for something that custom.
