### ISSUE TITLE
ZipException on attempt to inject into existing JAR

### ISSUE THREAD

**Issue by saksmt** [raphw/byte-buddy#386]
Stacktrace:
```
Exception in thread "main" java.util.zip.ZipException: invalid entry size (expected 1789 but got 2398 bytes)
        at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:262)
        at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:360)
        at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
        at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:377)
        at net.bytebuddy.dynamic.DynamicType$Default.inject(DynamicType.java:4324)
        at net.bytebuddy.dynamic.DynamicType$Default.inject(DynamicType.java:4334)
```

Codesample:
```java
new ByteBuddy()
    .<Object>redefine(typePool.describe("SomeEntity").resolve(), classLocator)
    .defineProperty("newProp", typePool.describe("java.lang.String").resolve())
    .make()
    .inject(jarFile)
```

**Comment by raphw** [comment]
Thanks, the meta data was not copied correctly. This will be fixed in the next version.
