### ISSUE TITLE
How to use ByteBuddy in Tomcat

### ISSUE THREAD

**Issue by xiaoxinba** [raphw/byte-buddy#398]
tomcat：apache-tomcat-7.0.70
bytebuddy：1.7.6

i use -javaagent:   add my agent.jar , but when i start tomcat:   `FATAL ERROR in native method: processing of -javaagent failed
java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:327)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.matcher.ElementMatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Exception in thread "main" Disconnected from server`

Why??

**Comment by raphw** [comment]
Do you bundle the agent together with Byte Buddy? You can use the Maven Shade plugin to achieve that, for example. It seems like the Byte Buddy library is missing.

**Comment by xiaoxinba** [comment]
I fount that if not use ByteBuddy library, it can work well in tomcat. 
so i want to know if only ByteBuddy need bundle by Maven Shade plugin?

**Comment by ascrutae** [comment]
@xiaoxinba  you can add maven shade plugin like this: [go ~](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-agent-core/pom.xml#L145-L207)

**Comment by raphw** [comment]
Closing, please reopen if still relevant.
