### ISSUE TITLE
Hotswapping classes throws an IllegalStateException

### ISSUE THREAD

**Issue by Anon10W1z** [raphw/byte-buddy#40]
Using the code in the example:
```
ClassLoader classLoader = ClassLoader.getSystemClassLoader();
ClassLoadingStrategy classLoadingStrategy = ClassReloadingStrategy.fromInstalledAgent();
class Foo {
	String m() {
		return "foo";
	}
}
class Bar {
	String m() {
		return "bar";
	}
}
Foo foo = new Foo();
new ByteBuddy().redefine(Bar.class).name(Foo.class.getName()).make().load(Foo.class.getClassLoader(), classLoadingStrategy);
System.out.println(foo.m());
```
Prints out "bar" as expected but throws an IllegalStateException right after.
```
java.lang.IllegalStateException: ClassReader.accept() should be called with EXPAND_FRAMES flag
	at net.bytebuddy.jar.asm.commons.LocalVariablesSorter.visitFrame(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.jar.asm.commons.RemappingMethodAdapter.visitFrame(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.doCreate(TypeWriter.java:1351) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:1335) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:917) ~[byte-buddy-0.6.12.jar:?]
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:209) ~[byte-buddy-0.6.12.jar:?]
```

**Comment by raphw** [comment]
Thanks for the info. You are right, this is required by an ASM adapter I am using which has this requirement without documenting it. I am not yet sure when I have time to look at it. The easiest is to redefine the class itself instead of renaming it:

```java
Foo foo = new Foo();
new ByteBuddy()
  .redefine(Bar.class)
  .method(named("m")).intercept(FixedValue.value("bar")) 
  .make()
  .load(Foo.class.getClassLoader(), classLoadingStrategy);
System.out.println(foo.m());
```

I will however fix this on the long run once I have taken care of more pressing problems with 0.7.

**Comment by Anon10W1z** [comment]
On a side note, is there any way to modify the class that an existing class extends from?

**Comment by raphw** [comment]
No there is not and this is by design. Byte Buddy is designed with binary compatible instrumentation in mind. You would rather create a new class that subclasses the desired subclass for implementing the desired class.

**Comment by Anon10W1z** [comment]
Alright, thank you for your help. I definitely love this library regardless!

**Comment by raphw** [comment]
Thank you. All the class swapping functionality is not used by too many people but I hope that these features become more useful with the evolution of the JVM.

For the reported error: The ASM library could actually work with the non-expanded frames. The remapper that I use is rather generic in its functionality  which is why they require it. The easiest would however be to not require the expansion for simple use cases. I filed a bug with ASM and I hope that they will take it. Otherwise, I need to craft some sort of work-around in the future.

**Comment by raphw** [comment]
I leave the issue open until it no longer fails.

**Comment by Anon10W1z** [comment]
Oh right, my bad sorry.

**Comment by raphw** [comment]
No problem. Again, thanks for reporting.

**Comment by raphw** [comment]
I resolved this issue on master with a workarround that works for Byte Buddy's use case. At best, ASM will offer support for this out-of-the-box at some point. Since the 0.7 release has gone wrong, I reverted master to a stable non-generic version for now and will release a version 0.6.13 some time.

**Comment by raphw** [comment]
0.6.13 is released where this should be fixed.
