### ISSUE TITLE
Inconsistent frame length error

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#408]
I ran into an odd `java.lang.IllegalStateException: Inconsistent frame length` issue when writing a test for a transformation I was doing.  I can't quite understand it, but I tried to consolidate it as much as I could.

You can see the test here: https://github.com/DataDog/dd-trace-java/blob/tyler/broken/broken/src/test/groovy/BrokenTest.groovy
When I run it in IntelliJ, it passes, but running via gradle the test fails due to not instrumenting caused by the following stacktrace:

```
java.lang.IllegalStateException: Inconsistent frame length for public java.lang.String BrokenClass.someMethod(java.lang.String): 0
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:4062)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:4016)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:7309)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1440)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1126)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:698)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:500)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8905)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at BrokenTest.$spock_feature_0_0(BrokenTest.groovy:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:188)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:406)
	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:324)
	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288)
	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278)
	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:269)
	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:263)
	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238)
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:481)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:464)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

Any idea what is causing this instrumentation error?
I'm running it on jdk1.8.0_131 on a Mac if that makes a difference.
Let me know if you need any further details.

Thanks!

**Comment by tylerbenson** [comment]
Interesting theory.  It might be jacoco, the code coverage tool. I can try running without that next week and see if that makes a difference.

**Comment by tylerbenson** [comment]
Enumerating the commands that run:

```
> gradle :broken:test --dry-run
:broken:compileJava SKIPPED
:broken:compileGroovy SKIPPED
:broken:processResources SKIPPED
:broken:classes SKIPPED
:broken:compileTestJava SKIPPED
:broken:compileTestGroovy SKIPPED
:broken:processTestResources SKIPPED
:broken:testClasses SKIPPED
:broken:test SKIPPED

BUILD SUCCESSFUL in 1s
```

There doesn't appear to be any code coverage tool running here.  In my main branch I have jacoco, but I removed that before submitting this issue.  Maybe it's something that groovy itself is doing?

**Comment by raphw** [comment]
It might indeed be Spock. Is there cglib on the class path? Newer versions of Spock can use either Byte Buddy or cglib. Cglib creates classes that often embed strange meta data. This might be it? Maybe the code generator is different based on your build location?

**Comment by raphw** [comment]
As a work-around, you could also turn on `ClassWriter.COMPUTE_FRAMES` for your build but I do not recommend that in production.

**Comment by tylerbenson** [comment]
These are the classes that Intellij seems to think are on the classpath:

![image](https://user-images.githubusercontent.com/734411/36460332-a674fdce-1703-11e8-849c-755c774e7e23.png)

Since this does seem isolated to a test environment, I don't mind if you want to just close this issue.  I just wasn't sure if this was indicative of a potentially thornier bug.

**Comment by raphw** [comment]
In this case, there should not be a problem. I assume that this might be related to something strange in the Groovy compiler.

I have plans to add a mode to Byte Buddy Advice that is less powerful but avoids the root cause of this error. It will be a bit of work but in the long time, I think most users can apply this mode to avoid suffering this. It is really strange that this only happens using Gradle but not IntelliJ. The other way round would make more sense. Eventually, one would need to dump the byte code of the class in question for both cases and compare them what could at least give clues.

If you would provide me with the byte code, I will have a look without being able to promise that there is anything I can do as the initial byte code seems to be broken to begin with....

**Comment by tylerbenson** [comment]
What is the best way to get the bytecode that you’re looking for? Add an interceptor somewhere that writes it to a file?

**Comment by raphw** [comment]
You can attach the class file for `BrokenClass` in this thread. As the class file is apparently transformed such that this error is triggered, you can also set a break point where the exception is thrown. Then browse down to the `TypeWriter` where the byte array for the original class file is resolved. Store this byte array somehow using your debugger and attach the resulting file to this thread.

Thanks for helping out!

**Comment by raphw** [comment]
This should no longer happen as of Byte Buddy 1.8.2, please reopen the ticket if you experience this problem again.

**Comment by tylerbenson** [comment]
@raphw Thanks for fixing this.  Sorry I never got around to providing the information you asked for.  This tab got lost and I forgot about it.  On the plus side, I haven't seen it since, so I think it is fixed.

**Comment by raphw** [comment]
No worries, thanks for getting back!
