### ISSUE TITLE
Redefine throws exception, if class is compiled with JDT and method parameter names are present

### ISSUE THREAD

**Issue by Speyns** [raphw/byte-buddy#445]
I was trying to use mockito with inline mocking on JDT, and encountered an exception while calling ByteBuddy.
I was able to isolate the exception outside of mockito.

Use `ByteBuddy.redefine(...)` with a class including a lambda capturing an enclosing local variable, compiled with JDK and method parameter names enabled.
Compiling with `javac` works without issue (even with [-parameters option](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#BHCFFJBJ)).

Exception:
```
java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getParameters
        at net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter$Dispatcher$ForJava8CapableVm.getParameter(ParameterDescription.java:387)
        at net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter$Dispatcher$ForJava8CapableVm.isNamePresent(ParameterDescription.java:355)
        at net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter.isNamed(ParameterDescription.java:227)
        at net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:147)
        at net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:107)
        at net.bytebuddy.description.method.ParameterList$AbstractBase.asTokenList(ParameterList.java:80)
        at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:693)
        at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:334)
        at net.bytebuddy.description.method.MethodList$AbstractBase.asTokenList(MethodList.java:53)
        at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:223)
        at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:698)
        at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:676)
Caused by: java.lang.reflect.MalformedParametersException: Invalid parameter name ""
        at java.lang.reflect.Executable.verifyParameters(Executable.java:386)
        at java.lang.reflect.Executable.privateGetParameters(Executable.java:416)
        at java.lang.reflect.Executable.getParameters(Executable.java:357)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter$Dispatcher$ForJava8CapableVm.getParameter(ParameterDescription.java:383)
```

Call:
```
        URI classResource = Abc.class.getResource( Abc.class.getSimpleName() + ".class" ).toURI();
        byte[] classfileBuffer = Files.readAllBytes( Paths.get( classResource ) );
        ByteBuddy byteBuddy = new ByteBuddy();
        byteBuddy.redefine( Abc.class, ClassFileLocator.Simple.of( Abc.class.getName(), classfileBuffer ) ).make().getBytes();
```

Redefined class: 
```
class Abc {
    public Object getSomethingOf( String interestingArgument ) {
        Consumer<String> lambdaExpression = l -> interestingArgument.toString();
        return null;
    }
}
```
JDT enabled [method parameter names](https://help.eclipse.org/luna/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/JavaCore.html#COMPILER_CODEGEN_METHOD_PARAMETERS_ATTR)
`org.eclipse.jdt.core.compiler.codegen.methodParameters=generate`

Test project as attachment:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Java version: 1.8.0_152, vendor: Oracle Corporation
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```
[Issue - ByteBuddy JDT.zip](https://github.com/raphw/byte-buddy/files/1895122/Issue.-.ByteBuddy.JDT.zip)

**Comment by testn** [comment]
Sounds like Eclipse problem https://bugs.eclipse.org/bugs/show_bug.cgi?id=516833

**Comment by raphw** [comment]
This is a compiler problem. The exception roots in the reflection API which does not accept an empty parameter name.

**Comment by Speyns** [comment]
I validated the issue with the newer JDT from Eclipse Photon Milestone 6 (4.8.0M6)
Build id: 20180315-1217.

JDT problem with lambda parameter names is resolved.
