### ISSUE TITLE
Android Testmodule using Mockito ClassNotFoundException

### ISSUE THREAD

**Issue by RocketRider** [raphw/byte-buddy#461]
I am trying to reproduce a bug where my test only android modules are failing because of some class mismatch. But while doing so I found something else. Not sure what the problem is here. Maybe it is my fault.

You can take a look at the code here:
https://github.com/RocketRider/AndroidTestModuleBug
Run with:
`.\gradlew` module-flavor1-androidTest-only:connectedCheck

```
05:31:46 V/InstrumentationResultParser: 1) net.bytebuddy.agent.builder.ResettableClassFileTransformer
05:31:46 V/InstrumentationResultParser: java.lang.ClassNotFoundException: net.bytebuddy.agent.builder.ResettableClassFileTransformer
05:31:46 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:400)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
05:31:46 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: net.bytebuddy.agent.builder.ResettableClassFileTransformer
05:31:46 V/InstrumentationResultParser: at java.lang.VMClassLoader.findLoadedClass(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/instrument/ClassFileTransformer;
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.instrument.ClassFileTransformer" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.android.testing.blueprint.test-1/base.apk", zip file "/data/app/com.example.android.testing.blueprint.flavor1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.testing.blueprint.test-1/lib/x86, /data/app/com.example.android.testing.blueprint.flavor1-1/lib/x86, /system/lib, /vendor/lib]]
05:31:46 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: 2) net.bytebuddy.dynamic.loading.NoOpClassFileTransformer
05:31:46 V/InstrumentationResultParser: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.loading.NoOpClassFileTransformer
05:31:46 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:400)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
05:31:46 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.loading.NoOpClassFileTransformer
05:31:46 V/InstrumentationResultParser: at java.lang.VMClassLoader.findLoadedClass(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/instrument/ClassFileTransformer;
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.instrument.ClassFileTransformer" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.android.testing.blueprint.test-1/base.apk", zip file "/data/app/com.example.android.testing.blueprint.flavor1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.testing.blueprint.test-1/lib/x86, /data/app/com.example.android.testing.blueprint.flavor1-1/lib/x86, /system/lib, /vendor/lib]]
05:31:46 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: 3) net.bytebuddy.jar.asm.commons.JSRInlinerAdapter
05:31:46 V/InstrumentationResultParser: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.JSRInlinerAdapter
05:31:46 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:400)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
05:31:46 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.JSRInlinerAdapter
05:31:46 V/InstrumentationResultParser: at java.lang.VMClassLoader.findLoadedClass(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/bytebuddy/jar/asm/tree/MethodNode;
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.bytebuddy.jar.asm.tree.MethodNode" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.android.testing.blueprint.test-1/base.apk", zip file "/data/app/com.example.android.testing.blueprint.flavor1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.testing.blueprint.test-1/lib/x86, /data/app/com.example.android.testing.blueprint.flavor1-1/lib/x86, /system/lib, /vendor/lib]]
05:31:46 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: 4) net.bytebuddy.jar.asm.commons.TryCatchBlockSorter
05:31:46 V/InstrumentationResultParser: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.TryCatchBlockSorter
05:31:46 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:400)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
05:31:46 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
05:31:46 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
05:31:46 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.TryCatchBlockSorter
05:31:46 V/InstrumentationResultParser: at java.lang.VMClassLoader.findLoadedClass(Native Method)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/bytebuddy/jar/asm/tree/MethodNode;
05:31:46 V/InstrumentationResultParser: ... 9 more
05:31:46 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.bytebuddy.jar.asm.tree.MethodNode" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.android.testing.blueprint.test-1/base.apk", zip file "/data/app/com.example.android.testing.blueprint.flavor1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.testing.blueprint.test-1/lib/x86, /data/app/com.example.android.testing.blueprint.flavor1-1/lib/x86, /system/lib, /vendor/lib]]
05:31:46 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05:31:46 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05:31:46 V/InstrumentationResultParser: ... 9 more
```

**Comment by raphw** [comment]
Could you try to build Byte Buddy from master and include this version? I assume that it is an issue with some updated shading that I presumably just fixed. Android has stricter verification with regards to class path consistency and I excluded some shaded internal code that is never used by Byte Buddy but still referenced by another few unused classes.

If master works for you, I can make a quick release.

**Comment by RocketRider** [comment]
I will try the master. Thank you for the very quick response!

**Comment by raphw** [comment]
Did you use the Maven wrapper to use the correct version? If so, could you run with the `-e` and `-X` flags?

**Comment by testn** [comment]
sound like https://github.com/mockito/mockito/issues/922

**Comment by RocketRider** [comment]
Thank you!
Yes that is the issue. Updating test runner solved it.
