### ISSUE TITLE
Getting java.lang.NoClassDefFoundError when instrumenting spring-boot

### ISSUE THREAD

**Issue by jsyeo** [raphw/byte-buddy#473]
I'm getting this stacktrace whenever I try to instrument a spring-boot app. I am writing a javaagent that simply prints the call sites to stdout.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedMethodAccessor13
	at jdk.internal.reflect.GeneratedMethodAccessor13.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:404)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.commons.logging.LogFactory$Log4jLog.<clinit>(LogFactory.java:198)
	at org.apache.commons.logging.LogFactory$Log4jDelegate.createLog(LogFactory.java:166)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:109)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:99)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:198)
	at me.jasonyeo.DeltaApplication.main(DeltaApplication.java:11)
	... 8 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.GeneratedMethodAccessor13
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 28 more
```

This is what I have in my javaagent:
```java
public class MyAgent {

  public static void premain(String args, Instrumentation instrumentation) {
    new AgentBuilder.Default()
        .type(not(nameStartsWith("me.jasonyeo.analysis.")
            .or(nameStartsWith("org.springframework.boot.loader.jar."))
            .or(named(MethodInfo.class.getName()))))
        .transform((builder, typeDescription, classLoader, module) -> builder.visit(Advice.to(MyAdvice.class).on(any())))
        .installOn(instrumentation);
  }
}
```

This is my advice class:

```java
public class MyAdvice {

  public static final LinkedList<MethodInfo> stack = new LinkedList<>();

  @Advice.OnMethodEnter(inline = false)
  public static MethodInfo enter(@Advice.Origin("#t") String className,
                                 @Advice.Origin("#m") String method,
                                 @Advice.Origin("#s") String signature) {
    final MethodInfo methodInfo = new MethodInfo(className, method, signature);
    if (!stack.isEmpty()) {
      System.out.println("caller = " + stack.peek());
      System.out.println("callee = " + methodInfo);
    }
    stack.push(methodInfo);
    return methodInfo;
  }

  @Advice.OnMethodExit(inline = false)
  public static void exit(@Advice.Enter MethodInfo methodInfo) {
    stack.remove(methodInfo);
  }
}
```

I'm not sure what's wrong. It works with a simple java app but it doesn't seem to work with larger programs. It's probably related to https://github.com/raphw/byte-buddy/issues/87 but I am not sure if that's the case. The stacktrace is different.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
