### ISSUE TITLE
[question] Instrumenting Servlet with javaagent and prometheus java client

### ISSUE THREAD

**Issue by stefanorg** [raphw/byte-buddy#489]
I've similar issue as in #87 
My problem is with jboss as 7  class loading.

I'm trying to instrument javax.servlet.ServletRequest and collect some metrics with prometheus java library. 

I'm using:
* bytebuddy 1.8.0

```
package it.mycomp.jagent.impl;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import io.prometheus.client.CollectorRegistry;
import io.prometheus.client.Counter;
import io.prometheus.client.Summary;
import io.prometheus.client.exporter.common.TextFormat;
import io.prometheus.client.hotspot.DefaultExports;
import it.mycomp.jagent.ClassLoaderCache;
import it.mycomp.jagent.advice.ArgoHttpClientAdvice;
import it.mycomp.jagent.advice.AuthFilterAdvice;
import it.mycomp.jagent.advice.UserFilterAdvice;
import it.mycomp.jagent.helper.DebugListener;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.description.type.TypeDescription;
import org.apache.http.HttpHost;
import org.apache.http.HttpRequest;
import org.apache.http.protocol.HttpContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.FilterChain;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import java.io.IOException;
import java.io.StringWriter;
import java.lang.instrument.Instrumentation;
import java.lang.reflect.Modifier;
import java.net.InetSocketAddress;
import java.util.Collections;

import static net.bytebuddy.matcher.ElementMatchers.*;

/**
 * Created by Stefano Corallo (scorallo@mycomp.it) on 15/06/18.
 */
public class JAgentImpl {

    public static final Counter httpRequestsTotal;
    public static final Summary httpRequestsDuration;
    public static Logger agentLogger = LoggerFactory.getLogger(JAgentImpl.class);

    static {

        DefaultExports.initialize();

        httpRequestsTotal = Counter.build()
                .name("http_requests_total")
                .labelNames("method", "path", "status")
                .help("Total number of http requests.")
                .register();

        httpRequestsDuration = Summary.build()
                .quantile(0.5, 0.05)   // Add 50th percentile (= median) with 5% tolerated error
                .quantile(0.9, 0.01)   // Add 90th percentile with 1% tolerated error
                .quantile(0.99, 0.001) // Add 99th percentile with 0.1% tolerated error
                .name("http_request_duration")
                .labelNames("method", "path", "status")
                .help("Duration for serving the http requests in seconds.")
                .register();

    }

    public static void premain(String arguments, Instrumentation instrumentation) throws Exception {

        ClassLoader agentClassLoader = ClassLoaderCache.getInstance().currentClassLoader();

        agentLogger.debug("classes in instrumentation:: {}", instrumentation.getAllLoadedClasses().length);
        for (Class clazz : instrumentation.getAllLoadedClasses()) {
            agentLogger.debug(clazz.getName());
        }


        new AgentBuilder.Default()
                .with(DebugListener.getListener())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)                
                .type(isSubTypeOf(new TypeDescription.Latent("javax.servlet.GenericServlet", Modifier.PUBLIC | Modifier.ABSTRACT, TypeDescription.Generic.OBJECT)))
                .transform(
                        new AgentBuilder.Transformer.ForAdvice()
                                .include(compound)
                                .advice(
                                        named("service")
                                                .and(takesArgument(0, ServletRequest.class))
                                                .and(takesArgument(1, ServletResponse.class))
                                        , "it.mycomp.jagent.advice.PromServletAdvice"
                                )
                )
                .installOn(instrumentation);


        runHttpServer();
    }

    static void runHttpServer() throws Exception {
        InetSocketAddress address    = new InetSocketAddress(9300);
        HttpServer        httpServer = HttpServer.create(address, 10);
        httpServer.createContext("/metrics", new HttpHandler() {
            @Override
            public void handle(HttpExchange httpExchange) throws IOException {
                StringWriter respBodyWriter = new StringWriter();
                TextFormat.write004(respBodyWriter, CollectorRegistry.defaultRegistry.metricFamilySamples());
                byte[] respBody = respBodyWriter.toString().getBytes("UTF-8");
                httpExchange.getResponseHeaders().put("Context-Type", Collections.singletonList("text/plain; charset=UTF-8"));
                httpExchange.sendResponseHeaders(200, respBody.length);
                httpExchange.getResponseBody().write(respBody);
                httpExchange.getResponseBody().close();
            }
        });
        httpServer.start();
    }
}

```

The advice class:

```
package it.mycomp.jagent.advice;

import io.prometheus.client.Counter;
import io.prometheus.client.Summary;
import it.mycomp.jagent.ClassLoaderCache;
import it.mycomp.jagent.HttpContext;
import it.mycomp.jagent.impl.JAgentImpl;
import net.bytebuddy.asm.Advice;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.lang.reflect.Method;
import java.util.concurrent.TimeUnit;

import static it.mycomp.jagent.HttpContext.HTTP_METHOD;
import static it.mycomp.jagent.HttpContext.HTTP_PATH;


/**
 *
 */
public class PromServletAdvice {
    public static Logger agentLogger = LoggerFactory.getLogger(PromServletAdvice.class);
    public static long    startTime = 0;



    public static String stripPathParameters(String path) {

        // The URL path may include path parameters.
        // For example, REST URLs for querying an item might look like this:
        //
        //   /item/1
        //   /item/2
        //   /item/3
        //   etc.
        //
        // We don't want to create a new Prometheus label for each of these paths.
        // Rather, we want a single label like this:
        //
        //   /item/{id}
        //
        // This method replaces path parameters with placeholders. It is application specific and
        // should be adapted depending on the actual paths in an application.
        // For the demo, we just replace all numbers with {id}.

        return path
                .replaceAll("/[0-9]+", "/{id}")
                .replaceAll("/;jsessionid=\\w*", "")
                .replaceAll("/$", "")
                .replaceAll("\\?.*", ""); // Also remove path parameters, like "?jsessionid=..."
    }

    @Advice.OnMethodEnter
    public static void before(@Advice.This Object obj,
                              @Advice.Argument(value = 0) ServletRequest request,
                              @Advice.Argument(value = 1) ServletResponse response,
                              @Advice.Origin Method method) {



        ClassLoader classLoader = ClassLoaderCache.getInstance().currentClassLoader();
        agentLogger.debug("current classloader {} ", classLoader);
        agentLogger.debug("obj classloader {} ", obj.getClass().getClassLoader().toString());

        agentLogger.debug("Counter inside agent get::{} ", JAgentImpl.httpRequestsTotal.toString());
        agentLogger.debug("Counter inside agent class::{} ", JAgentImpl.httpRequestsTotal.toString());


        if (HttpServletRequest.class.isAssignableFrom(request.getClass()) && HttpServletResponse.class.isAssignableFrom(response.getClass())) {
            HttpServletRequest req = (HttpServletRequest) request;
            HttpContext.put(HttpContext.HTTP_METHOD, req.getMethod());
            HttpContext.put(HTTP_PATH, stripPathParameters(req.getRequestURI()));
            startTime = System.nanoTime();
            agentLogger.debug("Processing request for {} {} starting@{}",req.getMethod(), req.getRequestURI(), startTime);
        }
    }

    @Advice.OnMethodExit
    public static void after(@Advice.This Object obj,
                             @Advice.Argument(value = 0) ServletRequest request,
                             @Advice.Argument(value = 1) ServletResponse response,
                             @Advice.Origin Method method) {
        ClassLoader classLoader = ClassLoaderCache.getInstance().currentClassLoader();
        agentLogger.debug("current classloader {} ", classLoader);

        if (HttpServletRequest.class.isAssignableFrom(request.getClass()) && HttpServletResponse.class.isAssignableFrom(response.getClass())) {
            HttpServletResponse resp = (HttpServletResponse) response;
            try {
                double     duration      = ((double) System.nanoTime() - startTime) / (double) TimeUnit.SECONDS.toNanos(1L);
                String     http_method   = (String) HttpContext.get(HTTP_METHOD);
                String     path          = (String) HttpContext.get(HTTP_PATH);
                JAgentImpl.httpRequestsTotal.labels(http_method, path, Integer.toString(resp.getStatus())).inc();
                JAgentImpl.httpRequestsDuration.labels(http_method, path, Integer.toString(resp.getStatus())).observe(duration);
                agentLogger.debug("Register metric for {} {} with status={} and duration={}", method, path, resp.getStatus(), duration);
            } finally {
                HttpContext.clear(HTTP_METHOD, HTTP_PATH);
            }
        }
    }

}

```

The advice is instrumented correctly, but i get the following error:

```
jboss_1         | onTransformation:org.apache.catalina.servlets.DefaultServlet
jboss_1         | onTransformation:org.jboss.servlet.http.HttpEventServlet
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:842 - current classloader it.mycomp.jagent.PerDeploymentClassLoader@5e1de715 
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:842 - obj classloader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @3949cc16 (roots: /opt/jboss/jboss-as/modules) 
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:842 - Counter inside agent get::io.prometheus.client.Counter@a8eb1a8 
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:842 - Counter inside agent class::io.prometheus.client.Counter@a8eb1a8 
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.HttpContext:put:30 - Storing key=it.mycomp.jagent.HttpContext$Key@4c35aba4 with value=GET
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.HttpContext:put:30 - Storing key=it.mycomp.jagent.HttpContext$Key@2ac1f5d1 with value=/rest/version
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:842 - Processing request for GET /rest/version starting@374919790060409
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.advice.PromServletAdvice:service:848 - current classloader it.mycomp.jagent.PerDeploymentClassLoader@5e1de715 
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.HttpContext:get:38 - Read key=it.mycomp.jagent.HttpContext$Key@4c35aba4
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.HttpContext:get:38 - Read key=it.mycomp.jagent.HttpContext$Key@2ac1f5d1
jboss_1         | 2018-06-15 16:41:25 ERROR [,,,,] [http-/0.0.0.0:8080-1] org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/].[default]:invoke:309 - Servlet.service() for servlet default threw exception
jboss_1         | java.lang.ClassNotFoundException: io.prometheus.client.Counter from [Module "javax.servlet.api:main" from local module loader @3949cc16 (roots: /opt/jboss/jboss-as/modules)]
jboss_1         |       at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
jboss_1         |       at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
jboss_1         |       at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
jboss_1         |       at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
jboss_1         |       at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
jboss_1         |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
jboss_1         |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
jboss_1         |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
jboss_1         |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
jboss_1         |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
jboss_1         |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
jboss_1         |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
jboss_1         |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
jboss_1         |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:372)
jboss_1         |       at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
jboss_1         |       at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:679)
jboss_1         |       at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:931)
jboss_1         |       at java.lang.Thread.run(Thread.java:748)

```

When i try to increment the counter in the after advice : `JAgentImpl.httpRequestsTotal.labels(http_method, path, Integer.toString(resp.getStatus())).inc();`  the error is thrown.

I've tried also as suggested in #473 but with no luck.

Hope you can get me in the right direction.

Thanks

**Comment by raphw** [comment]
The solution is probably somewhere related to the `org.jboss.modules.ModuleClassLoader`. Your Java agent is loaded on the system class path and you would need to find out if:

1. The module class loader can see your agent classes at all (delegates to the system class loader). This can be solved by injecting your classes to the bootstrap loader that is universally visible.
2. The module class loader only delegates specific packages to its parents. (You might need to change your JBoss setup.)

**Comment by stefanorg** [comment]
Hi @raphw,

in the startup configuration of jboss AS, i've provided the needed library and this is the startup output :

```
=========================================================================
jboss_1         | 
jboss_1         |   JBoss Bootstrap Environment
jboss_1         | 
jboss_1         |   JBOSS_HOME: /opt/jboss/jboss-as
jboss_1         | 
jboss_1         |   JAVA: /usr/lib/jvm/java-1.7-openjdk/bin/java
jboss_1         | 
jboss_1         |   JAVA_OPTS:  -server -XX:+UseCompressedOops -Xms1024m -Xmx1024m -XX:MaxPermSize=512m -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 
                    -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.slf4j,ch.qos.cal10n,ch.qos.logback,biz.paluch.logging,javax.servlet.api,it.mycomp.jagent 
                    -Djava.awt.headless=true -Djboss.server.default.config=standalone.xml -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n 
                    -Duser.language=it -Duser.region=IT -Duser.timezone=Europe/Rome -Dfile.encoding=UTF-8 
                    -Xbootclasspath/p:/opt/jboss/jboss-as/modules/org/jboss/logmanager/main/jboss-logmanager-1.3.2.Final.jar
                            :/opt/jboss/jboss-as/modules/org/slf4j/main/slf4j-api-1.7.25.jar
                            :/opt/jboss/jboss-as/modules/org/slf4j/main/slf4j-ext-1.7.25.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/logback-core-1.1.9.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/logback-classic-1.1.9.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/logback-access-1.1.9.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/logstash-logback-encoder-4.8.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/jackson-core-2.6.5.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/jackson-databind-2.6.5.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/logback/main/jackson-annotations-2.6.5.jar
                            :/opt/jboss/jboss-as/modules/ch/qos/cal10n/main/cal10n-api-0.7.3.jar
                            :/opt/jboss/jboss-as/modules/org/apache/httpcomponents/argo/httpclient-4.5.3.jar
                            :/opt/jboss/jboss-as/modules/org/apache/httpcomponents/argo/httpcore-4.4.6.jar
                            :/opt/jboss/jboss-as/modules/javax/servlet/api/main/jboss-servlet-api_3.0_spec-1.0.1.Final.jar
                            :/opt/jboss/jboss-as/modules/biz/paluch/logging/main/logstash-gelf-1.11.1-SNAPSHOT.jar
                            :/opt/jboss/jboss-as/modules/it/mycomp/jagent/main/simpleclient-0.4.0.jar
                            :/opt/jboss/jboss-as/modules/it/mycomp/jagent/main/simpleclient_common-0.4.0.jar
                            :/opt/jboss/jboss-as/modules/it/mycomp/jagent/main/simpleclient_hotspot-0.4.0.jar
jboss_1         |  -Dorg.jboss.logging.provider=slf4j -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dlogback.configurationFile=/opt/jboss/jboss-as/standalone/configuration/logback.xml -javaagent:/opt/jboss/jboss-as/modules/it/mycomp/jagent/main/jagent.jar
jboss_1         | 
jboss_1         | =========================================================================

```

With the `-Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.slf4j,ch.qos.cal10n,ch.qos.logback,biz.paluch.logging,javax.servlet.api,it.mycomp.jagent` those modules/libraries should by visible to all classloader in the AS.

With the: `-Xbootclasspath/p:....` i put the jar `simpleclient-0.4.0.jar ...` in the boot classpath.

The strange think that i've noticed is that the class `HttpContext` (is my own class in the it.mycomp namespace) is called correctly in the scope of Servlet just before the exception, as you can see in the log:

```
jboss_1         | 2018-06-15 16:41:25 DEBUG [,,,,] [http-/0.0.0.0:8080-1] it.mycomp.jagent.HttpContext:get:38 - Read key=it.mycomp.jagent.HttpContext$Key@2ac1f5d1
```

The injected code in the servlet, can read the key from `it.mycomp.jagent.HttpContext` but can't read the Counter from the io.prometheus package.

**Comment by raphw** [comment]
I assume that this is because of JBoss not resolving the package as it is not configured in the JBoss modules descriptions. Ideally, you create your custom dispatchers and place them in some `java.` package on the bootclass path that is normally resolved by any class loader.

**Comment by stefanorg** [comment]
I'm not sure to understand what you meen with "custom dispatcher and place the in som java. package".

At the moment the only way i could find is to modify the module dependecies for the `javax.servlet.api` and add there the dependencies i need like this:

```
<module xmlns="urn:jboss:module:1.1" name="javax.servlet.api">
    <resources>
        <resource-root path="jboss-servlet-api_3.0_spec-1.0.1.Final.jar"/>
        <!-- Insert resources here -->
    </resources>
    <dependencies>
        <module name="io.prometheus.simpleclient" /> <--- this is the custom module with the needed library
    </dependencies>
</module>

```

I don't like this solution very much, because it means that for each module i want to instrument i need to add that dependency manually.

**Comment by raphw** [comment]
You would need to create some class `java.some.Dispatcher`, inject this class into the bootstrap path and then, from your Advice, you can only access this class to communicate with your agent. Otherwise, you must assume that only the classes that are normally available to the instrumented class are available.

**Comment by stefanorg** [comment]
Thanks for your response. Actually i did like you suggest.
I've created a class in my ajent (that acts like a proxy) and in my advice's i call that proxy in the scope of the agent classloader, that was set in the bootstrap path.

:+1:
