### ISSUE TITLE
ByteBuddy and the security manager

### ISSUE THREAD

**Issue by gsmet** [raphw/byte-buddy#493]
Hi,

For the Hibernate ORM project, we are trying to get ByteBuddy to work with the security manager enabled.

This is something that worked with our previous Javassist bytecode provider but does not work anymore with ByteBuddy.

One issue we spotted is that, when we use a method interceptor with a `MethodDelegation.to()`, a proxy is generated with this sort of things:
```java
    static {
        cachedValue$7i1hAKhy$4cscpe1 = Object.class.getDeclaredMethod("toString", new Class[0]);
        cachedValue$7i1hAKhy$5j4bem0 = Object.class.getDeclaredMethod("equals", Object.class);
        cachedValue$7i1hAKhy$7m9oaq0 = Object.class.getDeclaredMethod("clone", new Class[0]);
        cachedValue$7i1hAKhy$9pqdof1 = Object.class.getDeclaredMethod("hashCode", new Class[0]);
    }
```
and you can't call  `getDeclaredMethod()` outside of a privileged block if the security manager is enabled.

In Javassist, all these calls are run in privileged blocks if the security manager is enabled: https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/util/proxy/SecurityActions.java#L36 .

There are a couple of other calls that are sensible mostly related to manipulating the class loaders, calling `setAccessible()` on a field and so on.

Is there any plan to have ByteBuddy support the security manager in the near future? Or should we use Javassist in this particular case?

Thanks!

**Comment by raphw** [comment]
Yes, never thought of it to be honest. Of course, Byte Buddy should support this and I will implement an appropriate measure some time soon.

I cannot cooy the Javassist aproach unfortunately since Byte Buddy is a more general code generator but I think I have an idea of how to get it done.

**Comment by raphw** [comment]
I have a fix drafted but it will be a bit different in terms of the context being used.

The idea of Byte Buddy is to not create dependencies onto the library when creating code. The priviliged call will therefore happen from the static initializer and not from Byte Buddy.

Is this a problem for your use case?

**Comment by gsmet** [comment]
I think it will be an issue because we generate the proxy entities in the same package as the original entity (we need that to support signed jars) and we don't really want to force the users to give these permissions to their own code as that would defeat the purpose of the security manager.

Could we imagine being able to configure the calls made in the static initializer to redirect them to some Hibernate code that would expose a privileged `getDeclaredMethod()`? Pretty similar to what is done with Javassist, except we would provide it ourselves and pass it to ByteBuddy when creating the proxies.

**Comment by raphw** [comment]
I have never looked into the proxy implementation in detail but after checking, I can only say that this completely circumvents the security manager. It also breaks all compatibility to Java Modules.

By defining a publicly callable method `RuntimeSupport::find2Methods` that can be invoked by anybody on the class path, anybody can now apply the secured action with any inputs using Javassists privilege. I will not implement something like this in Byte Buddy and I would advice you against it as it makes Hibernate vunerable just like Javassist is currently vunerable. I argue that the privilege must be given to the proxy class.

If you really want to implement something like this, you can however do it already today, simply by registering a `MemberSubstitution`:

```
MemberSubstitution.relaxed()
  .method(ElementMatchers.is(Class.class.getDeclaredMethod("getDeclaredMethod", String.class, Class[].class)))
  .replaceWith(Foo.class.getDeclaredMethod("getDeclaredMethod", Class.class, String.class, Class[].class))
  .on(ElementMatchers.isTypeInitializer())
```

As said, I would however advice against it.

As for Byte Buddy, I will add a possibility to make secured calls in the next version but I will keep this configurable to allow redirections such as the one that you suggested.

**Comment by gsmet** [comment]
@raphw I think you might be right, maybe it's not such a good idea to do it as Javassist does.

To be honest, what I would prefer is having only the HIbernate code able to do privileged operation and not the entities but I don't think it's doable if we generate the proxies in the same package as the original entities.

**Comment by raphw** [comment]
@gsmet I gave this some more thought and I think it is possible by adding a caller check in the method similar to how the JDK guards its sensitive methods.

This would be similar to something like the following:
```java
public class HibernateLookupDispatcher {
  static Set<Class<?>> authorized = new SomeConcurrentSet<>();
  public static Method getDeclaredMethod(Class<?> type, String name, Class<?>[] parameters) {
    if (!authorized.contains(Reflection.getCallerClass())) throw new SecurityException();
    return AccessController.doPrivileged(() -> type.getDeclaredMethod(name, parameters));
  }
}
```

Doing so, Hibenate can generate the proxy and then add it to the `authorized` set before interacting with the class in any way. Since the initializer is triggered upon first use, Hibernate can authorize the class before its initializer is run. With the set being package-private, it is not possible for outsiders to authorize the class either.

You can then add the code as follows:

```java
MemberSubstitution.relaxed()
  .method(ElementMatchers.is(Class.class.getDeclaredMethod("getDeclaredMethod", String.class, Class[].class)))
  .replaceWith(HibernateLookupDispatcher.class.getDeclaredMethod("getDeclaredMethod", Class.class, String.class, Class[].class))
  .on(ElementMatchers.isTypeInitializer())
```

This way, lookups are only possible for proxies with the Hibernate access rights.

**Comment by gsmet** [comment]
Hi @raphw ,

I made some progress during the last 2 days, trying to clean up our ByteBuddy code and apply your suggested approach.

The calls don't get rewritten. I'm wondering if maybe I can't apply the rewrites directly to the current builder and need an intermediate representation?

The added calls are here: https://github.com/gsmet/hibernate-orm/blob/HHH-12857/hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java#L146 .

One other question I have is that we're supposed to change something like `MyClass.class.getDeclaredMethod(...)` by `HibernateLookupDispatcher.getDeclaredMethod(MyClass.class, ...)` and your substitution rule looks too simple to be true: it doesn't get the object and inject it in the parameters.

My current branch is here:
https://github.com/gsmet/hibernate-orm/tree/HHH-12857

Classes can be generated by simply using:
```
./gradlew test --tests=org.hibernate.bytecode.internal.bytebuddy.GenerateProxiesTest
```

They are saved in the Java temp directory (so `/tmp/` on Linux for instance) + `/bytebuddy/org/hibernate/bytecode/internal/bytebuddy/`. The class containing `$HibernateBasicProxy$` in its name does contain the calls I want rewritten.

Any help would be appreciated! Thanks!

**Comment by raphw** [comment]
Byte Buddy builders are immutable, you have to assign the result of .visit.

**Comment by gsmet** [comment]
@raphw yuk, thanks for pointing it out, sorry for the noise.

It nearly works, I still have a very specific issue with enhancement, which might be a ByteBuddy issue.

If I try to enhance the following class (the important part is the `Pattern` static initializer):
```java
@Entity(name = "SimpleEntity")
public class SimpleEntity {

	private static final Pattern PATTERN = Pattern.compile( "whatever" );

	@Id
	@GeneratedValue
	private Long id;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
}
```
using the `MemberSubstitution` visitors we discussed above, I end up with the following exception in ByteBuddy:

```
Caused by: java.lang.IllegalStateException: Cannot resolve type description for java.util.regex.Pattern
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:135)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:5842)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw$RawAnnotatedType.of(TypePool.java:3502)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw.resolveFieldType(TypePool.java:3394)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyFieldDescription.getType(TypePool.java:6147)
	at net.bytebuddy.description.field.FieldDescription$AbstractBase.getDescriptor(FieldDescription.java:101)
	at net.bytebuddy.matcher.DescriptorMatcher.matches(DescriptorMatcher.java:30)
	at net.bytebuddy.matcher.DescriptorMatcher.matches(DescriptorMatcher.java:11)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:96)
	at net.bytebuddy.asm.MemberSubstitution$SubstitutingMethodVisitor.visitFieldInsn(MemberSubstitution.java:1288)
	at net.bytebuddy.jar.asm.MethodVisitor.visitFieldInsn(MethodVisitor.java:385)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2207)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1274)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:679)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:391)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2880)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1653)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:180)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:94)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2669)
```

Note that it's not specific to `Pattern`, I have the same issue with other classes from the JDK (at least `String` in one of our tests).

It's easily reproducible with my branch:
https://github.com/gsmet/hibernate-orm/tree/HHH-12857

and this command:
```
./gradlew test --tests=org.hibernate.bytecode.internal.bytebuddy.GenerateProxiesTest
```

Hopefully, it won't be a rookie mistake this time.

Thanks for the help!

**Comment by raphw** [comment]
I could not run the tests on my machine, it claims the test does not exist. I do however wonder if you could set a breakpoint at `net.bytebuddy.asm.MemberSubstitution$SubstitutingMethodVisitor.visitFieldInsn` and check the `TypePool` being used and see what class file locator is registered with it. That Java types cannot be detected is a bit strange.

**Comment by raphw** [comment]
That said, I am working on a function to suppress this error when the relaxed mode is used. I am still wondering why this error occurs, therefore I would like to fix the error if there is any, not only the symptom.

**Comment by raphw** [comment]
Ok, it was so simple as running all tests and I found the problematic code from there. The problem is caused by Byte Buddy falling back to its default `TypePool` under type creation. This is controlled by invoking `DynamicType.Builder::make` in `ByteBuddyState:168`. The method accepts a `TypePool` in this method.

Without supplying a `TypePool`, Byte Buddy will create one for you based on the `ClassFileLocator` that is supplied in `EnhancerImpl:106`.

There are two potential solutions to this problem:
1. You extend the `ClassFileLocator` that you supply. You can for example supply: `new ClassFileLocator.Compount(ClassFileLocator.Simple.of(safeClassName, originalBytes), ClassFileLocator.ForClassLoader.of(enhancementContext.getLoadingClassLoader())). This approach would work but it will probably be less performant as the generated `TypePool` does not share a cache with the `TypePool` that you have already supplied.

2. You supply an appropriate `TypePool`. This is a more efficient solution. Just supply the `TypePool` from `EnhancerImpl` as an argument to `make`.

**Comment by gsmet** [comment]
@raphw sorry for the late reply, got caught up by other things and was planning to get back to you during the week-end but you beat me to it.

I applied your suggestion (2/) and it fixes my issue.

I'll try to get our SM tests run on top of that next week and hopefully they will succeed.

Thanks for the help!
