### ISSUE TITLE
Issues with the latest JDK 11 build and ByteBuddy 1.8.13

### ISSUE THREAD

**Issue by gsmet** [raphw/byte-buddy#497]
Hi,

With the latest JDK 11 build:
```
java version "11-ea" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11-ea+22)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11-ea+22, mixed mode)
```
and ByteBuddy 1.8.13, I have a few test failures in the ORM test suite.

For instance, with current master, the following command:
```
cd hibernate-core
../gradlew test --tests=org.hibernate.jpa.test.enhancement.TestLazyPropertyOnPreUpdate
```
gives the following error:
```
Caused by: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class org.hibernate.jpa.test.enhancement.TestLazyPropertyOnPreUpdate
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:117)
	at org.hibernate.testing.bytecode.enhancement.BytecodeEnhancerRunner$2.loadClass(BytecodeEnhancerRunner.java:94)
	... 40 more
Caused by: java.lang.UnsupportedOperationException
	at net.bytebuddy.jar.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:651)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:391)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1051)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1035)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1115)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1190)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1252)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7121)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:539)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:313)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:6728)
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:31)
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:12)
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:33)
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:14)
	at net.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:31)
	at net.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:12)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:428)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:163)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:94)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2669)
	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:113)
	... 41 more
```

I thought it might be a good idea to report the error as I haven't seen any open issues related.

Thanks!

**Comment by felixbarny** [comment]
Did you see https://github.com/raphw/byte-buddy/issues/492?

**Comment by gsmet** [comment]
@felixbarny thanks, I looked in the open issues but not the closed one.

Enabling the experimental features indeed allowed to run our tests.
