### ISSUE TITLE
java.lang.NullPointerException in RedefinitionStrategy

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#498]
```
Exception in thread "instana" java.lang.NullPointerException 
at com.instana.agent.tp.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4373) 
at com.instana.agent.tp.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.reset(AgentBuilder.java:9621) 
at com.instana.agent.tp.bytebuddy.agent.builder.ResettableClassFileTransformer$AbstractBase.reset(ResettableClassFileTransformer.java:261) 
```

**Comment by CodingFabian** [comment]
Not sure how a null value can be produced. but I have evidence of it happening ;)

**Comment by raphw** [comment]
Seems like this comes from an element of the array returned from`Instrumentation::getAllLoadedClasses`. A safe-guard cannot hurt.

**Comment by CodingFabian** [comment]
Ok, makese sense (I guess) have seen an element from getAllLoadedClasses being null before.
