### ISSUE TITLE
Mock inner classes using spock doesn't work when using byte-buddy

### ISSUE THREAD

**Issue by smoomrik** [raphw/byte-buddy#500]
Hello, 

I faced with the issue, but I'm not sure that this relates to byte-buddy or spockframework.
Could you please take a look.

byte-buddy: **1.8.13**

code sample:
```
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public class RequestFactory {
	private final RestTemplate restTemplate;
	
	public RequestFactory(RestTemplate restTemplate) {
		this.restTemplate = restTemplate;
	}
	
	PushNotificationRequestBuilder<Undefined, Undefined, Undefined> preparePushNotificationRequest() {
		return new PushNotificationRequestBuilder<>(restTemplate, null, null, null);
	}
	
	interface Defined {
	}
	
	interface Undefined {
	}
	
	static class EqualTypes<L, R> {
		static <T> EqualTypes<T, T> approve() {
			return new EqualTypes<>();
		}
	}
	
	class PushNotificationRequestBuilder<WithUrl, ForUser, WithBody> {
		
		private RestTemplate restTemplate;
		private Object body;
		private String userId;
		private String uri;
		
		private PushNotificationRequestBuilder(RestTemplate restTemplate, Object body, String userId, String uri) {
			this.restTemplate = restTemplate;
			this.body = body;
			this.userId = userId;
			this.uri = uri;
			
		}
		public PushNotificationRequestBuilder<Defined, ForUser, Defined> withUri(String uri) {
			return new PushNotificationRequestBuilder<>(restTemplate, body, userId, uri);
		}
		
		public PushNotificationRequestBuilder<WithUrl, ForUser, Defined> withBody(Object body) {
			return new PushNotificationRequestBuilder<>(restTemplate, body, userId, uri);
		}
		
		public PushNotificationRequestBuilder<WithUrl, Defined, WithBody> forUser(String userId) {
			return new PushNotificationRequestBuilder<>(restTemplate, body, userId, uri);
		}
		
		
		public ResponseEntity<Object> send(EqualTypes<PushNotificationRequestBuilder<Defined, Defined, Defined>,
			PushNotificationRequestBuilder<WithUrl, ForUser, WithBody>> approve) throws RestClientException {
			
			if(userId == null)
				return restTemplate.exchange(uri, HttpMethod.POST, new HttpEntity<>(body), Object.class);
			else
				return restTemplate.exchange(uri, HttpMethod.POST, new HttpEntity<>(body), Object.class, userId);
			
		}
	}
}
```

the test:

```
import spock.lang.Specification

class SpockMockingTest extends Specification{

    def "should create mock for inner class"(){
        when:
            def mock = Mock(RequestFactory.PushNotificationRequestBuilder)
        then:
            mock != null
    }
}

```
stacktrace:
```
java.lang.IllegalArgumentException: Could not create type

	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:139)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:108)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:65)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:51)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:296)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:286)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:105)
	at SpockMockingTest.should create mock for inner class(SpockMockingTest.groovy:9)
Caused by: java.lang.IllegalAccessError: class RequestFactory$PushNotificationRequestBuilder$SpockMock$Kd1TETqu cannot access its superclass RequestFactory$PushNotificationRequestBuilder
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.access$300(ByteArrayClassLoader.java:39)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:591)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:545)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:336)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName(Class.java:348)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.load(ByteArrayClassLoader.java:288)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:320)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:126)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4238)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory$1.call(ProxyBasedMockFactory.java:113)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory$1.call(ProxyBasedMockFactory.java:110)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
	... 13 more

```

**It works without byte-buddy in class path, but I can't exclude due to transitive dependencies**.

**Comment by raphw** [comment]
This is a consequence of some work being done to establish Java 11+ compatibility. Byte Buddy does no longer use any internal classes in its default configuration and Spock needs to update their class definition strategy to adapt to the changes. There is an open ticket in Spock, also to fix Java 11 compatibility.

You can set the `org.spockframework.mock.ignoreByteBuddy` property to true to use cglib, no matter the class path.
