### ISSUE TITLE
ByteBuddy crashed with JDK11: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe

### ISSUE THREAD

**Issue by Tibor17** [raphw/byte-buddy#504]
I used JDK 11 on Jenkins and I set `net.bytebuddy.experimental` to `true`.
The PowerMockito uses bytebuddy but I specified dependencies with LATEST version:
```
      <dependency>
        <groupId>net.bytebuddy</groupId>
        <artifactId>byte-buddy</artifactId>
        <version>1.8.14</version>
      </dependency>
      <dependency>
        <groupId>net.bytebuddy</groupId>
        <artifactId>byte-buddy-agent</artifactId>
        <version>1.8.14</version>
      </dependency>
```
Here is full stack trace:
```
22:58:34 [linux-jdk11-maven3.5.x] Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.booter.SystemUtilsTest$MockTest.testIsJava9AtLeast(SystemUtilsTest.java:321)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.booter.SystemUtilsTest$MockTest.shouldBeDifferentJdk9(SystemUtilsTest.java:304)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.Suite.runChild(Suite.java:128)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.Suite.runChild(Suite.java:27)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.Suite.runChild(Suite.java:128)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.Suite.runChild(Suite.java:27)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
22:58:34 [linux-jdk11-maven3.5.x] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:58:34 [linux-jdk11-maven3.5.x] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.apache.maven.surefire.shadefire.booter.ForkedBooter.main(ForkedBooter.java:74)
22:58:34 [linux-jdk11-maven3.5.x] Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:334)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:187)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:121)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:41)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.Mockito.mock(Mockito.java:1821)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:108)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.doCreateMock(DefaultMockCreator.java:61)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:53)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:62)
22:58:34 [linux-jdk11-maven3.5.x] 	... 61 more
22:58:34 [linux-jdk11-maven3.5.x] Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:334)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:187)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:121)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
22:58:34 [linux-jdk11-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:41)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.mockito.Mockito.mock(Mockito.java:1821)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:108)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.doCreateMock(DefaultMockCreator.java:61)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:53)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
22:58:34 [linux-jdk11-maven3.5.x] 	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:62)
22:58:34 [linux-jdk11-maven3.5.x] 	... 61 more
22:58:34 [linux-jdk11-maven3.5.x] 
22:58:34 [linux-jdk11-maven3.5.x] 
22:58:34 [linux-jdk11-maven3.5.x] Results :
22:58:34 [linux-jdk11-maven3.5.x] 
```

**Comment by raphw** [comment]
This is due to changes in the OpenJDK to further conceal internal API. I blogged about this here: http://mydailyjava.blogspot.com/2018/04/jdk-11-and-proxies-in-world-past.html?m=1
