### ISSUE TITLE
IBM JDK breaks PackageLookupStrategy creation logic

### ISSUE THREAD

**Issue by mdogan** [raphw/byte-buddy#510]
`PackageLookupStrategy` is created using following method:

```java
public PackageLookupStrategy run() {
    try {
        return new PackageLookupStrategy.ForJava9CapableVm(ClassLoader.class.getDeclaredMethod("getDefinedPackage", String.class));
    } catch (Exception ignored) {
        return PackageLookupStrategy.ForLegacyVm.INSTANCE;
    }
}
```

This logic checks existence of `getDefinedPackage(String)` method in `ClassLoader`, which is normally a public method in Java 9+ JDK. But in IBM JDK 1.8.0_171, `ClassLoader.getDefinedPackage(String)` exists as a package private method. 

When using byte-buddy with IBM JDK 8, classloading fails with;

```
java.lang.IllegalStateException: Cannot access final java.lang.Package java.lang.ClassLoader.getDefinedPackage(java.lang.String)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm.apply(ByteArrayClassLoader.java:561)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:439)
	[...]
Caused by: java.lang.IllegalAccessException: Class net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm can not access a member of class java.lang.ClassLoader with modifiers "final"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:114)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:399)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:391)
	at java.lang.reflect.Method.invoke(Method.java:501)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm.apply(ByteArrayClassLoader.java:559)
	... 29 more
``` 

Output of `java -version`:
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.17 - pxa6480sr5fp17-20180627_01(SR5 FP17))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180626_390413 (JIT enabled, AOT enabled)
OpenJ9   - 5cdc604
OMR      - a24bc01
IBM      - 21870d6)
JCL - 20180619_01 based on Oracle jdk8u171-b11
```

**Comment by raphw** [comment]
Thanks, good to know. Have not considered this possibility. I will fix this in the next release.

**Comment by raphw** [comment]
Fixed on master.
