### ISSUE TITLE
DynamicType in DynamicType

### ISSUE THREAD

**Issue by RuslanYaniuk** [raphw/byte-buddy#534]
Hi 

Consider this test as a description of the issue 
```java
    @Test
    public void test() throws IllegalAccessException, InstantiationException {
        DynamicType.Loaded dt = new ByteBuddy()
                .subclass(Object.class).make()
                .load(getClass().getClassLoader());
        Object value = dt.getLoaded().newInstance();

        Object object = new ByteBuddy()
                .subclass(Object.class)
                .defineField("field", value.getClass(), Visibility.PRIVATE)
                .make()
                .include(dt)
                .load(getClass().getClassLoader())
                .getLoaded()
                .newInstance();

        Field field = object.getClass().getDeclaredFields()[0];

        field.setAccessible(true);
        field.set(object, value);
    }
```

It produces

```
java.lang.IllegalArgumentException: Can not set net.bytebuddy.renamed.java.lang.Object$ByteBuddy$udyJSO0Y field net.bytebuddy.renamed.java.lang.Object$ByteBuddy$deJKZlZ0.field to net.bytebuddy.renamed.java.lang.Object$ByteBuddy$udyJSO0Y

	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at test.BeanBuilderTests.test(BeanBuilderTests.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by raphw** [comment]
This is because the class of `value` is not the same as that referenced in the field. If you call `load` without an explicit strategy, a new class loader is created with the provided class loader as a parent. If you include the dynamic type in the second class, this child class loader will load the first class individually.

If you called `field.getType().newInstance()`, it would work. Also, skip the first loading of a type to avoid the duplicate loading.

**Comment by RuslanYaniuk** [comment]
Thanks for your quick reply. 
So, if I want to create a type based on the previously generated types it's important not to load and use them before I finish the creation of the final type, is it correct?

**Comment by raphw** [comment]
You just have to make sure that the second type can see the class loader of the first type. If you include a dynamic type in another one, you instruct the library to load them in the same class loader, no matter what strategy you are using. Have a look at `ClassLoadingStrategy` for considering your options.
