### ISSUE TITLE
LambdaInstrumentationStrategy doesn't seem to handle regex lib from Java10

### ISSUE THREAD

**Issue by mar-kolya** [raphw/byte-buddy#558]
Please see this branch to reproduce the problem: https://github.com/mar-kolya/byte-buddy/commits/LambdaInstrumentationStrategy-failure

Essentially I take regex code from Java10 and try to create an instance of a `Pattern` with `LambdaInstrumentationStrategy` enabled.

I get this error:

```
java.lang.BootstrapMethodError: call site initialization exception

	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at test.regex.Pattern.Single(Pattern.java:6020)
	at test.regex.Pattern.single(Pattern.java:2846)
	at test.regex.Pattern.atom(Pattern.java:2327)
	at test.regex.Pattern.sequence(Pattern.java:2217)
	at test.regex.Pattern.expr(Pattern.java:2071)
	at test.regex.Pattern.group0(Pattern.java:3093)
	at test.regex.Pattern.sequence(Pattern.java:2125)
	at test.regex.Pattern.expr(Pattern.java:2071)
	at test.regex.Pattern.compile(Pattern.java:1783)
	at test.regex.Pattern.<init>(Pattern.java:1417)
	at test.regex.Pattern.compile(Pattern.java:1065)
	at net.bytebuddy.agent.builder.AgentBuilderDefaultApplicationTest.testNonCapturingLambda(AgentBuilderDefaultApplicationTest.java:577)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoClassDefFoundError: test/regex/Pattern$$Lambda$ByteBuddy$1
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at java.lang.invoke.LambdaMetafactory.metafactory(Unknown Source)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 45 more
Caused by: java.lang.ClassNotFoundException: test.regex.Pattern$$Lambda$ByteBuddy$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
```

On another project I've observed error that looks like this:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at datadog.trace.agent.TracingAgent.startAgent(TracingAgent.java:85)
        at datadog.trace.agent.TracingAgent.premain(TracingAgent.java:39)
        ... 6 more
Caused by: java.lang.IncompatibleClassChangeError: Interface method reference: java.util.regex.Pattern$BmpCharPredicate.union(Ljava/util/regex/Pattern$CharPredicate;)Ljava/util/regex/Pattern$CharPredicate;, is in an indirect superinterface of java.ut
        at java.base/java.util.regex.CharPredicates$$Lambda$ByteBuddy$19/874740624.union(Unknown Source)
        at java.base/java.util.regex.Pattern.clazz(Pattern.java:2674)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2108)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2038)
        at java.base/java.util.regex.Pattern.group0(Pattern.java:2944)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2093)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2038)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1760)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1409)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1065)
        at datadog.trace.agent.ot.decorators.URLAsResourceName.<clinit>(URLAsResourceName.java:16)
        at datadog.trace.agent.ot.decorators.DDDecoratorsFactory.createBuiltinDecorators(DDDecoratorsFactory.java:10)
        at datadog.trace.agent.ot.DDTracer.<init>(DDTracer.java:184)
        at datadog.trace.agent.ot.DDTracer.<init>(DDTracer.java:97)
        at datadog.trace.agent.ot.DDTracer.<init>(DDTracer.java:93)
        at datadog.trace.agent.ot.DDTracer.<init>(DDTracer.java:81)
        at datadog.trace.agent.tooling.TracerInstaller.installGlobalTracer(TracerInstaller.java:11)
        ... 12 more
```

Unfortunately I cannot reproduce that in simple setting yet, but my hope is that first and second errors are somehow related.

Please let me know if I can provide any additional information.

Thanks!

**Comment by mar-kolya** [comment]
After doing some digging it looks like the problem may be related to bridge methods being generated for anonymous class. It looks like somehow `defineAnonymousClass` doesn't like that - and this seems to result in its failure to define the lambda class.
It looks like that anything that gets those bridge methods not defined fixes at least first problem. For example I've tried adding `&& !methodDescription.isDefaultMethod()` to line 489 of `MethodRegistry`.

Unfortunately I do not quite understand what exactly is wrong with bridge methods in anonymous class:

```
  public test.regex.Pattern$CharPredicate union(test.regex.Pattern$CharPredicate);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #32                 // InterfaceMethod test/regex/Pattern$BmpCharPredicate.union:(Ltest/regex/Pattern$CharPredicate;)Ltest/regex/Pattern$CharPredicate;
       5: areturn
```

so I'm not sure what is the correct fix for this at the moment.

**Comment by raphw** [comment]
Are you sure this is not related to a circularity? Byte Buddy uses strings to work and the string class probably defined lambdas. This strategy is a rather heavy interception for very narrow use cases, I expect it to fail sometimes.

**Comment by mar-kolya** [comment]
I'm pretty sure this is not related to circularity for the following reasons:

* If I make `BmpCharPredicate` public (and not package-private) things start to work
* If I change byte-buddy to not inject bridge methods for default interface things start to work
* I've compared lambda class generated by byte-buddy and lambda class generated by 'stock' java lib - the only difference are those bridge methods.

So overall problem seems to be some weird interaction between bridge methods and `Unsafe. defineAnonymousClass`.

**Comment by raphw** [comment]
Maybe the bridge methods reference a class that is then loaded and causes a problem. I find the error message strange about the indirect superinterface.

I wonder if it would be sensible to just deactivate the bridge method generation for the lambda factory. But to be honest, I do not fully understand what the actual problem is.

Could you create a small reproduction project for me to run? I would then try to debug this.

**Comment by mar-kolya** [comment]
Please have a look here: https://github.com/mar-kolya/byte-buddy/commit/2b02266b53c3307f2ea3f0e77b1e43aed22a26e5 . I've added a test that demonstrates the problem - and even a commented out piece of code that seems to fix it.

> I find the error message strange about the indirect superinterface.

As I mentioned in my original bug report I cannot yet reproduce this in isolation from our whole project. But I have a feeling that first error there (`java.lang.NoClassDefFoundError: test/regex/Pattern$$Lambda$ByteBuddy$1`) is actually related, maybe its just a different manifestation of the same problem.

> I wonder if it would be sensible to just deactivate the bridge method generation for the lambda factory. 

This is what java lib seems to be doing.

If I may make another suggestion here: I think it would be nice to make `MetaFactoryRedirection`(and `AlternativeMetaFactoryRedirection`) to fallback to 'standard' implementation if replacement one fails (i.e. throws exception when tries to create lambda class). The way things are currently means that using `AgentBuilder.LambdaInstrumentationStrategy.ENABLED` affects all lambdas - even ones we do not want to instrument in any sensible way. And this in turn opens potential for errors like this one - which otherwise would have been ignored because we have no interest in instrumenting pattern matching guts.

**Comment by mar-kolya** [comment]
@raphw I've also pulled out a self contained example:

```
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.agent.builder.AgentBuilder;

public class Main {

    public static class HiddenInterfaceTestClass {
        @FunctionalInterface
        interface HiddenInterface {
            default boolean defaultMethod() {
                return false;
            }
            boolean func();
        }
        public static HiddenInterface packagePrivateInterface() {
            return () -> true;
        }
    }

    public static void main(String... args) {
        ByteBuddyAgent.install();
        new AgentBuilder.Default()
                .with(AgentBuilder.LambdaInstrumentationStrategy.ENABLED)
                .installOn(ByteBuddyAgent.getInstrumentation());

        HiddenInterfaceTestClass.packagePrivateInterface();
    }

}
```

This blows up with:

```
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at Main$HiddenInterfaceTestClass.packagePrivateInterface(Main.java:15)
	at Main.main(Main.java:25)
Caused by: java.lang.NoClassDefFoundError: Main$HiddenInterfaceTestClass$$Lambda$ByteBuddy$1
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 4 more
Caused by: java.lang.ClassNotFoundException: Main$HiddenInterfaceTestClass$$Lambda$ByteBuddy$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

Removing `.with(AgentBuilder.LambdaInstrumentationStrategy.ENABLED)` makes it not fail. This affects 1.9.4 as well.

**Comment by tylerbenson** [comment]
@raphw Is there anything else we can provide to help troubleshoot/fix this? Should we look into submitting a PR?

**Comment by raphw** [comment]
I think this is a class loading racing condition. The lambda meta factory is instrumented while the agent is loaded what probably causes the failure.

Are you using this strategy in production systems? This is quite risky as the strategy is fairly instable to begin with.

I do not have much time in the moment as this issue is so peticular but please send a PR my way and I will look into it!

**Comment by raphw** [comment]
Please reopen if there are further questions.
