### ISSUE TITLE
java.lang.IllegalStateException: No compatible attachment provider is available

### ISSUE THREAD

**Issue by Technerder** [raphw/byte-buddy#565]
public class MinecraftInjector {
	
		public static void agentmain(String args, Instrumentation instrumentation) {
			System.out.println("Loaded!");
		}
	
		public static void main(String[] args) {
	
			try {
	
				ByteBuddyAgent.attach(new File(MinecraftInjector.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()), "14276");
	
			} catch (URISyntaxException e) {
				e.printStackTrace();
			}
		}
	
	}

Keeps throwing this error:

	Exception in thread "main" java.lang.IllegalStateException: No compatible attachment provider is available
			at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:389)
			at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:248)
			at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:223)
			at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:210)
			at com.technerder.minecraftinjector.MinecraftInjector.main(MinecraftInjector.java:19)

On Java version 1.8.0_192

Any ideas on how to fix this issue?

**Comment by raphw** [comment]
Are you sure that you are running on a JDK? This will not work on a regular JVM/Android.

**Comment by raphw** [comment]
Please reopen the ticket if you have further questions.
