### ISSUE TITLE
TypePool caching error for classes loaded by Bootstrap ClassLoader

### ISSUE THREAD

**Issue by eyalkoren** [raphw/byte-buddy#573]
**Problem description:** we use ByteBuddy with our Java agent (and it's awesome :)). We use it with the `DescriptionStrategy.Default#POOL_ONLY` strategy. We provide an API that is implemented as a noop so that it does not depend on our agent code. When an agent is installed, we use BB to instrument functionality into these API classes. I tried to add the API classes to the agent jar, which is loaded from the Bootstrap CL, and BB fails to instrument them. I debugged and saw that while resolving two of our API classes, BB tries to verify that the return type of a method is visible to the instrumented class. While doing so, it uses a `ClassFileLocator` that is not properly constructed to locate the return type (another API class colocated at the same jar), which leads to `TypePool.Resolution.Illegal`, which fails the instrumentation.

**How to reproduce:** It can probably be reproduced otherwise, but since it happens in certain scenarios and not others, I will just instruct how to reproduce with our code: clone [our GitHub repo](https://github.com/elastic/apm-agent-java) and edit `elastic-apm-agent/pom.xml` to include the api classes into the agent jar as follows:
```
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>apm-agent-api</artifactId>
            <version>${project.version}</version>
        </dependency>
```
Then build (`mvn clean install -PskipTests=true`), attach the agent to the simplest Java app that makes a basic use of `co.elastic.apm.api.ElasticApm` and run.
If you want to debug the BB code, un-shade it by commenting out the following in same pom:
```
     <relocation>
         <pattern>net.bytebuddy</pattern>
         <shadedPattern>co.elastic.apm.shaded.bytebuddy</shadedPattern>
     </relocation>
```

**Workaround:** revert the first pom change to exclude the API code from the agent jar, build and add the API jar (located at `apm-agent-api/target`) to the classpath or put in the JRE `lib/ext` dir. Apparently this problem is specific to the Bootstrap CL.

**Comment by raphw** [comment]
Glad you like the library. I am not sure that this is a bug in Byte Buddy, it is not possible to locate class files of classes that were appended to the bootstrap class loader (this is why the corresponding method is called "appendToBootLoaderSearch" with emphasis on the search-bit.

In this case, you would need to adjust the class file locator that is provided to the agent where it would make a normal lookup but also check the location of your boot jar for class files. There is no other way around it.

**Comment by eyalkoren** [comment]
I see. So one option is to not fail due to resolving of dependencies of bootstrap classes (can make this optional) and the other is to enable jar search only for bootclasspath jars.
Do you see any of those interesting or do you want to close this issue?

**Comment by raphw** [comment]
What do you mean by "not fail"? Byte Buddy is already resolving all types lazily, if it is asked for example if a certain type is a subtype of another type, there is no way around it. If you want to ignored failed resolutions in matchers, have a look at `ElementMatchers::failSafe`.

I would recommand you to register your jar into the class file locator that is used, that way, Byte Buddy will not have any issues.

**Comment by eyalkoren** [comment]
> What do you mean by "not fail"? 
In this case I only match for type name and method name, so I don't expect to check (and fail due to) anything other than that.

**Comment by raphw** [comment]
Can you send me a stack trace?

**Comment by eyalkoren** [comment]
```
2018-12-04 15:36:57.880 [default task-6] DEBUG co.elastic.apm.impl.ElasticApmTracer - startTransaction '' 00-9c53093e2fe9d9a4093a604c67700ae1-89c38846d64d055b-01 {
2018-12-04 15:36:57.881 [default task-6] DEBUG co.elastic.apm.impl.ElasticApmTracer - Activating '' 00-9c53093e2fe9d9a4093a604c67700ae1-89c38846d64d055b-01 on thread 128
2018-12-04 15:36:57.885 [default task-6] DEBUG co.elastic.apm.bci.ElasticApmAgent - Type match for advice StartTransactionInstrumentation: name(equals(co.elastic.apm.api.ElasticApm)) matches class co.elastic.apm.api.ElasticApm
2018-12-04 15:36:57.885 [default task-6] DEBUG co.elastic.apm.bci.ElasticApmAgent - Type match for advice CurrentTransactionInstrumentation: name(equals(co.elastic.apm.api.ElasticApm)) matches class co.elastic.apm.api.ElasticApm
2018-12-04 15:36:57.886 [default task-6] DEBUG co.elastic.apm.bci.ElasticApmAgent - Type match for advice CurrentSpanInstrumentation: name(equals(co.elastic.apm.api.ElasticApm)) matches class co.elastic.apm.api.ElasticApm
2018-12-04 15:36:57.887 [default task-6] DEBUG co.elastic.apm.bci.ElasticApmAgent - Type match for advice CaptureExceptionInstrumentation: name(equals(co.elastic.apm.api.ElasticApm)) matches class co.elastic.apm.api.ElasticApm
2018-12-04 15:36:57.901 [default task-6] WARN co.elastic.apm.bci.bytebuddy.ErrorLoggingListener - ERROR on transformation co.elastic.apm.api.ElasticApm
java.lang.IllegalStateException: Cannot resolve type description for co.elastic.apm.api.Transaction
	at co.elastic.apm.shaded.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
	at co.elastic.apm.shaded.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
	at co.elastic.apm.shaded.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8115)
	at co.elastic.apm.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
	at co.elastic.apm.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
	at co.elastic.apm.shaded.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7631)
	at co.elastic.apm.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
	at co.elastic.apm.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
	at co.elastic.apm.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
	at co.elastic.apm.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
	at co.elastic.apm.shaded.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:48)
	at co.elastic.apm.shaded.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:27)
	at co.elastic.apm.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at co.elastic.apm.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at co.elastic.apm.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at co.elastic.apm.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at co.elastic.apm.shaded.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at co.elastic.apm.shaded.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:496)
	at co.elastic.apm.shaded.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:189)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10050)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10469)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10432)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10198)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10807)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10754)
	at java.security.AccessController.doPrivileged(Native Method)
	at co.elastic.apm.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10355)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:386)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	at co.elastic.webapp.TestServlet.doGet(TestServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
...
```

**Comment by eyalkoren** [comment]
OK, I will look into that. Thanks!
