### ISSUE TITLE
byte-buddy-maven-plugin Spring boot Controller instrument bug

### ISSUE THREAD

**Issue by shuvigoss** [raphw/byte-buddy#582]
hello @raphw 

```
public ReturnResult<FileInfo> fileInfo(@RequestParam String id, String token,
      @RequestParam String appId) {
    return ReturnResult.success(filesService.info(id, token, appId));
  }
```

if intercept this method will lost LocalVariableTable  Lead to Spring Mvc parse param error

```
java.lang.IllegalArgumentException: Name for argument type [java.lang.String] not available, and parameter name information not found in class file either.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:168)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:145)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:94)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
```

see `org.springframework.core.LocalVariableTableParameterNameDiscoverer`
![image](https://user-images.githubusercontent.com/3062921/50808283-bce91900-1338-11e9-93e5-34662e5775c1.png)

![image](https://user-images.githubusercontent.com/3062921/50812458-cf218200-134d-11e9-8c29-b44a4cdf5c17.png)

**Comment by raphw** [comment]
I assume that you are using rebasing together with an interceptor? In this case, you are correct. Spring is in a way applying a hack here where the name is extracted from the debug attributes for the method. If the method is rebased, this debug attributes are also moved.

Java 8 added an official way of adding names for parameters by compiling with the *-parameters* flag what also improves performance slighly if you enable it. This should not be affected.

**Comment by shuvigoss** [comment]
@raphw thx 
-parameters flag works fine because spring will use org.springframework.core.DefaultParameterNameDiscoverer to get param name,i think rebasing method should keep all  origin method info :)

**Comment by raphw** [comment]
I think this is the way to go here, remapping debugging attributes would just result in a mess.
