### ISSUE TITLE
Byte Buddy's method delegation leads to StackOverflowError

### ISSUE THREAD

**Issue by dvelopp** [raphw/byte-buddy#585]
When I try to proxy all the classes in applications that are run on Spring Boot, it leads me to StackOverflowError. 
e.g.
```
java.lang.StackOverflowError: null
at com.dvelopp.agenttest.MethodCallContext.getCaller(MethodCallContext.java:18)
at com.dvelopp.agenttest.Main$Interceptor.intercept(Main.java:108)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.MapPropertySource.getSource(MapPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource$accessor$d92Pg8OK(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource$auxiliary$ATPz5tSr.call(Unknown Source)
at com.dvelopp.agenttest.Main$Interceptor.intercept(Main.java:122)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.MapPropertySource.getSource(MapPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource$accessor$d92Pg8OK(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource$auxiliary$ATPz5tSr.call(Unknown Source)
at com.dvelopp.agenttest.Main$Interceptor.intercept(Main.java:122)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.MapPropertySource.getSource(MapPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource.getSource$accessor$d92Pg8OK(SystemEnvironmentPropertySource.java)
at org.springframework.core.env.SystemEnvironmentPropertySource$auxiliary$ATPz5tSr.call(Unknown Source)
at com.dvelopp.agenttest.Main$Interceptor.intercept(Main.java:122)
```
It can easily been reproduced with using my agent:
https://github.com/dvelopp/agent_template
When you run it on the default "complete" project from here:
https://spring.io/guides/gs/spring-boot/

I could also reproduce the same with my agent on other Spring Based applications. 
I tried the same with Advice approach and I faced the same issue.

Strackoverflow discussion:
https://stackoverflow.com/questions/54136831/byte-buddys-method-delegation-leads-to-stackoverflowerror?noredirect=1#comment95174068_54136831

**Comment by dvelopp** [comment]
Updated the link to my agent.

**Comment by raphw** [comment]
As a start, you should not instrument the Byte Buddy classes, this might initiate this problem.

**Comment by raphw** [comment]
One last exclusion before I look into it: Please exclude synthetic types as you might hit Byte Buddy proxies that live in different packages,

**Comment by dvelopp** [comment]
@raphw , added:
`.or(ElementMatchers.isSynthetic())`
https://github.com/dvelopp/agent_template/blob/master/src/main/java/com/dvelopp/agenttest/Main.java
The same problem persists.

**Comment by raphw** [comment]
Sorry for not getting back to you. Did you ever solve your problem?

I still think that you have instrumented two types in recurisve relationship to one another.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
