### ISSUE TITLE
Invoke original method with different arguments without importing the original class

### ISSUE THREAD

**Issue by CROSP** [raphw/byte-buddy#600]
Hi,

First of all, thank you for this awesome tool.
I am trying to intercept a method. Firstly, instantiating `Agent`.

```
public class TestAgent {
    public static void premain(String arguments,
                               Instrumentation instrumentation) {
        System.out.println("CREATING AGENT");
        new AgentBuilder.Default()
                .with(AgentBuilder.Listener.StreamWriting.toSystemError())
                .type(named("com.test.example.SimpleClass"))
                .transform((builder, type, classLoader, module) ->
                        builder.method(named("greet"))
                                .intercept(MethodDelegation.to(ErrorLoggingInterceptor.class))
                ).installOn(instrumentation);
        //interceptErrorLogging();
    }
}
```
And my `ErrorLoggingInterceptor` class is defined as follows.

```
public class ErrorLoggingInterceptor {
    @RuntimeType
    public static String intercept(@AllArguments Object[] allArguments,
                                   @Origin Method method,
                                   @SuperCall Callable<?> callableMethod,
                                   @Super Object superObject) throws Exception {
        Arrays.stream(allArguments).forEach(o -> System.out.println(o.toString()));
        System.out.println("INTERCEPTING");
        System.out.println(superObject);
        System.out.println("RESULT FROM ORIGINAL METHOD " + callableMethod.call());
        System.out.println("AFTER CALLING");
        return "FROM INTERCEPTOR";
    }
}
```

But I need to call original method with different arguments. So I tried the following code 

` System.out.println("ORIGINAL METHOD INVOCATION : " + method.invoke(superObject, allArguments));`

But got the error
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
```

However when I log the method object and the original object itself I get valid class names, without proxies of auxilary. 

```
com.test.example.SimpleClass@72a7c7e0
public java.lang.String com.test.example.SimpleClass.greet(java.lang.String)
```
In your tutorial you showed a way to invoke a method on a `SuperObject` itself, howeve I cannot import the original object class 
Could you please suggest how to solve the issue?

**Comment by raphw** [comment]
Hi, I think you want to:

```java
@RuntimeType
public static String intercept(@AllArguments Object[] allArguments,
                                   @SuperMethod Method superMethod,
                                   @SuperCall Callable<?> callableMethod,
                                   @This Object self) throws Exception {
  return (String)  superMethod.invoke(self, allArguments);
}

**Comment by CROSP** [comment]
@raphw Thank you so much for the instant response. Your code snippet works like a charm.
Appreciate your help!

**Comment by raphw** [comment]
Glad it works!
