### ISSUE TITLE
ByteBuddyAgent.install() failure error missing details

### ISSUE THREAD

**Issue by rendaw** [raphw/byte-buddy#607]
In my case the agent installation failed because a required module wasn't in module-info.java - this module is listed in the actual error from various calls within the AttachmentProvider but they are swallowed and `Unloaded.INSTANCE` is returned instead, which raises an error with no details.

**Comment by raphw** [comment]
I think the module dependency is declared to be static as it is possible to attach when including a Linux socket connection or a custom attachment mechanism. Could you give me the stack trace to better understand what happened?

**Comment by rendaw** [comment]
To clarify, this ticket is about the error message being unclear rather than confusion about required libraries (although I didn't see anything regarding this in the documentation).  Here's the stack trace:
```
Exception in thread "main" java.lang.IllegalStateException: No compatible attachment provider is available
	at net.bytebuddy.agent/net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:389)
	at net.bytebuddy.agent/net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:374)
	at net.bytebuddy.agent/net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:342)
	at net.bytebuddy.agent/net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:328)
	at test2/test2.Main.main(Main.java:7)
```

**Comment by raphw** [comment]
I will consider changing the message but I think I should make the javadoc more clear.

**Comment by raphw** [comment]
I clarified the javadoc.
