### ISSUE TITLE
Adding external jvm agent breaks internal ByteBuddyAgent, NexusAccessor

### ISSUE THREAD

**Issue by safasofuoglu** [raphw/byte-buddy#616]
Hello, we had an internal ByteBuddyAgent configured and running without issues. Right now we are trying to integrate datadog APM agent, which is also utilizing ByteBuddy.

When we try to run with the added datadog agent through
`java -javaagent:dd-java-agent.jar -jar backend.jar`
it fails, complaining about IllegalAccessError for field `net.bytebuddy.dynamic.Nexus.NO_QUEUE`:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalAccessError: tried to access field net.bytebuddy.dynamic.Nexus.NO_QUEUE from class net.bytebuddy.dynamic.NexusAccessor
    at net.bytebuddy.dynamic.NexusAccessor.<init>(NexusAccessor.java:68)
    at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Split.<init>(AgentBuilder.java:3169)
    at net.bytebuddy.agent.builder.AgentBuilder$Default.<init>(AgentBuilder.java:8397)
    at net.bytebuddy.agent.builder.AgentBuilder$Default.of(AgentBuilder.java:8577)
    at net.bytebuddy.agent.builder.AgentBuilder$Default.of(AgentBuilder.java:8531)
    at net.bytebuddy.agent.builder.AgentBuilder$Default.of(AgentBuilder.java:8520)
    at config.DataPreprocessor.install(DataPreprocessor.kt:39)
```

The error goes away if we disable nexus in the main application, but we're not sure about the consequences of doing so.

Please advise.

Thanks,

**Comment by raphw** [comment]
Ok, I was dumb here. I assume that Datadog runs Byte Buddy on the boot loader where the class loader now differs such that the field is no longer visible. I need to move the constant to the accessor, of course.

I will fix this in the next version.

**Comment by safasofuoglu** [comment]
Thanks @raphw . Is there a workrdound you can suggest in the meantime? We are okay to move things around to get this working, if there's a way.

**Comment by raphw** [comment]
You can scan the DD jar and disable the nexus using the property in the rebased namespace. I am pretty sure you do not need it there.

**Comment by raphw** [comment]
I fixed the issue on master, if you use the snapshot version in the mean-time, this should also solve your problem!
