### ISSUE TITLE
Child-first class loading cause deadlock on startup

### ISSUE THREAD

**Issue by honganan** [raphw/byte-buddy#632]
Hi, Sorry I am here to trouble you again. We caught thread deadlock when application start. The situation is very much like with your answer of this issue: https://github.com/stagemonitor/stagemonitor/issues/179

We have a child-first class loader to load any class including the application's main class. This loading process starts from application's maven package phrase. And when application init it starts multi thread to do other things. Child-first class loader, and async initialization matches 
 with your description in above issue.
Here is my deadlock detection log from `jstack`. What strange is the 'main' thread is waiting a int array lock, that confused us very.

```
Found one Java-level deadlock:
=============================
"pool-3-thread-1":
  waiting to lock monitor 0x00007f9ce0006168 (object 0x000000076ccd0000, a com.youzan.aladdin.container.loader.AladdinClassLoader),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007f9ce0003f08 (object 0x000000076cd06008, a [I),
  which is held by "Apollo-RemoteConfigRepository-1"
"Apollo-RemoteConfigRepository-1":
  waiting to lock monitor 0x00007f9ce0006168 (object 0x000000076ccd0000, a com.youzan.aladdin.container.loader.AladdinClassLoader),
  which is held by "main"

Java stack information for the threads listed above:
===================================================
"pool-3-thread-1":
	at com.youzan.aladdin.extend.report.SkyNetReporter.run(SkyNetReporter.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"main":
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1034)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1019)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1099)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1174)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7075)
	at net.bytebuddy.matcher.ModifierMatcher.matches(ModifierMatcher.java:31)
	at net.bytebuddy.matcher.ModifierMatcher.matches(ModifierMatcher.java:12)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1210)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:9337)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at com.youzan.aladdin.container.loader.AbstractCommonClassLoader.defineClass(AbstractCommonClassLoader.java:228)
	at com.youzan.aladdin.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:257)
	at com.youzan.aladdin.container.loader.AbstractCommonClassLoader$1.run(AbstractCommonClassLoader.java:251)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.youzan.aladdin.container.loader.AbstractCommonClassLoader.findCustomClass(AbstractCommonClassLoader.java:250)
	at com.youzan.aladdin.container.loader.AbstractCommonClassLoader.loadCustomClass(AbstractCommonClassLoader.java:291)
	at com.youzan.aladdin.container.loader.AladdinClassLoader.loadClass(AladdinClassLoader.java:138)
	- locked <0x000000076ccd0000> (a com.youzan.aladdin.container.loader.AladdinClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.youzan.aladdin.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at com.youzan.aladdin.boot.loader.Launcher.launch(Launcher.java:83)
	at com.youzan.aladdin.boot.loader.Launcher.launch(Launcher.java:50)
	at com.youzan.aladdin.boot.loader.JarLauncher.main(JarLauncher.java:52)
"Apollo-RemoteConfigRepository-1":
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1034)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1019)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1099)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1174)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7075)
	at net.bytebuddy.matcher.ModifierMatcher.matches(ModifierMatcher.java:31)
	at net.bytebuddy.matcher.ModifierMatcher.matches(ModifierMatcher.java:12)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1210)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:9337)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1852)
	- locked <0x000000076cd0c428> (a sun.net.www.protocol.http.HttpURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	- locked <0x000000076cd0c428> (a sun.net.www.protocol.http.HttpURLConnection)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.ctrip.framework.apollo.util.http.HttpUtil.doGetWithSerializeFunction(HttpUtil.java:96)
	at com.ctrip.framework.apollo.util.http.HttpUtil.doGet(HttpUtil.java:49)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:216)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:131)
	- locked <0x000000076cd75378> (a com.ctrip.framework.apollo.internals.RemoteConfigRepository)
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**Comment by raphw** [comment]
The problem is as described in the linked ticket. Thread A awaits loading a class from a loader that is currently loaded from thread B and vice versa. If you load Byte Buddy, you add to the classes being loaded such that this lock occurs. 

To solve this, you need to exclude more classes from your agent or preload classes to not block the loading process.

**Comment by honganan** [comment]
I get it. Now I add a class loader ignore matcher when I new the `AgentBuilder.Default` like blow, In our situation, every class is loaded by our child first class loader. And if we limit only classes that loading by this class loader will be enhanced then this problem can be avoid right? This is how we install and set the agent:
```java
            ByteBuddyAgent.install();

            PluginFinder pluginFinder = new PluginFinder(getPlugins());
            new AgentBuilder.Default()
                .ignore(
                    new MyDisjunction(
                        new AgentBuilder.RawMatcher.ForElementMatchers(any(), new NullMatcher<>().or(not(new EqualityMatcher<>(loader)))),
                        new AgentBuilder.RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.")
                            .or(nameStartsWith("org.slf4j."))
                            .or(nameStartsWith("ch.qos.logback."))
                            .or(nameStartsWith("org.apache.logging."))
                            .or(nameStartsWith("com.youzan.aladdin."))
                            .or(nameStartsWith("org.groovy."))
                            .or(nameContains("javassist"))
                            .or(nameContains(".asm."))
                            .or(allRontgenSnifferExcludeToolkit())
                            .or(nameStartsWith("sun.reflect."))
                            .or(ElementMatchers.<TypeDescription>isSynthetic())))
                )
                .type(pluginFinder.buildMatch())
                .transform(new Transformer(pluginFinder))
                .with(new Listener())
                .installOnByteBuddyAgent();
```

**Comment by raphw** [comment]
Yes, a lock happens if you load classes from a loader that needs to lock another loader to load a dependant class which is currently loaded by another thread that requires the first loader to load a dependant.

**Comment by honganan** [comment]
Thanks! Thank you for professional analysis! We are first time to use byte-buddy to manipulate byte code in our production environment. It's really a nice framework. I will study more about it.

**Comment by raphw** [comment]
Glad I could help, please reopen if there is more to do.

**Comment by honganan** [comment]
We still found DeadLock in production env after doing the above filter. In extremely case, A parent class loader load some class triggers `AgentBuilder$Default$ExecutingTransformer#transform` execute, which should load classes like `JavaModule` and 'java.lang.Module'. These happens before the `ignoreMatcher` works in `AgentBuilder.Default.ExecutingTransformer#resolve`. These will still probably dead lock in Child-first class loader situation.
 Finally our solution is filter before enter the `AgentBuilder$Default$ExecutingTransformer#transform` to avoid loading any byte-buddy class by creating a proxy like transformer:
```java
Instrumentation instrumentation = ByteBuddyAgent.install();

PluginFinder pluginFinder = new PluginFinder(getPlugins());
ResettableClassFileTransformer classFileTransformer = new AgentBuilder.Default()
    .ignore(
        new MyDisjunction(
            new AgentBuilder.RawMatcher.ForElementMatchers(any(), new NullMatcher<>().or(not(new EqualityMatcher<>(loader)))),
            new AgentBuilder.RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.")
                .or(nameStartsWith("org.slf4j."))
                .or(nameStartsWith("ch.qos.logback."))
                .or(nameStartsWith("org.apache.logging."))
                .or(nameStartsWith("org.groovy."))
                .or(nameContains("javassist"))
                .or(nameContains(".asm."))
                .or(nameStartsWith("sun.reflect."))
                .or(ElementMatchers.<TypeDescription>isSynthetic())))
    )
    .type(pluginFinder.buildMatch())
    .transform(new Transformer(pluginFinder))
    .with(new Listener())
    .installOnByteBuddyAgent();

boolean removeResult = instrumentation.removeTransformer(classFileTransformer);
if (!removeResult) {
    logger.error("apm classfiletransformer proxy failed");
    return;
}
instrumentation.addTransformer(new MyClassFileTransformer(classFileTransformer, loader), false);
```
and in `MyClassFileTransformer` we filter the class loader before call the byte-buddy's transformer:
```java
@Override
public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined,
    ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {

    try {
        if (targetClassLoader != loader) {
            return classfileBuffer;
        }
        String normalizedClassName = className.replaceAll("/", ".");
        if (normalizedClassName.startsWith("...")) {
            return classfileBuffer;
        }

        return classFileTransformer.transform(loader, className, classBeingRedefined, protectionDomain, classfileBuffer);
    } catch (Throwable t) {
        logger.warn("transform class {} exception: {}", className, t);
        return classfileBuffer;
    }
}
```

**Comment by raphw** [comment]
Glad you solved it. You can still use Byte Buddy's API by registering a `TransformerDecorator` that returns a delegating transformer.

**Comment by honganan** [comment]
Wow! This new fresh feature is exactly what we want. Nice! We are using version 1.7.9-RELEASE and We will upgrade to latest version to use this more graceful feature.

**Comment by qsLI** [comment]
Any idea about the int array lock? 

To the best of my knowledge, the class of int[] type in JVM is built-in, and there should be no corresponding JVMTI event notification. However, from the call stack, it seems that bytebuddy has received the event of int array class loading. 

Moreover, the location of this lock cannot be found from the output of jstack, it should be a C++ level lock. If it is a classloader lock, the output should not be [I, so it can only be an initialization lock.

We have also encountered cases of waiting for the int array lock in production, which may be the init lock of the int array.

![image](https://github.com/raphw/byte-buddy/assets/6805785/ee244d2c-dd7e-49f0-81d9-c8e1ce5f9530)

![image](https://github.com/raphw/byte-buddy/assets/6805785/08211d72-a541-49b2-8319-9ae0e63fa78c)

**Comment by honganan** [comment]
> Any idea about the int array lock?
> 
> To the best of my knowledge, the class of int[] type in JVM is built-in, and there should be no corresponding JVMTI event notification. However, from the call stack, it seems that bytebuddy has received the event of int array class loading.
> 
> Moreover, the location of this lock cannot be found from the output of jstack, it should be a C++ level lock. If it is a classloader lock, the output should not be [I, so it can only be an initialization lock.
> 
> We have also encountered cases of waiting for the int array lock in production, which may be the init lock of the int array.
> 
> ![image](https://private-user-images.githubusercontent.com/6805785/300809418-ee244d2c-dd7e-49f0-81d9-c8e1ce5f9530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjkwOTAsIm5iZiI6MTcwNjY2ODc5MCwicGF0aCI6Ii82ODA1Nzg1LzMwMDgwOTQxOC1lZTI0NGQyYy1kZDdlLTQ5ZjAtODFkOS1jOGUxY2U1Zjk1MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDIzOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk0OGQzMTUzZjI0ZDIyZjI2ZWYxNGFhNTFkMjIxMmRmNTk5ZGY4ZWVmNDFlYzY2YTk1ZGYwZmI1YmYwMzBlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EVVVOTjCfXuEUfy4fA8ClvIrbaRcufxcUvyiq6H0tqo)
> 
> ![image](https://private-user-images.githubusercontent.com/6805785/300809507-08211d72-a541-49b2-8319-9ae0e63fa78c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjkwOTAsIm5iZiI6MTcwNjY2ODc5MCwicGF0aCI6Ii82ODA1Nzg1LzMwMDgwOTUwNy0wODIxMWQ3Mi1hNTQxLTQ5YjItODMxOS05YWUwZTYzZmE3OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDIzOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI4YzMwZTRlNTBkMzU1NjNjODdkN2IzNmQ1NTZhMWE3MjUzMGZmMWY3NmFhYTgxZWY4OWIxOTMwZTI0YzVmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._myNseN0zjz-WnP5uQSEf_TKEjIoQSBB6srP1n2kd5E)

The problem decribed in this issue occurs only if you break the parent delegation when loading class.

**Comment by qsLI** [comment]
> @qsLI The problem decribed in this issue occurs only if you break the parent delegation when loading class.

The [I lock is  init lock
```cpp
void java_lang_Class::initialize_mirror_fields(Klass* k,
                                               Handle mirror,
                                               Handle protection_domain,
                                               Handle classData,
                                               TRAPS) {
  // Allocate a simple java object for a lock.
  // This needs to be a java object because during class initialization
  // it can be held across a java call.
  typeArrayOop r = oopFactory::new_typeArray(T_INT, 0, CHECK);
  set_init_lock(mirror(), r);

  // Set protection domain also
  set_protection_domain(mirror(), protection_domain());

  // Initialize static fields
  InstanceKlass::cast(k)->do_local_static_fields(&initialize_static_field, mirror, CHECK);

 // Set classData
  set_class_data(mirror(), classData());
}
```
