### ISSUE TITLE
 java.lang.NoSuchMethodError: net.bytebuddy.dynamic.ClassFileLocator$ForClassLoader.read(Ljava/lang/Class;)[B

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#637]
I use this for this agent to instrument httpUrlConnection. But I fails to launch my agent in my service.

        File temp = Files.createTempDirectory("tmp").toFile();
        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation).inject(Collections.singletonMap(
                new TypeDescription.ForLoadedType(httpUrlConnectionInterceptor.class),
                ClassFileLocator.ForClassLoader.read(httpUrlConnectionInterceptor.class)));

        new AgentBuilder.Default(bytebuddy).enableBootstrapInjection(instrumentation, temp)
                .type(pluginFinder.buildMatch())
                .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))
                .installOn(instrumentation);

mistake information:

Exception in thread "main" java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoSuchMethodError: net.bytebuddy.dynamic.ClassFileLocator$ForClassLoader.read(Ljava/lang/Class;)[B
	at com.ivoyant.skyrunning.agent.SkyRunningAgent.premain(SkyRunningAgent.java:63)
	... 6 more

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by raphw** [comment]
Is there another version of Byte Buddy included in the project? Or is the agent missing alltogether? If you attach your agent, no dependencies are included if they are not bundled in the attached jar file.

**Comment by raphw** [comment]
Please reopen if there are further questions.
