### ISSUE TITLE
IBM J9 error

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#652]
Hi

SkyWalking gets reports from users in J9 VM. I am not familiar with that. Based on the logs,
https://github.com/apache/skywalking/issues/2652#issuecomment-492062199. SkyWalking ProtectiveShieldMatcher prints the logs, such as this
```
WARN 2019-05-14 10:58:35:839 main ProtectiveShieldMatcher :  Byte-buddy occurs exception when match type. 
java.lang.IllegalStateException: Cannot resolve type description for java.util.Properties
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:8024)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3619)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:314)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:281)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:53)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:31)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:160)
```

I tried to add some ignore rules for these classes, https://github.com/apache/skywalking/compare/j9-compatible , but look like doesn't work.

`ProtectiveShieldMatcher` is following our former discussion, it should just simply print the logs and return `false` as a fail-safe. 

```java
/**
 * In some cases, some frameworks and libraries use some binary codes tech too. From the community feedback, some of
 * them have compatible issues with byte-buddy core, which trigger "Can't resolve type description" exception.
 *
 * So I build this protective shield by a nested matcher. When the origin matcher(s) can't resolve the type, the
 * SkyWalking agent ignores this types.
 *
 * Notice: this ignore mechanism may miss some instrumentations, but at most cases, it's same. If missing happens,
 * please pay attention to the WARNING logs.
 *
 * @author wu-sheng
 */
public class ProtectiveShieldMatcher<T> extends ElementMatcher.Junction.AbstractBase<T> {
    private static final ILog logger = LogManager.getLogger(ProtectiveShieldMatcher.class);

    private final ElementMatcher<? super T> matcher;

    public ProtectiveShieldMatcher(ElementMatcher<? super T> matcher) {
        this.matcher = matcher;
    }

    public boolean matches(T target) {
        try {
            return this.matcher.matches(target);
        } catch (Throwable t) {
            logger.warn(t, "Byte-buddy occurs exception when match type.");
            return false;
        }
    }
}
```

But this time, it is JVM related classes or eclipse osgi related. does J9VM have some protection mechanism? How should I change the codes?

**Comment by wu-sheng** [comment]
Also, I noticed the following log
```
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
	at java.security.AccessController.doPrivileged(AccessController.java:386)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:201)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:447)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:331)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:155)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:800)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:581)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:786)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:764)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:741)
	at org.eclipse.osgi.framework.internal.core.MessageResourceBundle.load(MessageResourceBundle.java:208)
	at org.eclipse.osgi.util.NLS.initializeMessages(NLS.java:88)
	at org.eclipse.osgi.framework.internal.core.Msg.<clinit>(Msg.java:96)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:1010)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:966)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:549)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:484)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:275)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.launch(StartLevelManager.java:245)
	at org.eclipse.osgi.framework.internal.core.SystemBundle.resume(SystemBundle.java:155)
	at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:503)
	at org.eclipse.osgi.framework.internal.core.OSGi.launch(OSGi.java:51)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:289)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
	at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
	at org.eclipse.core.launcher.Main.run(Main.java:981)
	at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:340)
	at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:110)
```

Is the osgi class define mechanism causing some conflicts?

**Comment by PrettyJerry** [comment]
I also met the same question and eagerly look forward to your answer and solution.

**Comment by raphw** [comment]
That is strange, this class is on the boot loader and should also be visible. I assume that it has something to do with how the application is deployed. Under the covers, this means that `type.getClassLoader().getResourceAsStream("java/util/Properties.class)` returns `null`.

What class are you trying to instrument when this error occurs and what class loader is this class loaded by?

You can configure the agent to use a different `LocationStrategy`, for example one that also queries a class loader's parent directly if the class loader is of a given type. This can be helpful for OSGi-related class loaders that do not properly delegate to their parent.

**Comment by wu-sheng** [comment]
> What class are you trying to instrument when this error occurs and what class loader is this class loaded by?

From my understanding, SkyWalking doesn't plan to instrument any particular class at this moment. Because from the log, it is still in byte-buddy scan stage, no SkyWalking codes activated, except for `ProtectiveShieldMatcher` only.

> You can configure the agent to use a different LocationStrategy, for example one that also queries a class loader's parent directly if the class loader is of a given type. This can be helpful for OSGi-related class loaders that do not properly delegate to their parent.

I am not sure how I could set up the LocationStrategy. Currently, bytebuddy should is matching the classes based on the plugin matchers(https://github.com/apache/skywalking/blob/j9-compatible/apm-sniffer/apm-agent/src/main/java/org/apache/skywalking/apm/agent/SkyWalkingAgent.java#L94)

**Comment by wu-sheng** [comment]
>  Under the covers, this means that type.getClassLoader().getResourceAsStream("java/util/Properties.class) returns null.

I am confused about this too. Do you know any strategy in J9VM? Which is trying to refuse the user codes access it? Or, is this just because of unexpected class loader? Such as OSGI class loader?

**Comment by wu-sheng** [comment]
@pmq5205209 Any special setting on Websphere about the J9VM? Could you dig about that?

**Comment by pmq5205209** [comment]
> 
> 
> @pmq5205209 Any special setting on Websphere about the J9VM? Could you dig about that?

I did not change Websphere 7.0 except adding javaagent to server.xml and changing J9VM 1.6 to J9VM 1.7. I are sure that Websphere 7.0 can start successfully after change J9VM 1.6 to J9VM 1.7 without add SkyWalking javaagent to server.xml.

**Comment by wu-sheng** [comment]
@pmq5205209 I haven't used Websphere before. Is `server.xml` the way to change JVM argument for javaagent? In Weblogic, I think there is a UI page to add `-javaagent`.

**Comment by wu-sheng** [comment]
@pmq5205209 I am a little worried about the agent being loaded by a wrong class loader. @raphw Is this possible to trigger this issue?

**Comment by pmq5205209** [comment]
> 
> 
> @pmq5205209 I am a little worried about the agent being loaded by a wrong class loader. @raphw Is this possible to trigger this issue?

Sorry, I did not describe clearly. I had set "-javaagent:/.../skywalking-agent.jar" in the WebShpere's web console, and then I found 'genericJvmArguments="-javaagent:D:/skywalking-agent/skywalking-agent/skywalking-agent.jar"' in the server.xml.

**Comment by raphw** [comment]
You can set a location strategy in the `AgentBuilder` build process.

**Comment by wu-sheng** [comment]
@raphw could you show me some examples of how to do this? I should set the jar folder to locate classes?

**Comment by peng-yongsheng** [comment]
@pmq5205209 We can't see your environment, could you provide our a single VM with an installed Websphere and let us can log in it.

**Comment by wu-sheng** [comment]
>  We can't see your environment, could you provide our a single VM with an installed Websphere and let us can log in it.

@pmq5205209 please only share this in private, if you want.

**Comment by guojie0701** [comment]
> @pmq5205209 We can't see your environment, could you provide our a single VM with an installed Websphere and let us can log in it.

our env  is in private cloud, howerver we can do it in this way:  we strictly follow you advice to do testcases  including your  sourcecode  and jars

**Comment by guojie0701** [comment]
> > We can't see your environment, could you provide our a single VM with an installed Websphere and let us can log in it.
> 
> @pmq5205209 please only share this in private, if you want.

we can do it.

**Comment by wu-sheng** [comment]
@raphw What is the default locator of byte buddy if I did set? I assume we will need a `Compound` strategy? Such as the default one and `ClassFileLocator#ForFolder` together?

I am just guessing, trying to deliver a test version to them.

**Comment by raphw** [comment]
The default locator is one that uses the provided class loader of the instrumented class.

I would try a conpound locator that also searches the boot loader.

**Comment by wu-sheng** [comment]
@raphw I submitted PR https://github.com/apache/skywalking/pull/2708 , is this fitting for your suggestions?

**Comment by wu-sheng** [comment]
@raphw Interesting, if my PR changes are right, then based on https://github.com/apache/skywalking/pull/2708#issuecomment-493440215 , this issue isn't fixed by this.

**Comment by raphw** [comment]
You would need to return a compiund class file locator that contains both that locator and a ClassFileLocator.ForClassLoader that repreaents the current class loader.

**Comment by wu-sheng** [comment]
```java
            //Compound
            .with(new AgentBuilder.LocationStrategy.Compound(
                // Boot loader locator
                new AgentBuilder.LocationStrategy() {
                    @Override public ClassFileLocator classFileLocator(ClassLoader classLoader, JavaModule module) {
                        return ofBootLoader();
                    }
                },
                // and `ClassFileLocator.ForClassLoader.of(classLoader)`
                AgentBuilder.LocationStrategy.ForClassLoader.STRONG
            ))
```

I think I put the `LocationStrategy.Compound`. Do I miss anything?

**Comment by raphw** [comment]
No, my oversight.

And the same problem occurs?

That is very strange.

**Comment by wu-sheng** [comment]
@raphw Yes, they say so at here, https://github.com/apache/skywalking/pull/2708#issuecomment-493440215

Do you know anyone good at Websphere? I am guessing there is a special setting there. Something like doesn't allow to access the class file through class loader?

**Comment by wu-sheng** [comment]
Also, this is an very old WAS and J9VM. websphere 6.1+ J9VM 1.6.0

**Comment by raphw** [comment]
Could you run a simple program on it just with:

getClass().getClassLoader().getResourceAsStream("java/util/Properties.class")

I wonder if the JVM just does not allow class file lookups.

**Comment by wu-sheng** [comment]
@pmq5205209 could you try this in your codes? And share with us the logs of execution result.

**Comment by pmq5205209** [comment]
![图片](https://user-images.githubusercontent.com/19252220/57965800-69887680-797b-11e9-95ad-0733726b3f15.png)
Is that OK? I used the IBM jdk.

**Comment by pmq5205209** [comment]
![图片](https://user-images.githubusercontent.com/19252220/57965814-e1ef3780-797b-11e9-8b01-ec631c1733b8.png)

**Comment by raphw** [comment]
The code is looking right. Did you run it?

**Comment by wu-sheng** [comment]
@pmq5205209 Does SkyWalking report error, just in j9vm or in Websphere with j9vm? I think you said it was at Websphere.

Your main demo looks like don't run in Websphere.

**Comment by wu-sheng** [comment]
@pmq5205209 we need this demo codes run in the same environment. Including vm, os and web container. If your local j9vm could report the same error, please let's know.

**Comment by pmq5205209** [comment]
![图片](https://user-images.githubusercontent.com/19252220/57966492-2501d880-7985-11e9-92c1-5b9d4d62f1e9.png)
I add codes like this. I run the agent with WebShpere , I cannot find the logs that contain string "SkyWalkingAgent Debug".
"

**Comment by wu-sheng** [comment]
Add these codes in your application, with your own log, you don't need agent to run this test

**Comment by pmq5205209** [comment]
Sorry. I find logs in WebShpere's native_stdout.log. 
![图片](https://user-images.githubusercontent.com/19252220/57966636-57acd080-7987-11e9-8faa-0d5c64500055.png)

**Comment by raphw** [comment]
Then I assume that the container has run out of file handles. This causes an impossibility of opening new resource streams.

**Comment by wu-sheng** [comment]
Change the os file handler limit setting?

**Comment by raphw** [comment]
That or there is a resource leak where you only delay the problem and where the JVM unfortunately swallows IO exceptions from the method in question.

**Comment by PrettyJerry** [comment]
ulimit  the open file 1024 ---> 65525 or unlimited ?

**Comment by wu-sheng** [comment]
@PrettyJerry Yes. Try unlimited and see what happens, with the agent.

**Comment by pmq5205209** [comment]
After set file handler to 65535，the agent's logs were not different. And I can see the file handler of WebShpere was 378 . If the upper limit of the file handle is exceeded, there will be too many open files printed in websphere's log.

**Comment by wu-sheng** [comment]
@raphw Any idea how to address this issue?

**Comment by raphw** [comment]
Not really without a reproduction. I still expect that an `IOException` is thrown in the `getResourceAsStream` method where the exception is swallowed and `null` is returned which would trigger this message. You could instrument the method and intercept the exception or set a break point to see what exception is being hidden.

**Comment by wu-sheng** [comment]
@raphw Status update, check this, https://github.com/apache/skywalking/issues/2652#issuecomment-503551872

This error was caused by Websphere security mechanism.

**Comment by raphw** [comment]
Good to know, thanks for the update!
