### ISSUE TITLE
TypePool Illegal Resolution

### ISSUE THREAD

**Issue by dpsoft** [raphw/byte-buddy#659]
**Problem description**: We are using ByteBuddy with our Java agent ([Kanela]). We're instrumenting some classes in the bootstrap classloader, injecting the advisor classes in this way:

```java
public static void inject(File folder, Instrumentation instrumentation, java.util.List<Class<?>> allClasses) {
        ClassInjector.UsingInstrumentation
                .of(folder, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
                .inject(collect(allClasses));
    }

private static Map<TypeDescription.ForLoadedType, byte[]> collect(List<Class<?>> allClasses) {
        return allClasses
                .stream()
                .collect(Collectors.toMap(TypeDescription.ForLoadedType::new, ClassFileLocator.ForClassLoader::read));
    }
```
using `byte-buddy 1.8.22` and run fine.

Then when we update to `byte-buddy 1.9.12` and change the `inject` method to:

```java
public static void inject(File folder, Instrumentation instrumentation, java.util.List<Class<?>> allClasses) {
        ClassInjector.UsingInstrumentation
                .of(folder, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
                .injectRaw(ClassFileLocator.ForClassLoader.readToNames(allClasses));
}
```
with this change leads to a `TypePool.Resolution.Illegal` with this `stack`:

```
[main] ERROR 2019-05-29 15:02:43  Logger : Error => java.util.concurrent.ScheduledThreadPoolExecutor with message Cannot resolve type description for kamon.executors.instrumentation.ExecutorsInstrumentationAdvisors$RunnableWrapperAdvisor. Class loader: Bootstrap ClassLoader: java.lang.IllegalStateException: Cannot resolve type description for kamon.executors.instrumentation.ExecutorsInstrumentationAdvisors$RunnableWrapperAdvisor
	at kanela.agent.libs.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
	at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
	at kanela.agent.libs.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getDeclaredMethods(TypeDescription.java:8045)
	at kanela.agent.libs.net.bytebuddy.asm.Advice.to(Advice.java:334)
	at kanela.agent.libs.net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:10946)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$ForAdvice$Entry$ForUnifiedAdvice.resolve(AgentBuilder.java:2528)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$ForAdvice.transform(AgentBuilder.java:2314)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2614)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10126)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
	at java.security.AccessController.doPrivileged(Native Method)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6734)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7011)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6860)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4728)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9272)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9242)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:11235)
	at kanela.agent.builder.AgentInstaller.install(AgentInstaller.java:45)
	at kanela.agent.InstrumentationLoader.lambda$load$4(InstrumentationLoader.java:50)
	at kanela.agent.libs.io.vavr.collection.List.map(List.java:1017)
	at kanela.agent.InstrumentationLoader.load(InstrumentationLoader.java:42)
	at kanela.agent.Kanela.lambda$null$0(Kanela.java:78)
```
Thanks in advance and any advice is welcome!

[Kanela]: https://github.com/kamon-io/kanela

**Comment by raphw** [comment]
The error does not seem to come from the code you posted but from a Java agent applying an instrumentation. Is `kamon.executors.instrumentation.ExecutorsInstrumentationAdvisors$RunnableWrapperAdvisor` among the classes being injected into the boot loader? Could you set a breakpoint and see under what name it is listed in each version's map?

**Comment by dpsoft** [comment]
Here a screenshot of the values that arrive:

![image](https://user-images.githubusercontent.com/2567525/58645455-c9671180-82d9-11e9-82a6-f71bc5b7e719.png)

and the advisors basically are:

![image](https://user-images.githubusercontent.com/2567525/58646639-37acd380-82dc-11e9-9286-f0ec391f0e8a.png)

Thanks!

**Comment by raphw** [comment]
Please, could you create a reproduction. 

To me, it looks like a class loading race condition.

**Comment by dpsoft** [comment]
please close the issue if you wish, when I have more information, ask you again. Thanks

**Comment by raphw** [comment]
You can keep it open, good to retain the history as I will probably not remember it at the time.

**Comment by dpsoft** [comment]
Hi, I've found the issue and for our use case with only change this:
```java
new AgentBuilder.Transformer.ForAdvice()
                .advice(this.methodMatcher, advisorClass.getName())
                .withExceptionHandler(AdviceExceptionHandler.instance());
```
to this:

```java
 new AgentBuilder.Transformer.ForAdvice()
                .advice(this.methodMatcher, advisorClass.getName())
                .include(advisorClass.getClassLoader())
                .withExceptionHandler(AdviceExceptionHandler.instance());
```
all is running like a charm!

Thanks a lot!

**Comment by raphw** [comment]
Of course, this is obvious now that I think of it. Your agent's class loader is not in a common hierarchy with the instrumented class's loader and needs to be added explicitly to make Byte Buddy annotations available.
