### ISSUE TITLE
why budybuddy still work after i reset instrument?

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#672]
public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {

        final PluginFinder pluginFinder = new PluginFinder(new PluginBootStrap().loadPlugins());

        final ByteBuddy bytebuddy = new ByteBuddy();
         defaultAgent = new AgentBuilder.Default(bytebuddy)
               // .with(AgentBuilder.Listener.StreamWriting.toSystemError())
                //.with(AgentBuilder.RedefinitionStrategy.
               // RETRANSFORMATION)
                //disableClassFormatChanges()
                .enableBootstrapInjection(instrumentation, temp)
                .type(pluginFinder.buildMatch())
                .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))
                //.with(new Listener())
               // .installOn(instrumentation)
         ;
                                       final ResettableClassFileTransformer resetter = defaultAgent.installOn(instrumentation);
     
 
        resetter.reset(instrumentation,AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);

    }

I use reset to reset instrumentation, Why bytbuddy still works fine? I think before I re-installOn the instrumentation, it should not work.

**Comment by zheyiyi** [comment]
it  cause this error.
 org.jctools-core.MpscChunkedArrayQueue: available
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:09:08.500 [Thread-2] DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.processId: 10460 (auto-detected)
14:09:08.505 [Thread-2] DEBUG io.grpc.netty.shaded.io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: Cannot apply redefinition on sun.instrument.InstrumentationImpl@74960bfa
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$3.check(AgentBuilder.java:4522)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4623)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.reset(AgentBuilder.java:10514)
	at net.bytebuddy.agent.builder.ResettableClassFileTransformer$AbstractBase.reset(ResettableClassFileTransformer.java:288)
	at net.bytebuddy.agent.builder.ResettableClassFileTransformer$AbstractBase.reset(ResettableClassFileTransformer.java:235)
	at net.bytebuddy.agent.builder.ResettableClassFileTransformer$AbstractBase.reset(ResettableClassFileTransformer.java:224)
	at com.ivoyant.skyrunning.agent.SkyRunningAgent.premain(SkyRunningAgent.java:111)
	... 6 more

**Comment by raphw** [comment]
Try registering a listener in the reset call. Your retransformation needs to be leave a class file in its original state to be resettable. Most JVMs, including HotSpot, do not support adding fields or methods after a class was defined for the first time.

**Comment by zheyiyi** [comment]
> Try registering a listener in the reset call. Your retransformation needs to be leave a class file in its original state to be resettable. Most JVMs, including HotSpot, do not support adding fields or methods after a class was defined for the first time.

     final ResettableClassFileTransformer resetter = defaultAgent.installOn(instrumentation);
     resetter.reset(instrumentation,AgentBuilder.RedefinitionStrategy.RETRANSFORMATION, null,
                null, AgentBuilder.RedefinitionStrategy.Listener.StreamWriting.toSystemOut());

it print:
   Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: Cannot apply redefinition on sun.instrument.InstrumentationImpl@51891008
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$3.check(AgentBuilder.java:4522)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4623)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.reset(AgentBuilder.java:10514)
	at com.ivoyant.skyrunning.agent.SkyRunningAgent.premain(SkyRunningAgent.java:109)
	... 6 more

**Comment by zheyiyi** [comment]
I register a listener, and it showed above. is there  any way to solve the problem?

**Comment by raphw** [comment]
It seems as if your agent is not retransformation capable. You have to declare retransformability in the agent's manifest.

**Comment by zheyiyi** [comment]
> It seems as if your agent is not retransformation capable. You have to declare retransformability in the agent's manifest.

Thanks, it solved. But Why I do this, it still instrument. 

   ResettableClassFileTransformer resetter = defaultAgent.installOn(instrumentation);    
   resetter.reset(instrumentation,AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);
   instrumentation = null;
   resetter = null

**Comment by raphw** [comment]
You can register a listener with your reset. Potentially, the reset fails. Also check the return value of the method call.

**Comment by raphw** [comment]
Please reopen if there are further questions.
