### ISSUE TITLE
my bytebuddy affect original class

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#687]
I instrument class java.util.concurrent.ThreadPoolExecutor's execute method.

The error:

java.lang.NoClassDefFoundError: com/ivoyant/tracing/plugins/multiThread/MultiThreadInterceptor/MultiThreadInterceptor
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343) ~[na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:420) [na:1.8.0_191]
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

My MultiThreadInterceptor exits but why can't it see it?

**Comment by raphw** [comment]
I assume that `MultiThreadInterceptor` is on the system class path and not on the bootstrap path. Classes on the bootstrap path cannot see classes on the system class path where any Java agent or program is loaded which is why this error is triggered.

You have to include your interceptor in the bootstrap path to make this work.

**Comment by raphw** [comment]
Please reopen if there are further questions.
