### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Class already loaded: class ysoserial.payloads.test.Source

### ISSUE THREAD

**Issue by hktalent** [raphw/byte-buddy#688]
```
package ysoserial.payloads.test;

public class Source {
    public  static String hello(String name) {return null;}

}

package ysoserial.payloads.test;

public class Target {
	public static String hello(String name) {
        return "Hello" + name+ "!";
    }
}




package ysoserial.payloads.test;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.matcher.ElementMatchers;

public class TestByteBuddy {

	public static void main(String[] args) throws Exception {
		TestByteBuddy tb = new TestByteBuddy();
		String helloWorld = new ByteBuddy()
                .redefine(Source.class)               
                .method(ElementMatchers.named("hello"))
                .intercept(MethodDelegation.to(Target.class))
                .make()
                .load(tb.getClass().getClassLoader())
                .getLoaded()
                .newInstance()
                .hello("World");
		
		Source.hello("xxx");
	}

}
```

```
Exception in thread "main" java.lang.IllegalStateException: Class already loaded: class ysoserial.payloads.test.Source
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.load(ByteArrayClassLoader.java:306)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:357)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5623)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5612)
	at ysoserial.payloads.test.TestByteBuddy.main(TestByteBuddy.java:16)
```

**Comment by raphw** [comment]
That is expected, you are trying to define a class in a class loader where looking up this class loader's classes would always trigger a "parent-first" class loading. Since the class loader of `TestByteBuddy` already defines a class named `Source` in the package in question, the redefined class in the newly created class loader can never be loaded.

To avoid this, either rename the class or use a `CHILD_FIRST` injection strategy as a second argument to `load`. However, this will still not do what you intend to do since you invoke a static method which is bound to the namespace of the class loader calling it where the non-transformed method will be invoked as it now exists in two class loaders. To avoid this, you would need to use Java reflection to avoid the implicit namespace binding and do:

```java
.getMethod("hello", String.class).invoke(null, "World");
```

rather then the new instance call.
