### ISSUE TITLE
byte-buddy-android "Could not locate class file for xxxx"

### ISSUE THREAD

**Issue by KB5201314** [raphw/byte-buddy#690]
cannot redefine any Class, because "Could not locate class file"
env: Android 8.1.0

code:
```
new ByteBuddy().redefine(Object.class).make().load(classLoader).getLoaded();
```
also have tested with class belong to apk file

exception:
```
Caused by: java.lang.IllegalStateException: Could not locate class file for java.lang.Object
        at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:118)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3392)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:217)
        at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:120)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
        at top.imlk.qqhdfy.stub.FragmentHelper.install(FragmentHelper.java:19)
        at top.imlk.qqhdfy.hook.Injector.doHook(Injector.java:373)
        at java.lang.reflect.Method.invoke(Native Method) 
        at top.imlk.qqhdfy.hook.Injector$1.afterHookedMethod(Injector.java:74) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375) 
        at com.tencent.mobileqq.qfix.QFixApplication.attachBaseContext(<Xposed>) 
        at android.app.Application.attach(Application.java:189) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1103) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1087) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:983) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
```

**Comment by KB5201314** [comment]
I write this code just want to insert my custom class into a existed PathClassLoader

**Comment by raphw** [comment]
Android does not retain class files at runtime, you are only able to subclass on it.
