### ISSUE TITLE
Intercept Java 8 lambda-expressions, Using LambdaInstrumentationStrategy failed

### ISSUE THREAD

**Issue by mliu111477** [raphw/byte-buddy#693]
I want to intercept lambda-expressions, use LambdaInstrumentationStrategy.ENABLED, but get some error. here is my byteBuddy example code:
`new AgentBuilder.Default()
                .with(AgentBuilder.LambdaInstrumentationStrategy.ENABLED)
                .type(any()).transform(new AgentBuilder.Transformer() {
            @Override
            public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                return builder;
            }
        }).installOn(instrumentation);` 

I use jdk1.8.0_65, and buye-buddy 1.7.9. here is my exception print.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: Could not install class file transformer
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:8279)
	at com.lagou.pard.agent.PardAgent.premain(PardAgent.java:108)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Instrumentation does not support manipulation of loaded classes: sun.instrument.InstrumentationImpl@4416d64f
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.loading.ClassReloadingStrategy.of(ClassReloadingStrategy.java:119)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$1.apply(AgentBuilder.java:6261)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:8259)
	... 7 more

**Comment by raphw** [comment]
Your agent must be retransformation capable, this must be declared in the agent manifest. Your agent does not seem to allow this.

**Comment by mliu111477** [comment]
ok, thanks. The exception has gone.
But I also cannot intercept the lambda-expression. Here is my Java code:
`Executors.newSingleThreadExecutor().execute(() -> {
        System.out.println(1);
});`

My bytebuddy code like this:
`.type(hasSuperType(named("java.lang.Runnable").and(not(isInterface())))`

It's not work, how can i intercept this thread run.

**Comment by raphw** [comment]
Did you make sure that:
1. enable logging (register a `StreamWriting` listener)
2. make sure that the class is not loaded before the lambda strategy is registered

**Comment by mliu111477** [comment]
ok, It's discovery this class load.
![image](https://user-images.githubusercontent.com/3417650/61988802-202e6480-b059-11e9-84c9-0bb47dd057e6.png)

but when I transform this class, got another exception.
When transform I intercept run method, java agent code:
`builder = builder.method(not(isStatic()).and(mather)).intercept(MethodDelegation.withDefaultConfiguration().to(methodInterceptor));`

matcher: `(name(equals(run)) and not(isAbstract()))`

add a AgentBuilder.Listener, on `onError` method, got this Exception:
`[Byte Buddy] ERROR com.lagou.kw.vod.test.Demo$$Lambda$ByteBuddy$1 [sun.misc.Launcher$AppClassLoader@14dad5dc, null, loaded=false]
java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of public void com.lagou.kw.vod.test.Demo$$Lambda$ByteBuddy$1.run() to dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@901c650c or dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@55d0ba2
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:578)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:597)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.doResolve(MethodDelegationBinder.java:597)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$BindingResolver$Default.resolve(MethodDelegationBinder.java:553)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1028)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1051)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:620)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:609)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:3980)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1125)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:698)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:500)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:200)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8905)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9306)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9269)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9047)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9625)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9575)
	at java.security.AccessController.doPrivileged(Native Method)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9194)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.AgentBuilder$LambdaInstrumentationStrategy$LambdaInstanceFactory.make(AgentBuilder.java:6485)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.LambdaFactory.invoke(LambdaFactory.java:163)
	at dep.com.lagou.pard.dependencies.net.bytebuddy.agent.builder.LambdaFactory.make(LambdaFactory.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at com.lagou.kw.vod.test.Demo.main(Demo.java:20)`

**Comment by raphw** [comment]
As the delegation suggests, it is not clear to Byte Buddy what method is your delegation target. You can reduce the number of considered methods to resolve the ambiguity.

**Comment by mliu111477** [comment]
sorry, I just want to delegation the "run" method. I don't know what I should to do?
Could you help me, just give a example code for delegate the "run" method,? thank you.

**Comment by raphw** [comment]
The problem is that `methodInterceptor` offers too many possible delegation targets. You can add a `filter` step to reduce the amount of methods that Byte Buddy considers for this target.

**Comment by mliu111477** [comment]
sorry, can you give me a doc? I can't find it.

**Comment by raphw** [comment]
http://bytebuddy.net/javadoc/1.9.16/net/bytebuddy/implementation/MethodDelegation.WithCustomProperties.html#filter-net.bytebuddy.matcher.ElementMatcher-

**Comment by mliu111477** [comment]
Ok,I already have try this method.
But I filter the “run” method, it return empty method list, I don’t know why?

**Comment by raphw** [comment]
You do not filter for the run method here but for potential methods to delegate to. Your target class is the problem, not the instrumented type.

**Comment by mliu111477** [comment]
ok, I tried.
when I intercept simple runnable#run is work well, code like this:
`Executors.newSingleThreadExecutor().execute(new Runnable() {
            @Override
            public void run() {
                System.out.println(1);
            }
        });` 

but when I use lambda-expression to execute:
`Executors.newSingleThreadExecutor().execute(() -> {
            System.out.println(1);
        });`
 I got exception:
`java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at com.lagou.kw.vod.test.Demo.main(Demo.java:26)
Caused by: java.lang.NoClassDefFoundError: com/lagou/kw/vod/test/Demo$$Lambda$ByteBuddy$1
	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.lagou.kw.vod.test.Demo$$Lambda$ByteBuddy$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more`

I seem some same issue, this is a JDK 8 bug and fix on JDK 9?
has any possible fix in on JDK 8 or just my code has problem?

**Comment by raphw** [comment]
I assume that the class you are instrumenting is not capable of seeing the class that you specify as `methodInterceptor` what makes sense since it is anonymous. You should define a public class as a delegation target that is available to the class loader of the lambda class.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.

**Comment by goudai** [comment]
@mrproliu have you implemented rewrite runnable to complete threadlocal cross-thread pool transparent transmission.

**Comment by mrproliu** [comment]
> @mrproliu �have you implemented rewrite runnable to complete threadlocal cross-thread pool transparent transmission.

Sorry, I'm not following this anymore. If you have any goods news please let me know.

**Comment by goudai** [comment]
> > @ mrproliu-您已实现可运行的重写以完成线程本地跨线程池透明传输。
> 
> 抱歉，我不再关注此内容。如果您有任何货物新闻，请告诉我。

有没有比较好的跨线程池传递threadlocal的方案呀。老哥

**Comment by libinglong** [comment]
> > > @ mrproliu-您已实现可运行的重写以完成线程本地跨线程池透明传输。
> > 
> > 
> > 抱歉，我不再关注此内容。如果您有任何货物新闻，请告诉我。
> 
> 有没有比较好的跨线程池传递threadlocal的方案呀。老哥

@goudai alibaba transmittable-thread-local
