### ISSUE TITLE
[Question] An unexpected issue for JDK 9

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#697]
Hi

We are adding the plugin by using the bootstrap plugin of `HttpClient` in https://github.com/apache/skywalking/pull/3171.

```
java.lang.IllegalAccessError: superinterface check failed: class sun.net.www.http.HttpClient (in module java.base) cannot access class org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance (in unnamed module @0x555590) because module java.base does not read unnamed module @0x555590
```

What we did is, `EnhancedInstance` interface added to the target class, implement it dynamically like this
https://github.com/apache/skywalking/blob/c76fb4053e/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/ClassEnhancePluginDefine.java#L123-L125

`EnhancedInstance` has been injected to bootstrap classloader, but look like there is a model definition to take care in JDK9.  What should I do to make this compatible in both JDK9+ and old JDK?

**Comment by raphw** [comment]
If you access your code from a module, you have to insert a read edge from this module to your unnamed module. 

Byte Buddy offers some convenience for this by the DSL step addModuleReadEdge to your class.

**Comment by wu-sheng** [comment]
Do you have any example of how to use it? I think I need to check JDK version, if it turns JDK9+, we need to call that.

**Comment by raphw** [comment]
```java
agentBuilder = agentBuilder.assureReadEdgeTo(EnhancedInstance.class)
```

Byte Buddy will apply the Java 9 check for you and only adjust the module if the module system exists.

**Comment by wu-sheng** [comment]
So, we should wait for the next release? When do you think? I think checking by ourselves is not wise.

**Comment by raphw** [comment]
No need. This has been in Byte Buddy for quite some time.

**Comment by wu-sheng** [comment]
Oh, so you mean, I just use it directly. This should be called after these classes injected in bootstrap classloader, right?

**Comment by raphw** [comment]
Yes.

**Comment by wu-sheng** [comment]
I am installing openjdk 9/11/12. Then test to see what happens. ByteBuddy should have supported all these, right?

**Comment by raphw** [comment]
Yes.

**Comment by wu-sheng** [comment]
Before any change, this is the error
```
Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class java.net.HttpURLConnection (in module java.base) cannot access class org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance (in unnamed module @0x2449cff7) because module java.base does not read unnamed module @0x2449cff7
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at Main.main(Main.java:28)
```

Then I added all generated classes and interfaces like this, just after the bootstrap inject.
```java
    private static final String[] HIGH_PRIORITY_CLASSES = {
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.BootstrapInterRuntimeAssist",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceConstructorInterceptor",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsAroundInterceptor",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.MethodInterceptResult",
        "org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.OverrideCallable",
        "org.apache.skywalking.apm.agent.core.plugin.bootstrap.IBootstrapLog",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.RuntimeType",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.This",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.AllArguments",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.AllArguments$Assignment",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.SuperCall",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.Origin",
        SHADE_PACKAGE + "net.bytebuddy.implementation.bind.annotation.Morph"
    };

    public static AgentBuilder inject(PluginFinder pluginFinder, AgentBuilder agentBuilder,
        Instrumentation instrumentation) throws PluginException {

        Map<String, byte[]> classesTypeMap = new HashMap<String, byte[]>();

        if (!prepareJREInstrumentation(pluginFinder, classesTypeMap)) {
            return agentBuilder;
        }

        for (String highPriorityClass : HIGH_PRIORITY_CLASSES) {
            loadHighPriorityClass(classesTypeMap, highPriorityClass);
        }

        File temp = null;
        try {
            temp = new File(AgentPackagePath.getPath(), "bootstrapJarTmp");
        } catch (AgentPackageNotFoundException e) {
            logger.error(e, "Bootstrap plugin exist, but SkyWalking agent can't create bootstrapJarTmp folder. Shutting down.");
            throw new UnsupportedOperationException("Bootstrap plugin exist, but SkyWalking agent can't create bootstrapJarTmp folder. Shutting down.", e);
        }

        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation).injectRaw(classesTypeMap);

        ///////////////////////////////////////////////
        // These are my added things.
        for (String highPriorityClass : HIGH_PRIORITY_CLASSES) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(highPriorityClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+", e);
            }
        }
        for (String generatedClass : classesTypeMap.keySet()) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(generatedClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high generated class " + generatedClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high generated class " + generatedClass + " to public access in JDK9+", e);
            }
        }
        // These are my added things.
        ///////////////////////////////////////////////
        
        agentBuilder = agentBuilder.enableBootstrapInjection(instrumentation, temp);
        return agentBuilder;
```

The new error shows out
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at Main.main(Main.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.net.HttpURLConnection.<clinit>(HttpURLConnection.java:360)
	... 4 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:122)
	... 9 more
Caused by: java.lang.IllegalStateException: Cannot load injected class
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2133)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:96)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3099)
	... 14 more
Caused by: java.lang.ClassNotFoundException: java.net.HttpURLConnection$auxiliary$k383GFSI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2127)
	... 16 more
```

`java.net.HttpURLConnection$auxiliary$k383GFSI` looks like the ByteBuddy generated class.
What is the problem here?

**Comment by raphw** [comment]
You will need to enable `unsafeBootstrapInjection` as the auxiliary types are not otherwise visible on the boot loader.

**Comment by wu-sheng** [comment]
Is this required to be added in specific place?

I added like this, but still, fail
```java
        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation).injectRaw(classesTypeMap);

        agentBuilder = agentBuilder.enableUnsafeBootstrapInjection();
        for (String highPriorityClass : HIGH_PRIORITY_CLASSES) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(highPriorityClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+", e);
            }
        }
        for (String generatedClass : classesTypeMap.keySet()) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(generatedClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high generated class " + generatedClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high generated class " + generatedClass + " to public access in JDK9+", e);
            }
        }
```

**Comment by raphw** [comment]
You probably need to enable an eager type injection strategy, do you have a reproducion?

**Comment by wu-sheng** [comment]
> You probably need to enable an eager type injection strategy

How to enable it?

> do you have a reproducion?

By `enableUnsafeBootstrapInjection` added, same log.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at Main.main(Main.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.net.HttpURLConnection.<clinit>(HttpURLConnection.java:360)
	... 4 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:122)
	... 9 more
Caused by: java.lang.IllegalStateException: Cannot load injected class
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2133)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:96)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3099)
	... 14 more
Caused by: java.lang.ClassNotFoundException: java.net.HttpURLConnection$auxiliary$HlvrMuCs
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2127)
	... 16 more
```

**Comment by wu-sheng** [comment]
Btw, as SkyWalking needs JDK9- compatible, we exclude ByteBuddy module-info.class in package stage like this, is that related?
```xml
<plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <createSourcesJar>true</createSourcesJar>
                            <shadeSourcesContent>true</shadeSourcesContent>
                            <transformers>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Premain-Class>${premain.class}</Premain-Class>
                                        <Can-Redefine-Classes>${can.redefine.classes}</Can-Redefine-Classes>
                                        <Can-Retransform-Classes>${can.retransform.classes}</Can-Retransform-Classes>
                                    </manifestEntries>
                                </transformer>
                            </transformers>
                            <artifactSet>
                                <excludes>
                                    <exclude>com.lmax:*</exclude>
                                    <exclude>*:gson</exclude>
                                    <exclude>io.grpc:*</exclude>
                                    <exclude>io.netty:*</exclude>
                                    <exclude>io.opencensus:*</exclude>
                                    <exclude>com.google.*:*</exclude>
                                    <exclude>com.google.guava:guava</exclude>
                                </excludes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>${shade.net.bytebuddy.source}</pattern>
                                    <shadedPattern>${shade.net.bytebuddy.target}</shadedPattern>
                                </relocation>
                            </relocations>
                            <filters>
                                <!-- Exclude like this -->
                                <filter>
                                    <artifact>net.bytebuddy:byte-buddy</artifact>
                                    <excludes>
                                        <exclude>META-INF/versions/9/module-info.class</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by raphw** [comment]
As for the issue, did you try this strategy: http://bytebuddy.net/javadoc/1.9.16/net/bytebuddy/agent/builder/AgentBuilder.InitializationStrategy.SelfInjection.Eager.html

The shade plugin should exclude the module-info by default.

**Comment by wu-sheng** [comment]
Added like this. Same error. Do I do this right? I am not familiar w/ the strategy, just guessing from API.

![image](https://user-images.githubusercontent.com/5441976/62140395-821ef080-b31d-11e9-8360-7375f73a6ffc.png)

**Comment by raphw** [comment]
The API is immutable, you have to reassign the value to `agentBuilder`.

**Comment by wu-sheng** [comment]
That error is gone, change to this.

```
ERROR 2019-07-30 23:12:22:492 main SkyWalkingAgent :  Enhance class java.net.HttpURLConnection error. 
java.lang.IllegalStateException: Cannot load injected class
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2133)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:96)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Eager$Dispatcher.register(AgentBuilder.java:3294)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10043)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10461)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10424)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10190)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10873)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10811)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:550)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at Main.main(Main.java:28)
Caused by: java.lang.ClassNotFoundException: java.net.HttpURLConnection$auxiliary$qO9LA3JM
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2127)
	... 17 more
```

Look like there is another strategy in `#injectRaw`.

**Comment by raphw** [comment]
`ClassInjector$UsingInstrumentation` indicates that the unsafe injection strategy is not activated.

**Comment by wu-sheng** [comment]
> ClassInjector$UsingInstrumentation indicates that the unsafe injection strategy is not activated.

Yes. Does inject need to happen after `agentBuilder#installOn`?

**Comment by raphw** [comment]
It should happen on demand upon a particular instrumentation. Can you try and trace why the instance is not used?

**Comment by wu-sheng** [comment]
This is the call stack, anything I need to pay attention?
![image](https://user-images.githubusercontent.com/5441976/62144113-d3ca7980-b323-11e9-82cf-7b4fed20195e.png)

All I saw is
> resolve:10091, AgentBuilder$Default$Transformation$Simple$Resolution$BootstrapClassLoaderCapableInjectorFactory (net.bytebuddy.agent.builder)

When `classLoader == null`, it goes into this way.

**Comment by wu-sheng** [comment]
<bytebuddy.version>1.9.2</bytebuddy.version>

**Comment by raphw** [comment]
I'll look into it tonight.

**Comment by wu-sheng** [comment]
Thanks. I am going to sleep now. Chat tomorrow.

**Comment by raphw** [comment]
Alright, you are overriding unsafe reflection a little further down, you should use unsafe injection instead of bootstrap injection.

**Comment by wu-sheng** [comment]
> you are overriding unsafe reflection a little further down

What OP I did to override?

> you should use unsafe injection instead of bootstrap injection.

I changed the injection to `ClassInjector.UsingUnsafe.ofBootLoader().injectRaw(classesTypeMap);`. 
But still get this error. Look like still using `ClassInjector$UsingInstrumentation.injectRaw`. Why this happens? I think the same as the above one, **overriding unsafe reflection**.

```
ERROR 2019-07-31 10:46:03:459 main SkyWalkingAgent :  Enhance class java.net.HttpURLConnection error. 
java.lang.IllegalStateException: Cannot load injected class
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2133)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:96)
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Eager$Dispatcher.register(AgentBuilder.java:3294)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10043)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10461)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10424)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10190)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10873)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10811)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:550)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at Main.main(Main.java:28)
Caused by: java.lang.ClassNotFoundException: java.net.HttpURLConnection$auxiliary$7pCp1yBb
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingInstrumentation.injectRaw(ClassInjector.java:2127)
	... 17 more
```

**Comment by wu-sheng** [comment]
I changed codes like this

```
        ClassInjector.UsingUnsafe.ofBootLoader().injectRaw(classesTypeMap);

        agentBuilder = agentBuilder.enableUnsafeBootstrapInjection();

        for (String highPriorityClass : HIGH_PRIORITY_CLASSES) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(highPriorityClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high priority class " + highPriorityClass + " to public access in JDK9+", e);
            }
        }
        for (String generatedClass : classesTypeMap.keySet()) {
            try {
                agentBuilder = agentBuilder.assureReadEdgeTo(instrumentation, Class.forName(generatedClass));
            } catch (ClassNotFoundException e) {
                logger.error(e, "Fail to open the high generated class " + generatedClass + " to public access in JDK9+");
                throw new UnsupportedOperationException("Fail to open the high generated class " + generatedClass + " to public access in JDK9+", e);
            }
        }

        return agentBuilder;
```
It works JDK 11(included)-, as you mentioned in documents. In JDK12, it shows error as following.
```
ERROR 2019-07-31 11:10:34:050 main SkyWalkingAgent :  SkyWalking agent inject bootstrap instrumentation failure. Shutting down. 
java.lang.UnsupportedOperationException: Could not access Unsafe class: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Unavailable.initialize(ClassInjector.java:2014)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1747)
	at org.apache.skywalking.apm.agent.core.plugin.bootstrap.BootstrapInstrumentBoost.inject(BootstrapInstrumentBoost.java:104)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
```

How I could make things working in JDK12 and further?

**Comment by raphw** [comment]
To me it still looks like you are using the instrumentation strategy which is not compatible with the module system on the boot path. Can you set a break point in line 10134 of `AgentBuilder` and check what `bootstrapInjectionStrategy` is used.

**Comment by wu-sheng** [comment]
@raphw I think, you were reading my deleted message :) Sorry for that. After I posted, I realized I did the wrong change. Now, it is fixed and working in JDK 8 - 11.

Now, the question is, is there a way to do in JDK12? As the unsafe is documented not supported  in JDK12, which matches the test result.

**Comment by raphw** [comment]
Byte Buddy should fallback to jdk.internal.misc.Unsafe. This is resolved in line 1911 of `ClassInjector`. Can you check why this is not working?

**Comment by wu-sheng** [comment]
> Byte Buddy should fallback to jdk.internal.misc.Unsafe. This is resolved in line 1911 of ClassInjector. Can you check why this is not working?

It works in the latest version, at my OpenJDK 12. Look like an old version BUG.

Thanks. I think I could close this thread for now. JDK 1.6 - 12 are supported now.

**Comment by wu-sheng** [comment]
A reminder, you may want to change the comments of `UsingUnsafe`. From the tests, it works in JDK 12 by leveraging the `fallback` mechanism, right? But the comment says it doesn't support.

```java
    /**
     * <p>
     * A class injector that uses {@code sun.misc.Unsafe} to inject classes.
     * </p>
     * <p>
     * <b>Important</b>: This strategy is no longer available after Java 11.
     * </p>
     */
    @HashCodeAndEqualsPlugin.Enhance
    class UsingUnsafe extends AbstractBase {
```

**Comment by raphw** [comment]
This was true previously but I found a way to get around this. You are right, I need to remove the comment.

**Comment by wu-sheng** [comment]
> This was true previously but I found a way to get around this. You are right, I need to remove the comment.

:) Great to have the bytebuddy to avoid multiple issues caused by JVM versions

**Comment by kriegaex** [comment]
@wu-sheng, do you happen to have an [MCVE](https://stackoverflow.com/help/mcve) for this? This looks like bits and pieces of code, I guess nobody except you and Rafael could figure out the final version.

**Comment by wu-sheng** [comment]
@kriegaex I didn't write MCVE, because all of the codes we discussed are open source in https://github.com/apache/skywalking. We build the agent on the top of bytebuddy.

**Comment by kriegaex** [comment]
Sorry, that is too complex for me. Several classes involved, doing a lot of project-specific stuff. I think I do not have the time to study the bootstrapping for your whole tool. I just wanted a simple use case for making something like [this](https://gist.github.com/kriegaex/0f4dd4c9d05f3a68e3a8e1ed75359c3b) work on Java 9, because simply switching from instrumentation to unsafe via

```java
      .UsingUnsafe
      .ofBootLoader()
      .inject(
        Collections.singletonMap(
          new TypeDescription.ForLoadedType(MyInterceptor.class),
          ClassFileLocator.ForClassLoader.read(MyInterceptor.class)
        )
```
only works on Java 8 for me, not 9+. I see you doing more things, but I am not sure which ones are essential to me. That is why I asked for an [MCVE](https://stackoverflow.com/help/mcve).

**Comment by wu-sheng** [comment]
I am afraid I don't have one.

**Comment by kriegaex** [comment]
Now, we do have an [MCVE](https://stackoverflow.com/help/mcve) outside of Apache SkyWalking, because I was triggered to revisit the problem after almost three years:

https://gist.github.com/kriegaex/0f4dd4c9d05f3a68e3a8e1ed75359c3b

BTW, what happened to Byte Buddy use in SkyWalking? It seems to be gone. I never used SkyWalking, so I did not investigate.
