### ISSUE TITLE
How to deal w/ module-info.java existing

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#699]
Hi

We solved the bootstrap instrumentation in all JDKs. Now I want to dig more for JDK 9 - 12. As the module introduced in JDK, although most people don't use today, I want the plugin mechanism ready to go.

I write a simple test,
Main.java
```
public class Main {
    public static void main(String[] args) throws IOException {
        URL obj = new URL("http://www.baidu.com");
        HttpURLConnection con = (HttpURLConnection)obj.openConnection();

        // optional default is GET
        con.setRequestMethod("GET");
        System.out.println(con.getRequestMethod());
//        con.setChunkedStreamingMode(0);

        //add request header

        int responseCode = con.getResponseCode();
        System.out.println("Response Code : " + responseCode);

        BufferedReader in = new BufferedReader(
            new InputStreamReader(con.getInputStream()));
        String inputLine;
        StringBuffer response = new StringBuffer();

        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();

        //print result
        System.out.println(response.toString());
    }
}
```

Empty module-info.java
```java
module JRE.test {
}
```

After I installed the agent, in JDK 9 -12, it shows the following error
- Do bootstrap instrumentation
```
ERROR 2019-08-01 14:24:38:322 main SkyWalkingAgent :  SkyWalking agent inject bootstrap instrumentation failure. Shutting down. 
java.lang.UnsupportedOperationException: Could not access Unsafe class: sun.misc.Unsafe
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Unavailable.initialize(ClassInjector.java:2033)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1765)
	at org.apache.skywalking.apm.agent.core.plugin.bootstrap.BootstrapInstrumentBoost.inject(BootstrapInstrumentBoost.java:102)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
```

- Do simple Main function instrumentation
```
DEBUG 2019-08-01 14:26:48:650 main SkyWalkingAgent :  On Transformation class a.Main. 
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at JRE.test/a.Main.<clinit>(Main.java)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: Cannot get package using reflection: sun.misc.Unsafe
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getPackage(ClassInjector.java:418)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:220)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3143)
	... 10 more
```

How should I avoid these? And make the plugin works if user turns module definition on?

**Comment by raphw** [comment]
Normally, the reflection initialization should be capable of accessing the class. Can you check the reflection-based injector's static type initializer and see where things go wrong?

**Comment by wu-sheng** [comment]
In `UsingUnsafe` class declaration
```java
private static final Dispatcher.Initializable DISPATCHER = AccessController.doPrivileged(Dispatcher.CreationAction.INSTANCE);
```

The value runs into Unavailable directly.
![image](https://user-images.githubusercontent.com/5441976/62295368-75c2a100-b49f-11e9-935b-e18b56517a24.png)

Then in `#injectRaw` method, `DISPATCHER.initialize()` triggers the error.
```
ERROR 2019-08-01 21:01:31:865 main SkyWalkingAgent :  SkyWalking agent inject bootstrap instrumentation failure. Shutting down. 
java.lang.UnsupportedOperationException: Could not access Unsafe class: sun.misc.Unsafe
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Unavailable.initialize(ClassInjector.java:2033)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1765)
	at org.apache.skywalking.apm.agent.core.plugin.bootstrap.BootstrapInstrumentBoost.inject(BootstrapInstrumentBoost.java:102)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
```

This error happens in bootstrap instrumentation. When doing normal class(AppClassLoader) instrumentation, same reason but in different stack.

**Comment by wu-sheng** [comment]
In `CreationAction#run`L1873, `Class.forName("sun.misc.Unsafe")` triggers exception, then it runs into `Unavailable` expcetion.

![image](https://user-images.githubusercontent.com/5441976/62296942-c091e800-b4a2-11e9-981f-2495c3149ad1.png)

**Comment by wu-sheng** [comment]
Unexpected is, this class should exist in JDK 9, but after I add this module definition, the exception happens.

**Comment by raphw** [comment]
Normally, Byte Buddy should itself be loaded in the unnamed module which should be able to see the `jdk.unsupported` module. Did you load Byte Buddy on the module path, too?

Can you check if `CreatedAction` is part of a module?

**Comment by wu-sheng** [comment]
> Did you load Byte Buddy on the module path, too?

No, how to load? The module system is pretty new to me. Basically, I did as old Java codes did.

**Comment by wu-sheng** [comment]
Does any of this file required in skywalking agent.jar?
![image](https://user-images.githubusercontent.com/5441976/62298050-d7d1d500-b4a4-11e9-9462-ed04ac7cc50c.png)

Is this related to your question -> `Did you load Byte Buddy on the module path, too?`?

**Comment by wu-sheng** [comment]
`Dispatcher.CreationAction.INSTANCE` looks like in `unnamed` module. 

![image](https://user-images.githubusercontent.com/5441976/62299297-42841000-b4a7-11e9-9be1-6856aa25b782.png)

Is this right?

**Comment by wu-sheng** [comment]
After I added this, the exception gone.
```java
module JRE.test {
    requires jdk.unsupported;
}
```

And it turns a new error
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at JRE.test/a.Main.<clinit>(Main.java)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Cannot access delegate$76kpri0 from class a.Main
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:126)
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:187)
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3146)
	... 10 more
Caused by: java.lang.IllegalAccessException: class net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField cannot access class a.Main (in module JRE.test) because module JRE.test does not export a to unnamed module @641856
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
	at java.base/java.lang.reflect.Field.set(Field.java:778)
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:124)
	... 12 more
```

Then I need to open package `a` too.
```
module JRE.test {
    exports a;
    requires jdk.unsupported;
}

After all these changes, the agent works again. But this is not friendly, as agent always instruments many inside classes. Do you have any suggestion for this? Should this happen?
```

**Comment by wu-sheng** [comment]
- `requires jdk.unsupported;` makes bootstrap instrumentation works.
- `exports a;` makes `a.Main#main` static method instrumentation works.

**Comment by wu-sheng** [comment]
After all these changes, the agent works again. But this is not friendly, as agent always instruments many inside classes. Do you have any suggestion for this? Should this happen?

**Comment by raphw** [comment]
Yes, Byte Buddy is probably loaded as an agent in this case such that it automatically ends up in the unnamed module. This should not happen and it does neither happen when I try it locally.

Can you create a reproduction of this? If you are in the unnamed module, the `jdk.unsupported` module should automatically be read by the agent such that your exception makes little sense to me.

Does your agent share a namespace with your test classes? It seems like it to me since adding `jdk.unsupported` fixes your error.

**Comment by wu-sheng** [comment]
Hi, I am using the adjusted real SkyWalking codes to repoduce the issue.

For agent codes
- repo, https://github.com/apache/skywalking/tree/bug-reproduce
- compile, https://github.com/apache/skywalking/blob/bug-reproduce/docs/en/guides/How-to-build.md#build-from-github. You need `submodule` before maven package.

Once you package the whole project once, you could use `./mvnw clean package -Pagent -Dmaven.test.skip=true` to re-package agent. The compiled result will be placed in `skywalking-agent` folder, like this. The agent premain is in `SkyWalkingAgent` class.
![image](https://user-images.githubusercontent.com/5441976/62374226-0f588400-b56e-11e9-87fb-b1d4c4cb91ec.png)

The instrumentation definition of bootstrap, you could find at `BootstrapInstrumentBoost#inject`. Try to instrument `java.net.HttpURLConnection#setRequestMethod`(`URLInstrumentation` test class only).

Another normal class instrument is `a.Main#main` in `URLInstrumentation2`.

You could active one of them(default both) in `resources/skywalking-plugin.def` of the same module of `URLInstrumentation2`.

![image](https://user-images.githubusercontent.com/5441976/62375288-8a229e80-b570-11e9-8639-56653f4ba223.png)


For target monitored codes.
- repo, https://github.com/wu-sheng/JRE-test
- vm arguments for agent, `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5006 -javaagent:/Users/wusheng/Documents/GitHub/incubator-skywalking/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.is_open_debugging_class=true`
- JRE, OpenJDK 11(9 is same)

Error
```
ERROR 2019-08-02 21:45:08:764 main SkyWalkingAgent :  SkyWalking agent inject bootstrap instrumentation failure. Shutting down. 
java.lang.UnsupportedOperationException: Could not access Unsafe class: sun.misc.Unsafe
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Unavailable.initialize(ClassInjector.java:2033)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1765)
	at org.apache.skywalking.apm.agent.core.plugin.bootstrap.BootstrapInstrumentBoost.inject(BootstrapInstrumentBoost.java:96)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
```

**Comment by wu-sheng** [comment]
FYI, I was using IDEA to start the demo project, rather than do real package and `java`.

**Comment by raphw** [comment]
The error that I get is:

> Caused by: java.lang.IllegalArgumentException: Cannot access delegate$as2bgn0 from class a.Main

what makes sense since you are using delegation to a field where Byte Buddy needs to access an injected class that is added to the module. In this case, you have to add a read and write edge.

**Comment by raphw** [comment]
Alright, I see what is missing. Byte Buddy adds read edges but it does not currently open the package what is required to inject the instance via the Nexus. I do however not think it is a good idea to go down this path with an agent, to be honest, it would be better to delegate to a stateless class and rather manage the state of this class.

I will add a ticket to allow for not only adding read edges but to also export the package of the instrumented class. 

I can however not reproduce the problem that you describe with *jdk.unsupported*. If I just *export a* to the module info, everything works for me.

**Comment by raphw** [comment]
Alright, I added the package export in case that a *from-and-to* option is requested. I will wait a week or two to gather some feedback with the changes on today's release, normally I need to make a few bug fixes rather quickly but I think this should work then.

In the mean time, have a look at my commit and just copy the sections to Skywalking if you cannot wait for the release.

**Comment by wu-sheng** [comment]
Which changes should I do in SkyWalking? Could you submit a pull request to that branch? Locally, I rebuild the master codes and get the same error. 

Could you tell me how you run the demo codes?

**Comment by wu-sheng** [comment]
> If I just export a to the module info, everything works for me.

What do you do about this?

**Comment by wu-sheng** [comment]
I keep seeing this in my local env. I am assuming we are running demo in different ways.
```java
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at JRE.test/a.Main.<clinit>(Main.java)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: Cannot get package using reflection: sun.misc.Unsafe
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getPackage(ClassInjector.java:417)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:219)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:111)
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3147)
	... 10 more
```

**Comment by wu-sheng** [comment]
> I can however not reproduce the problem that you describe with jdk.unsupported. If I just export a to the module info, everything works for me.

After I exported a, I have to add `--add-modules jdk.unsupported` to VM options to make the error disappear. Is this the right move?

Also, how could I make the target class accessible(for AppClassLoader inter)? Or I have to change it to a stateless way? I could by following the way I did for the bootstrap class loader.

**Comment by wu-sheng** [comment]
Well, @raphw I think I got your idea, just except `jdk.unsupported`

So, this is the only question.

**I have to add `--add-modules jdk.unsupported` to VM options to make the error disappear. Is this the right move?**

**Comment by wu-sheng** [comment]
This is the PR I changed https://github.com/apache/skywalking/pull/3199. 

Today, I haven't changed the plugin mechanism to remove `stateful interceptor class`. Consider trying that in another PR as ByteBuddy supported the current way, although it is not good.

So, I will wait for your new release, and confirmation about the question above and the following part of the SkyWalking document.
- Java Platform Module System (JPMS)
Since Java 9, JDK introduces a new level of abstraction above packages, formally known as the Java Platform Module System (JPMS), or “Modules” for short.
If you are using this JDK feature, add `--add-modules jdk.unsupported` to the JVM argument if your application hasn't require `jdk.unsupported`.

**Comment by raphw** [comment]
Alright, learned something new. I finally downloaded a JRE (from Azul, Oracle does not distribute them anymore). The JRE in contrast to the JDK does not load the *jdk.unsupported* module if and only if there is no library on the class path. I do not find this entirely correct behavior, the JVM could even know that a Java agent will be resolved on the class path since it is part of the command line.

As of now, you are right that you need to resolve the *jdk.unsupported* module manually. There is a way around this by using `jdk.internal.misc.Unsafe` instead which is in an isolated module that you could open.

However, Byte Buddy does not yet support configuring a custom strategy and the default one does not support this. I will leave this ticket open as a reminder to offer something like this at some point.

In the end, I do however consider this a bug in the JRE distribution as the *jdk.unsupported* module should be resolved if an agent is active (static or dynamic). What JRE distribution are you running?

**Comment by raphw** [comment]
I tried a bunch of runtimes now and this only seems to happen with Zulu Community.

**Comment by wu-sheng** [comment]
I am always using openJDK to do all these tests.
![image](https://user-images.githubusercontent.com/5441976/62431229-2a86e780-b758-11e9-8a70-9fd87d485cf7.png)

> Wu-Sheng-s-MacBook-Pro:~ wusheng$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

Used to download JDK like this
> Wu-Sheng-s-MacBook-Pro:jd-gui-osx-1.4.0 wusheng$ brew cask install adoptopenjdk11
==> Satisfying dependencies
==> Downloading https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_x64_mac_hotspot_11.0.4_11.pk
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/140419044/2c803680-a962-11e9-9ee9-823459fcd826?X-Amz-Algori
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk11'.
==> Installing Cask adoptopenjdk11
==> Running installer for adoptopenjdk11; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is AdoptOpenJDK
installer: Installing at base path /
installer: The install was successful.
🍺  adoptopenjdk11 was successfully installed!
Wu-Sheng-s-MacBook-Pro:jd-gui-osx-1.4.0 wusheng$ brew cask install adoptopenjdk12
==> Satisfying dependencies
==> Downloading https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.2%2B10/OpenJDK12U-jdk_x64_mac_hotspot_12.0.2_10.pk
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/172940752/bea82f00-a9a2-11e9-9d35-79643d220f13?X-Amz-Algori
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk12'.
==> Installing Cask adoptopenjdk12
==> Running installer for adoptopenjdk12; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.

No special change. As far as I keep using modules to manage dependency, even 3rd party libs, such as gson, log4j, the `--add-modules jdk.unsupported` is always required.

**Comment by wu-sheng** [comment]
When is 1.10.1 release plan? I will wait for that to update SkyWalking PR https://github.com/apache/skywalking/pull/3199. There is nothing urgent, SkyWalking doesn't include this in 6.3.0 due to this is compatible change to the plugin system.

**Comment by raphw** [comment]
I think that I will include a workaround for the unavailability of *jdk.unsupported* and make a release after that. I have also registered an issue with OpenJDK for this phenomenon: https://bugs.openjdk.java.net/browse/JDK-8229121

**Comment by raphw** [comment]
This should be taken care of on master now. I reworked the injection strategy and there is now a way to configure injection:

```java
ClassInjector.UsingUnsafe.Factory factory = ClassInjector.UsingUnsafe.Factory.resolve(instrumentation);
factory.make(null, null).injectRaw(classesTypeMap);
agentBuilder = agentBuilder.with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(factory));
```

**Comment by wu-sheng** [comment]
@raphw What is this new API for? Make the rejector working w/ agentBuilder for?

**Comment by raphw** [comment]
It gives you a means of falling back to `jdk.internal.misc.Unsafe` what is possible using the `Instrumentation` API. Since that latter class is not part of an optional module, no harm is done.

**Comment by wu-sheng** [comment]
By using commit[`b609711564`] to test, the `--add-modules jdk.unsupported` is not required anymore. Although, I have to change SkyWalking agent by removing Disruptor dependency, which can not run in this way.

Thanks, @raphw, provide such a convenient way.

**Comment by raphw** [comment]
Glad it works for you. I just released a new version.
