### ISSUE TITLE
Attaching bytebudy javaagent to Websphere failing

### ISSUE THREAD

**Issue by mjok** [raphw/byte-buddy#705]
Hello, 

I'am trying to write an javaAgent using byte-buddy library. I have built my agent with maven-shade and tried attaching on WebSphere.
It does work fine on test, but failing won WebSphere application server with exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:408)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:423)
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@44166cd
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510)
	at com.jkoolcloud.javaam.App.premain(App.java:44)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:603)
	... 10 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: target not found
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:97)
	at com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:43)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 16 more

Fatal error: processing of -javaagent failed
```

That's a simple code:

```
	public static void premain(String options, Instrumentation inst) throws IOException {
		System.out.println("Starting from premain");
		System.out.println(com.sun.tools.attach.VirtualMachine.list());
		ByteBuddyAgent.install();
<..>
}
```

And the output:
```
Starting from premain
[com.ibm.tools.attach.attacher.OpenJ9AttachProvider@9b8975d9: 17128 com.ibm.ws.bootstrap.WSLauncher com.ibm.ws.management.tools.WsServerLauncher C:\Users\slabs\IBM\WebSphere\AppServer2\profiles\AppSrv01\config slabs-marius-PCNode01Cell slabs-marius-PCNode01 server1]
```

Any suggestions I could try-out?

P.S. I have added my agent to security.policy
```
grant codeBase "file:c:/workspace/probe/target/probeAll.jar" {
  permission java.security.AllPermission;
};
```

**Comment by raphw** [comment]
I am confused, why are you calling `install` from premain? If you are writing an agent, you already have an `Instrumentation` available. Normally, you call the method to avoid the requirement of specifying an agent on the command line.

From your stack it seems like the VM you are running from runs with a different process id then what Byte Buddy expects. Can you debug this by adding break points to see what process id is resolved and what process id the process actually has?

**Comment by mjok** [comment]
Thank you, actually i did not had to call ```install```. 

I have tried to debug. Seems that process id is correct. I'am attaching the screenshot.
![byteBuddy](https://user-images.githubusercontent.com/10325240/62522513-86c23800-b83a-11e9-86e7-94b1dee09f43.JPG)

**Comment by raphw** [comment]
No, but it seems like something happend during your attachment attempt in J9s native code.
