### ISSUE TITLE
Unable to instrument FileInputStream and FileOutputStream classes

### ISSUE THREAD

**Issue by spradeepkishore** [raphw/byte-buddy#710]
Hi
We have customized Elastic APM JAVA agent.
https://github.com/elastic/apm-agent-java

We are instrumenting FileInputStream and FileOutputStream classes. It is throwing following exception:
2019-08-14 01:29:18.687 [main] WARN co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - Error on transformation java.io.FileOutputStream
java.lang.IllegalStateException: Cannot write to read-only parameter class java.lang.String at 1
	at co.elastic.apm.agent.shaded.bytebuddy.asm.Advice$OffsetMapping$Target$ForVariable$ReadOnly.resolveWrite(Advice.java:878)
	at co.elastic.apm.agent.shaded.bytebuddy.asm.Advice$Dispatcher$Inlining$CodeTranslationVisitor.visitVarInsn(Advice.java:8199)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.MethodVisitor.visitVarInsn(MethodVisitor.java:348)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2027)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1283)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
	at co.elastic.apm.agent.shaded.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:7328)
	at co.elastic.apm.agent.shaded.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:9376)
	at co.elastic.apm.agent.shaded.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:49)
	at co.elastic.apm.agent.shaded.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:62)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.Label.accept(Label.java:357)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1823)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1283)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
	at co.elastic.apm.agent.shaded.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
	at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3393)
	at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
	at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:217)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10132)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10889)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10836)
	at java.security.AccessController.doPrivileged(Native Method)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6734)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7011)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6860)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4728)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9272)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9242)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:11234)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:147)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:103)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at co.elastic.apm.agent.bci.AgentMain.init(AgentMain.java:85)
	at co.elastic.apm.agent.bci.AgentMain.premain(AgentMain.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

Agent builder is available at https://github.com/elastic/apm-agent-java/blob/master/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java

 .disableClassFormatChanges() is already set

Attached my advice classes

**Comment by spradeepkishore** [comment]
public class FileInputStreamInstrumentation extends ElasticApmInstrumentation {

    @Override
    public Collection<String> getInstrumentationGroupNames() {
        return Arrays.asList("file-system");
    }

    @Nullable
    @VisibleForAdvice
    @Advice.OnMethodEnter(suppress = Throwable.class)
    public static void enter(@Advice.Argument(0) String fileName,
                             @Advice.Local("span") Span span) {
		try {
			if (tracer == null || tracer.getActive() == null) {
				return;
			}

			final TraceContextHolder<?> activeSpan = tracer.getActive();
			if (activeSpan == null || !activeSpan.isSampled()) {
				return;
			}
			
			if (fileName == null) {
				return;
			}
			else {
				fileName = fileName.toLowerCase();
			}
			if (fileName.endsWith(".jar") || fileName.endsWith(".war")) {
				return;
			}

			span = activeSpan.createSpan();

			if (span == null) {
				return;
			}

			span.withType("file").withSubtype("io").withAction("read").appendToName(fileName);
			// span.getContext().
			span.activate();
		} catch (Exception e) {
		}
    }
    
    @Nullable
    @VisibleForAdvice
    @Advice.OnMethodExit(suppress = Throwable.class, onThrowable = Throwable.class)
    public static void exit(//@Advice.This HttpURLConnection thiz,
                            //@Nullable @Advice.Thrown Throwable t,
                            //@Advice.FieldValue("responseCode") int responseCode,
    						@Advice.Argument(0) String fileName,
                            @Nullable @Advice.Local("span") Span span,
                            @Advice.Origin String signature) {
    	try {
    		if (span!=null)
    			span.end();
    	} catch (Exception e) {}
    }

	@Override
	public ElementMatcher<? super TypeDescription> getTypeMatcher() {
		return is(FileInputStream.class);
	}

	@Override
	public ElementMatcher<? super MethodDescription> getMethodMatcher() {
		return named("open");
	}
}

**Comment by raphw** [comment]
You have to declare parameters as writable: `@Advice.Argument(value = 0, readOnly = false)`.

Note that this way, you are changing the value that is available during the execution of the actual method.

**Comment by spradeepkishore** [comment]
Thank you for quick response. 

I set readOnly=false but that is causing an application to load files (eg: .xhtml files) in tomcat. The same application works if i dont set readOnly=false, which means, the transformation failed on FileInputStream class.

java.io.FileNotFoundException: /opt/apache-tomcat-8.5.34/webapps/root/orange.xhtml (No such file or directory)
    java.io.FileInputStream.open0(Native Method)
    java.io.FileInputStream.open(FileInputStream.java:195)
    java.io.FileInputStream.<init>(FileInputStream.java:138)
    java.io.FileInputStream.<init>(FileInputStream.java:93)
    sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    com.sun.faces.facelets.impl.DefaultFaceletCache._getLastModified(DefaultFaceletCache.java:172)
    com.sun.faces.facelets.impl.DefaultFaceletCache.access$000(DefaultFaceletCache.java:62)
    com.sun.faces.facelets.impl.DefaultFaceletCache$2.newInstance(DefaultFaceletCache.java:93)
    com.sun.faces.facelets.impl.DefaultFaceletCache$2.newInstance(DefaultFaceletCache.java:89)
    com.sun.faces.util.ExpiringConcurrentCache$1.call(ExpiringConcurrentCache.java:99)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    com.sun.faces.util.ExpiringConcurrentCache.get(ExpiringConcurrentCache.java:114)
    com.sun.faces.facelets.impl.DefaultFaceletCache.getViewMetadataFacelet(DefaultFaceletCache.java:143)
    com.sun.faces.facelets.impl.DefaultFaceletCache.getViewMetadataFacelet(DefaultFaceletCache.java:62)
    com.sun.faces.facelets.impl.DefaultFaceletFactory.getMetadataFacelet(DefaultFaceletFactory.java:260)
    com.sun.faces.facelets.impl.DefaultFaceletFactory.getMetadataFacelet(DefaultFaceletFactory.java:209)
    com.sun.faces.application.view.ViewMetadataImpl.createMetadataView(ViewMetadataImpl.java:114)
    com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:233)
    com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
    com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
    javax.faces.webapp.FacesServlet.service(FacesServlet.java:409)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by raphw** [comment]
You are transforming the file name in your transformation, maybe what you want to is to retain `readOnly = true` and rather assign the transformed value to a new variable.

**Comment by spradeepkishore** [comment]
Thank you very much.
