### ISSUE TITLE
bytebuddy error-java.lang.IllegalStateException: Unexpected complex array component type boolean

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#725]
I instrument this function but it show the following error

    package com.att.brandservices.shared.supporting.storage.cassandra.accessors;
    import com.att.brandservices.shared.supporting.model.lookup.RewardByPayoutDate;
    import com.datastax.driver.mapping.Result;
    import com.datastax.driver.mapping.annotations.Accessor;
    import com.datastax.driver.mapping.annotations.Query;
    import com.datastax.driver.mapping.annotations.QueryParameters;
    import java.time.LocalDate; 
    @Accessor
    public interface RewardByPayoutDateAccessor {
    @Query("SELECT * FROM lookup_reward_by_payout WHERE payout = :payoutDate and actor = :actor")
    @QueryParameters(consistency = "LOCAL_QUORUM")
    Result<RewardByPayoutDate> getAll(LocalDate payoutDate, String actor);

    @Query("DELETE FROM lookup_reward_by_payout WHERE payout = :payoutDate and actor = :actor and rewardid = :rewardid")
    @QueryParameters(consistency = "LOCAL_QUORUM")
    Result<RewardByPayoutDate> delete(LocalDate payoutDate, String actor, String rewardid);
    }

My instrumentation is 

    

                defaultAgent = defaultAgent.type(ElementMatchers.isInterface().and(ElementMatchers.named("com.att.brandservices.shared.supporting.storage.cassandra.accessors.RewardByPayoutDateAccessor")))
                .transform(new AgentBuilder.Transformer.ForAdvice()
                        .include(CassandraInterceptor.class.getClassLoader())
                        .advice(ElementMatchers.isMethod().and(ElementMatchers.nameContains("getAll")),
                                (CassandraInterceptor.class.getName())));

My interceptor is :
    
    public class CassandraInterceptor {

    @Advice.OnMethodEnter
    private static void before(@Advice.Origin Method method, @Advice.AllArguments Object[] allArguments){

    }

    @Advice.OnMethodExit
    static void exit(@Advice.Origin Method method) {

    }}

```
[Byte Buddy] ERROR com.att.brandservices.shared.supporting.storage.cassandra.accessors.RewardByPayoutDateAccessor [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=false]
java.lang.IllegalStateException: Unexpected complex array component type boolean
	at net.bytebuddy.pool.TypePool$AbstractBase$RawDescriptionArray.resolve(TypePool.java:881)
	at net.bytebuddy.pool.TypePool$AbstractBase$RawDescriptionArray.hashCode(TypePool.java:904)
	at net.bytebuddy.description.annotation.AnnotationDescription$AbstractBase.hashCode(AnnotationDescription.java:513)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at net.bytebuddy.description.method.MethodDescription$Token.hashCode(MethodDescription.java:1943)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.containsKey(HashMap.java:596)
	at java.util.HashSet.contains(HashSet.java:204)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder$RebaseableMatcher.matches(RebaseDynamicTypeBuilder.java:273)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder$RebaseableMatcher.matches(RebaseDynamicTypeBuilder.java:241)
	at net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:216)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10050)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10469)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10432)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10198)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10807)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10754)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10355)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.att.brandservices.shared.supporting.service.RewardPayout.applyPayout(RewardPayout.java:121)
	at com.att.brandservices.shared.supporting.service.RewardPayout.applyPayout(RewardPayout.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by raphw** [comment]
Seems like I got some annotation parsing wrong. I will need to have a look!

**Comment by raphw** [comment]
I just had a look and found that I had reworked this part a few weeks ago, some of the internal classes in the stack do no longer exist even. Could you retest this with the most recent release of Byte Buddy?

**Comment by raphw** [comment]
Please reopen this if you still have issues.

**Comment by spmason** [comment]
Hi, I've got a similar error on one of my projects, using the `1.10.5` release (via the Maven plugin if that helps):

```
#19 35.73 [ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.5:transform (default) on project myproject: Failed to transform class files in /myproject/target/classes: Unexpected complex component type: double -> [Help 1]
#19 35.73 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.5:transform (default) on project myproject: Failed to transform class files in /myproject/target/classes
#19 35.73     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
#19 35.73     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
#19 35.73     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
#19 35.73     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
#19 35.73     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
#19 35.73     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
#19 35.73     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.73     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
#19 35.73     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.73     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
#19 35.74     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
#19 35.74     at java.lang.Thread.run (Thread.java:834)
#19 35.74 Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to transform class files in /myproject/target/classes
#19 35.74     at net.bytebuddy.build.maven.ByteBuddyMojo.apply (ByteBuddyMojo.java:299)
#19 35.74     at net.bytebuddy.build.maven.ByteBuddyMojo.execute (ByteBuddyMojo.java:195)
#19 35.74     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
#19 35.74     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
#19 35.74     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
#19 35.74     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
#19 35.74     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
#19 35.74     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
#19 35.74     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
#19 35.74     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.74     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
#19 35.74     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.74     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
#19 35.74     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
#19 35.74     at java.lang.Thread.run (Thread.java:834)
#19 35.74 Caused by: java.lang.IllegalStateException: Unexpected complex component type: double
#19 35.74     at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue$ForNonPrimitiveArray.doResolve (TypePool.java:5968)
#19 35.75     at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue.hashCode (TypePool.java:5780)
#19 35.75     at net.bytebuddy.description.annotation.AnnotationDescription$AbstractBase.hashCode (AnnotationDescription.java:437)
#19 35.75     at java.util.AbstractList.hashCode (AbstractList.java:567)
#19 35.75     at net.bytebuddy.description.method.MethodDescription$Token.hashCode (MethodDescription.java:1951)
#19 35.75     at java.util.HashMap.hash (HashMap.java:339)
#19 35.75     at java.util.HashMap.put (HashMap.java:607)
#19 35.75     at java.util.HashSet.add (HashSet.java:220)
#19 35.75     at java.util.AbstractCollection.addAll (AbstractCollection.java:352)
#19 35.75     at java.util.HashSet.<init> (HashSet.java:120)
#19 35.75     at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder$RebaseableMatcher.of (RebaseDynamicTypeBuilder.java:276)
#19 35.75     at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make (RebaseDynamicTypeBuilder.java:226)
#19 35.75     at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make (DynamicType.java:3621)
#19 35.75     at net.bytebuddy.build.Plugin$Engine$Default.apply (Plugin.java:3638)
#19 35.75     at net.bytebuddy.build.maven.ByteBuddyMojo.apply (ByteBuddyMojo.java:297)
#19 35.75     at net.bytebuddy.build.maven.ByteBuddyMojo.execute (ByteBuddyMojo.java:195)
#19 35.75     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
#19 35.75     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
#19 35.75     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
#19 35.75     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
#19 35.76     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
#19 35.76     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
#19 35.76     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
#19 35.76     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.76     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
#19 35.76     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
#19 35.76     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
#19 35.76     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
#19 35.76     at java.lang.Thread.run (Thread.java:834)
```

The environment is simply a docker container using the `maven:3.6-jdk-11` image (so Java 11/Maven 3.6)

**Comment by spmason** [comment]
Oh, looks like I can't re-open @raphw because I didn't make this issue

**Comment by raphw** [comment]
Would you be able to give me an example of the type that you are trying to transform? I don't need any of the code, just the class and it's content.

**Comment by lujiajing1126** [comment]
I also have this issue even with v1.10.9

In my case, I am going to use a special annotation like `@Timed` annotation in micrometer, here is the definition
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java

then I am trying to interceptor all methods that are annotated with `@Timed` annotation. 

```
[wosai.hera 2020-04-28 16:44:05:804 +0800] [main] ERROR com.wosai.middleware.hera.agent.Agent - Enhance class com.wosai.middleware.tester.hera.HelloController error.
java.lang.IllegalStateException: Unexpected complex component type: double
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue$ForNonPrimitiveArray.doResolve(TypePool.java:5968)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue.hashCode(TypePool.java:5780)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.annotation.AnnotationDescription$AbstractBase.hashCode(AnnotationDescription.java:437)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.method.MethodDescription$Token.hashCode(MethodDescription.java:1952)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.HashSet.<init>(HashSet.java:120)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder$RebaseableMatcher.of(RebaseDynamicTypeBuilder.java:276)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:226)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10648)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10595)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10186)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:285)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1469)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:682)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1605)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:494)
	at org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration$DispatcherServletRegistrationCondition.checkDefaultDispatcherName(DispatcherServletAutoConfiguration.java:173)
	at org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration$DispatcherServletRegistrationCondition.getMatchOutcome(DispatcherServletAutoConfiguration.java:164)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:225)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:371)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:271)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)
	at org.springframework.context.annotation.ConfigurationClassParser.access$800(ConfigurationClassParser.java:110)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:811)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:808)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:779)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:192)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.wosai.middleware.tester.hera.HeraTesterApplication.main(HeraTesterApplication.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

I got some error like this.

**Comment by raphw** [comment]
I think I found the problem and just here: https://github.com/raphw/byte-buddy/commit/1fddd12dbe56af9a1bc10ede1cb49dc9cc7c0e63

**Comment by lujiajing1126** [comment]
> I think I found the problem and just here: [1fddd12](https://github.com/raphw/byte-buddy/commit/1fddd12dbe56af9a1bc10ede1cb49dc9cc7c0e63)

I confirm my problem has been fixed with the latest commit. Thx!
