### ISSUE TITLE
Handle missing types more gracefully

### ISSUE THREAD

**Issue by jpfourny** [raphw/byte-buddy#730]
I am struggling with a real-world case of instrumenting JDBC drivers that have incomplete (read optional) dependencies. Several JDBC vendors (including Microsoft and Oracle) assemble driver packages that include support for multiple JDBC levels and multiple Java language levels, but they don't always separate implementations very cleanly. For example, when DriverManager preloads Microsoft SqlServer driver, the class com.microsoft.sqlserver.jdbc.SQLServerConnection43 will be used for both Java 7 and Java 8. However, this class makes indirect references to types only available to Java 8 (ex: java.sql.ShardingKey). The only reason this works is because they rely on Java's lazy-loading mechanism and never end up "touching" the Java-8 specific bits. However, when instrumentation via ByteBuddy has a go at these types, we may end up failing the transformation all together. 

What follows is an example stack trace of when a relevance matcher fails in net.bytebuddy.dynamic.scaffold.MethodRegistry.Default.prepare(..) due to failed type resolution: 

> java.lang.IllegalStateException: Cannot resolve type description for java.sql.ShardingKey
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:153)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1270)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7119)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:539)
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:313)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:6726)
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:31)
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:12)
	at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:33)
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:14)
	at net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:31)
	at net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:12)
	at net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:31)
	at net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:11)
	at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
	at net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:32)
	at net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:13)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:428)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:163)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:9167)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9578)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9541)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:9309)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9906)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9855)
	at java.security.AccessController.doPrivileged(AccessController.java:704)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9464)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:200)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:450)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:389)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:730)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:935)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:880)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:343)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:863)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1848)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:391)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:415)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:491)
	at java.sql.DriverManager$2.run(DriverManager.java:614)
	at java.sql.DriverManager$2.run(DriverManager.java:594)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:594)

Ideally, I would require an implementation of MethodRegistry that is lenient by treating failures from the relevance matcher as false match (ie: fail-safe matcher). I don't see an obvious way to influence the implementation of MethodRegistry.

**Comment by raphw** [comment]
Technically speaking, this is something that the JVM does not support. It supports optional types on the byte code level but not as part of signatures. Lazy loading of those is not part of the spec but an optionally applied performance optimization that will neither be acceptable to AOT compilers.

That said, I see your use case but there is currently no way. One possibility would be to allow wrapping the matcher with a suppression mechanism for unknown types. But even easier, you can use a type pool that returns stubs for types that are not available.

Is this in an agent? In this case, you could also use a method registry only for declared methods. That way, Byte Buddy only considers methods already declared by the type and does not need to assert visibility.
