### ISSUE TITLE
Spaces in executable name causes the program to crash

### ISSUE THREAD

**Issue by villesau** [raphw/byte-buddy#732]
when running mockito (and bytebuddy) in IntelliJ, the test run crashes since the java executable has spaces in the path. The problem anyhow is not spaces, but quoting paths that has spaces. Spaced paths should not be quoted. This fails when running the program.

problematic lines:

https://github.com/raphw/byte-buddy/blame/11855e663f21dcc8a6b59dc0133007fd07bb11c0/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L717

https://github.com/raphw/byte-buddy/blob/11855e663f21dcc8a6b59dc0133007fd07bb11c0/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L659

Minimal repro of quotes in file name:

```
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Hello {
  
  public static void main(String []args) throws IOException {
    try {
      List<String> list = new ArrayList<String>();
      list.add("\"/Applications/IntelliJ IDEA 2019.3 EAP.app/Contents/jbr/Contents/Home/bin/java\"");
      ProcessBuilder builder = new ProcessBuilder(list);
      builder.start();
      System.out.println("finished");
    } catch (Exception e) {
      System.out.println(e);
    }
  }  
}

```

If I take quotes off, the program runs fine. I believe this might have been a breaking change in some Java version. I'm running java 12.0.1 and IntelliJ is running Java 11.0.4+12-b462.3 on macOS.

Related issue for IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-222903

**Comment by villesau** [comment]
An easy solution would be to take the quoting away, but I suspect it might blow up legacy javas. Maybe the java version needs to be detected during runtime? In any case this prevents from running tests with mockito in IntelliJ at the moment,

**Comment by villesau** [comment]
This is the full stacktrace:

```
Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
  at controllers.MockModules.getItemStore(MyClass1Test.kt:77)
  while locating utilities.ItemStore
    for the 2nd parameter of controllers.MyClass1.<init>(MyClass1.kt:49)
  while locating controllers.MyClass1
    for the 1st parameter of routes.ApiRoutes.<init>(ApiRoutes.kt:20)
  while locating routes.ApiRoutes

1 error
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
  at controllers.MockModules.getItemStore(MyClass1Test.kt:77)
  while locating utilities.ItemStore
    for the 2nd parameter of controllers.MyClass1.<init>(MyClass1.kt:49)
  while locating controllers.MyClass1
    for the 1st parameter of routes.ApiRoutes.<init>(ApiRoutes.kt:20)
  while locating routes.ApiRoutes

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at controllers.MyClass1Test.<init>(MyClass1Test.kt:173)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy37.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:240)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:228)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
	at org.mockito.Mockito.mock(Mockito.java:1908)
	at controllers.MockModules.getItemStore(MyClass1Test.kt:407)
	at controllers.MockModules$$FastClassByGuice$$18413b66.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 49 more
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@525a929c
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:22)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:19)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	... 74 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 11
JVM vendor name    : JetBrains s.r.o
JVM vendor version : 11.0.4+12-b462.3
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.4+12-b462.3
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14.6

	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:168)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
	... 79 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@45831e6b
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:427)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:401)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:353)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:330)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:104)
	... 85 more
Caused by: java.io.IOException: Cannot run program ""/Applications/IntelliJ IDEA 2019.3 EAP.app/Contents/jbr/Contents/Home/bin/java"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:485)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:420)
	... 89 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 92 more

controllers.MyClass1Test > import from url CSV format FAILED
    com.google.inject.ProvisionException: Unable to provision, see the following errors:
    1) Error in custom provider, java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
      at controllers.MockModules.getItemStore(MyClass1Test.kt:77)
      while locating utilities.ItemStore
        for the 2nd parameter of controllers.MyClass1.<init>(MyClass1.kt:49)
      while locating controllers.MyClass1
        for the 1st parameter of routes.ApiRoutes.<init>(ApiRoutes.kt:20)
      while locating routes.ApiRoutes
    1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at controllers.MyClass1Test.<init>(MyClass1Test.kt:173)
        Caused by:
        java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
            at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
            at com.sun.proxy.$Proxy37.isTypeMockable(Unknown Source)
            at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
            at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
            at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:240)
            at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:228)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
            at org.mockito.Mockito.mock(Mockito.java:1908)
            at controllers.MockModules.getItemStore(MyClass1Test.kt:407)
            at controllers.MockModules$$FastClassByGuice$$18413b66.invoke(<generated>)
            at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
            at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
            at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
            at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
            at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
            at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
            at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
            at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
            at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
            at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
            at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
            at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
            at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
            at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
            at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
            at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
            at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
            at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
            ... 2 more
            Caused by:
            java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@525a929c
                at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
                at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
                at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
                at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:22)
                at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:19)
                at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
                ... 27 more
                Caused by:
                org.mockito.exceptions.base.MockitoInitializationException: 
                Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)
                Java               : 11
                JVM vendor name    : JetBrains s.r.o
                JVM vendor version : 11.0.4+12-b462.3
                JVM name           : OpenJDK 64-Bit Server VM
                JVM version        : 11.0.4+12-b462.3
                JVM info           : mixed mode
                OS name            : Mac OS X
                OS version         : 10.14.6
                    at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:168)
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                    at java.base/java.lang.Class.newInstance(Class.java:584)
                    at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
                    ... 32 more
                    Caused by:
                    java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@45831e6b
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:427)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:401)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:353)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:330)
                        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:104)
                        ... 38 more
                        Caused by:
                        java.io.IOException: Cannot run program ""/Applications/IntelliJ IDEA 2019.3 EAP.app/Contents/jbr/Contents/Home/bin/java"": error=2, No such file or directory
                            at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
                            at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
                            at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:485)
                            at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:420)
                            ... 42 more
                            Caused by:
                            java.io.IOException: error=2, No such file or directory
                                at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
                                at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
                                at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
                                at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
                                ... 45 more
```

**Comment by tmohme** [comment]
Still the same behavior with 1.10.3 on macOS 10.14.5 with IntelliJ 2019.2.4 (coming with JDK11, path with spaces), Kotlin 1.3.50 with mockk.
As @villesau already mentioned, the cause is the quoting in https://github.com/raphw/byte-buddy/blob/60d58b875c6096eda38ed026d92f24bf029bd0ba/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L659. When I manually remove the quotes my tests execute successfully.
Works well outside IntelliJ (openjdk 11.0.5, path without spaces).

**Comment by tmohme** [comment]
@villesau Do you know of any workaround?

**Comment by raphw** [comment]
Sorry, this went under. I just fixed it on master. Thanks for reporting.

**Comment by villesau** [comment]
@raphw Will the fix be released soon?

**Comment by vngrp** [comment]
@raphw thank you for solving this 🙏

@villesau as a workaround you can point Java Home to a path without a space. 
1. Open Project Structure (`cmd + ;`)
2. Go to SDK's and edit the JDK home path

If you don't have another version to link you can get one like this:
```
brew update
brew install java11
```

Then you can edit the JDK home path at the Project structure to:
/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home

**Comment by raphw** [comment]
I will do a release some time this week!

**Comment by raphw** [comment]
Should be working in the latest release. Please tell me if not.

**Comment by ayayron-onx** [comment]
Ran into this issue in Android Studio running on MacOS 11.4

Renaming Android Studio.app to AndroidStudio.app made the bug go away. Any chance we can get a fix for that?

**Comment by raphw** [comment]
I don't have a Mac and CI servers do not generally reproduce this issue. The problem is somewhere here: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L658

Feel free to try out what escaping is solving the issue for you and check if the change also works for the path without the white space. Maybe this is required for Mac, but I do not really know either.
