### ISSUE TITLE
Unable to instrument class file version on Java 6 on JDK 11

### ISSUE THREAD

**Issue by drodriguezhdez** [raphw/byte-buddy#740]
`JDK: 11.0.2`
`Byte-Buddy: 1.10.1`

Trying to instrument a certain library that was compiled in Java 6, it is being shown the following error:

```
java.lang.IllegalStateException: Cannot write invoke dynamic instruction for class file version Java 6
```

However, if I use JDK 1.7/1.8, the class is instrumented without problems.

Did I miss something to instrument these kind of classes?
Thanks so very much!

**Comment by raphw** [comment]
Do you have a stacktrace?

**Comment by drodriguezhdez** [comment]
```
java.lang.IllegalStateException: Cannot write invoke dynamic instruction for class file version Java 6
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$ForClassFileVersion.assertInvokeDynamic(TypeWriter.java:2980)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$Compound.assertInvokeDynamic(TypeWriter.java:3150)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$ValidatingMethodVisitor.visitInvokeDynamicInsn(TypeWriter.java:3269)
        at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:451)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.onVisitInvokeDynamicInsn(ExceptionTableSensitiveMethodVisitor.java:198)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitInvokeDynamicInsn(ExceptionTableSensitiveMethodVisitor.java:186)
        at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:451)
        at net.bytebuddy.utility.visitor.StackAwareMethodVisitor.visitInvokeDynamicInsn(StackAwareMethodVisitor.java:310)
        at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:451)
        at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:451)
        at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2240)
        at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1283)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:7379)
        at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:9427)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:49)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:62)
        at net.bytebuddy.jar.asm.Label.accept(Label.java:357)
        at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1823)
        at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1283)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:688)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:400)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3397)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:217)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10123)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10907)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10845)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10413)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6865)
        at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7142)
        at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6991)
        at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4858)
        at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9350)
        at net.bytebuddy.agent.builder.AgentBuilder$Default.installOnByteBuddyAgent(AgentBuilder.java:9390)
        at net.bytebuddy.agent.builder.AgentBuilder$Default.installOnByteBuddyAgent(AgentBuilder.java:9382)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOnByteBuddyAgent(AgentBuilder.java:11178)
        at com.undefinedlabs.scope.rules.AbstractSingleScopeAgentRuleTest.getTransformers(AbstractSingleScopeAgentRuleTest.java:20)
        at com.undefinedlabs.scope.rules.AbstractScopeAgentRuleTest.instrumentedTracing(AbstractScopeAgentRuleTest.java:129)
        at com.undefinedlabs.scope.rules.ApacheHttpClientScopeAgentRuleTest.should_instrument_httpclient_put_connection_exception(ApacheHttpClientScopeAgentRuleTest.java:113)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

**Comment by raphw** [comment]
I assume that you are using an advice template that uses an invokedynamic instruction, most likely a lambda expression. If your targeted class file was compiled against Java 6, it is illegal to inline such an expression into the instrumented class, no matter what JVM version you are running.

Make sure to compile your advice classes against Java 6 byte code level. That is the most universal to consider.

**Comment by drodriguezhdez** [comment]
By default, my classes are compiled using target 1.7, so the `@Advice methods` is not using lambda expressions or anything that doesn't fulfil the 1.7 target.

**Comment by raphw** [comment]
The stack trace clearly indicates that your class reader discovers an invoke dynamic instruction in your advice code. Can you set a breakpoint where the exception is thrown? This would give you information where. 

W

**Comment by drodriguezhdez** [comment]
OK, here we are:

![image](https://user-images.githubusercontent.com/29516565/66920281-3e39ae80-f023-11e9-9b96-82cc40fcf31c.png)

It seems Java 11 is making something "illegal" for Java 6 when concat Strings, right?

**Comment by raphw** [comment]
Yes, Java 11 implements string concatenation based on invoke dynamic. Ideally, you put all advice code into a seperate module and compile it with a source and byte code target of Java 6.

**Comment by drodriguezhdez** [comment]
Fixed!

Thanks for the support!
