### ISSUE TITLE
[Question] Duplicate method name Exception

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#750]
I'm following this tutorial to create java-agent with bytebuddy (https://github.com/ShehanPerera/javaagent-bytebuddy/blob/master/samples/execution-time/src/main/java/com/github/shehanperera/timers/Agent.java)

all good until I apply the created java agent to my application, 

It throw exception `Duplicate method name`, 
any advice the common fault of this error ?

```
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name "clone" with signature "()Ljava.lang.Object;" in class file com/amazonaws/AmazonWebServiceRequest$1
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by davidasync** [comment]
I change this
```
builder
 .method(ElementMatchers.any())
 .intercept(Advice.to(TimerAdvice.class))
```

to 
```
builder
 .visit(Advice.to(TimerAdvice::class.java).on(ElementMatchers.any()))
```

And the error disappear, not sure why
but it solve my case hohoho

**Comment by raphw** [comment]
That is a strange error anyways, I assume that the `clone` method was reimplemented from its super type somehow and was duplicated eventually.

If you can create a reproduction I am happy to have a look.
