### ISSUE TITLE
[Question] @Advice.This at @Advice.OnMethodEnter cause duplicate class definition error

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#757]
Hello,
I have this class
**// PlaygroundAgent.kt**
```
object PlaygroundAgent {
  @JvmStatic
  fun premain(arguments: String?, instrumentation: Instrumentation?) {
    println("Agent for time measure")

    AgentBuilder.Default()
      .with(AgentBuilder.InitializationStrategy.SelfInjection.Eager())
      .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
      .type( nameContains<TypeDescription>("SampleImpl").and(not(isInterface())).and(not(isStatic())))
      .transform { builder, typeDescription, classLoader, module ->
        builder
          .visit(Advice.to(TimerAdvice::class.java).on(nameContains("method4")))
      }.installOn(instrumentation)
  }
}
```

**// SampleImpl.kt**
```
class SampleImpl(val var1: String) : SampleInterface {
    init {
        println("This is constructor")
    }

    override suspend fun method1() {
        try {
            Thread.sleep(500)
            println("This is Method 1")
        } catch (e: InterruptedException) {
            //Ignore
        }
    }

    override suspend fun method2() {
        try {
            Thread.sleep(1000)
            println("This is Method 2 with $var1")
        } catch (e: InterruptedException) {
            //Ignore
        }

    }

    override suspend fun method3(number: Number, word: String, bool: Boolean) {
        println("number :$number | string :$word | boolean :$bool")
    }

    @Throws(Exception::class)
    override suspend fun method4(): String {
//      val x = 1/0
      return ""
    }
}
```

**// TimerAdvice.kt**
```
object TimerAdvice{
  @JvmStatic
  @Advice.OnMethodEnter(suppress = Throwable::class)
  @Throws(Exception::class)
  private fun enter(@Advice.This sampleImpl: SampleImpl): Long {
    println(sampleImpl.var1)
    return System.currentTimeMillis()
  }
```

This code cause this error 
```
java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/SampleImpl"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.SampleServiceKt.main(SampleService.kt:4)
	at com.SampleServiceKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at com.SampleServiceKt.main(SampleService.kt)

```

However, when I change TimerAdvice.kt to this
```
  @JvmStatic
  @Advice.OnMethodEnter(suppress = Throwable::class)
  @Throws(Exception::class)
  private fun enter(@Advice.This sampleImpl: Any): Long {
    println((sampleImpl as SampleImpl).var1)
    return System.currentTimeMillis()
  }
```

It works as expected, 
Any idea why I shud accept Any instead of SampleImpl class at `@Advice.This`

**Comment by raphw** [comment]
You are loading the `SampleImpl` class while instrumenting `SampleImpl`. This causes the class to be loaded prematurely during its original loading which results in its duplicate definition at the end of the loading process.

You can avoid this by not using `Advice.to(TimerAdvice::class.java)` where Byte Buddy uses reflection to describe classes what implicates class loading of signature types but rather use a `TypePool.Default` to describe the class as a `TypeDescription`. This way, Byte Buddy parses the class file by itself and no signature types get loaded.

PS: Always store and reuse `Advice` classes. They are immutable and expensive.
