### ISSUE TITLE
Can not set static XXXX field com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean.delegate$3i30do0 to XXXX

### ISSUE THREAD

**Issue by wangbin3685** [raphw/byte-buddy#759]
I start agent by -javaagent . It runs well with springboot. It throws exception with spring mvc 
and HandlerInterceptor.
The following is exception:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean#0' defined in class path resource [spring/business-config.xml]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:881)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:808)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:544)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1243)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	... 24 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1102)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean.<clinit>(JsonProxyFactoryBean.java)
	... 42 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:122)
	... 47 more
Caused by: java.lang.IllegalArgumentException: 

 Can not set static XXXX field com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean.delegate$3i30do0 to XXXX

	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:109)
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:172)
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3102)
	... 52 more
```

**Comment by raphw** [comment]
Seems like a class loading issue. Might the agent live in a different class loader then the application?

**Comment by wangbin3685** [comment]
> Seems like a class loading issue. Might the agent live in a different class loader then the application?
Thank you for your reply! But how can I make them in the same classloader?

**Comment by raphw** [comment]
Really dependens on your deployment. Are you running on an application container? If so, the Spring classes probably live in their own class loader.

You should make sure that your application classes have no dependencies on the agent classes, otherwise they will exist in two class loaders.

**Comment by wangbin3685** [comment]
My application  have the same dependencies with  the agent classes. But I can not exclude the dependencies in both.

**Comment by raphw** [comment]
In this case, consider using a so-called trampoline agent. This agent is basically just taking the jar that would be the actual agent as an argument, creates a new URL class loader with the boot loader as its parent and adds this single jar file to it. It then invokes the premain method on this created loader via reflection.

This way, the two library versions don't get in each others way and you also do not need to make any changes to your actual agent. You only change the agent's class loader.

**Comment by wangbin3685** [comment]
I am grateful and excited for your answer. But I do not know about  trampoline agent. Could you please tell me some detail information.(e.g website)

**Comment by wangbin3685** [comment]
Would it work that use BootstrapClassLoader in premain  to loader ?

**Comment by raphw** [comment]
You would simply implement an agent such as the following:
```java
public class TrampolineAgent {
  public static void premain(String argument, Instrumentation inst) throws Exception {
    new URLClassLoader(new URL[] {argument}, null)
      .loadClass("my.EntryPoint")
      .getMethod("premain", String.class, Instrumentation.class)
      .invoke(null, null, inst);
  }
}
```

This way your actual agent that is referenced via the `argument` is loaded in a seperated class loader that inherits from the boot loader. If you want to transfer an argument, just add some convention, e.g. add the argument after a comma that you seperate.

**Comment by wangbin3685** [comment]
I use TrampolineAgent to run the target agent. But in the target agent, some resource can not be got.

```
 String classResourcePath = AgentPackagePath.class.getName().replaceAll("\\.", "/") + ".class";
       
 URL resource = ClassLoader.getSystemClassLoader().getResource(classResourcePath);
```
In the code, the "resource" can not be instantiated by "ClassLoader.getSystemClassLoader().getResource(classResourcePath)"

**Comment by raphw** [comment]
If you use a trampoline agent, the actual agent is no longer loaded by the system class loader, I guess therefore your agent cannot be loaded.
