### ISSUE TITLE
java.lang.IllegalStateException: Cannot assign

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#760]
I got this error when apply my visitor at my code

```
java.lang.IllegalStateException: Cannot assign org.eclipse.jetty.client.AbstractHttpConnection arg0 to class org.eclipse.jetty.client.HttpExchange
	at net.bytebuddy.asm.Advice$OffsetMapping$ForArgument.resolve(Advice.java:1411)
	at net.bytebuddy.asm.Advice$OffsetMapping$ForArgument$Unresolved.resolve(Advice.java:1514)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.apply(Advice.java:6527)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:6270)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1062)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:631)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:355)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:6264)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:7972)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:34)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:47)
	at net.bytebuddy.jar.asm.Label.accept(Label.java:359)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1781)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1238)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:631)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:355)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2883)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1652)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:209)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:9167)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9578)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9541)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:9309)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9906)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9855)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9464)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.client.HttpClient.getDestination(HttpClient.java:250)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:160)
```

and here's the code
```
  @JvmStatic
  @Advice.OnMethodEnter
  @Throws(Exception::class)
  private fun enter(@Advice.This thiz: Any, @Advice.Argument(value = 0, readOnly = false) arg: HttpExchange) {
    // TODO
  }
```

I assume this is happened because I take arg as HttpExchange,
but when I change that code to 
```
  @JvmStatic
  @Advice.OnMethodEnter
  @Throws(Exception::class)
  private fun enter(@Advice.This thiz: Any, @Advice.Argument(value = 0, readOnly = false) arg: AbstractHttpConnection) {
    // TODO
  }
```

the error changes to 
```
java.lang.IllegalStateException: Cannot assign org.eclipse.jetty.client.HttpExchange arg0 to class org.eclipse.jetty.client.AbstractHttpConnection
	at net.bytebuddy.asm.Advice$OffsetMapping$ForArgument.resolve(Advice.java:1411)
	at net.bytebuddy.asm.Advice$OffsetMapping$ForArgument$Unresolved.resolve(Advice.java:1514)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.apply(Advice.java:6527)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:6270)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1062)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:631)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:355)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:6264)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:7972)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:34)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:47)
	at net.bytebuddy.jar.asm.Label.accept(Label.java:359)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1781)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1238)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:631)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:355)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2883)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1652)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:209)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:9167)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9578)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9541)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:9309)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9906)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9855)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9464)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

that is pretty weird I think

**Comment by davidasync** [comment]
Shame on me,
actually there's overloading function that take 2 arguments, 

so to resolve this, just simply filter the builder to this

```
builder
      .visit(
          Advice
          .to(JettyHttpClientVisitor::class.java)
          .on(
            isMethod<MethodDescription>()
              .and<MethodDescription>(isProtected())
              .and<MethodDescription>(named<NamedElement>("send"))
              .and<MethodDescription>(takesArguments<MethodDescription>(1)))
      )
```

**Comment by raphw** [comment]
Glad you figured it out!
