### ISSUE TITLE
Injecting code to existing class fails with an exception

### ISSUE THREAD

**Issue by ohad7** [raphw/byte-buddy#770]
I'm trying to do custom stack manipulation for an existing method during compile time, I've followed the example code [here](https://bytebuddy.net/#/tutorial) however I'm getting the following exception when running the intercept:

```
Caused by: java.lang.AbstractMethodError: Receiver class com.yahoo.moneyball.ExampleStackManipulation$SumMethod does not define or inherit an implementation of the resolved method abstract apply(Lorg/objectweb/asm/MethodVisitor;Lnet/bytebuddy/implementation/Implementation$Context;Lnet/bytebuddy/description/method/MethodDescription;)Lnet/bytebuddy/implementation/bytecode/ByteCodeAppender$Size; of interface net.bytebuddy.implementation.bytecode.ByteCodeAppender.
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:713)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:698)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:4702)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3397)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
        at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:245)
        at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:120)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
        at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:3637)
        at net.bytebuddy.build.gradle.TransformationAction.apply(TransformationAction.java:151)
``` 

I think the issue is that the jar that is packaged in bytebuddy contains an altered version of the class names, meaning org/objectweb/asm/MethodVisitor turns into net.bytebuddy.jar.asm.MethodVisitor

**Comment by ohad7** [comment]
OK, my bad - I was using the wrong dependecy (should have been using net.bytebuddy:byte-buddy-dep:1.10.2)

A related question on manipulating bytecode using StackManipulation, is it possible to inject the prior method bytecode instead of replacing it? I want to add code at the end of the method and Advice.Exit is not suitable for that use case

**Comment by raphw** [comment]
Exit advice seems to be what you should use for this. How comes that you think that you cannot use it?

**Comment by ohad7** [comment]
I would like to reference a local variable inside the method. I thought I can use @Advice.Local but realised it's only for local variables between the entry and exit methods. I figured that a possible solution would be if I would use a method visitor to visit the method original code, then add my instructions after it ends, but I think stack manipulation replaces the method and there's no hook to the original bytecode.

**Comment by ohad7** [comment]
Any chance this is possible to do?

**Comment by ohad7** [comment]
OK, I figured out I need to be using the AsmVisitorWrapper to do that. If anyone is wondering how it's done, You can use the here code for reference:
https://stackoverflow.com/questions/41623023/bytebuddy-asmvisitorwrapper

The secret is to use builder.visit(asmVisitor) and not builder.intercept()
 
Thanks Rafael for this awesome library, It's definitely a game changer.

**Comment by raphw** [comment]
Glad you figured it out, thanks for getting back, too!
