### ISSUE TITLE
How can i proxy all method on existing object  use InvocationHandler?

### ISSUE THREAD

**Issue by XhstormR** [raphw/byte-buddy#796]
I use byte-buddy with xposexd hook framework on Android, and i want to dynamically proxy the InputStream returned by the Socket's getInputStream method.

This is the code i wrote:
```java
import de.robv.android.xposed.XC_MethodHook
import de.robv.android.xposed.XposedBridge
import net.bytebuddy.ByteBuddy
import net.bytebuddy.android.AndroidClassLoadingStrategy
import net.bytebuddy.implementation.InvocationHandlerAdapter
import net.bytebuddy.matcher.ElementMatchers
import java.io.InputStream
import java.net.Socket

object SocketInputStreamHook : XC_MethodHook() {

    override fun afterHookedMethod(param: MethodHookParam) {
        val socket = param.thisObject as Socket
        val inputStream = param.result as InputStream

        val invocationHandler = SocketInputStreamInvocationHandler(socket, inputStream)

        val inputStreamProxy = ByteBuddy()
                .subclass(clazz<InputStream>())
                .method(ElementMatchers.any())
                .intercept(InvocationHandlerAdapter.of(invocationHandler))
                .make()

        val map = AndroidClassLoadingStrategy.Injecting(createTempDir())
                .load(XposedBridge.BOOTCLASSLOADER, inputStreamProxy.allTypes)
        val clazz = map[inputStreamProxy.typeDescription]!!
        val msg = clazz.newInstance()

        println(msg.toString())
    }
}

import java.io.InputStream
import java.lang.reflect.InvocationHandler
import java.lang.reflect.Method
import java.net.Socket

class SocketInputStreamInvocationHandler(
        val socket: Socket,
        val target: InputStream
) : InvocationHandler {

    override fun invoke(proxy: Any, method: Method, args: Array<out Any>?): Any? {
        println("okok123")
        return if (args == null) method.invoke(target)
        else method.invoke(target, args)
    }
}
```

But it fails:
```
2019-12-23 23:05:55.354 23131-23165/com.example.leo.myapplication E/EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.lang.reflect.InvocationHandler.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[])' on a null object reference
        at net.bytebuddy.renamed.java.io.InputStream$ByteBuddy$SdxOnbxe.toString(Unknown Source:9)
        at com.example.leo.myapplication.SocketInputStreamHook.afterHookedMethod(SocketInputStreamHook.kt:27)
        at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
        at EdHooker_.hook(Unknown Source:130)
        at com.android.okhttp.okio.Okio.source(Okio.java:205)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.example.leo.myapplication.MainActivity.post(MainActivity.kt:67)
        at com.example.leo.myapplication.MainActivity.post$default(MainActivity.kt:57)
        at com.example.leo.myapplication.MainActivity$c$1.invoke(MainActivity.kt:46)
        at com.example.leo.myapplication.MainActivity$c$1.invoke(MainActivity.kt:12)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2019-12-23 23:05:55.355 23131-23164/com.example.leo.myapplication E/EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.lang.reflect.InvocationHandler.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[])' on a null object reference
        at net.bytebuddy.renamed.java.io.InputStream$ByteBuddy$rRvuNBmx.toString(Unknown Source:9)
        at com.example.leo.myapplication.SocketInputStreamHook.afterHookedMethod(SocketInputStreamHook.kt:27)
        at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
        at EdHooker_.hook(Unknown Source:130)
        at com.android.okhttp.okio.Okio.source(Okio.java:205)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.example.leo.myapplication.MainActivity.getInputStream(MainActivity.kt:83)
        at com.example.leo.myapplication.MainActivity.get(MainActivity.kt:53)
        at com.example.leo.myapplication.MainActivity.get$default(MainActivity.kt:52)
        at com.example.leo.myapplication.MainActivity$b$1.invoke(MainActivity.kt:38)
        at com.example.leo.myapplication.MainActivity$b$1.invoke(MainActivity.kt:12)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Can byte-buddy proxy the use of existing objects like Java Dynamic Proxy? What's the best way to do this?

**Comment by XhstormR** [comment]
I tried using Pipe way to proxy method, here is my code:
```java
import de.robv.android.xposed.XC_MethodHook
import net.bytebuddy.ByteBuddy
import net.bytebuddy.android.AndroidClassLoadingStrategy
import net.bytebuddy.implementation.MethodDelegation
import net.bytebuddy.implementation.bind.annotation.Pipe
import net.bytebuddy.matcher.ElementMatchers
import java.io.InputStream
import java.net.Socket
import java.util.function.Function

object SocketInputStreamHook : XC_MethodHook() {

    override fun afterHookedMethod(param: MethodHookParam) {
        val socket = param.thisObject as Socket
        val inputStream = param.result as InputStream

        val inputStreamProxy = ByteBuddy()
                .subclass(clazz<InputStream>())
                .method(ElementMatchers.any())
                .intercept(MethodDelegation.withDefaultConfiguration()
                        .withBinders(Pipe.Binder.install(clazz<Function<InputStream, Any?>>()))
                        .to(ForwardingLoggerInterceptor(inputStream))
                )
                .make()

        val map = AndroidClassLoadingStrategy.Injecting(createTempDir())
                .load(clazz<ForwardingLoggerInterceptor>().classLoader, inputStreamProxy.allTypes)
        val clazz = map[inputStreamProxy.typeDescription]!!

        val instance = clazz.newInstance()
        println(instance.toString())

        param.result = instance
    }
}

import net.bytebuddy.implementation.bind.annotation.Pipe
import net.bytebuddy.implementation.bind.annotation.RuntimeType
import java.io.InputStream
import java.util.function.Function

class ForwardingLoggerInterceptor(private val inputStream: InputStream) {

    @RuntimeType
    fun log(@Pipe pipe: Function<InputStream, Any?>): Any? {
        println("haha123456")
        return pipe.apply(inputStream)
    }
}
```

But it throw another exception:
```
2019-12-24 12:52:57.369 30870-30905/com.example.leo.myapplication E/EdXposed-Bridge: java.lang.IllegalStateException: Cannot invoke protected java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException from outside of class via @Pipe proxy
        at net.bytebuddy.implementation.bind.annotation.Pipe$Binder$Redirection$MethodCall.appender(Pipe.java:445)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:233)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:205)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:740)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:212)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
        at net.bytebuddy.implementation.bind.annotation.Pipe$Binder$Redirection.make(Pipe.java:295)
        at net.bytebuddy.implementation.Implementation$Context$Default.register(Implementation.java:889)
        at net.bytebuddy.implementation.bind.annotation.Pipe$Binder$Redirection.apply(Pipe.java:309)
        at net.bytebuddy.implementation.bind.MethodDelegationBinder$ParameterBinding$Anonymous.apply(MethodDelegationBinder.java:257)
        at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:225)
        at net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build.apply(MethodDelegationBinder.java:561)
        at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:225)
        at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1283)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:713)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:698)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:605)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5133)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1933)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:225)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
        at com.example.leo.myapplication.SocketInputStreamHook.afterHookedMethod(SocketInputStreamHook.kt:26)
        at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
        at EdHooker_.hook(Unknown Source:130)
        at com.android.okhttp.okio.Okio.source(Okio.java:205)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
```

**Comment by raphw** [comment]
I assume that you meant to intercept methods by `isPublic()`. Protected methods of another instance cannot be legally invoked from another instance, this is why the exception is thrown for the protected `clone` method.

As for your first interceptor, you have not annotated the parameters with anything meaningful, therefore Byte Buddy could not map your interception.

**Comment by XhstormR** [comment]
Thank you, the library is amazing, the code is working now.

I still have a question, how to specify a method to proxy only the public method named read, and then another method to proxy the remaining public method, ElementMatchers class doesn't seem to support composition conditions, Thank you again.

```java
class SocketInputStreamHook : XC_MethodHook() {
    override fun afterHookedMethod(param: MethodHookParam) {
        val socket = param.thisObject as Socket
        val inputStream = param.result as InputStream

        val inputStreamProxy = ByteBuddy()
                .subclass(clazz<InputStream>())
                .method(ElementMatchers.isPublic())
                .intercept(MethodDelegation.withDefaultConfiguration()
                        .withBinders(Pipe.Binder.install(clazz<Function<*, *>>()))
//                        .filter(ElementMatchers.named("readPublicCall"))
                        .to(ForwardingLoggerInterceptor(inputStream))
                )
                .make()
                .load(clazz<Hook>().classLoader, AndroidClassLoadingStrategy.Injecting(createTempDir()))
                .loaded
                .newInstance()

        param.result = inputStreamProxy
    }
}

class ForwardingLoggerInterceptor(private val inputStream: InputStream) {

    @RuntimeType
    fun readPublicCall(@Pipe pipe: Function<Any, *>): Any? {
        println("read public method called")
        return pipe.apply(inputStream)
    }

    @RuntimeType
    fun otherPublicCall(@Pipe pipe: Function<Any, *>): Any? {
        println("other public method called")
        return pipe.apply(inputStream)
    }
}
```

**Comment by raphw** [comment]
You can define several interceptions targeting the same interceptor. The last defined matcher would always be chosen.

Define the catch all interceptor first, then later intercept the specific method call. 

Alternatively, define your own AmbigouityResolver to choose the interception method appropriately.

**Comment by XhstormR** [comment]
Sorry, can you give me a minimal example, I'm not quite sure how to do this?

**Comment by raphw** [comment]
For example:

```java
builder
  .method(ElementMatchers.isPublic())
  .intercept(MethodDelegation.to(PublicInterceptor.class))
  .method(ElementMatchers.named("foo"))
  .intercept(MethodDelegation.to(FooInterceptor.class))
```

This would cause all methods named `foo` to be intercepted by `FooInterceptor`, no matter if they are public or not. Only if that second method does not match a method, the first interceptor is considered. This way, you can add several interceptors with different priorities.

**Comment by XhstormR** [comment]
Thank you very much for your help!
