### ISSUE TITLE
Unable to install agent with IntelliJ bundled SDK on MacOS

### ISSUE THREAD

**Issue by bitbrain** [raphw/byte-buddy#802]
When using Bytebuddy within IntelliJ and bundled Java 11 on MacOS it caused the following exception:
```
Caused by: java.io.IOException: Cannot run program ""/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin/java"": error=2, No such file or directory
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
    at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:669)
    at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:601)
    ... 102 more
```
The culprit seems to be [ByteBuddyAgent.java#L664](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L664) 

## Additional Info:
```
IntelliJ Version 2019.3.1 (IU-193.5662.53)
bytebuddy 1.9.16
 ```

**Comment by raphw** [comment]
Interesting. Where is the *java* executable located in your case? It should be somewhere within /Applications/IntelliJ IDEA.app/Contents/jbr/.

**Comment by bitbrain** [comment]
```
➜  bin pwd
/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin
➜  bin ll
total 1376
-rwxr-xr-x@ 1 ************  admin    54K 18 Dec 05:35 jaotc
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 java
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 javac
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 jdb
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 jjs
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 jrunscript
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 keytool
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 pack200
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 rmid
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 rmiregistry
-rwxr-xr-x@ 1 ************  admin    49K 18 Dec 05:35 serialver
-rwxr-xr-x@ 1 ************  admin   111K 18 Dec 05:35 unpack200
```
It seems to be there - maybe the issue is related to the whitespace in the path?

**Comment by dengarcia** [comment]
Looking at the code at the line specified in the ticket by @bitbrain , it seems that System.getProperty(JAVA_HOME) should be "quoted"

`quote(System.getProperty(JAVA_HOME)`

**Comment by raphw** [comment]
Weirdly enough, I had the opposite ticket once before: https://github.com/raphw/byte-buddy/issues/732

**Comment by bitbrain** [comment]
@raphw this is **very** bizarre indeed. Logically, the `quote()` solution should work. Let me have another look into this.

**Comment by raphw** [comment]
Thanks, maybe it's Java version dependant, too. Does it work if you quote it? Try an older release where the quoting is still applied.

**Comment by kcy1019** [comment]
Weird. Currently I am experiencing the same issue as #732.

Environment: macOS 10.14.6, Idea 2019.2.3 with bundled Java 11. (`$JAVA_HOME = /Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home`)

Minimal reproducible code:

```java
import java.io.*;

public class Main {
	private static String quote(String value) {
		return value.contains(" ")
				? '"' + value + '"'
				: value;
	}
	public static void main(String[] args) throws IOException, InterruptedException {
		String s = System.getProperty("java.home");
		System.out.println(new ProcessBuilder(quote(s+"/bin/java")).start().waitFor());
	}
}
```

```bash
$ javac Main.java && java Main
Exception in thread "main" java.io.IOException: Cannot run program ""/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin/java"": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at Main.main(Main.java:10)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 2 more
```

Without the quote, it runs fine.

**Comment by kcy1019** [comment]
For whom with the same trouble, here's a clean workaround:

1. Press `⌘ + ;` to open Project Structure.
2. Select `Download JDK` from `Platform Settings > SDKs` tab.
3. Download new SDK to some path **without** whitespaces.
4. Congratulations! You've solved the problem!

**Comment by raphw** [comment]
This problem still confuses me, the path is escaped, so this should not be an issue normally.

**Comment by bitbrain** [comment]
@raphw what confuses me is that there was #732 which was the exact opposite of what the fix for this issue would be. I believe the "correct" solution is having both, but dependent on JDK/OS version maybe? Super weird.

**Comment by raphw** [comment]
Yes, I start to think that this must be the case but I don't get what rule this follows. Maybe some MacOS versions require it while others forbid it? I tried to find out but I have not used MacOS in my life and don't own a mac where my CDI servers also just build as expected...

**Comment by dzastinas** [comment]
Same error with 

```Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 11
JVM vendor name    : JetBrains s.r.o
JVM vendor version : 11.0.8+10-b944.6842174
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.8+10-b944.6842174
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.16

	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:171)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
	... 59 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@101fc88e
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:358)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:326)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:312)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:101)
	... 65 more
Caused by: java.io.IOException: Cannot run program ""/Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:442)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:377)
	... 69 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 72 more
```

Although error reports 'OS version         : 10.16' real iOS version is 11.1 (20C69)

**Comment by dzastinas** [comment]
I renamed Android Studio Preview.app to AndroidStudioPreview.app and error is gone.

Will try the tests.

**Comment by raphw** [comment]
I went back and forth with how to escape this on a Mac; what worked for some users broke it for others so I do not really have a good idea without owning a Mac myself...

**Comment by dzastinas** [comment]
Could be java runtime or macOS issue. 

`System.out.println(new ProcessBuilder(quote(s+"/bin/java")).start().waitFor());` was working only when removed surround double quotes (")  function to:

`System.out.println(new ProcessBuilder(s+"/bin/java").start().waitFor());`

What was strange, that single quotes (') did not help. Although it was working in macOS terminal with spaces in paths.

**Comment by mikereiche** [comment]
Why are the quotes being added?  The first arg is the path of the executable.  From the first character to the last character. This is not a string parsed by a shell.  Unless one has  in the default directory, a sub-directory name beginning with a double-quote, and the java executable is named java"  - then this isn't going to work.

**Comment by raphw** [comment]
To account for whitespaces in the path. There were reports of breakage without them and adding them fixed things. I am not sure what the rules for (all) versions of MacOS are. Is there a reference you are aware of?

**Comment by mikereiche** [comment]
Ah. It's a Mac OS thing.  I didn't get that.  It's probably best to work-around it using a path with no spaces rather than risk breaking everything else.

**Comment by raphw** [comment]
Without a white space, it is no problem either way, but people tend to run into this issue.

**Comment by sickworm** [comment]
Same issue. Any plan to fix this when path includes white space?

**Comment by raphw** [comment]
As stated, this issue seems to flip flop. I don't own a Mac, so I struggle to reproduce this.

**Comment by bitbrain** [comment]
I am wondering - could we fix this by changing the `quote` function to only wrap quotes if the string it wraps does not contain quotes already? I guess this would add some implicit behaviour and may lead to side effects elsewhere... or we introduce a new method called `quoteIfNotQuoted` - you get the idea.

Alternatively, maybe replacing any whitespace characters with a path encoded equivalent might do the trick as well, have not tried it yet.

**Comment by raphw** [comment]
This might be a solution, could you test if this works Nd send a PR? I don't have a Mac to test.

**Comment by azabost** [comment]
Hey. I would like to let you know I'm probably facing the same problem with Android Studio embedded JDK after migrating from Java 8 to Java 11.

```
java.lang.ExceptionInInitializerError
	at com.example.Test.<init>(Test.kt:38)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@1787bc24
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:427)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:401)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:353)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:330)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:134)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:34)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	... 40 more
Caused by: java.io.IOException: Cannot run program ""/Users/azabost/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-3/211.7628.21.2111.8139111/Android Studio.app/Contents/jre/Contents/Home/bin/java"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:485)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:420)
	... 47 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 50 more
```

For comparison: my JDK 8 is located in

```
/Users/azabost/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home
```

And JDK 11 in

```
/Users/azabost/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-3/211.7628.21.2111.8139111/Android Studio.app/Contents/jre/Contents/Home
```

Btw, as you can see, I'm using JetBrains Toolbox to install Android Studio and other JetBrains IDEs.

**Comment by raphw** [comment]
Seems like the one time you are using a JRE. You could add a recent version of JNA to the class path where Byte Buddy will attempt an emulation.

**Comment by azabost** [comment]
I guess the newer version of ByteBuddy seems to work correctly. Once I updated the versions of [mockk](https://github.com/mockk/mockk) and [Mockito](https://github.com/mockito/mockito) (which use ByteBuddy), the problem disappeared.

**Comment by dsellarsnr** [comment]
@raphw yes! it worked.
