### ISSUE TITLE
ByteBuddyAgent install method works with tools.jar but fails with powermock-module-javaagent.jar

### ISSUE THREAD

**Issue by arivazhaganj** [raphw/byte-buddy#813]
_Versions:
byte-buddy - _1.10.8_
Mockito - _3.0.0_
Powermock - _2.0.0__

**Scenario:**
Test case involving PowerMock (to mock and spy static classes and methods)
Mockito2 -> Normal mocking and it is done on a Spring context as well.

Facing issue on this line in Attacher.java:

    Object virtualMachineInstance = virtualMachineType
                .getMethod(ATTACH_METHOD_NAME, String.class)
                .invoke(STATIC_MEMBER, processId);

**Success on IDE (Eclipse):**  The above invoke method is invoked via tools.jar (based on debugging in eclipse and matching debug line with source code )

**Failure scenario in Maven Console:** Invoke method makes use of powermock-module-javaagent JAR's VirtualMachine.java (attach method) --> This returns empty AttachProviders and hence subsequently throws null pointer exception.

**P.S:** SImilar configuration works fine in Maven console on _different project_ where i have only Powermock (for mocking static class and methods).

Error Log:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ghx.tpm.api.ISubscribedProductParameterService]: Factory method 'subscribedProductParameterService' threw exception; nested exception is java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@614aeccc
Caused by: java.lang.IllegalStateException: Failed to load MockMaker implementation: mock-maker-inline
Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 

Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.161-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_161-b12
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.4.0-166-generic

Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@3c89bb12
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NullPointerException 
```

**Comment by raphw** [comment]
I think this is a limitation of Java 8 where only one class loader can load the attach API. Did you try with a Java 11 VM?

**Comment by arivazhaganj** [comment]
@raphw , unfortunately i had to work only with Java 8. Any workaround or alternate solutions possible?

**Comment by arivazhaganj** [comment]
@raphw  i faced this error when i used both PowerMockRule with mock-maker-inline configuration. But after replacing PowerMockRule with PowerMockRunner, this error no longer occurs. But unfortunately facing another error when running multiple test cases

Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.161-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_161-b12
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.4.0-166-generic

	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:168) ~[mockito-core-3.0.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_161]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_161]
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:68) ~[mockito-core-3.0.0.jar:na]
	... 62 common frames omitted
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@520f2ae1
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613) ~[byte-buddy-agent-1.10.8.jar:na]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586) ~[byte-buddy-agent-1.10.8.jar:na]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538) ~[byte-buddy-agent-1.10.8.jar:na]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515) ~[byte-buddy-agent-1.10.8.jar:na]
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:104) ~[mockito-core-3.0.0.jar:na]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_161]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_161]
	... 63 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[byte-buddy-agent-1.10.8.jar:na]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[byte-buddy-agent-1.10.8.jar:na]
	... 69 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: Native Library /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libattach.so already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907) ~[na:1.8.0_161]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845) ~[na:1.8.0_161]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_161]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_161]
	at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:342) ~[na:na]
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63) ~[na:na]
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208) ~[na:na]
	... 75 common frames omitted

**Comment by arivazhaganj** [comment]
@raphw , I need your general suggestion as well.. I had to work with Java 8, and existing test cases make use of Spring Context, Mockito, Powermock (To mock/spy static and final methods). 
Current Versions :1.10.19 (Mockito).  1.7.3 (PowerMock). 
All compilation issues and most of the test cases are resolved after upgrade.
Target Versions: 3.0.0 (Mockito), 2.0.0 (PowerMock).

But as created in issue, facing issues with mock-maker-inline in combination with Powermock  and Mockito. Is there genuinely a perfect way around to go ahead with this upgrade? Or better to hold back for Mockito to provide support for mock and spy static and final methods and get rid of Powermockito.

Share your thoughts please. Thanks in advance.

**Comment by raphw** [comment]
PowerMock uses class loader isolation but in Java 8, the tools.jar can only loaded once in a single VM. This contradicts the isolation of class loaders as it attempts a new attachment every time. I am afraid that this could only be solved within PowerMock (or by running a newer VM).

**Comment by arivazhaganj** [comment]
Thanks for your input @raphw.. let me check if PowerMock have a solution for this.
