### ISSUE TITLE
Can't make interceptor with auxiliary class for redefined class which is not final after redefinition

### ISSUE THREAD

**Issue by Spikhalskiy** [raphw/byte-buddy#82]
Hi,

I have an issue with redefining final class.

Let's start with code:
```
public final class FinalObject {
    public final void method(String param) {}
}

public class InterceptorsInitializer {

    public static void main(String[] args) {
        check();
    }

    public static void check() {
        TypePool typePool = TypePool.Default.ofClassPath();
        TypeDescription clazz = new ByteBuddy()
                .rebase(typePool.describe("FinalObject").resolve(), ClassFileLocator.ForClassLoader.ofClassPath())
                .modifiers(TypeManifestation.PLAIN) //our class can be final and we have no access to it - so remove final
                .make()
                .getTypeDescription();
        ByteBuddyCommons.isExtendable(clazz);
    }
```

This code works fine and as expected. New type description is extendable, because we removed final by TypeManifestation.PLAIN

Let's add
```
public class Interceptors {
    public static void method(@Super FinalObject original, @Argument(0) String param) {}
}
```
and rewrite InterceptorInitializer:
```
    public static void main(String[] args) {
        registerModificationInterception();
    }

    public static void registerModificationInterception() {
        TypePool typePool = TypePool.Default.ofClassPath();
        Class clazz = new ByteBuddy()
                .rebase(typePool.describe("FinalObject").resolve(), ClassFileLocator.ForClassLoader.ofClassPath())
                .modifiers(TypeManifestation.PLAIN)
                .method(named("method")).intercept(MethodDelegation.to(typePool.describe("Interceptors").resolve()))
                .make()
                .load(InterceptorsInitializer.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
    }
```
After try to run main():
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot extend a final type: class FinalObject
	at net.bytebuddy.utility.ByteBuddyCommons.isExtendable(ByteBuddyCommons.java:181)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:270)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:258)
	at net.bytebuddy.implementation.auxiliary.TypeProxy.make(TypeProxy.java:100)
	at net.bytebuddy.implementation.Implementation$Context$Default.register(Implementation.java:772)
	at net.bytebuddy.implementation.auxiliary.TypeProxy$ForSuperMethodByConstructor.apply(TypeProxy.java:472)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$ParameterBinding$Anonymous.apply(MethodDelegationBinder.java:207)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build.apply(MethodDelegationBinder.java:556)
	at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:214)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1215)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:510)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:2986)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.doCreate(TypeWriter.java:2545)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2529)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1481)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:258)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$AbstractDelegatingBuilder.make(DynamicType.java:2177)
	at InterceptorsInitializer.registerModificationInterception(InterceptorsInitializer.java:34)
	at InterceptorsInitializer.main(InterceptorsInitializer.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
So, looks like we get an exception about "class if final" when trying to create auxiliary class for ```@Super FinalObject original```. If change Interceptors to
```
public class Interceptors {
    public static void method(@Argument(0) String param) {}
}
```
we don't get any exception.

So, we get an exception about "type if final" in rebasing where we actually removing this final manifestation from TypeDescription (and this removing works, we checked it in previous code).

**Comment by raphw** [comment]
Right, the interception does not currently consider the redefined state. This can be fixed easily.

**Comment by raphw** [comment]
This is now fixed in master and will be part of the next release.

**Comment by Spikhalskiy** [comment]
Thanks, @raphw!

**Comment by Spikhalskiy** [comment]
@raphw In case if I don't apply ".modifiers(TypeManifestation.PLAIN)" I got an error : "java.lang.IllegalArgumentException: Cannot extend a final type: class SimpleObject" It's absolutely unclear from this message that I can't use auxiliary type @Super if class remains final and I can solve this both by removing usage of auxiliary type or adding Plain manifestation. It looks like... I just couldn't make all of this (rebasing for example) for final class. Everybody will need some time, desire and patience to find that it's related to @Super parameter. I think diagnostic message here should be improved.

**Comment by raphw** [comment]
You are right, I improved the error message.
