### ISSUE TITLE
java.lang.SecurityException: Prohibited package name: java.lang

### ISSUE THREAD

**Issue by dinix2008** [raphw/byte-buddy#826]
An error occurs when using 1.10.8 version under Netbeans RCP 11.3 on Java 8. While the previous version 1.10.6 or under Java 11 works well. This is due to the fact that there is a class "java.lang.Module" in the dependency org.netbeans.modules:org-netbeans-bootstrap:RELEASE113

> java.lang.SecurityException: Prohibited package name: java.lang
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:656)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:755)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:344)
	at net.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:331)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.utility.JavaModule.<clinit>(JavaModule.java:44)
Caused: java.lang.ExceptionInInitializerError
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction.run(ByteArrayClassLoader.java:667)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction.run(ByteArrayClassLoader.java:655)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.<clinit>(ByteArrayClassLoader.java:81)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:357)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5707)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5696)

**Comment by raphw** [comment]
Alright, any idea why netbeans bundles a class? This can never work correctly. I think it's fair to add the additional given that Netbeans is used by a lot of people but I think this should be fixed on their end, too.

**Comment by dinix2008** [comment]
> Alright, any idea why netbeans bundles a class?

For cross-compilation (JDK 8 or 11), here is their commit - https://github.com/apache/netbeans/commit/4325e6ca3600c7234072df38ce50ff8c69172343

> but I think this should be fixed on their end

I absolutely agree, and, I think, as soon as they refuse to compile with JDK 8, they will delete this code

**Comment by raphw** [comment]
Is this still an issue? Please get in touch if so. I am closing this ticket in the mean time.
