### ISSUE TITLE
byte-buddy-android DexFile is Closeable, but never closed

### ISSUE THREAD

**Issue by TWiStErRob** [raphw/byte-buddy#832]
Repro: put this before creating mocks in an instrumentation test.
```
StrictMode.setVmPolicy(
	new VmPolicy.Builder()
		.penaltyLog()
		.penaltyDeath()
		.detectLeakedClosableObjects()
		.build()
);
```

<details>
<summary>
<i>StrictMode: A resource was acquired at attached stack trace but never released.</i>
<pre>
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.loadDex(DexFile.java:151)
        at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting$Dispatcher$ForLegacyVm.loadDex(AndroidClassLoadingStrategy.java:483)
</pre>
(for more stack click here)
</summary>

```
03-31 20:32:19.826 8911-8919/net.twisterrob.inventory.debug E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.loadDex(DexFile.java:151)
        at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting$Dispatcher$ForLegacyVm.loadDex(AndroidClassLoadingStrategy.java:483)
        at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting.doLoad(AndroidClassLoadingStrategy.java:415)
        at net.bytebuddy.android.AndroidClassLoadingStrategy.load(AndroidClassLoadingStrategy.java:142)
        at net.bytebuddy.android.AndroidClassLoadingStrategy$Injecting.load(AndroidClassLoadingStrategy.java:408)
        at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5686)
        at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:174)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
        at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
        at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
        at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.createMock(AndroidByteBuddyMockMaker.java:39)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
        at org.mockito.Mockito.mock(Mockito.java:1908)
        at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:44)
        at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:19)
        at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
        at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:39)
        at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:63)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:58)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:42)
        at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:68)
        at MyrTest.setUp(MyTest.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
    	at ...
```

</details>

Fix should be quite simple: call `dexFile.close();` in a `try-finally` in `net.bytebuddy.android.AndroidClassLoadingStrategy.Injecting#doLoad`.

**Comment by TWiStErRob** [comment]
More details: it actually doesn't implement `Closeable`, but reports itself as such:
```
public final class DexFile {
    private final CloseGuard guard = CloseGuard.get();
    public DexFile(String fileName) throws IOException {
        guard.open("close");
```
This line has been there since [Ice Cream Sandwich](https://android.googlesource.com/platform/libcore/+/ics-mr1-release/dalvik/src/main/java/dalvik/system/DexFile.java#77), it wasn't there in [Gingerbread](https://android.googlesource.com/platform/libcore/+/gingerbread-release/dalvik/src/main/java/dalvik/system/DexFile.java#75).

**Comment by raphw** [comment]
You are right, I missed it but just fixed it on master. Will be part of the next release.

**Comment by TWiStErRob** [comment]
Wow, quick fix, nice! A bit more complicated than I expected :)

@raphw why did you [reflect](https://github.com/raphw/byte-buddy/commit/e894a039ea62a01e34e70e711895bf6bd6762a61#diff-40ca767ade67a6450c241a0a402011d9R235) on [DexFile.close](https://developer.android.com/reference/dalvik/system/DexFile#close())? it was added in API 1.

**Comment by raphw** [comment]
was it? it's not in the api i have bundled for some reason. was it gone for a while?

**Comment by TWiStErRob** [comment]
Hmm, Maven... Gradle with `compileSdkVersion 28` has a public `DexFile.close` method.
Even yours has it in com.google.android:android:4.1.1.4
I think you closed the wrong DexFile.
[This](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-android/src/main/java/net/bytebuddy/android/AndroidClassLoadingStrategy.java#L704) object needs to be closed.
Compare:
com.android.dx.dex.file.DexFile (no close)
dalvik.system.DexFile (has close)

**Comment by TWiStErRob** [comment]
I think you can revert most of the commit.

**Comment by raphw** [comment]
Possibly, I am just confused that the method does not exist in my binaries that I use for the local build since those are from Google... I will have another look.

**Comment by TWiStErRob** [comment]
It is correct that they exist, and it is correct that they don't. There are two classes we are talking about. You can change the code to close whatever you can without reflection. The other one is not "closeable". Thanks for taking another look.

**Comment by raphw** [comment]
You are right, fixed it now. Thanks!

**Comment by TWiStErRob** [comment]
Nice! Thank you!
https://github.com/raphw/byte-buddy/commit/625429ea9093589604dcbec91eb0a57575768263
