### ISSUE TITLE
more sensible thing to do than throw new IllegalStateException("Cannot resolve type description for " + name);

### ISSUE THREAD

**Issue by sevensecondsaway** [raphw/byte-buddy#85]
I'm trying to intercept methods in classes that implement a certain interface :  type(ElementMatchers.isSubTypeOf(MyInterface.class))

Here's an example of the exception I get when running this under spring-boot. Could byte buddy just ignore that HandlerMethodArgumentResolver isn't there and move on?

Error - org.springframework.data.web.PageableHandlerMethodArgumentResolver, Cannot resolve type description for org.springframework.web.method.support.HandlerMethodArgumentResolver
java.lang.IllegalStateException: Cannot resolve type description for org.springframework.web.method.support.HandlerMethodArgumentResolver
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:152)
	at net.bytebuddy.pool.TypePool$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:5933)
	at net.bytebuddy.pool.TypePool$LazyTypeDescription$LazyTypeList.get(TypePool.java:5823)
	at net.bytebuddy.pool.TypePool$LazyTypeDescription$LazyTypeList$Generified.get(TypePool.java:5864)
	at net.bytebuddy.pool.TypePool$LazyTypeDescription$LazyTypeList$Generified.get(TypePool.java:5860)
	at net.bytebuddy.description.type.generic.GenericTypeList$ForDetachedTypes.get(GenericTypeList.java:224)
	at net.bytebuddy.description.type.generic.GenericTypeList$ForDetachedTypes.get(GenericTypeList.java:154)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at net.bytebuddy.description.type.generic.GenericTypeList$AbstractBase.asErasures(GenericTypeList.java:75)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:350)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:377)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:28)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:10)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatcherPair.matches(AgentBuilder.java:312)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:2460)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:2867)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:2990)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:158)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:130)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.util.ClassUtils.isPresent(ClassUtils.java:327)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition$MatchType$2.matches(OnClassCondition.java:122)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.getMatchingClasses(OnClassCondition.java:95)
	at org.springframework.boot.autoconfigure.condition.OnClassCondition.getMatchOutcome(OnClassCondition.java:52)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:203)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:509)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:454)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
	at hello.Application.main(Application.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)

**Comment by raphw** [comment]
You can always implement a `BinaryResolver` that supresses types that cannot be resolved. However, in theory, Byte Buddy cannot tell that `PageableHandlerMethodArgumentResolver` does not implement `MyInterface`, therefore the exception is a sensible action.

I do however wonder: Why is the Spring jar file not visible to the agent? It should be resolvable via the instrumented class's `ClassLoader`. Otherwise, the class can never be loaded successfully anyways.

**Comment by sevensecondsaway** [comment]
A custom matcher does the job! Thanks! 

And congratulations on the Duke's Choice award, well deserved! Byte Buddy is a true gem.

**Comment by raphw** [comment]
Glad that helped and that you like Byte Buddy!
