### ISSUE TITLE
How to exclude already loaded classes from transformation?

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#859]
This transformer works nicely for removing the `final` modifier from classes and methods during classloading. I can hot-attach it via `ByteBuddyAgent` or - in order to catch more bootstrap classes - start it right from a Java agent in order to make it kick in a bit earlier.

Please note my excludes for some packages and classes which will lead to problems because they are already loaded and/or being used during transformation.

```java
package de.scrum_master.bytebuddy;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.asm.ModifierAdjustment;
import net.bytebuddy.description.modifier.MethodManifestation;

import java.lang.instrument.Instrumentation;
import java.lang.reflect.Modifier;

import static net.bytebuddy.matcher.ElementMatchers.*;

public class RemoveFinalTransformer {
  public static void install(Instrumentation instrumentation) {
    new AgentBuilder.Default()
      .disableClassFormatChanges()
      .ignore(none())
      .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
      .with(AgentBuilder.RedefinitionStrategy.Listener.StreamWriting.toSystemError())
      .with(AgentBuilder.Listener.StreamWriting.toSystemError().withTransformationsOnly())
      .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
      .with(AgentBuilder.InstallationListener.StreamWriting.toSystemError())
      .type(any()
          .and(not(nameStartsWith("net.bytebuddy.")))
          .and(not(nameStartsWith("de.scrum_master.bytebuddy.")))
          .and(not(nameStartsWith("java.lang.invoke.BoundMethodHandle$Species_L")))
          .and(not(nameStartsWith("com.sun.proxy.$Proxy")))
          .and(not(named("java.lang.UnsupportedOperationException")))
          .and(not(nameStartsWith("org.junit.")))
          .and(not(nameStartsWith("com.intellij.")))
      )
      .transform((builder, typeDescription, classLoader, module) ->
          builder
            // Definalise type
            .modifiers(typeDescription.getModifiers() & ~Modifier.FINAL)
            // Make final methods non-final (also non-abstract, non-native, but that should not be a problem)
            .visit(new ModifierAdjustment().withMethodModifiers(isFinal(), MethodManifestation.PLAIN))
      ).installOn(instrumentation);
  }
}
```

Still when running from the Java agent (after I already added ByteBuddy and my transformer to the boot classpath via `Instrumentation.appendToBootstrapClassLoaderSearch(..)` I am getting error logs from the transformer like:

```text
[Byte Buddy] BEFORE_INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@27973e9b on sun.instrument.InstrumentationImpl@312b1dae
[Byte Buddy] REDEFINE BATCH #0 [656 of 656 type(s)]
[Byte Buddy] TRANSFORM sun.util.resources.de.CurrencyNames_de_DE [sun.misc.Launcher$ExtClassLoader@34a245ab, null, loaded=true]
[Byte Buddy] REDEFINE ERROR #0 [656 of 656 type(s)]
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class modifiers
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRedefinition.doApply(AgentBuilder.java:7126)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6993)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4855)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:9463)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9384)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:10986)
	at de.scrum_master.bytebuddy.RemoveFinalTransformer.install(RemoveFinalTransformer.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at de.scrum_master.bytebuddy.ByteBuddyAspectAgent.attachRemoveFinalTransformer(ByteBuddyAspectAgent.java:68)
	at de.scrum_master.bytebuddy.ByteBuddyAspectAgent.premain(ByteBuddyAspectAgent.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
I tried to find a general way to exclude classes which are already loaded because by definition changing modifiers is forbidden during redefinition or retransformation, so there is no point in trying anyway. The more classes I exclude, the more new ones appear in the error log. If I just deactivate logging, everything works fine in my tests, I can mock the formerly final classes etc. But actually I like the log information, but want to get rid of those messages via excluding the already loaded classes. I also tried the `failSafe()` matcher, but to no avail.

**Comment by raphw** [comment]
Simply drop the `REDEFINITION` part. Byte Buddy will then not attempt to redefine classes. If you wanted to discriminate what transformers to apply, you can register a `RawMatcher` where the state of class loading is indicated by a boolean.

**Comment by kriegaex** [comment]
> Simply drop the `REDEFINITION` part. Byte Buddy will then not attempt to redefine classes.

That works in a simple scenario. In a more complex setup where
*  I have a simple Java agent (not using `ByteBuddyAgent`, BTW) and
* I first attach the ByteBuddy JAR and my transformation library to the boot classloader
* before attaching my transformer (which is inside the library just attached to the boot classloader),
it fails. More precisely, if I add the `REDEFINITION` part, it works but logs a few errors like the one in this ticket.

If I remove it, though, I am getting:

```text
[Byte Buddy] ERROR java.lang.reflect.InvocationTargetException [null, null, loaded=false]
java.lang.ClassCircularityError: java/lang/reflect/InvocationTargetException
	at java.lang.Class.getDeclaredMethods0(Native Method)
```

and lots of these for many classes:

```text
[Byte Buddy] ERROR sun.misc.PostVMInitHook [null, null, loaded=false]
java.lang.NoClassDefFoundError: Could not initialize class net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$ForLoadedReturnType.getAnnotationReader(TypeDescription.java:6696)
```

Why the including (rather illogically) the `REDEFINITION` part makes my tests work, I don't understand. I just happened to find out via trial and error.

BTW, I also have to add `.disableClassFormatChanges()` in order to make it work, which is also illogical because a transformation changing modifiers does by definition change the class format. But without it, in my scenario I get something really bad at the end of my test. The JVM just dies:

```text
[Byte Buddy] TRANSFORM java.net.UnknownHostException [null, null, loaded=false]
Exception in thread "Monitor Ctrl-Break" java.lang.NoClassDefFoundError: sun/reflect/GeneratedMethodAccessor4
	at sun.reflect.GeneratedMethodAccessor4.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
(...)
[Byte Buddy] TRANSFORM sun.reflect.GeneratedMethodAccessor5 [sun.reflect.DelegatingClassLoader@4f9a3314, null, loaded=false]
java.lang.NoClassDefFoundError: sun/reflect/GeneratedMethodAccessor5
	at sun.reflect.GeneratedMethodAccessor5.<clinit>(Unknown Source)
(...)
[Byte Buddy] TRANSFORM java.lang.Shutdown [null, null, loaded=false]
[Byte Buddy] TRANSFORM sun.misc.VMSupport [null, null, loaded=false]
[Byte Buddy] TRANSFORM sun.reflect.GeneratedMethodAccessor7 [sun.reflect.DelegatingClassLoader@39cb740c, null, loaded=false]
[Byte Buddy] TRANSFORM sun.reflect.GeneratedMethodAccessor6 [sun.reflect.DelegatingClassLoader@77edd171, null, loaded=false]
Error: A JNI error has occurred, please check your installation and try again

Process finished with exit code 1
```

> If you wanted to discriminate what transformers to apply, you can register a `RawMatcher` where the state of class loading is indicated by a boolean.

Yesterday I already temporarily added this:

```java
      .ignore(AgentBuilder.RawMatcher.ForLoadState.LOADED)
```

then again I am getting an initial `ClassCircularityError: java/lang/reflect/InvocationTargetException` and a whole bunch of subsequent `NoClassDefFoundError: Could not initialize class net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader`.

This is why I suggested to you in the chat that we look into it together during an online session because it is much easier to see than to explain.

---

Maybe you are wondering why I am even attaching my transformation library plus ByteBuddy to the boot classloader. The reason is that the same transformation library also has an option to attach `Advice`s to already loaded JRE bootstrap classes, which works just fine and is quite flexible because my library hides the `AgentBuilder` stuff from the user, he just needs to specify class and method matchers as well as before/after actions which can be simple lambdas.

My problems with the `RemoveFinalTransformer` occur without any advices applied, there is no other transformer active. If I used my `RemoveFinalTransformer` as shown in the initial post, it works nicely except for the exceptions logged which I first asked about, both alone and in combination with my advice solution.

**Comment by kriegaex** [comment]
BTW, you added this ticket to the 1.10.10 milestone, but 1.10.10 was already released...

**Comment by kriegaex** [comment]
I found a workaround which fixes my problems and makes all exceptions go away from the log. I thought about this first:

>   More precisely, if I add the `REDEFINITION` part, it works but logs a few errors like the one in this ticket. If I remove it, though, I am getting:
> 
> ```
> [Byte Buddy] ERROR java.lang.reflect.InvocationTargetException [null, null, loaded=false]
> java.lang.ClassCircularityError: java/lang/reflect/InvocationTargetException
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> ```

So I just gave it a try and added this to my agent's `premain` method:

```java
    instr.appendToBootstrapClassLoaderSearch(findJarFile("de/scrum_master/bytebuddy/aspect/Weaver.class"));
    instr.appendToBootstrapClassLoaderSearch(findJarFile("net/bytebuddy/agent/builder/AgentBuilder.class"));

    // TODO: Why is this this necessary in order to avoid a ClassCircularityError in ByteBuddy?
    ClassLoader
      .getSystemClassLoader()
      .getParent()
      .loadClass("java.lang.reflect.InvocationTargetException");
```

So if I do it in this order
  1. add my transformer library and the ByteBuddy to the boot classpath
  2. manually load class `InvocationTargetException` in order to avoid the `ClassCircularityError` later
  3. add my `RemoveFinalTransformer` to the instrumentation instance
the transformer works flawlessly even with bootstrap classes involved. I really like to know why the circularity error occurs inside ByteBuddy in the first place. Please can you investigate, @raphw? Maybe there is a subtle bug which could be avoided. But I am not sure. It just feels strange having to do that.

Now I can also get rid of `REDEFINE` in my transformer and condense it down to:

```java
package de.scrum_master.bytebuddy;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.asm.ModifierAdjustment;
import net.bytebuddy.description.modifier.MethodManifestation;

import java.lang.instrument.Instrumentation;
import java.lang.reflect.Modifier;

import static net.bytebuddy.matcher.ElementMatchers.*;

public class RemoveFinalTransformer {
  public static void install(Instrumentation instrumentation) {
    new AgentBuilder.Default()
      // TODO: Why is this needed? The class format (modifiers) *is* changed. Must be some side effect.
      .disableClassFormatChanges()

      // Include bootstrap classes that otherwise would be excluded by default
      //
      // Caveat: do not use something like
      //   .ignore(nameStartsWith("de.scrum_master.bytebuddy."))
      // because it does not work as expected and leads to
      //   IllegalStateException: Cannot resolve type description
      .ignore(none())

      // It works without this -> reactivate on demand
      //.ignore(AgentBuilder.RawMatcher.ForLoadState.LOADED)

      // It works without RedefinitionStrategy.* -> reactivate on demand
      //.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
      //.with(AgentBuilder.RedefinitionStrategy.Listener.StreamWriting.toSystemError())

      .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
      .with(AgentBuilder.Listener.StreamWriting.toSystemError().withTransformationsOnly())
      .with(AgentBuilder.InstallationListener.StreamWriting.toSystemError())

      .type(any()
          // Exclude ByteBuddy and this transformer library
          .and(not(nameStartsWith("net.bytebuddy.")))
          .and(not(nameStartsWith("de.scrum_master.bytebuddy.")))
          // Exclude dynamically created JRE classes without class files
          .and(not(nameMatches("com\\.sun\\.proxy\\.\\$Proxy.+")))
          .and(not(nameMatches("java\\.lang\\.invoke\\.BoundMethodHandle\\$Species_L.+")))
          // Exclude JUnit, Hamcrest, IntelliJ IDEA
          .and(not(nameStartsWith("org.junit.")))
          .and(not(nameStartsWith("junit.")))
          .and(not(nameStartsWith("org.hamcrest.")))
          .and(not(nameStartsWith("com.intellij.")))
      )

      .transform((builder, typeDescription, classLoader, module) ->
          builder
            // Remove 'final' modifier from classes
            .modifiers(typeDescription.getModifiers() & ~Modifier.FINAL)
            // Exclude non-final methods
            .ignoreAlso(not(isFinal()))
            // Remove 'final' modifier from methods
            .visit(new ModifierAdjustment()
              .withMethodModifiers(isFinal().and(isNative()), MethodManifestation.NATIVE)
              .withMethodModifiers(isFinal().and(isBridge()), MethodManifestation.BRIDGE)
              .withMethodModifiers(isFinal().and(not(isNative().or(isBridge()))), MethodManifestation.PLAIN))
      )

      .installOn(instrumentation);
  }
}
```

The second open question is: Why do I need `disableClassFormatChanges()`? I saw that this is a meta option setting several others. One of several them must have the side effect to make the transformer working because without this option it fails as described in a previous post.

**Comment by kriegaex** [comment]
FYI, here is the full stack trace of the circularity error if it helps you to pinpoint the root cause:

```text
[Byte Buddy] ERROR java.lang.reflect.InvocationTargetException [null, null, loaded=false]
java.lang.ClassCircularityError: java/lang/reflect/InvocationTargetException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$CreationAction.run(TypeDescription.java:2526)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$CreationAction.run(TypeDescription.java:2511)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader.<clinit>(TypeDescription.java:2343)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$ForLoadedReturnType.getAnnotationReader(TypeDescription.java:6696)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$ForLoadedReturnType.resolve(TypeDescription.java:6684)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6270)
	at net.bytebuddy.description.method.MethodDescription$TypeSubstituting.getReturnType(MethodDescription.java:1608)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:845)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:922)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1107)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:634)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:615)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:629)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:567)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:471)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10648)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10595)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10186)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.rt.execution.application.AppMainV2$Agent.premain(AppMainV2.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

**Comment by kriegaex** [comment]
I have a third question, too: Is there a general way to exclude dynamically created classes? As you see above, my workaround for now is:

```java
          // Exclude dynamically created JRE classes without class files
          .and(not(nameMatches("com\\.sun\\.proxy\\.\\$Proxy.+")))
          .and(not(nameMatches("java\\.lang\\.invoke\\.BoundMethodHandle\\$Species_L.+")))
```

But matching for naming patterns feels awfully fragile.

**Comment by raphw** [comment]
You can exclude classes by `isSynthetic`, however, not all classes set this modifier. As for `disableClassFormatChanges`, it simplifies the type description representation but still allows some simpler modifications such as modifier changes.

Your problem is a more complex one as that it can be easily solved by Byte Buddy. Byte Buddy is using the JVM's classes. If these classes are loaded for the first time by Byte Buddy during an insturmentation, then this class will also be attempted to be instrumented. If no matcher kicks in at an early enough time, Byte Buddy will require the currently loaded class during instrumenting this class and a circularity error is thrown and propagated.

If instrumenting JDK classes, you should know which classes and efficiently exclude the remainder. The good news is that the central classes used by Byte Buddy rarely change but you need to wiggle your way to an efficient solution, also by using name exclusion matchers.

**Comment by kriegaex** [comment]
> You can exclude classes by `isSynthetic`, however, not all classes set this modifier.

Well, the dynamic proxies created inside the JRE classes are not `synthetic`, at least not in this case, as can be seen if I modify my sample code like this:

```java
.transform((builder, typeDescription, classLoader, module) -> {
        System.out.println("[RFT] " + Modifier.toString(typeDescription.getModifiers()) + " " + typeDescription + " / " + typeDescription.isSynthetic());
          return builder.(...);
```

Then it prints:

```text
[RFT] public final class com.sun.proxy.$Proxy5 / false
[Byte Buddy] ERROR com.sun.proxy.$Proxy5 [null, null, loaded=false]
```

Besides, the circularity error is gone since I explicitly pre-loaded class `InvocationTargetException` from the previously posted call stack in my Java agent. Now as you can see, it cannot find a ByteBuddy annotation when trying to transform the proxy type. Here is the full stack trace:

```text
[Byte Buddy] ERROR com.sun.proxy.$Proxy5 [null, null, loaded=false]
java.lang.IllegalStateException: Cannot resolve type description for net.bytebuddy.asm.Advice$OnMethodExit
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8324)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:7978)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1655)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1611)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3752)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6270)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:632)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:567)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:471)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10648)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10595)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10186)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.reflect.Proxy.defineClass0(Native Method)
	at java.lang.reflect.Proxy.access$300(Proxy.java:228)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:642)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:305)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:303)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:293)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:588)
	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:630)
	at net.bytebuddy.description.method.MethodDescription$ForLoadedMethod.getDeclaredAnnotations(MethodDescription.java:1257)
	at net.bytebuddy.asm.Advice.locate(Advice.java:462)
	at net.bytebuddy.asm.Advice.to(Advice.java:340)
	at net.bytebuddy.asm.Advice.to(Advice.java:322)
	at net.bytebuddy.asm.Advice.to(Advice.java:299)
	at de.scrum_master.bytebuddy.aspect.Weaver$AdviceType.<clinit>(Weaver.java:38)
	at de.scrum_master.bytebuddy.aspect.Weaver.<init>(Weaver.java:74)
	at de.scrum_master.bytebuddy.aspect.CommandLineAgentIT.weaveLoadedApplicationClass(CommandLineAgentIT.java:54)
	(...)
```

As you can see,
  * my application issues `Advice.to()`
  * which later leads to `MethodDescription$ForLoadedMethod.getDeclaredAnnotations()`
  * which calls JRE reflection method `Method.getDeclaredAnnotations()`
  * which later for some reason creates the proxy instance in `Proxy$ProxyClassFactory.apply()` by calling a native method.
  * Then later the ByteBuddy transformer is called from `sun.instrument.TransformerManager.transform()`, kicking off the rest of the transformation process for the proxy.
  * Ultimately, BB tries to create a type description for the proxy, also trying to resolve BB annotations such as `@Advice.OnMethodExit` and others later (I can see it in my log). Why it cannot resolve those types is an open question.

I really do not understand why BB cannot resolve its own annotations, especially given the fact that my Java agent explicilty uses `Instrumentation.appendToBootstrapClassLoaderSearch()` for both ByteBuddy and my own transformation library. The advices annotated by those annotations also work flawlessly. Besides, if I put the libraries on the boot classpath via command line, the exceptions go away. what is the difference anyway? When my agent adds them to the boot classloader search path dynamically, both libraries habe not been used or referenced yet. This seems to be related to the way BB tries to resolve classes or cache them in its own type pool because the JVM definitely knows those classes.

**Comment by raphw** [comment]
The JVM creates proxies to represent annotations, this is how they are implemented in the JVM.

You might have better luck by using a `TypePool` to describe your advice code. You can for example use `new AgentBuilder.Transformer.ForAdvice`. This will resolve the advice in the context of your target class's class loader without relying on the reflection API.

**Comment by kriegaex** [comment]
I tried, but the result was exactly the same, i.e. aspect weaving works nicely but I see the same exceptions as before, no matter if I do something fancy like

```java
        .type(typeMatcher)
        .transform(new AgentBuilder.Transformer.ForAdvice()
            .with(AgentBuilder.LocationStrategy.ForClassLoader.STRONG)
            .include(
              MethodAspect.class.getClassLoader(),
              Weaver.class.getClassLoader(),
              Proxy.class.getClassLoader(),
              Advice.OnMethodExit.class.getClassLoader()
            )
            .with(Assigner.DEFAULT)
            .withExceptionHandler(new Advice.ExceptionHandler.Simple(Removal.SINGLE))
            .advice(adviceType.getMethodType().and(methodMatcher), MethodAspect.class.getName())
        );
```

similar to code copied from here:
https://github.com/raphw/byte-buddy/blob/05d400b9c30be9df5bcf5d59d7475c0f557f41e9/byte-buddy-dep/src/test/java/net/bytebuddy/agent/builder/AgentBuilderDefaultApplicationRedefinitionReiterationTest.java#L98-L103)

Or if I simplify it to:

```java
        .type(typeMatcher)
        .transform(new AgentBuilder.Transformer.ForAdvice()
            .advice(adviceType.getMethodType().and(methodMatcher), MethodAspect.class.getName())
        );
```

**Comment by kriegaex** [comment]
Okay, I found a workaround which helps me to avoid using 

    -Xbootclasspath/a:../path/to/bytebuddy-aspect-agent-1.0-SNAPSHOT.jar;/path/to/byte-buddy-1.10.10.jar

via a compound class file location strategy explicitly using the JAR files (ByteBuddy, my transformer library) my agent has previously added to the boot class path in its `premain` method. The agent hands over `File`s pointing to those JARs, the transformer creator then uses them to add them to the compound locator like this:

```java
      // In agent mode, avoid IllegalStateException when trying to resolve ByteBuddy annotations
      .with(getLocationStrategyWithJars(jarFiles))
```

```java
  private static AgentBuilder.LocationStrategy getLocationStrategyWithJars(File[] jarFiles) {
    List<AgentBuilder.LocationStrategy> locationStrategies = new ArrayList<>();

    // Add the default strategy first
    AgentBuilder.LocationStrategy defaultLocationStrategy = AgentBuilder.LocationStrategy.ForClassLoader.STRONG;
    locationStrategies.add(defaultLocationStrategy);

    // Add JAR files, usually provided by ByteBuddyAspectAgent and only needed
    // if they have been injected into boot class path
    for (File jarFile : jarFiles) {
//      System.out.println("[RFT] Adding class file locator for " + jarFile);
      try {
        ClassFileLocator locator = ClassFileLocator.ForJarFile.of(jarFile);
        locationStrategies.add((classLoader, module) -> locator);
      } catch (IOException e) {
        System.err.println("[RFT] Error creating class file locator for JAR file: " + jarFile);
        e.printStackTrace();
      }
    }
    return locationStrategies.size() < 2
      ? defaultLocationStrategy
      : new AgentBuilder.LocationStrategy.Compound(locationStrategies);
  }
```

I find this intricate and cumbersome to implement and would much prefer a fix in ByteBuddy because actually those classes are resolvable at the moment the transformer is created. There should be a way to improve BB in this respect. This kind of double book-keeping, first adding the libraries to the boot class path and then again to a class file locator, is not pretty.

**Comment by kriegaex** [comment]
After I have replaced the ByteBuddy-based transformer by an ASM-based one using a `ClassVisitor`, all my problems are gone:

* No more special excludes are necessary in order to avoid warnings.
* It is no longer necessary to pre-load `InvocationTargetException` in order to avoid circularity errors.

The ASM solution also seems to be faster than the ByteBuddy version. BTW, I am still using the ASM classes already relocated into BB because I use BB for my aspect framework in other places anyway. But the "remove final" transformer which can either be used together with the aspects or stand-alone works in all scanarios.

---

Having said that, I leave it up to you, @raphw, to either close the ticket or to answer my remaining questions here because I am still eager to learn and to understand in order to avoid similar problems in the future. Maybe my issues also point to problems within BB itself and you could use this as a chance to address them. I can always check out an older version again and re-test, just in case you adjust something based on my error reports. Thank you so far for the helpful discussion here. :-)

**Comment by raphw** [comment]
If you only want to change modifiers of a class and it's methods, I'd recommend you to use ASM myself. ASM is a much simpler library and if you do not need to process type hierarchies, I'd use it myself for such a trivial case. Byte Buddy builds itself on top of it; at best it could be equally efficient.

Byte Buddy abstracts over a lot of functionality that would require a lot of work to implement in ASM. Two that you seem to be using is type hierarchy matchers and advice. These abstractions load a bunch of types that are probably not loaded when using ASM which causes the circularities that you observe. You need very explicit exclusions for what types you want to ignore, naturally, Byte Buddy depends on more JVM standard class library classes than ASM.
