### ISSUE TITLE
Catch-all Interceptor Method Requires @AllArguments Parameter to be Present

### ISSUE THREAD

**Issue by saden1** [raphw/byte-buddy#86]
Given the following:

```java 
public class TestCase {

    public static class Greeter {

        public String hello() {
            return "hello";
        }

        public String world() {
            return "world";
        }

        public String greet() {
            return hello() + " " + world();
        }
    }

    public static class GreeterInterceptor {

        @RuntimeType
        public Object delegate(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception {
            return zuper.call();
        }

        public String hello(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();

        }

        public String world(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

    }

    public static void main(String[] args) throws Exception {
        Greeter instance = new ByteBuddy().subclass(Greeter.class)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(to(new GreeterInterceptor()).filter(not(isDeclaredBy(Object.class)))).make()
                .load(TestCase.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded()
                .newInstance();

        String result = instance.greet();
        System.out.println(result);

    }
}
```

If I remove ```"@AllArguments Object... args"``` parameter from the ```delegate``` method interception does not work. I'm not sure if this is a bug or the right behavior but I would think the ```delegate``` method would be selected regardless of whether ```@AllArguments``` argument is present.

**Comment by raphw** [comment]
It is not a bug, Byte Buddy tries to find a *best match* among the possible delegation methods and fails due to their ambiguity. Without the `@AllArguments` parameter, Byte Buddy needs to decide which one of:

```java
@RuntimeType
public Object delegate(@SuperCall Callable<?> zuper /*, @AllArguments Object... args */) throws Exception {
  return zuper.call();
}

public String hello(@SuperCall Callable<String> zuper) throws Exception {
  return zuper.call().toUpperCase();
}

 public String world(@SuperCall Callable<String> zuper) throws Exception {
  return zuper.call().toUpperCase();
}
```

to select. Both have the same injector requirement (a `Callable`) and all return types are assignable to the return type of the intercepted method. Therefore, Byte Buddy - instead of magically choosing for your - fails with an exception. However, with the parameter present, Byte Buddy decides that the `delegate` method renders the most complex interceptor and chooses this one over the two other possibilities.

I am however wondering what you are trying to achieve. As a fallback, when all interceptors are ambigous, Byte Buddy considers the name of the interceptor and chooses that interception method with an equal name to the intercepted method. This works for `hello` and `world`. If you renamed `delegate` to `greet`, it would also work in your case.

I can however only recommend you not to rely on the built-in selection mechanisms for complex, unintuitive cases. Rather make the selection explicit what results in more readable code. You can even implement your own `AmbiguityResolver` and register it with the `MethodDelegation`.

**Comment by saden1** [comment]
As always, great explanation. My goal is to only intercept ```hello``` and ```world``` but not ```greet```. I could write my own AmbiguityResolver or register the two methods I am interested with my MethodDelegation but that's not clean or as extensible. I really want to avoid having to deal with string representation of method names and instead rely on a type-safe approach where I create an interceptor that selectively declares methods I want to intercept and a catch-all method.

What do you think about ByteBuddy introducing a new &#64;Fallback annotation to denote a method as catch-all method? 

```
public static class GreeterInterceptor {

        @RuntimeType
        @Fallback
        public Object delegate(@SuperCall Callable<?> zuper) throws Exception {
            return zuper.call();
        }

        public String hello(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();

        }

        public String world(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

    }
```

Regardless of method parameters if a match is not found in the above example ```delegate``` is always called.

**Comment by raphw** [comment]
I think what you are trying to achieve might already be covered by the BindingPriority annotation. Can you look into this possibility for your use-case?

**Comment by saden1** [comment]
It was the first thing I tried :smile: It did not work :rage:

```java 
public class TestCase {

    public static class Greeter {

        public String hello() {
            return "hello";
        }

        public String world() {
            return "world";
        }

        public String greet() {
            return hello() + " " + world();
        }
    }

    public static class GreeterInterceptor {

        @RuntimeType
        @BindingPriority(Integer.MIN_VALUE)
        public Object delegate(@SuperCall Callable<?> zuper) throws Exception {
            return zuper.call();
        }

        public String hello(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();

        }

        public String world(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

    }

    public static void main(String[] args) throws Exception {
        Greeter instance = new ByteBuddy().subclass(Greeter.class)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(to(new GreeterInterceptor()).filter(not(isDeclaredBy(Object.class)))).make()
                .load(TestCase.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded()
                .newInstance();

        String result = instance.greet();
        System.out.println(result);

    }
}
```

Result:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of public java.lang.String com.tangocard.scratch.TestCase$Greeter.greet() to MethodDelegationBinder.MethodBinding.Builder.Build{target=public java.lang.String com.tangocard.scratch.TestCase$GreeterInterceptor.world(java.util.concurrent.Callable) throws java.lang.Exception, registeredTargetIndices={java.lang.Object@6df97b55=0}, methodInvocation=MethodInvocation.Invocation{typeDescription=class com.tangocard.scratch.TestCase$GreeterInterceptor, methodDescription=public java.lang.String com.tangocard.scratch.TestCase$GreeterInterceptor.world(java.util.concurrent.Callable) throws java.lang.Exception}, parameterStackManipulations=[MethodDelegationBinder.ParameterBinding.Anonymous{anonymousToken=java.lang.Object@6df97b55, delegate=MethodCallProxy.AssignableSignatureCall{specialMethodInvocation=Instrumentation.SpecialMethodInvocation.Simple{typeDescription=class com.tangocard.scratch.TestCase$Greeter, methodDescription=public java.lang.String com.tangocard.scratch.TestCase$Greeter.greet()}, serializableProxy=false}}], terminatingStackManipulation=StackManipulation.Compound{stackManipulations=[StackManipulation.Trivial.INSTANCE, MethodReturn.REFERENCE]}} or MethodDelegationBinder.MethodBinding.Builder.Build{target=public java.lang.String com.tangocard.scratch.TestCase$GreeterInterceptor.hello(java.util.concurrent.Callable) throws java.lang.Exception, registeredTargetIndices={java.lang.Object@7225790e=0}, methodInvocation=MethodInvocation.Invocation{typeDescription=class com.tangocard.scratch.TestCase$GreeterInterceptor, methodDescription=public java.lang.String com.tangocard.scratch.TestCase$GreeterInterceptor.hello(java.util.concurrent.Callable) throws java.lang.Exception}, parameterStackManipulations=[MethodDelegationBinder.ParameterBinding.Anonymous{anonymousToken=java.lang.Object@7225790e, delegate=MethodCallProxy.AssignableSignatureCall{specialMethodInvocation=Instrumentation.SpecialMethodInvocation.Simple{typeDescription=class com.tangocard.scratch.TestCase$Greeter, methodDescription=public java.lang.String com.tangocard.scratch.TestCase$Greeter.greet()}, serializableProxy=false}}], terminatingStackManipulation=StackManipulation.Compound{stackManipulations=[StackManipulation.Trivial.INSTANCE, MethodReturn.REFERENCE]}}
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.resolve(MethodDelegationBinder.java:952)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.process(MethodDelegationBinder.java:883)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1218)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:510)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:444)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:3193)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1481)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:234)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$AbstractDelegatingBuilder.make(DynamicType.java:2177)
	at com.tangocard.scratch.TestCase.main(TestCase.java:59)
```

**Comment by raphw** [comment]
Yes, you are suffering the same issue with this strategy. Byte Buddy can now discard the first method due to its low priority but is still faced with two ambiguous choices. You would need to set `@BindingPriority(Integer.MAX_VALUE)` on the first method. However, you probably want the method name to be considered first. This you can achieve by adjusting the default order of the resolvers:

```java
.intercept(to(new GreeterInterceptor())
   .defineAmbiguityResolver(MethodNameEqualityResolver.INSTANCE,
        BindingPriority.Resolver.INSTANCE
```

This way, the method name is considered as a first criteria and the priority as a second. By default, it is the other way arround.

**Comment by raphw** [comment]
I hope this helped. As I have not heard back from you, I am now closing this issue. Feel free to reopen it if any question remains.

**Comment by saden1** [comment]
Your suggestion didn't work.

Here's what my test case looks like:

```java
public class FallbackInterceptorTest {

    @Test
    public void test() throws InstantiationException, IllegalAccessException {
        GreeterInterceptor interceptor = new GreeterInterceptor();
        Greeter greeter = new ByteBuddy().subclass(Greeter.class)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(to(interceptor)
                        .filter(not(isDeclaredBy(Object.class)))
                        .defineAmbiguityResolver(
                                MethodNameEqualityResolver.INSTANCE,
                                BindingPriority.Resolver.INSTANCE)
                )
                .make()
                .load(TestCase.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded()
                .newInstance();

        String result = greeter.greet();
    }

    public static class Greeter {

        public String hello() {
            return "hello";
        }

        public String world() {
            return "world";
        }

        public String greet() {
            return hello() + " " + world();
        }
    }

    public static class GreeterInterceptor {

        @RuntimeType
        @BindingPriority(Integer.MIN_VALUE)
        public Object _default(@SuperCall Callable<?> zuper, @AllArguments Object[] args) throws Exception {
            return zuper.call();
        }

        public String hello(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();

        }

        public String world(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

    }

}
```

```
java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of public java.lang.String bytebuddy.test.FallbackInterceptorTest$Greeter.greet() to MethodDelegationBinder.MethodBinding.Builder.Build{target=public java.lang.String bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor.hello(java.util.concurrent.Callable) throws java.lang.Exception, registeredTargetIndices={java.lang.Object@5204062d=0}, methodInvocation=MethodInvocation.Invocation{typeDescription=class bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor.hello(java.util.concurrent.Callable) throws java.lang.Exception}, parameterStackManipulations=[MethodDelegationBinder.ParameterBinding.Anonymous{anonymousToken=java.lang.Object@5204062d, delegate=MethodCallProxy.AssignableSignatureCall{specialMethodInvocation=Implementation.SpecialMethodInvocation.Simple{typeDescription=class bytebuddy.test.FallbackInterceptorTest$Greeter, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$Greeter.greet(), stackManipulation=MethodInvocation.Invocation{typeDescription=class bytebuddy.test.FallbackInterceptorTest$Greeter, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$Greeter.greet()}}, serializableProxy=false}}], terminatingStackManipulation=StackManipulation.Compound{stackManipulations=[StackManipulation.Trivial.INSTANCE, MethodReturn.REFERENCE]}} or MethodDelegationBinder.MethodBinding.Builder.Build{target=public java.lang.String bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor.world(java.util.concurrent.Callable) throws java.lang.Exception, registeredTargetIndices={java.lang.Object@2fd66ad3=0}, methodInvocation=MethodInvocation.Invocation{typeDescription=class bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$GreeterInterceptor.world(java.util.concurrent.Callable) throws java.lang.Exception}, parameterStackManipulations=[MethodDelegationBinder.ParameterBinding.Anonymous{anonymousToken=java.lang.Object@2fd66ad3, delegate=MethodCallProxy.AssignableSignatureCall{specialMethodInvocation=Implementation.SpecialMethodInvocation.Simple{typeDescription=class bytebuddy.test.FallbackInterceptorTest$Greeter, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$Greeter.greet(), stackManipulation=MethodInvocation.Invocation{typeDescription=class bytebuddy.test.FallbackInterceptorTest$Greeter, methodDescription=public java.lang.String bytebuddy.test.FallbackInterceptorTest$Greeter.greet()}}, serializableProxy=false}}], terminatingStackManipulation=StackManipulation.Compound{stackManipulations=[StackManipulation.Trivial.INSTANCE, MethodReturn.REFERENCE]}}
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.resolve(MethodDelegationBinder.java:952)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.process(MethodDelegationBinder.java:883)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1224)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:564)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:498)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:3450)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1577)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:164)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2472)
	at bytebuddy.test.FallbackInterceptorTest.test(FallbackInterceptorTest.java:39)
```

**Comment by raphw** [comment]
I was under the impression that you did not want to intercept the `greet` method. You need to specify this on your matcher such as `not(isDeclaredBy(Object.class).or(named("greet"))`. In this case your example works. Otherwise, intercepting `greet` is still ambiguous as all three methods could be used for delegation. Byte Buddy only discards the first one due to the low binding priority, leaving it to decide between the other two where none has an equal name to `greet` what renders the binding ambiguous.

**Comment by saden1** [comment]
What I am trying to do is have bytebuddy intercept methods defined in the interceptor (hello and world) and for those methods not defined in the interceptor delegated to _default method. In essence have the interceptor be the place were interception decisions are made. I don't want to intercept the greet method but I also don't want to explicitly specify every method I would like to intercept. For example, the bellow works but it is not strongly typed or scalable when you have to intercept lots of methods:

```
  GreeterInterceptor interceptor = new GreeterInterceptor();
        Greeter greeter = new ByteBuddy().subclass(Greeter.class)
                .method(named("hello").or(named("world")).or(named("rinceAndRepeat")))
                .intercept(to(interceptor)
                        .filter(not(isDeclaredBy(Object.class)))
                )
                .make()
                .load(TestCase.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded()
                .newInstance();

        greeter.greet();
```


Question, does bytebuddy analyze the instance class (Greeter) and the interceptor (GreeterInterceptor) to make decisions about  what method should be used to intercept a particular method call?

**Comment by saden1** [comment]
Also, shouldn't the name of the method take precedence in my test case? If you have two methods with the same name there is bound to be ambiguity but in my case all the methods have a unique name.

**Comment by saden1** [comment]
One thing to note is that the issue also manifests itself when rebasing a class.

**Comment by raphw** [comment]
Then you should set the priority to `Integer.MAX_VALUE` or some other high value. In this case, all methods are bound to an interceptor of their name first and by their priority second. This way, the equal-named methods are bound to their equivalents and all other methods fallback to your `_default` interceptor.

**Comment by saden1** [comment]
It worked! Awesome! Thank you for all the help!

**Comment by saden1** [comment]
Just upgraded to release 1.6.9 and the following code no longer seems to work:

```java
import java.util.concurrent.Callable;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.MethodNameEqualityResolver;
import net.bytebuddy.implementation.bind.annotation.AllArguments;
import net.bytebuddy.implementation.bind.annotation.BindingPriority;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder;
import static net.bytebuddy.matcher.ElementMatchers.isDeclaredBy;
import static net.bytebuddy.matcher.ElementMatchers.not;
import org.junit.Test;


public class FallbackInterceptorST {

    @Test
    public void test() throws InstantiationException, IllegalAccessException {
        GreeterInterceptor interceptor = new GreeterInterceptor();
        Greeter greeter = new ByteBuddy().subclass(Greeter.class)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(MethodDelegation.withEmptyConfiguration()
                        .withBinders(TargetMethodAnnotationDrivenBinder.ParameterBinder.DEFAULTS)
                        .withResolvers(MethodNameEqualityResolver.INSTANCE, BindingPriority.Resolver.INSTANCE)
                        .filter(not(isDeclaredBy(Object.class)))
                        .to(interceptor)
                )
                .make()
                .load(FallbackInterceptorST.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded()
                .newInstance();

        String result = greeter.greet();
    }

    public static class Greeter {

        public String hello() {
            return "hello";
        }

        public String world() {
            return "world";
        }

        public String greet() {
            return hello() + " " + world();
        }
    }

    public static class GreeterInterceptor {

        @RuntimeType
        @BindingPriority(Integer.MAX_VALUE)
        public Object _default(@SuperCall Callable<?> zuper, @AllArguments Object[] args) throws Exception {
            return zuper.call();
        }

        @RuntimeType
        public String hello(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

        @RuntimeType
        public String world(@SuperCall Callable<String> zuper) throws Exception {
            return zuper.call().toUpperCase();
        }

    }

}
```

It looks like the custom binders and resolvers is set are overriden in [this line of code](https://github.com/raphw/byte-buddy/blob/02779453c5a472372eb1ccc729e32ba59eb83f6e/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodDelegation.java#L1305).

**Comment by raphw** [comment]
You are right, I fixed this on head. Thanks for the report.
