### ISSUE TITLE
Use advice api with kotlin and proguard case inconsistent exception

### ISSUE THREAD

**Issue by XhstormR** [raphw/byte-buddy#884]
I have two jar packages, one is optimized by proguard. The unprocessed jar package works fine, but the processed jar package throws an exception:

```
[Byte Buddy] ERROR org.apache.catalina.core.ApplicationFilterChain [org.springframework.boot.loader.LaunchedURLClassLoader@6d5380c2, null, loaded=true]
java.lang.IllegalStateException: public static final boolean com.xhstormr.app.红烧乳鸽.trace(java.lang.Object[],java.lang.String) is inconsistent at 0: 0
        at com.xhstormr.app.dB.红烧排骨(Unknown Source)
        at com.xhstormr.app.dC.红烧排骨(Unknown Source)
        at com.xhstormr.app.bd.a_(Unknown Source)
        at com.xhstormr.app.vJ.a_(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.vv.红烧乳鸽(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.bf.红烧狮子头(Unknown Source)
        at com.xhstormr.app.ar.红烧排骨(Unknown Source)
        at com.xhstormr.app.Ah.红烧鳝段(Unknown Source)
        at com.xhstormr.app.Ah.a_(Unknown Source)
        at com.xhstormr.app.vI.红烧排骨(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.vv.红烧乳鸽(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.vv.红烧排骨(Unknown Source)
        at com.xhstormr.app.pS.红烧排骨(Unknown Source)
        at com.xhstormr.app.pM.红烧排骨(Unknown Source)
        at com.xhstormr.app.ri.红烧排骨(Unknown Source)
        at com.xhstormr.app.松肉.红烧排骨(Unknown Source)
        at com.xhstormr.app.松肉.红烧排骨(Unknown Source)
        at com.xhstormr.app.松肉.红烧排骨(Unknown Source)
        at com.xhstormr.app.糖酥排骨.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.xhstormr.app.松肉.transform(Unknown Source)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:193)
        at com.xhstormr.app.Q.红烧排骨(Unknown Source)
        at com.xhstormr.app.P.红烧排骨(Unknown Source)
        at com.xhstormr.app.J.红烧排骨(Unknown Source)
        at com.xhstormr.app.烧花鸭.红烧排骨(Unknown Source)
        at com.xhstormr.app.烧花鸭.红烧排骨(Unknown Source)
        at com.xhstormr.app.烧肉.红烧排骨(Unknown Source)
        at com.xhstormr.app.AgentMainKt.agentmain(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
```

I checked the source code and found that an exception was thrown here: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L5547, maybe related to this https://github.com/mockito/mockito/issues/1152

This is the kotlin code I wrote:
```kotlin
    val advice = Advice
        .withCustomMapping()
        .bind(clazz<Value>(), args)
        .to(clazz<Tracing>())
        .on(ElementMatchers.named("internalDoFilter"))
    AgentBuilder.Default()
        .with(AgentBuilder.Listener.StreamWriting.toSystemOut().withErrorsOnly())
        .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
        .type(ElementMatchers.named("org.apache.catalina.core.ApplicationFilterChain"))
        .transform { builder, _, _, _ -> builder.visit(advice) }
        .installOn(inst)
```

This is the library I use and proguard version is 7.0.0:
![123](https://user-images.githubusercontent.com/10527522/84860160-28442800-b0a1-11ea-9135-c5c048a2f813.jpg)

This is the processed jar package: [test.zip](https://github.com/raphw/byte-buddy/files/4790569/test.zip)

**Comment by raphw** [comment]
ProGuard will mess up your advice such that it no longer can be used as a template by Byte Buddy. ProGuard often rearranges stack maps what makes them untranslatable. If you only exclude `Tracing` from obfuscation, it should work.

**Comment by XhstormR** [comment]
I added the following code in proguard-rules.pro:
```
-keep class com.xhstormr.app.Tracing { *; }
```
But he still throws an exception:
```
[Byte Buddy] ERROR org.apache.catalina.core.ApplicationFilterChain [org.springframework.boot.loader.LaunchedURLClassLoader@6d5380c2, null, loaded=true]
java.lang.IllegalStateException: public static final boolean com.xhstormr.app.Tracing.trace(java.lang.Object[],java.lang.String) is inconsistent at 0: 0
```

**Comment by XhstormR** [comment]
I added the following code in proguard-rules.pro, still throws an exception, looks like it cannot be used at the same time:
```
-dontoptimize
-dontshrink
-dontobfuscate
```

**Comment by raphw** [comment]
Do you have a bit more of the stack trace in the obfuscated code? It should only happen for the advice methods where their shape and frame setup must not be wrangled.

**Comment by XhstormR** [comment]
This is the exception log and jar package generated after adding the following code:
```
-dontoptimize
-dontshrink
-dontobfuscate
```

```
[Byte Buddy] ERROR org.apache.catalina.core.ApplicationFilterChain [org.springframework.boot.loader.LaunchedURLClassLoader@6d5380c2, unnamed module @78c7f9b3, loaded=false]
java.lang.IllegalStateException: public static final boolean com.xhstormr.app.Tracing.trace(java.lang.Object[],java.lang.String) is inconsistent at 0: 0
        at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:5547)
        at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default$ForAdvice.translateFrame(Advice.java:6261)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$CodeTranslationVisitor.visitFrame(Advice.java:8644)
        at net.bytebuddy.jar.asm.MethodVisitor.visitFrame(MethodVisitor.java:299)
        at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2046)
        at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1488)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:718)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:401)
        at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:7735)
        at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:9877)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:49)
        at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:81)
        at net.bytebuddy.jar.asm.Label.accept(Label.java:358)
        at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2028)
        at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1488)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:718)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:401)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3827)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
        at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:252)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10722)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10660)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10219)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:129)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.catalina.core.ApplicationFilterFactory.createFilterChain(ApplicationFilterFactory.java:70)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:174)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

[test.zip](https://github.com/raphw/byte-buddy/files/4802193/test.zip)

**Comment by raphw** [comment]
From the trace it shows that ProGuard still must be messing with the frames of the advice class. No idea how to turn it of but that is the problem.

**Comment by XhstormR** [comment]
Can you look at this issue https://github.com/Guardsquare/proguard/issues/50 ? After discussion, it seems that Proguard generated the StackMapTable property acceptable to the JVM, but byte-buddy does not recognize this property.

**Comment by raphw** [comment]
Byte Buddy requires the original format of the stack map table to retain it's inlineability. Byte Buddy does not run the code, it uses it as a template. If ProGuard tempers with the stack map frames, no matter if the JVM can accept it, the templating engine cannot merge the frames into the original method anymore.

**Comment by sagar-cws** [comment]
@XhstormR @raphw this seems like a old issue but was there any solution to this?
i'm facing the same issue.
Thanks.

**Comment by raphw** [comment]
Exclude the advice class from obfuscation and write it in Java.
