### ISSUE TITLE
Running bytebuddy at java 11 enviroment with app compiled with java 8

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#898]
Hi there, 
I've application that running at java 11 runtime, but the code is compiled to java 8
And also I've java agent jar (also compiled to java 8) that built with byte buddy that attached to the application
```
  configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
```
Turns out it produce these errors, is it expected ?

![image](https://user-images.githubusercontent.com/17562956/86949309-a6fc2480-c178-11ea-952d-3dea33f6bf5f.png)

**Comment by raphw** [comment]
No, but the errors should come with a stack trace and exception. What do those say?

**Comment by davidasync** [comment]
ahh yes that's comes with this error,
I found that errors occurred due to different version of java version 

```
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:148)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:136)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:61)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1067)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1053)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1133)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1208)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1270)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:7049)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:6561)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:6584)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.isAssignableFrom(TypeDescription.java:7231)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:6562)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:6594)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:30)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:11)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1219)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:9030)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:9041)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:9281)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:9611)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9578)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9541)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:9309)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:9978)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:9918)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9497)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1192)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.json.JSONObject.populateMap(JSONObject.java:1458)
	at org.json.JSONObject.<init>(JSONObject.java:315)
	at com.traveloka.autocomplete.util.ElasticsearchUtil.createAutoCompleteSpecMap(ElasticsearchUtil.java:114)
	at com.traveloka.autocomplete.util.ElasticsearchUtil.generateElasticSearchQuery(ElasticsearchUtil.java:89)
	at com.traveloka.autocomplete.service.SearchIndexElasticSearchServiceImpl.generateElasticSearchQuery(SearchIndexElasticSearchServiceImpl.java:627)
	at com.traveloka.autocomplete.service.SearchIndexElasticSearchServiceImpl.searchIndexObjectMultipleTypeAprsaci(SearchIndexElasticSearchServiceImpl.java:724)
	at com.traveloka.autocomplete.service.SearchIndexElasticSearchServiceImpl.searchEntityFromMultipleTypes(SearchIndexElasticSearchServiceImpl.java:241)
	at com.traveloka.autocomplete.service.SearchIndexBaseServiceImpl.getExactSuggestion(SearchIndexBaseServiceImpl.java:608)
	at com.traveloka.autocomplete.service.SearchIndexBaseServiceImpl.getAutoCompleteInternal(SearchIndexBaseServiceImpl.java:331)
	at com.traveloka.autocomplete.service.SearchIndexBaseServiceImpl.getAutoCompleteBySpec(SearchIndexBaseServiceImpl.java:177)
	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dk.rpc.common.DefaultClassInvoker.invokeAsyncMethod(DefaultClassInvoker.java:163)
	at org.dk.rpc.common.DefaultClassInvoker.invokeAsync(DefaultClassInvoker.java:148)
	at org.dk.rpc.server.JsonRpcDoubleDispatchAsyncHttpServlet.doPost(JsonRpcDoubleDispatchAsyncHttpServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.GzipHandler.handle(GzipHandler.java:264)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by davidasync** [comment]
ahh yes that's comes with this error,
I found that errors occurred due to different version of java version 

```
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:148)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:136)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:61)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:1067)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:1053)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$401(TypePool.java:1133)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1208)
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1270)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:7049)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:6561)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableFrom(TypeDescription.java:6584)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.isAssignableFrom(TypeDescription.java:7231)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignable(TypeDescription.java:6562)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isAssignableTo(TypeDescription.java:6594)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:30)
	at net.bytebuddy.matcher.SubTypeMatcher.matches(SubTypeMatcher.java:11)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1219)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.matches(AgentBuilder.java:9030)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple.resolve(AgentBuilder.java:9041)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Compound.resolve(AgentBuilder.java:9281)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.resolve(AgentBuilder.java:9611)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9578)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9541)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1400(AgentBuilder.java:9309)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:9978)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:9918)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9497)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1192)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
...
	
```

**Comment by raphw** [comment]
You must be using a rather old version of Byte Buddy, I assume?

**Comment by davidasync** [comment]
> You must be using a rather old version of Byte Buddy, I assume?

I believe I'm using latest version which is `1.10.13`

**Comment by raphw** [comment]
This seems unlikely since Byte Buddy is complaining to not know Java 11. Is there possibly an old version on the class path?

**Comment by davidasync** [comment]
> This seems unlikely since Byte Buddy is complaining to not know Java 11. Is there possibly an old version on the class path?

Hmm I'm not sure about this, but after update the libraries at my application to satisfy java 11 runtime, my app could run as expected in java 8 runtime

btw I'll close this issue ya thanks for your response
