### ISSUE TITLE
Can we enhance class twice or more times?

### ISSUE THREAD

**Issue by dengliming** [raphw/byte-buddy#903]
Now, I found a problem. I use two apm agent. They all depend on bytebuddy.
And occur below exception, Seems all the class that contains `$auxiliary$` are enhanced fail.
```
2020-07-27 15:59:17.071[WARN]-[localhost-startStop-1]-[c.y.y.a.c.c.a.AgentListener.onError(69)]: Enhance class org.redisson.client.RedisConnection error.classLoader = WebappClassLoader^M
  context: ROOT^M
  delegate: false^M
----------> Parent Classloader:^M
java.net.URLClassLoader@44924587^M

java.lang.IllegalStateException: Cannot resolve type description for org.redisson.client.RedisConnection$auxiliary$jRMfo4rx
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8122)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7631)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:505)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:218)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10123)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10833)
        at com.yametech.yangjian.agent.thirdparty.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10780)
        at java.security.AccessController.doPrivileged(Native Method)

```

**Comment by raphw** [comment]
If a Java agent uses delegation, Byte Buddy needs to inject new classes into the target class loader. These classes have no representation as class files and cannot be resolved later. 

Ideally, you do not rely on such injection and hierarchy matching and use `Advice` to instrument classes. Also register a `MethodGraph.Compiler.ForDeclaredMethods` in the `ByteBuddy` instance for the `AgentBuilder`.

**Comment by dengliming** [comment]
Hi~ For historical reasons, now we use static method of `Interceptor`. Is there any way to avoid this problem without using `Advice `?

**Comment by raphw** [comment]
You can resolve a custom `TypePool` or `ClassFileLocator` where you make this information available. Otherwise, you need to unfortunately bet on using `Advice`.

**Comment by dengliming** [comment]
Can you provide some examples?

**Comment by raphw** [comment]
You'd need to register a `Listener` where the `DynamicType` is provided in the `onTransformed` method. You can extract class files from there. Additionally, you'd need to register a custom `ClassLocatorStrategy` where you need to return these byte arrays if the previously transformed class's auxiliary classes are requested.
