### ISSUE TITLE
class redefinition failed: attempted to delete a method

### ISSUE THREAD

**Issue by asasas234** [raphw/byte-buddy#908]
@raphw I need your help.
We enhance the method of 1 class, the test environment is fine, the online environment reports the following error, not quite clear what the reason is

java.lang.IllegalStateException: Error invoking java.lang.instrument.Instrumentation#retransformClasses                                                             
        at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(ClassReloadingStrategy.java:500)                    
        at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$2.apply(ClassReloadingStrategy.java:565)                                                   
        at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.load(ClassReloadingStrategy.java:225)                                                               
        at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)                                                         
        at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5686)                                                                           
        at com.skyeye.k12.teacher.common.util.ByteBuddyUtils.lambda$byteBuddyJob$2(ByteBuddyUtils.java:71)                                                          
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)                                                                                                  
        at com.skyeye.k12.teacher.common.util.ByteBuddyUtils.byteBuddyJob(ByteBuddyUtils.java:66)                                                                   
        at com.skyeye.k12.teacher.common.util.ByteBuddyUtils.byteBuddy(ByteBuddyUtils.java:29)                                                                      
        at com.skyeye.k12.teacher.logback.api.listener.LogbackApplicationListener.onApplicationEvent(LogbackApplicationListener.java:40)                            
        at com.skyeye.k12.teacher.logback.api.listener.LogbackApplicationListener.onApplicationEvent(LogbackApplicationListener.java:21)                            
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)                         
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)                           
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)                           
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)                                         
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)                                         
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)                                        
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)               
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)                                              
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)                     
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743)                                                                           
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390)                                                                    
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)                                                                               
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)                                                                              
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)                                                                              
        at com.koolearn.shuangshi.mobi.core.KooShuangshiMobiCoreApplication.main(KooShuangshiMobiCoreApplication.java:20)                                           
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                         
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)                                                                           
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)                                                                                        
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)                                                                                        
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)                                                                                    
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method                                                         
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)                                                                                    
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)                                                                      
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                         
        at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(ClassReloadingStrategy.java:492)                    
        ... 33 common frames omitted

**Comment by asasas234** [comment]
Our code is as follows

private static void byteBuddyJob(ApplicationContext applicationContext) {
        Map<String, Object> jobHandlerMap = applicationContext.getBeansWithAnnotation(JobHandler.class);
        if (!CollectionUtils.isEmpty(jobHandlerMap)) {
            try{
                jobHandlerMap.forEach((name, jobHandler) -> {
                    log.info("byteBuddyJob : {},class : {}",name,AopUtils.getTargetClass(jobHandler));
                    ByteBuddyAgent.install();
                   ;
                    new ByteBuddy().redefine(AopUtils.getTargetClass(jobHandler))
                            .visit(Advice.to(JobHandlerAdvisor.class).on(ElementMatchers.named("execute")))
                            .make()
                            .load(jobHandler.getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
                });
            }catch (Exception e){
                log.warn("byteBuddyJob error, e: {}",e.getMessage());
            }

        }
    }

**Comment by asasas234** [comment]
Our code is as follows

`private static void byteBuddyJob(ApplicationContext applicationContext) {
        Map<String, Object> jobHandlerMap = applicationContext.getBeansWithAnnotation(JobHandler.class);
        if (!CollectionUtils.isEmpty(jobHandlerMap)) {
            try{
                jobHandlerMap.forEach((name, jobHandler) -> {
                    log.info("byteBuddyJob : {},class : {}",name,AopUtils.getTargetClass(jobHandler));
                    ByteBuddyAgent.install();
                   ;
                    new ByteBuddy().redefine(AopUtils.getTargetClass(jobHandler))
                            .visit(Advice.to(JobHandlerAdvisor.class).on(ElementMatchers.named("execute")))
                            .make()
                            .load(jobHandler.getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
                });
            }catch (Exception e){
                log.warn("byteBuddyJob error, e: {}",e.getMessage());
            }

        }
    }`

**Comment by asasas234** [comment]
Our code is as follows
```
private static void byteBuddyJob(ApplicationContext applicationContext) {
        Map<String, Object> jobHandlerMap = applicationContext.getBeansWithAnnotation(JobHandler.class);
        if (!CollectionUtils.isEmpty(jobHandlerMap)) {
            try{
                jobHandlerMap.forEach((name, jobHandler) -> {
                    log.info("byteBuddyJob : {},class : {}",name,AopUtils.getTargetClass(jobHandler));
                    ByteBuddyAgent.install();
                   ;
                    new ByteBuddy().redefine(AopUtils.getTargetClass(jobHandler))
                            .visit(Advice.to(JobHandlerAdvisor.class).on(ElementMatchers.named("execute")))
                            .make()
                            .load(jobHandler.getClass().getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
                });
            }catch (Exception e){
                log.warn("byteBuddyJob error, e: {}",e.getMessage());
            }

        }
    }
```

**Comment by asasas234** [comment]
Our bytebuddy version is 1.9.16.

**Comment by asasas234** [comment]
JobHandler inherits an abstract class, the execute method is defined on the abstract class, and the subclass we want to augment implements this method

**Comment by raphw** [comment]
Typically, this is because you are adding fields or methods. The exception should have a cause (if you do not only log the message but the entire exception. This should indicate if such a change was made.

**Comment by asasas234** [comment]
@raphw We'll see, I suspect it may have something to do with the addition of the startup parameter-javaagent to the line, and our code may conflict with the jar specified by the agent.

**Comment by raphw** [comment]
This other agent might not be retransformation capable what would break the retransformation as the first agent's changes are no longer applied.

**Comment by asasas234** [comment]
@raphw I've confirmed that it's the startup plus-javaagent that's causing the problem, and that this agent will implement 1 interface, plus 1 property, and 2 methods on the target class I'm trying to enhance. I see the bytecode that failed after my redefine, and I'm wondering why just the 2 methods are gone, but the property and interface are still there, what is the reason for this, and what other solution is there to keep both the -javaagent specified by the agent and our own enhanced code in this case?

**Comment by asasas234** [comment]
```
public class TeacherLiveJobHandler extends IJobHandler implements EnhancedInstance  {
   private volatile Object _$EnhancedClassField_ws;
}
public interface EnhancedInstance {
    Object getSkyWalkingDynamicField();

    void setSkyWalkingDynamicField(Object value);
}

```
The EnhancedInstance interface and the _$EnhancedClassField_ws property are the enhancements initiated by that agent package at startup.

**Comment by asasas234** [comment]
@raphw I have an idea that I'm planning to try, and I'd also like to ask you to see if it's possible. Or do you have any better suggestions, I plan to do a subclass implementation of the target class through Spring's BeanPostProcessor via ByteBuddy's subClass, bytebuddy's interceptor method is MethodDelegation, finally I bytebuddy The advice target's class is now the same class that was previously created in BeanPostProcessor via the bytebuddy subClass.

Translated with www.DeepL.com/Translator (free version)

**Comment by asasas234** [comment]
@raphw I have an idea, I can use the Maven plugin provided by bytebuddy to de-enhance the bytecode at compile time, so that I enhance it first, then the -javaagent specifies the agent to enhance it, and that solves the problem!

**Comment by raphw** [comment]
If one agent does not support redefinition, redefinition is likely not an option and the Maven alternative seems to be a good idea. This way, you assure that the agent considers your changes to be part of the original class files.

**Comment by asasas234** [comment]
@raphw Thanks, that's what I ended up doing.
