### ISSUE TITLE
Gradle BUILD FAILED

### ISSUE THREAD

**Issue by zuomengjun** [raphw/byte-buddy#909]
my build.gradle is :
```
apply plugin: "net.bytebuddy.byte-buddy-gradle-plugin"
configurations {
    examplePlugin
}
byteBuddy {
    transformation {
        plugin = "com.skyeye.k12.teacher.common.util.ByteBuddyPlugin"
        classPath = configurations.examplePlugin
    }
}
```

Build failures:
```
BUILD FAILED in 4s
3 actionable tasks: 1 executed, 2 up-to-date
Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)
20:14:00: Task execution finished 'compileJava'.
```

**Comment by asasas234** [comment]
梦君你报的是这个错啊~~，这个网络连接超时，应该是你当时网络状况不太好，或者需要翻墙才能下载~~

**Comment by zuomengjun** [comment]
> 梦君你报的是这个错啊~~，这个网络连接超时，应该是你当时网络状况不太好，或者需要翻墙才能下载~~

志博，byte插件能下载下来，我用的阿里的仓库地址，我感觉貌似是这块配置的方式不对，它找不到我的ByteBuddyPlugin
```
byteBuddy {
    transformation {
        plugin = "com.skyeye.k12.teacher.common.util.ByteBuddyPlugin"
        classPath = configurations.examplePlugin
    }
}
```

**Comment by raphw** [comment]
I would not know how this error relates to Byte Buddy. Did you build with debug logging?

**Comment by zuomengjun** [comment]
> I would not know how this error relates to Byte Buddy. Did you build with debug logging?

Hello, I use execute this command: 'gradlew :worker:compileJava --stacktrace', Then there are the following errors, 
I don't understand this code：'net.bytebuddy.dynamic.ClassFileLocator$ForJarFile.of(ClassFileLocator.java:767)'
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':worker:compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Error accessing file system
        at net.bytebuddy.build.gradle.TransformationAction.execute(TransformationAction.java:78)
        at net.bytebuddy.build.gradle.TransformationAction.execute(TransformationAction.java:41)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:762)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:729)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at net.bytebuddy.dynamic.ClassFileLocator$ForJarFile.of(ClassFileLocator.java:767)
        at net.bytebuddy.build.gradle.TransformationAction.apply(TransformationAction.java:117)
        at net.bytebuddy.build.gradle.TransformationAction.execute(TransformationAction.java:76)
        ... 38 more

```

**Comment by raphw** [comment]
It seems like the ZIP file your build is creating is corrupted: *java.util.zip.ZipException: error in opening zip file* - have you tried opening it manually (the jar file)?

**Comment by zuomengjun** [comment]
> It seems like the ZIP file your build is creating is corrupted: _java.util.zip.ZipException: error in opening zip file_ - have you tried opening it manually (the jar file)?

Hello, problem found, I have introduced a dependency of type POM in my build.gradle file, which is treated as a JAR file and thus causes 'error in opening zip file', Doesn't the ByteBuddy plugin support it?

**Comment by raphw** [comment]
No, this should work, too. The exception is coming from the standard library, though that the zip file appeared invalid.
