### ISSUE TITLE
Redefine doesn't work in Android.

### ISSUE THREAD

**Issue by lianghanzhen** [raphw/byte-buddy#910]
I tried to replace `subclass` `Object` class with `redefine` in android test probject, I had the exception:

`
net.bytebuddy.android.test W/net.bytebuddy: java.lang.IllegalStateException: Could not locate class file for java.lang.Object
        at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:118)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3822)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
        at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
        at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3595)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3819)
        at net.bytebuddy.android.test.TestActivity$TestRun.onClick(TestActivity.java:146)
        at android.view.View.performClick(View.java:7869)
        at android.widget.TextView.performClick(TextView.java:14958)
        at android.view.View.performClickInternal(View.java:7838)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29362)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
`

The cause is: [this method](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/ClassFileLocator.java#L438) always returns `null`.

**Comment by raphw** [comment]
Android does not support redefinition due to its runtime compiling from Java byte code to compiled machine code upon installation.

**Comment by lianghanzhen** [comment]
Are there any other ways to override a method? What I tried to achieve is override [`transform`](https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/lang/invoke/MethodHandle.java;l=1466?q=MethodHandle) method in `java.lang.invoke.MethodHandle` which is not allowed in Android.

**Comment by raphw** [comment]
You can move it to build time with Byte Buddy's Gradle plugin, as far as I know this is the only option.
