### ISSUE TITLE
Question about MethodCall.TargetHandler.ForMethodParameter.resolve

### ISSUE THREAD

**Issue by raner** [raphw/byte-buddy#928]
I'm trying to debug some code generation issues in a project of mine, and I get an IOOBE at `MethodCall.TargetHandler.ForMethodParameter.resolve`:
```
java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at net.bytebuddy.description.ByteCodeElement$Token$TokenList.get(ByteCodeElement.java:174)
	at net.bytebuddy.description.ByteCodeElement$Token$TokenList.get(ByteCodeElement.java:125)
	at net.bytebuddy.description.ByteCodeElement$Token$TokenList.get(ByteCodeElement.java:174)
	at net.bytebuddy.description.ByteCodeElement$Token$TokenList.get(ByteCodeElement.java:125)
	at net.bytebuddy.description.method.ParameterList$ForTokens.get(ParameterList.java:639)
	at net.bytebuddy.description.method.ParameterList$ForTokens.get(ParameterList.java:608)
	at net.bytebuddy.implementation.MethodCall$TargetHandler$ForMethodParameter.resolve(MethodCall.java:2493)
	at net.bytebuddy.implementation.MethodCall$Appender.apply(MethodCall.java:3507)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:600)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5660)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3595)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3819)
        ...
```
In [MethodCall.java:2490](https://github.com/raphw/byte-buddy/blob/101f6ef40ffbec8049069cd531c2956c71565c64/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodCall.java#L2490), I see a guard, but that guard is not kicking in, because the index is equal to the size, not greater.
Should line 2490 be
```
                if (instrumentedMethod.getParameters().size() <= index) {
```
or is this somehow a 1-based list index instead of a 0-based one, and there is something else wrong with my how code sets up the `DynamicType.Builder`?
There is definitely a bug in my own code that invokes this, but I was surprised to see an IOOBE instead of an `IllegalArgumentException` thrown by the guard.

**Comment by raphw** [comment]
You're right, it's a bad boundcheck.

**Comment by raphw** [comment]
Fixed on master, thanks for reporting!
