### ISSUE TITLE
[Bug] Anonymous class declared in static lambda (<clinit>()V not declared by class)

### ISSUE THREAD

**Issue by ZeroErrors** [raphw/byte-buddy#929]
I am experimenting with `byte-buddy` using the `byte-buddy-maven-plugin` on an existing codebase, however, when run it fails to execute. Failing with `<clinit>()V not declared by class` being thrown from here: https://github.com/raphw/byte-buddy/blob/byte-buddy-1.10.15/byte-buddy-dep/src/main/java/net/bytebuddy/pool/TypePool.java#L2961

<details> 
  <summary>Full Exception</summary>

```
[ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.14:transform (default) on project ...: Failed to transform class files in .\target\classes: <clinit>()V not declared by class ... -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.14:transform (default) on project ...: Failed to transform class files in .\target\classes
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to transform class files in .\target\classes
    at net.bytebuddy.build.maven.ByteBuddyMojo.apply (ByteBuddyMojo.java:314)
    at net.bytebuddy.build.maven.ByteBuddyMojo.execute (ByteBuddyMojo.java:207)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
Caused by: java.lang.IllegalStateException: <clinit>()V not declared by class ...
    at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TypeContainment$WithinMethod.getEnclosingMethod (TypePool.java:2943)
    at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription.getEnclosingMethod (TypePool.java:2573)
    at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getEnclosingMethod (TypeDescription.java:8306)
    at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent (InstrumentedType.java:396)
    at net.bytebuddy.ByteBuddy.rebase (ByteBuddy.java:888)
    at net.bytebuddy.build.EntryPoint$Default$1.transform (EntryPoint.java:78)
    at net.bytebuddy.build.Plugin$Engine$TypeStrategy$ForEntryPoint.builder (Plugin.java:877)
    at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call (Plugin.java:4478)
    at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call (Plugin.java:4455)
    at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.accept (Plugin.java:3538)
    at net.bytebuddy.build.Plugin$Engine$Default.apply (Plugin.java:4302)
    at net.bytebuddy.build.maven.ByteBuddyMojo.apply (ByteBuddyMojo.java:312)
    at net.bytebuddy.build.maven.ByteBuddyMojo.execute (ByteBuddyMojo.java:207)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run$$$capture (FutureTask.java:264)
    at java.util.concurrent.FutureTask.run (FutureTask.java)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
```
</details>

<br/>

After doing some debugging I found the piece of code that was causing the problem and put together a short snippet that recreates it. The code causing this allocates an anonymous object inside of a static lambda.
```java
public class Example {
    public static final Supplier<Object> TEST = () -> new Object() {
    };

    public static void main(String[] args) {
        System.out.println(TypePool.Default.ofSystemLoader()
                .describe(Example.class.getName() + "$1")
                .resolve()
                .getEnclosingMethod());
    }
}
```

<br/>

I then ran this with several different combinations of JDK and source/target versions, with some interesting results.
_(All of these run with byte-buddy 1.10.15)_
<table>
  <thead>
    <tr>
      <th rowspan="2">JDK</th>
      <th colspan="8" style="text-align: center;">-source &nbsp; -target</th>
    </tr>
    <tr>
      <th>15</th>
      <th>14</th>
      <th>13</th>
      <th>12</th>
      <th>11</th>
      <th>10</th>
      <th>9</th>
      <th>8</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>15</th>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:heavy_check_mark:</td>
      <td>:heavy_check_mark:</td>
    </tr>
    <tr>
      <th>14.0.2</th>
      <td>N/A</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:heavy_check_mark:</td>
    </tr>
    <tr>
      <th>13.0.2</th>
      <td>N/A</td>
      <td>N/A</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
      <td>:x:</td>
    </tr>
    <tr>
      <th>11.0.8</th>
      <td>N/A</td>
      <td>N/A</td>
      <td>N/A</td>
      <td>N/A</td>
      <td>:heavy_check_mark:</td>
      <td>:heavy_check_mark:</td>
      <td>:heavy_check_mark:</td>
      <td>:heavy_check_mark:</td>
    </tr>
  </tbody>
</table>

<br/>

On the versions where this succeeds you get the output
```java
private static java.lang.Object Example.lambda$static$0()
```

**Comment by raphw** [comment]
Interesting. I am wondering: can you access the enclosing method when using the Java reflection API? I am wondering if they are having the same issue or if the JVM can resolve it. I am curious because: if the JVM can figure it out, Byte Buddy likely can, too.

**Comment by ZeroErrors** [comment]
Tweaked the example to print out various stuff using reflection:
```java
public class Example {
    private static Supplier<Object> TEST = () -> new Object() {
    };

    public static void main(String[] args) throws ClassNotFoundException {
        System.out.println("Fields: " + Arrays.toString(Example.class.getDeclaredFields()));
        System.out.println("Classes: " + Arrays.toString(Example.class.getDeclaredClasses()));
        System.out.println("Methods: " + Arrays.toString(Example.class.getDeclaredMethods()));

        System.out.println();
        Class<?> theClass = Class.forName(Example.class.getName() + "$1");
        System.out.println("Class: " + theClass);
        System.out.println("EnclosingConstructor: " + theClass.getEnclosingConstructor());
        System.out.println("EnclosingMethod: " + theClass.getEnclosingMethod());
        System.out.println("EnclosingClass: " + theClass.getEnclosingClass());

        System.out.println();
        System.out.println(TypePool.Default.ofSystemLoader()
                .describe(Example.class.getName() + "$1")
                .resolve()
                .getEnclosingMethod());
    }
}
```

This is the output using JDK 15 and targeting Java 15:
```
Fields: [private static java.util.function.Supplier Example.TEST]
Classes: []
Methods: [public static void Example.main(java.lang.String[]) throws java.lang.ClassNotFoundException, private static java.lang.Object Example.lambda$static$0()]

Class: class Example$1
EnclosingConstructor: null
EnclosingMethod: null
EnclosingClass: class Example

Exception in thread "main" java.lang.IllegalStateException: <clinit>()V not declared by class Example
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TypeContainment$WithinMethod.getEnclosingMethod(TypePool.java:2961)
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription.getEnclosingMethod(TypePool.java:2584)
	at Example.main(Example.java:30)
```

Running the same thing on JDK 15 but instead targeting Java 9:
```
Fields: [private static java.util.function.Supplier Example.TEST]
Classes: []
Methods: [public static void Example.main(java.lang.String[]) throws java.lang.ClassNotFoundException, private static java.lang.Object Example.lambda$static$0()]

Class: class Example$1
EnclosingConstructor: null
EnclosingMethod: private static java.lang.Object Example.lambda$static$0()
EnclosingClass: class Example

private static java.lang.Object Example.lambda$static$0()
```

**Comment by raphw** [comment]
Seems like a new format is allowed in Java 15. I'll look into it and fix it! Thanks for reporting!

**Comment by raphw** [comment]
I think it's now fixed on master. Thanks for reporting!
