### ISSUE TITLE
Can't run on Jav 16-ea: java.lang.IllegalArgumentException: Unsupported class file major version 60

### ISSUE THREAD

**Issue by garydgregory** [raphw/byte-buddy#934]
Hi there,

Over at [Apache Commons Text](https://github.com/apache/commons-text) on Java 16-ea because we use Mockito which uses Byte Buddy, we see errors due to:

java.lang.IllegalArgumentException: Unsupported class file major version 60

For example:

```
[ERROR] Errors:
[ERROR] testAppendln_StringBuilder_int_int  Time elapsed: 0.459 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: class org.apache.commons.text.TextStringBuilder.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 16
JVM vendor name    : Oracle Corporation
JVM vendor version : 16-ea+16-712
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 16-ea+16-712
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface org.apache.commons.text.Builder, class java.lang.Object, class org.apache.commons.text.TextStringBuilder, interface java.io.Serializable, interface java.lang.CharSequence, interface java.lang.Appendable]
        at org.apache.commons.text.TextStringBuilderAppendInsertTest.testAppendln_StringBuilder_int_int(TextStringBuilderAppendInsertTest.java:873)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface org.apache.commons.text.Builder, class java.lang.Object, class org.apache.commons.text.TextStringBuilder, interface java.io.Serializable, interface java.lang.CharSequence, interface java.lang.Appendable]
        at org.apache.commons.text.TextStringBuilderAppendInsertTest.testAppendln_StringBuilder_int_int(TextStringBuilderAppendInsertTest.java:873)
Caused by: java.lang.IllegalStateException:

Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
        at org.apache.commons.text.TextStringBuilderAppendInsertTest.testAppendln_StringBuilder_int_int(TextStringBuilderAppendInsertTest.java:873)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
        at org.apache.commons.text.TextStringBuilderAppendInsertTest.testAppendln_StringBuilder_int_int(TextStringBuilderAppendInsertTest.java:873)
```

See any GitHub Action build here:
https://github.com/apache/commons-text/actions

For example:
https://github.com/apache/commons-text/runs/1188127402?check_suite_focus=true

**Comment by raphw** [comment]
Set - Dnet.bytebuddy.experimental=true and it works unless something changes in the VM.

**Comment by garydgregory** [comment]
That works like a charm, thank you for your quick reply.
