### ISSUE TITLE
Illegal modifiers for mysql driver

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#94]
Looks like latest bytebudy refuses to validate the mysql driver (5.1.36 in my case): 
```
java.lang.IllegalStateException: Illegal modifiers 132097 for public abstract java.math.BigDecimal java.sql.CallableStatement.getBigDecimal(int,int) throws java.sql.SQLException
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:771)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:530)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:182)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:2790)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:3077)
```

```
java.lang.IllegalStateException: Illegal modifiers 132097 for public abstract java.lang.String com.mysql.jdbc.MySQLConnection.getCharsetNameForIndex(int) throws java.sql.SQLException
```

**Comment by CodingFabian** [comment]
and
```
java.lang.IllegalStateException: Illegal modifiers 131073 for public void com.mysql.jdbc.PreparedStatement.setUnicodeStream(int,java.io.InputStream,int) throws java.sql.SQLException
```

**Comment by raphw** [comment]
Thanks, probably forgot to include something.

In production, you should always disable validation for performance reason:

```
new ByteBuddy().with(TypeValidation.DISABLED);
```

**Comment by CodingFabian** [comment]
Thanks for the type validation hin. But I assume I can leave this on for a while to report more edge cases :)

**Comment by raphw** [comment]
Chances are that you will. The class file format gained some exceptions and quirks over the years.

**Comment by raphw** [comment]
The problem was a missing filtering of the deprecation-pseudo modifiers by the `TypePool`. This is now resolved.

**Comment by CodingFabian** [comment]
great! Yeah I had speculated that its the deprecation, which is somehow hacked into the type system.
Thanks for the quick fix!
