### ISSUE TITLE
Gradle plugin sample for Android

### ISSUE THREAD

**Issue by lianghanzhen** [raphw/byte-buddy#942]
Hi, do you have gradle plugin sample for Android? I tried to follow the doc, but had this error:

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method byteBuddy() for arguments on project ':app' of type org.gradle.api.Project.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.methodMissingException(BasicScript.java:161)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:166)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:83)
```

**Comment by raphw** [comment]
Byte Buddy only registers itself into Gradle's lifecycle if the Java plugin is found which is not the case when using the Android plugin. There is however a third-party plugin that might do the job for you: https://github.com/LikeTheSalad/android-buddy
