### ISSUE TITLE
Byte Buddy eagerly tries to load fields not present on class path

### ISSUE THREAD

**Issue by YoannBuch** [raphw/byte-buddy#95]
I'm using a java agent to trace a spring boot application, and I run into the situation where [BeanDefinitionLoader](https://github.com/spring-projects/spring-boot/blob/f96dea701120bcffce4dc303f152691c68f9c620/spring-boot/src/main/java/org/springframework/boot/BeanDefinitionLoader.java) is instantiated. When that happens Byte Buddy takes over with some initialization strategy where it eagerly tries to get and load all the fields of `BeanDefinitionLoader`.

Problem is that one of the fields is of type `GroovyBeanDefinitionReader` which implements `groovy.lang.GroovyObject`, a type present in the following **optional** dependency:

```
       <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
            <optional>true</optional>
        </dependency>
```
Since groovy is not present on the classpath of my application, I get a `ClassNotFoundException` on `groovy.lang.GroovyObject`.

As you can see in [BeanDefinitionLoader](https://github.com/spring-projects/spring-boot/blob/f96dea701120bcffce4dc303f152691c68f9c620/spring-boot/src/main/java/org/springframework/boot/BeanDefinitionLoader.java) the use of `GroovyBeanDefinitionReader` is guarded by the method `isGroovyPresent()`. However Byte Buddy can't be that smart and know when a class should or shouldn't be loaded.

I don't know much about what the various initialization strategies do and what the default is. So I tried them all. `SelfInjection.EAGER|LAZY|SPLIT` gives me the same result. `NoOp` and `Minimal` make my application fail really early on.

Would you mind sharing what these different initialization strategies are for? And which one to use when?

Also what can I do to solve my problem? (which I think can be generalized to a lot of projects where optional dependencies are used)

```
java.lang.ExceptionInInitializerError: null
	at org.springframework.boot.SpringApplication.createBeanDefinitionLoader$original$81B0XJ03(SpringApplication.java:743) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.createBeanDefinitionLoader$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$qbF83HLB.call(Unknown Source) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.load$original$81B0XJ03(SpringApplication.java:683) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.load$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$qpT3pJ8M.call(Unknown Source) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.load(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun$original$81B0XJ03(SpringApplication.java:343) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$JBzd4vRy.call(Unknown Source) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$6nKk9cif.call(Unknown Source) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$OHb5GwoZ.call(Unknown Source) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run$original$81B0XJ03$accessor$pAUDUZdh(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication$auxiliary$SLryc4x7.call(Unknown Source) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.agent.instrumentation.MethodInterceptor.intercept(MethodInterceptor.java:32) [com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.flow.website.Application.main(Application.java:12) [classes/:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.boot.BeanDefinitionLoader.<clinit>(BeanDefinitionLoader.java) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	... 31 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at net.bytebuddy.agent.builder.Nexus.initialize(Nexus.java:95) ~[com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	... 35 common frames omitted
Caused by: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_79]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_79]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_79]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_79]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.7.0_79]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2499) ~[na:1.7.0_79]
	at java.lang.Class.getDeclaredField(Class.java:1951) ~[na:1.7.0_79]
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:101) ~[com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180) ~[com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:1238) ~[com.flow.agent-0.0.1-SNAPSHOT.jar:na]
	... 39 common frames omitted
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	... 57 common frames omitted
```

**Comment by raphw** [comment]
First of all, to me this is clearly a bug in Spring Boot. It is not feasible to define a field or any other part of a class signature with a type that is only optionally present. This breaks any use of core reflection on such classes. The way it should be done is to declare a field of type object and to cast the field to the Groovy type only if Groovy is present. Even without using a Java agent, optional types must not be part of any member within a class that is loaded within an application when this optional type is not present as the JVM can choose to resolve such types eagerly.

The purpose of the `InitializationStrategy` is to guarantee that a class is fully usable when it is loaded. For example:

```java
new ByteBuddy()
  .subclass(Foo.class)
  .method(named("toString"))
  .intercept(MethodDelegation.to(new Object() {
    public String doSomething() {
      return "something";
    }
  }))
  .make();
```

The above example delegates to an instance and this instance needs to be stored in a static field. This static field is set to `null` after creating the class. Within a Java agent instrumentation, a class only exists as a byte array. Therefore, Byte Buddy applies an initialization strategy where the aboves class's initializer (`static { ... }`) is implemented to call back into Byte Buddy where the static field is set. You can avoid this by not delegating to any instances but rather to static methods by supplying a type reference to the `MethodDelegation`. The problem you observe is caused by the call to `getDeclaredField` of `LoadedTypeInitializer.ForStaticField` which triggers the VM to resolve all field types where one is not defined. (Note that Byte Buddy does not access the field in question at all, it is only a side effect of reflection.)

The strategies you mention have different levels of resolution:
- `NoOp` does not apply any class setup. This only works if there is nothing do be done, i.e. there are no static fields to set up and there exist no auxiliary types (An auxiliary type is a helper class, like an inner class for implementing a `Runnable` that fullfils the `@SuperCall` contract.
- `Minimal` does not apply any `LoadedTypeInitializer`s and only loads auxiliary classes that are explicitly marked to be safe. Loading an auxiliary type can cause problems when the auxiliary type is a subclass of the instrumented class what would cause the subclass to be loaded.
- `SelfInjection` is a strategy where Byte Buddy implements the class initializer to set all fields once the class is loaded. The initializer then calls back to the framework and asks for itself being initialized. The type of self-injection determines if the auxiliary types are either loaded in the intiializer (`LAZY`), during instrumentation (`EAGER`) or depending on their safeness of being loaded eager or lazy (`SPLIT`).

If you choose to not use `SelfInjection`, you need to make sure that you initialize your classes manually what is an option to avoid your current problem. The real problem is though, if the dependency is missing, it is not possible to do this using core reflection. Even if you do it manually, reflection will always fail with a `ClassNotFoundError`.

**Comment by YoannBuch** [comment]
Thank you Raphael for the detailed explanation!

That seems to me like a reasonable workaround until they fix this issue (though I suspect it's not an isolated case, and not only other parts of Spring Boot but also other projects may have this issue too).

I wasn't really wanting to use a type reference because it's hard to test. But the example you provided is perfect, I can still inject whatever dependencies I need into `Foo` without the need to make static calls, awesome. I'll give it a try.

And thank you for the pull request, I'll keep an eye on it.

**Comment by raphw** [comment]
Spring uses a lot of optional dependencies but none of this is legal as I currently try to explain it on the linked ticket. There is nothing a third-party framework can do about it and if they choose not to fix it, there is nothing I can do.

Thanks for reporting!

**Comment by raphw** [comment]
FYI, Spring Boot has fixed their bug on `HEAD`.

**Comment by wilkinsona** [comment]
@YoannBuch It's also in the 1.3.x branch. If you'd like to try a 1.3.3 snapshot, one will be available from https://repo.spring.io/libs-snapshot once [this build](https://build.spring.io/browse/BOOT-PUB4-6) has finished.

**Comment by YoannBuch** [comment]
Thank you all! I'll give it a try asap.

**Comment by YoannBuch** [comment]
Tested with the 1.3.x branch and it's fixed. Thank you @wilkinsona and @raphw!
