### ISSUE TITLE
Error invoking java.lang.instrument.Instrumentation#retransformClasses on SAP JVM

### ISSUE THREAD

**Issue by SylvainJuge** [raphw/byte-buddy#956]
We recently faced an unexpected instrumentation error on a customer SAP JVM, and we wonder if that could be a known issue with either bytebuddy or SAP JVMs.

- we only instrument methods, we should not modify class structure
- we added a `BatchReallocator` in order to split a failing batch with `RedefinitionStrategy.Listener.BatchReallocator.splitting()`
- with the reallocator, we can see that we only have two classes that trigger the issue:
   - `java.util.concurrent.AbstractExecutorService`
   - the other one is an anonymous class of our agent that extends `java.util.concurrent.ScheduledThreadPoolExecutor` and which does not define any method that should be instrumented.

This issue is triggered with version 1.18.1 of https://github.com/elastic/apm-agent-java which embeds bytebuddy version `1.10.12`, it does the same with `1.10.15` but did not tried with more recent versions due to other issues.

The issue happens with SAP JVM 8.1.065 (which is Java 8u261), but we haven't been able to reproduce it locally so far.

We are currently waiting to have bytecode dumps to see if there is any structural change that would explain this.

Here is the full stack trace triggered by Elastic agent.
```
2020-10-13 14:20:58,799 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Error invoking java.lang.instrument.Instrumentation#retransformClasses
java.lang.IllegalStateException: Error invoking java.lang.instrument.Instrumentation#retransformClasses
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6916) ~[?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7187) ~[?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:7032) [?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4868) [?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:9502) [?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9423) [?:?]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:11025) [?:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:232) [?:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:151) [?:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:137) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at co.elastic.apm.agent.bci.AgentMain.init(AgentMain.java:103) [elastic-apm-agent-1.18.2-SNAPSHOT.jar:?]
	at co.elastic.apm.agent.bci.AgentMain.premain(AgentMain.java:57) [elastic-apm-agent-1.18.2-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386) [?:1.8.0_261]
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401) [?:1.8.0_261]
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) ~[?:1.8.0_261]
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6908) ~[?:?]
	... 21 more

```

**Comment by raphw** [comment]
The byte code dumps would certainly help to provide an answer. Are you sure there's no other agent involved?

**Comment by SylvainJuge** [comment]
After some further investigation there was another agent involved (Optier), and removing it made the error disappear.

This issue can thus be closed, sorry for the noise.

**Comment by raphw** [comment]
No worries, that's the typical issue. One non-retransformable agent makes retransforming for shared targets practically impossible.
