### ISSUE TITLE
JavaConstant.Dynamic.ofInvocation() doesn't seem to permit interface default methods as bootstrap methods

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#957]
Using JDK 15, if I try to use `List#of(E[])` (a `static` interface method declared on `List` itself) as a bootstrap method, I get:
```
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class java/util/List. Method 'java.util.List of(java.lang.Object[])' at index 19 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at java.base/java.lang.invoke.MethodHandleNatives.copyOutBootstrapArguments(Native Method)
	at java.base/java.lang.invoke.BootstrapMethodInvoker$VM_BSCI.copyConstants(BootstrapMethodInvoker.java:402)
	at java.base/java.lang.invoke.BootstrapMethodInvoker$VM_BSCI.fillCache(BootstrapMethodInvoker.java:377)
	at java.base/java.lang.invoke.AbstractConstantGroup$WithCache.get(AbstractConstantGroup.java:278)
	at java.base/java.lang.invoke.BootstrapMethodInvoker$PullAdapter.pullFromBootstrapMethod(BootstrapMethodInvoker.java:509)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:117)
	at java.base/java.lang.invoke.ConstantBootstraps.makeConstant(ConstantBootstraps.java:72)
	at java.base/java.lang.invoke.MethodHandleNatives.linkDynamicConstantImpl(MethodHandleNatives.java:327)
	at java.base/java.lang.invoke.MethodHandleNatives.linkDynamicConstant(MethodHandleNatives.java:319)
```
I've edited this bug description to remove what I thought was the problem.  Now I just don't know what the problem is at all.  😄

**Comment by ljnelson** [comment]
I'm wondering if the problem is here:

https://github.com/raphw/byte-buddy/blob/e4ce4af1bab578a7ac3497d07449e50628d050e7/byte-buddy-dep/src/main/java/net/bytebuddy/utility/JavaConstant.java#L1609-L1613

Note line 1613.  I'll investigate.

**Comment by ljnelson** [comment]
Yep; that's the problem; if I replace that `false` with `methodDescription.getDeclaringType().isInterface()` the problem goes away.  PR coming shortly.

**Comment by ljnelson** [comment]
See #958.
