### ISSUE TITLE
How to invoke java method with parameter

### ISSUE THREAD

**Issue by ericfoongcheesoon** [raphw/byte-buddy#964]
This is something I have research for sometime, I want to invoke a Java method via intercept() method of DynamicType.Builder, with net.bytebuddy.implementation.MethodCall. This is the java code I want to generate,
new MethodExec().process("data1", "data2");

How to implement this line of code in bytebuddy?

**Comment by raphw** [comment]
You want to invoke a constructor and then a method on the constructor?

You can nest:

```java
MethodCall`s - MethodCall.invoke(<process>)
  .on(MethodCall.construct(<method exec>))
  .withArguments("data1", "data2")
```

**Comment by ericfoongcheesoon** [comment]
I have implemented the code:
Method m=MethodExec.class.getDeclaredMethod("process", String.class, String.class);

.defineMethod("test2", String.class, Visibility.PUBLIC)
.withParameter(String.class)
.withParameter(String.class)
.intercept(
  MethodCall.invoke(m)
  .on(MethodCall.construct(MethodExec.class.getDeclaredConstructor()))
.withArgument(0,1));
				);

but get this exception:
Cannot invoke public java.lang.String com.app.MethodExec.test(java.lang.String, java.lang.String) on public static volatile net.bytebuddy.implementation.MethodCall

**Comment by raphw** [comment]
Use: `onMethodCall(...)`, not `.on()`. If you use the latter, Byte Buddy will invoke the method on the actual instance you provide which is of course not meaningful.

**Comment by ericfoongcheesoon** [comment]
I change the .on() to .onMethodCall():

.defineMethod("test2", String.class, Visibility.PUBLIC)
.withParameter(String.class)
.withParameter(String.class)
.intercept(
MethodCall.invoke(m)
.onMethodCall(MethodCall.construct(MethodExec.class.getDeclaredConstructor()))
.withArgument(0,1));
);

but get this exception:
Caused by: java.lang.IllegalStateException: Cannot invoke public java.lang.String com.millionstrengthknowledge.interceptorprj.interceptor.MethodExec.process(java.lang.String,java.lang.String) on void
	at net.bytebuddy.implementation.MethodCall$TargetHandler$ForMethodCall$Resolved.toStackManipulation(MethodCall.java:2619)
	at net.bytebuddy.implementation.MethodCall$Appender.toStackManipulation(MethodCall.java:3547)
	at net.bytebuddy.implementation.MethodCall$Appender.apply(MethodCall.java:3508)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:600)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitEnd(TypeWriter.java:5110)


This is the code for MethodExec.java:
public class MethodExec {
	public String process(String s1, String s2) {
		return s1+s2;
	}
}

**Comment by raphw** [comment]
That's a bug that I just fixed on master. Byte Buddy incorrectly resolves the return type of a constructor as `void`.

**Comment by ericfoongcheesoon** [comment]
TQ for the bug fix.
