### ISSUE TITLE
Unable to use MethodDelegation with method(..).intercept(..) 

### ISSUE THREAD

**Issue by ArtfulCoder** [raphw/byte-buddy#970]
I am using ByteBuddy version 1.10.18

I am unable to use MethodDelegation with method(..).intercept(..) 

I am able to intercept with FixedValue.value(...)
`.method(not(isAbstract()).and(named("print"))).intercept(FixedValue.value(1000)); // <- THIS WORKS
`

But when I try the following:
`.method(not(isAbstract()).and(named("print"))).intercept(MethodDelegation.to(new LoggerInterceptor())); // <- THIS DOESNT WORK`

I get the following error:
`java.lang.IllegalArgumentException: None of [public static java.lang.Object org.abhi.Main$LoggerInterceptor.intercept(java.util.concurrent.Callable,java.lang.reflect.Method,java.lang.Object[]) throws java.lang.Exception] allows for delegation from public java.lang.Integer org.abhi.Main$Foo.print(java.lang.Integer)
`

_Even if LoggerInterceptor was a top-level public class, it gives the same error.
My primary goal is to track what methods are getting invoked and to record those method invocations along with the Parameter names of the those methods. The Advice API would not give me the Method object, and hence the need for Interception.

Any help is appreciated!

Thank you!

Full code and log pasted below.

```
package org.abhi;

import static net.bytebuddy.matcher.ElementMatchers.isAnnotatedWith;
import static net.bytebuddy.matcher.ElementMatchers.nameContains;
import static net.bytebuddy.matcher.ElementMatchers.nameStartsWith;

import java.lang.reflect.Method;
import java.util.concurrent.Callable;
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.agent.builder.AgentBuilder.RedefinitionStrategy;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.annotation.AllArguments;
import net.bytebuddy.implementation.bind.annotation.Origin;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import net.bytebuddy.matcher.ElementMatcher.Junction;

import static net.bytebuddy.matcher.ElementMatchers.*;

public class Main {

  @Deprecated
  public static class Foo {
    public Integer print(Integer x) {
      System.out.println("Foo:print: " + x);
      return x;
    }
  }

  public static class LoggerInterceptor {

    @RuntimeType
    public static Object intercept(@SuperCall Callable<?> zuper, @Origin final Method method, @AllArguments Object[] args) throws Exception {
      System.out.println("INTERCEPTED");
      return zuper.call();
    }

//    @RuntimeType
//    public static void intercept(@Origin final Method method) throws Exception {
//      System.out.println("INTERCEPTED");
//    }
  }

  public static void main(String args[]) {
    ByteBuddyAgent.install();
    Junction<? super TypeDescription> matcher = nameStartsWith("org.abhi.").and(isAnnotatedWith(Deprecated.class));

    new AgentBuilder.Default()
        .disableClassFormatChanges()
          .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
        .with(RedefinitionStrategy.RETRANSFORMATION)
        .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
        .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
        .type(matcher)
        .transform(
            (builder, typeDescription, classLoader, module) -> {
              return builder
//                  .method(not(isAbstract()).and(named("print"))).intercept(FixedValue.value(1000)); // <- THIS WORKS
                  .method(not(isAbstract()).and(named("print"))).intercept(MethodDelegation.to(LoggerInterceptor.class)); // <- THIS DOESNT WORK
            })
        .installOnByteBuddyAgent();

    Foo obj = new Foo();
    System.out.println(obj.toString());
    Integer retval = obj.print(1);
    System.out.println("ABHI: returned value is " + retval);
  }
}
```

Trimmed output

```
[Byte Buddy] COMPLETE java.lang.Comparable [null, module java.base, loaded=true]
[Byte Buddy] DISCOVERY java.io.Serializable [null, module java.base, loaded=true]
[Byte Buddy] IGNORE java.io.Serializable [null, module java.base, loaded=true]
[Byte Buddy] COMPLETE java.io.Serializable [null, module java.base, loaded=true]
[Byte Buddy] DISCOVERY java.lang.Object [null, module java.base, loaded=true]
[Byte Buddy] IGNORE java.lang.Object [null, module java.base, loaded=true]
[Byte Buddy] COMPLETE java.lang.Object [null, module java.base, loaded=true]
[Byte Buddy] DISCOVERY org.abhi.Main$Foo [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15, unnamed module @6892b3b6, loaded=false]
[Byte Buddy] ERROR org.abhi.Main$Foo [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15, unnamed module @6892b3b6, loaded=false]
java.lang.IllegalArgumentException: None of [public static java.lang.Object org.abhi.Main$LoggerInterceptor.intercept(java.util.concurrent.Callable,java.lang.reflect.Method,java.lang.Object[]) throws java.lang.Exception] allows for delegation from public java.lang.Integer org.abhi.Main$Foo.print(java.lang.Integer)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1346)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor$CodePreservingMethodVisitor.visitCode(TypeWriter.java:5316)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1480)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:711)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:394)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3918)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10366)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10761)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10699)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10258)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.abhi.Main.main(Main.java:63)
[Byte Buddy] COMPLETE org.abhi.Main$Foo [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15, unnamed module @6892b3b6, loaded=false]
org.abhi.Main$Foo@4f6f416f
Foo:print: 1
ABHI: returned value is 1
[Byte Buddy] DISCOVERY java.util.IdentityHashMap$KeyIterator [null, module java.base, loaded=false]
[Byte Buddy] IGNORE java.util.IdentityHashMap$KeyIterator [null, module java.base, loaded=false]
[Byte Buddy] COMPLETE java.util.IdentityHashMap$KeyIterator [null, module java.base, loaded=false]
[Byte Buddy] DISCOVERY java.util.IdentityHashMap$IdentityHashMapIterator [null, module java.base, loaded=false]
[Byte Buddy] IGNORE java.util.IdentityHashMap$IdentityHashMapIterator [null, module java.base, loaded=false]
```

**Comment by raphw** [comment]
When using `AgentBuilder.TypeStrategy.Default.REDEFINE`, you replace methods with new methods. In this case, you are erasing `foo` and put your delegation in instead of. Since this means that there is no super method to call, the instrumentation cannot work.

You might consider `AgentBuilder.TypeStrategy.Default.REBASE` (the default).

**Comment by ArtfulCoder** [comment]
Thank you for your response!

I tried  REBASE Type strategy, along with two interception variations, and both failed with different exceptions

**ATTEMPT 1** 
For the code below I get an exception
```
java.lang.IllegalStateException: Field values caching was disabled: class java.lang.reflect.Method
	at net.bytebuddy.implementation.Implementation$Context$Disabled.cache(Implementation.java:714)
	at net.bytebuddy.implementation.bytecode.constant.MethodConstant$CachedMethod.apply(MethodConstant.java:462)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$ParameterBinding$Anonymous.apply(MethodDelegationBinder.java:257)
	at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:225)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build.apply(MethodDelegationBinder.java:561)
	at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:225)
	at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1347)
```

Code: 
```
 new AgentBuilder.Default()
        .disableClassFormatChanges()
          .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
        .with(RedefinitionStrategy.RETRANSFORMATION)
        .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
        .with(AgentBuilder.TypeStrategy.Default.REBASE)
        .type(matcher)
        .transform(
            (builder, typeDescription, classLoader, module) -> {
              return builder
                  .method(not(isAbstract()).and(named("print")))
                  .intercept(MethodDelegation.to(LoggerInterceptor.class)
                  .andThen(SuperMethodCall.INSTANCE)); // <- THIS DOESNT WORK
            })
        .installOnByteBuddyAgent();
```

**ATTEMPT 2**

For the code below, I get a different exception:

```
java.lang.IllegalStateException: Registration of auxiliary types was disabled: net.bytebuddy.implementation.auxiliary.MethodCallProxy@94a317da
	at net.bytebuddy.implementation.Implementation$Context$Disabled.register(Implementation.java:686)
	at net.bytebuddy.implementation.auxiliary.MethodCallProxy$AssignableSignatureCall.apply(MethodCallProxy.java:445)
	at net.bytebuddy.implementation.bind.MethodDelegationBinder$ParameterBinding$Anonymous.apply(MethodDelegationBinder.java:257)
```


Code: 

```
  .with(AgentBuilder.TypeStrategy.Default.REBASE)
        .type(matcher)
        .transform(
            (builder, typeDescription, classLoader, module) -> {
              return builder
                  .method(not(isAbstract()).and(named("print")))
                  .intercept(MethodDelegation.to(LoggerInterceptor.class)); // Interceptor took a SuperCall Callable and invoked it.
            })
        .installOnByteBuddyAgent();
```

**Comment by raphw** [comment]
When using `.disableClassFormatChanges()`, Byte Buddy does not allow for adding fields or methods to loaded classes what does not work well with rebasing or delegation.

If you want to process loaded classes, I recommend you using `Advice` which is more friendly to such transformations.
