### ISSUE TITLE
Rebasing of a Class with a Method Annotated with @Deprecated Throws Exception

### ISSUE THREAD

**Issue by saden1** [raphw/byte-buddy#98]
ByteBuddy throws an exception if you try to rebase a class that has a method annotated &#64;Deprecated. If you remove the annotation it works. This seems like a bug.

```java
public class ModifierRebaseTest {

    @Test
    public void test() {
        String className = "bytebuddy.test.ModifierRebaseTest$Greeting";
        TypePool typePool = TypePool.Default.ofClassPath();
        TypeDescription typeDescription = typePool.describe(className).resolve();
        ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofClassPath();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();

        new ByteBuddy()
                .rebase(typeDescription, locator)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(to(new GreetingInterceptor()))
                .make()
                .load(classLoader, ClassLoadingStrategy.Default.INJECTION);

        new Greeting().phrase();

    }

    public static class GreetingInterceptor {

        @RuntimeType
        public void intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception {
            zuper.call();
        }
    }

    public static class Greeting {

        /**
         * Having @Deprecated annotation on the method results in
         * java.lang.IllegalStateException: Illegal modifiers 131076 for
         * protected java.lang.String
         * bytebuddy.test.ModifierRebaseTest$Greeting.phrase(java.lang.String)
         */
        @Deprecated
        protected String phrase(String phrase) {
            return phrase;
        }

        public String phrase() {
            return "Hello";
        }
    }
}
```

```
java.lang.IllegalStateException: Illegal modifiers 131076 for protected java.lang.String bytebuddy.test.ModifierRebaseTest$Greeting.phrase(java.lang.String)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:771)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:530)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:182)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2472)
```

**Comment by raphw** [comment]
This was adressed in version 1.1.0 - what version are you using?

**Comment by saden1** [comment]
I was using 1.0.3 and didn't see release 1.1.0. Upgrading to the latest release resolves the issue.

Thanks.
