### ISSUE TITLE
Gradle plugin fails on incomplete classpath

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#980]
Hi! I am trying to use the Gradle plugin to apply some post transformations on a shadowed jar. Coincidentally enough, the project shades ByteBuddy :)

Since ByteBuddy agent has optional dependencies (JNA), the plugin seems to fail to handle it and fails with:
```
Caused by: java.lang.IllegalStateException: Cannot resolve type description for com.sun.jna.Library
        at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157)
        at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
        at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8376)
        at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:8009)
        at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1678)
        at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1634)
        at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3783)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6301)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:632)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:567)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
        at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:471)
        at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:224)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4498)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4455)
        at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.accept(Plugin.java:3538)
        at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4302)
```

Reproducer:
```groovy
import net.bytebuddy.build.gradle.ByteBuddyJarTask
import net.bytebuddy.description.type.TypeDescription
import net.bytebuddy.dynamic.ClassFileLocator
import net.bytebuddy.dynamic.DynamicType

plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "4.0.2"
    id 'net.bytebuddy.byte-buddy-gradle-plugin' version '1.10.18'
}

repositories {
    jcenter()
}

shadowJar {
    dependsOn(project.tasks.jar)
}
project.tasks.build.dependsOn(shadowJar)

class DummyPlugin implements net.bytebuddy.build.Plugin {

    @Override
    boolean matches(TypeDescription target) {
        return true;
    }

    @Override
    DynamicType.Builder<?> apply(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassFileLocator classFileLocator) {
        System.out.println("Transforming " + typeDescription);
        return builder;
    }

    @Override
    void close() throws IOException {

    }
}

task pp(type: ByteBuddyJarTask) {
    dependsOn(tasks.shadowJar)
    source = tasks.shadowJar.outputs.files.singleFile
    target = new File(tasks.shadowJar.outputs.files.singleFile.toString() + ".pp.jar")
    classPath = configurations.shaded

    transformation {
        plugin = DummyPlugin.class
    }
}

dependencies {
    compile 'net.bytebuddy:byte-buddy-agent:1.10.9'
}
```

Since all I needed was to add an annotation, I was hoping I can do that without having to provide the full classpath (which is kinda hard to do given that it is unknown to me when I think about all shaded dependencies)

**Comment by raphw** [comment]
You should define an `EntryPoint` that does not do as much as you know you do not match any methods anyways. You can do so in the *transformation* closure. Try `new ByteBuddy().with(MethodGraph.Compiler.ForDeclaredMethods.INSTANCE`.
