### ISSUE TITLE
IllegalStateException: java.lang.reflect.Executable#getAnnotatedReceiverType on JDK 16 build 26

### ISSUE THREAD

**Issue by akarnokd** [raphw/byte-buddy#983]
I've been checking newer JDK builds with RxJava and up until JDK 16 build 24, everything passed.

Now with JDK 16 build 26, I get these failures:

```
io.reactivex.rxjava3.completable.CompletableTest > retry5Times FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: class io.reactivex.rxjava3.completable.CompletableTest$155.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 16
    JVM vendor name    : Oracle Corporation
    JVM vendor version : 16-ea+26-1764
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 16-ea+26-1764
    JVM info           : mixed mode, sharing
    OS name            : Linux
    OS version         : 5.4.0-1031-azure


    Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedReceiverType
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at io.reactivex.rxjava3.completable.CompletableTest.setUp(CompletableTest.java:3435)

        Caused by:
        java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedReceiverType
            at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2778)
            at net.bytebuddy.description.method.MethodDescription$ForLoadedMethod.getReceiverType(MethodDescription.java:1263)
            at net.bytebuddy.description.method.MethodDescription$TypeSubstituting.getReceiverType(MethodDescription.java:1619)
            at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:796)
            at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:373)
            at net.bytebuddy.dynamic.Transformer$ForMethod.transform(Transformer.java:298)
            at net.bytebuddy.dynamic.Transformer$ForMethod.transform(Transformer.java:253)
            at net.bytebuddy.dynamic.Transformer$Compound.transform(Transformer.java:645)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Entry.asPreparedEntry(MethodRegistry.java:596)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:484)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:213)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
            at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:199)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:29)
            at org.mockito.internal.util.MockUtil.lambda$createMock$0(MockUtil.java:48)
            at java.base/java.util.Optional.orElseGet(Optional.java:362)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:46)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
            at org.mockito.Mockito.spy(Mockito.java:2033)
            ... 1 more

            Caused by:
            java.lang.NullPointerException
                at java.base/java.lang.reflect.Executable.resolveOwner(Executable.java:774)
                at java.base/java.lang.reflect.Executable.resolveToOwnerType(Executable.java:759)
                at java.base/java.lang.reflect.Executable.getAnnotatedReceiverType(Executable.java:702)
                at java.base/jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:564)
                at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2774)
                ... 30 more
```

Please advise.

**Comment by raphw** [comment]
This is an error in OpenJDK but ironically one I just introduced there myself. This should be fixed by https://github.com/openjdk/jdk/pull/1414.

**Comment by eolivelli** [comment]
I am seeing this error after upgrading to latest JDK16-ea
```

Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedReceiverType
	at org.apache.zookeeper.test.StaticHostProviderTest.testReResolvingSingle(StaticHostProviderTest.java:718)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedReceiverType
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2778)
	at net.bytebuddy.description.method.MethodDescription$ForLoadedMethod.getReceiverType(MethodDescription.java:1263)
	at net.bytebuddy.description.method.MethodDescription$TypeSubstituting.getReceiverType(MethodDescription.java:1619)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:796)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:373)
	at net.bytebuddy.dynamic.Transformer$ForMethod.transform(Transformer.java:298)
	at net.bytebuddy.dynamic.Transformer$ForMethod.transform(Transformer.java:253)
	at net.bytebuddy.dynamic.Transformer$Compound.transform(Transformer.java:645)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Entry.asPreparedEntry(MethodRegistry.java:596)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:484)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:213)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:199)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:29)
	at org.mockito.internal.util.MockUtil.lambda$createMock$0(MockUtil.java:48)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:46)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
	at org.mockito.Mockito.spy(Mockito.java:2033)
	... 1 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getTypeParameters()" because "d" is null
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveReceiverType(TypeDescription.java:2774)
	... 29 more

```

**Comment by raphw** [comment]
The patch is not merged yet, this should get fixed in the next build iteration.

**Comment by akarnokd** [comment]
Looks like these have been resolved in 16b30 but now I get a different failure. I'll post it separately.

**Comment by raphw** [comment]
We'll follow this up on the other issue then.
