### ISSUE TITLE
NullPointerException in net.bytebuddy.dynamic.scaffold.MethodGraph.Compiler.Default#compile

### ISSUE THREAD

**Issue by kylelyk** [raphw/byte-buddy#988]
When running build time byte code enhancement in Hibernate 5.4.25.Final (byte-buddy 1.10.17), it appears that byte-buddy throws a NullPointerException with the following stacktrace:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Unable to enhance class : /Users/**/User.class
        at org.hibernate.orm.tooling.gradle.EnhancementHelper.doEnhancement(EnhancementHelper.java:127)
        at org.hibernate.orm.tooling.gradle.EnhancementHelper.enhance(EnhancementHelper.java:87)
        at org.hibernate.orm.tooling.gradle.HibernatePlugin$EnhancerAction.execute(HibernatePlugin.java:73)
        at org.hibernate.orm.tooling.gradle.HibernatePlugin$EnhancerAction.execute(HibernatePlugin.java:57)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more
Caused by: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class **.User
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:138)
        at org.hibernate.orm.tooling.gradle.EnhancementHelper.doEnhancement(EnhancementHelper.java:124)
        ... 87 more
Caused by: java.lang.NullPointerException
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:572)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.lambda$resolveGetter$0(ByteBuddyEnhancementContext.java:91)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.resolveGetter(ByteBuddyEnhancementContext.java:90)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getGetter(EnhancerImpl.java:518)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.doGetAnnotations(EnhancerImpl.java:547)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getAnnotations(EnhancerImpl.java:526)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.hasAnnotation(EnhancerImpl.java:476)
        at org.hibernate.bytecode.enhance.spi.DefaultEnhancementContext.isPersistentField(DefaultEnhancementContext.java:103)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.isPersistentField(ByteBuddyEnhancementContext.java:69)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.collectPersistentFields(PersistentAttributeTransformer.java:82)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.createTransformer(EnhancerImpl.java:357)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:305)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:132)
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:141)
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:132)
        ... 88 more
```

The problem is that the snapshots set does contain the interfaceType, but `net.bytebuddy.description.type.TypeDescription.Generic.LazyProjection#equals` doesn't return true for `net.bytebuddy.pool.TypePool.Default.LazyTypeDescription.TokenizedGenericType` instances. The method checks the equality of the resolved TypeDescription against the original TypeDescription and they don't match even though the original objects are identical in content. Maybe the fix would be to do `resolve().equals(other.resolve())`?

**Comment by raphw** [comment]
That is curious, the interface should have been visited, so yes, maybe the equality is not working out as expected when locating the type in the map. By looking through it, it should however work out for any case I can think of. You cannot call `other.resolve()` as it is not known what specific type *other* is of.

Is this a project you can share? I can likely find out quickly about this with a reproducer, if you can create one for your class **.User. Alternatively, can you set a break point in the line in question before the null pointer is occurring and check if the type in question can be found in the map to begin with? Maybe it is of an unexpected generic type and that's why it is not working out.

**Comment by kylelyk** [comment]
The project is not public so I'll try best to explain what I'm seeing in the debugger. 
<img width="1900" alt="Screen Shot 2020-12-17 at 2 45 40 PM" src="https://user-images.githubusercontent.com/3401359/102547656-c330b580-4076-11eb-8d56-9bee41a94045.png">


Looking into it more, I think that maybe the `.asErasure()` call in net.bytebuddy.description.type.TypeDescription.AbstractBase#equals is the problem since `getName().equals(typeDefinition.getTypeName())` actually succeeds while `getName().equals(typeDefinition.asErasure().getName())` fails since the `.asErasure()` turns `org.springframework.beans.factory.aspectj.AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport` into `interface org.springframework.beans.factory.aspectj.ConfigurableObject.

**Comment by raphw** [comment]
That is not supposed to happen. It turns `org.springframework.beans.factory.aspectj.AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport` into `org.springframework.beans.factory.aspectj.ConfigurableObject`? Those are two fully different classes after all.

That sounds like the lazy projection of the generic type is not working as it should, to be honest. Byte Buddy avoids calling the "generic" reflection accessors if a non-generic type is requested to avoid the overhead.

Can you confirm that the base type is actually changing? Since it is the Spring framework, can you share the particular version?

I wonder if AspectJ is messing up the generic types, too.

**Comment by kylelyk** [comment]
Spring is at 5.1.4.RELEASE and aspectj is 1.9.4. I have recorded my debug session to hopefully illustrate the issue better.
![out](https://user-images.githubusercontent.com/3401359/102636539-055b0500-4112-11eb-8057-c10a4bac61c1.gif)

**Comment by raphw** [comment]
Do I pick this up correctly that the erasure of the generic type for the tokenized generic type in the end is completely different?

Could you check this for me. What is the result of both `asErasure().getName()` and `getTypeName()` for the *other* variable in the equals method?

**Comment by raphw** [comment]
Could you send me the dot-class file of the failing class and its superclasses to rafael.wth@gmail.com? I'll promise to treat them confidentially.

**Comment by raphw** [comment]
After stepping through the GIF after splitting it in several images, it looks like the erasure of `AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport` is defined to be of the erasure `ConfigurableObject`.

If you get the loaded class for your `com.warehouse.model.User`, and if you call both `getInterfaces` and `getGenericInterfaces`, is there some discrepancy? It seems to me like aspectj is potentially messing up the class file if there is some trickery around it.

I am also confused by the existence of the class altogether. In https://docs.spring.io/spring-framework/docs/5.1.4.RELEASE/javadoc-api/org/springframework/beans/factory/aspectj/package-summary.html, i can only find `ConfigurableObject` and I can neither find the class in question anywhere in the Spring project. Is it generated somehow?

**Comment by kylelyk** [comment]
`other.asErasure().getName()` returns `org.springframework.beans.factory.aspectj.ConfigurableObject` and `other.getTypeName()` returns `org.springframework.beans.factory.aspectj.AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport`.

`User.class.getInterfaces()` and `User.class.getGenericInterfaces()` return the following (but in different orders):
```
result = {Type[2]@2340} 
 0 = {Class@2321} "interface org.springframework.beans.factory.aspectj.AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport"
 1 = {Class@2320} "interface org.springframework.beans.factory.aspectj.ConfigurableObject"
```

It appears that AbstractInterfaceDrivenDependencyInjectionAspect is generated at runtime since the source code of resulting class file is an .aj file.
https://github.com/spring-projects/spring-framework/blob/master/spring-aspects/src/main/java/org/springframework/beans/factory/aspectj/AbstractInterfaceDrivenDependencyInjectionAspect.aj

I've sent you an email with the required class files.

**Comment by raphw** [comment]
Sorry for the late reply. The problem lies indeed in the generic declaration which is illegal considering the declared interfaces. The difference in the class file is:

Generic declaration:
    0 - org/springframework/beans/factory/aspectj/AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport
    1 - org/springframework/beans/factory/aspectj/ConfigurableObject
    
Non-generic interfaces
    0 - org/springframework/beans/factory/aspectj/ConfigurableObject
    1 - org/springframework/beans/factory/aspectj/AbstractInterfaceDrivenDependencyInjectionAspect$ConfigurableDeserializationSupport

This distracts Byte Buddy as the generic declaration is no longer reliable. You can try to tell Byte Buddy to ignore generic declarations. This might cause a bunch of other problems but maybe it solves your case. You can force this behavior by setting `-Dnet.bytebuddy.raw=true`.

**Comment by rybalkinsd** [comment]
Hey @raphw 
Just want to highlight another case, even though `-Dnet.bytebuddy.raw=true` also helped to resolve it.

Similar thing with identical stack trace happens with a Kotliin data class with generic:

```kotlin
data class Foo<T> {
}
```
