### ISSUE TITLE
java.lang.NoClassDefFoundError: net.bytebuddy.dynamic.scaffold.FieldRegistry

### ISSUE THREAD

**Issue by simonjenga** [raphw/byte-buddy#99]
I am experiencing the the following error with the following versions of the JARS:
 ```
<artifactId>mockito-core</artifactId>
<version>2.0.36-beta</version>
```

 ```
<artifactId>byte-buddy</artifactId>
<version>0.7.8</version>
```
I created the following test class:

```
public final class MockingTest {
	
	private interface SimpleInterface {
		String returnString();		
		void returnNothing();
	}

	/**
     * SimpleInterfaceTest.
     *
     * @throws IOException If some problem inside
     */
    @Test
    public void simpleInterfaceTest() throws IOException {
    	final SimpleInterface simple = Mockito.mock(SimpleInterface.class);
    	MatcherAssert.assertThat(simple, Matchers.notNullValue());
    }
}
```

This is the stack-trace:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.simple.example.MockingTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in com.simple.example.MockingTest
simpleInterfaceTest(com.simple.example.MockingTest)  Time elapsed: 0.047 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/scaffold/FieldRegistry
        at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.<init>(MockBytecodeGenerator.java:35)
        at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.<init>(CachingMockBytecodeGenerator.java:20)
        at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:22)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:33)
        at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:13)
        at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:12)
        at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
        at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
        at org.mockito.Mockito.<clinit>(Mockito.java:1103)
        at com.simple.example.MockingTest.simpleInterfaceTest(MockingTest.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.scaffold.FieldRegistry
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 33 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(ZipFile.java:56)
        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:679)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:415)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at sun.misc.Resource.getBytes(Resource.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:444)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        ... 39 more

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  MockingTest.simpleInterfaceTest:25 -+ NoClassDefFound net/bytebuddy/dynamic/sca...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Previous versions of these JARS work OK:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.simple.example.MockingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.296 sec - in com.simple.example.MockingTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Try to reproduce this issue in the following environment:

```
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.7.0_80\jre
Apache Maven >= 3.1.1
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

The same error messages may appear on: 
```Apache Maven 3.2.1```, ```Apache Maven 3.2.5``` and ```Apache Maven 3.3.3```

Are there any major changes you introduced along the way in the byte-buddy library?

**Comment by simonjenga** [comment]
I just confirmed that this problem has been fixed in the latest:
 ```
<artifactId>mockito-core</artifactId>
<version>2.0.40-beta</version>
```

and

 ```
<artifactId>mockito-core</artifactId>
<version>2.0.41-beta</version>
```

You may close this issue.

**Comment by raphw** [comment]
The beta versions have some bigger api changes. This is now more stable since 1.0.0

**Comment by simonjenga** [comment]
@raphw OK, thanks for letting me know.
